### ISSUE TITLE
panic in on type formatting

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#10002]
```rust
fn f() {
    let entry = self.nodes.raw_entry_mut().from_hash(hash, |node| {
        node.0.kind() == kind
            && node.0.children().len() == children_ref.len()
            && node
                .0
                .children()
                .map(element_id)
                .eq(children_ref.iter().map(|(_, it)| element_id(it.as_deref())))
    });

}
```

selecing an exprssion and typing `{` panics in vscode:

```rust
fn f() {
    let entry = self.nodes.raw_entry_mut().from_hash(hash, |node| {
        node.0.kind() == kind
            && node.0.children().len() == children_ref.len()
            && {node
                .0
                .children()
                .map(element_id)
                .eq(children_ref.iter().map(|(_, it)| element_id(it.as_deref())))}
    });

}
```

```
Panic context:
> 
version: c6baf3dcf 2021-08-22 dev
request: textDocument/onTypeFormatting DocumentOnTypeFormattingParams {
    text_document_position: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                cannot_be_a_base: false,
                username: "",
                password: None,
                host: None,
                port: None,
                path: "/home/matklad/projects/rowan/src/green/node_cache/repro.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 8,
            character: 81,
        },
    },
    ch: "{",
    options: FormattingOptions {
        tab_size: 4,
        insert_spaces: true,
        properties: {},
        trim_trailing_whitespace: Some(
            true,
        ),
        insert_final_newline: Some(
            true,
        ),
        trim_final_newlines: Some(
            true,
        ),
    },
}

thread '<unnamed>' panicked at 'assertion failed: {\n    let text = snap.analysis.file_text(position.file_id)?;\n    text[usize::from(position.offset)..].starts_with(char_typed)\n}', crates/rust-analyzer/src/handlers.rs:268:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/core/src/panicking.rs:50:5
   3: rust_analyzer::handlers::handle_on_type_formatting
   4: rust_analyzer::dispatch::RequestDispatcher::on::{{closure}}::{{closure}}
   5: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 8:51:32 PM] Request textDocument/onTypeFormatting failed.
  Message: server panicked: assertion failed: {\n    let text = snap.analysis.file_text(position.file_id)?;\n    text[usize::from(position.offset)..].starts_with(char_typed)\n}
  Code: -32603 
Panic context:
> 
version: c6baf3dcf 2021-08-22 dev
request: textDocument/onTypeFormatting DocumentOnTypeFormattingParams {
    text_document_position: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                cannot_be_a_base: false,
                username: "",
                password: None,
                host: None,
                port: None,
                path: "/home/matklad/projects/rowan/src/green/node_cache/repro.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 8,
            character: 81,
        },
    },
    ch: "{",
    options: FormattingOptions {
        tab_size: 4,
        insert_spaces: true,
        properties: {},
        trim_trailing_whitespace: Some(
            true,
        ),
        insert_final_newline: Some(
            true,
        ),
        trim_final_newlines: Some(
            true,
        ),
    },
}

thread '<unnamed>' panicked at 'assertion failed: {\n    let text = snap.analysis.file_text(position.file_id)?;\n    text[usize::from(position.offset)..].starts_with(char_typed)\n}', crates/rust-analyzer/src/handlers.rs:268:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/core/src/panicking.rs:50:5
   3: rust_analyzer::handlers::handle_on_type_formatting
   4: rust_analyzer::dispatch::RequestDispatcher::on::{{closure}}::{{closure}}
   5: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 8:52:01 PM] Request textDocument/onTypeFormatting failed.
  Message: server panicked: assertion failed: {\n    let text = snap.analysis.file_text(position.file_id)?;\n    text[usize::from(position.offset)..].starts_with(char_typed)\n}
  Code: -32603 
```

**Comment by matklad** [comment]
Seems to be an upstream bug: https://github.com/microsoft/vscode-languageserver-node/issues/802

**Comment by matklad** [comment]
confirmed upstream bug, closing.
