### ISSUE TITLE
byte index is not a char boundary in string literal with non-ascii char

### ISSUE THREAD

**Issue by tatami4** [rust-analyzer/rust-analyzer#10219]
```rust
fn main() {
    println("⊞<|>");
}
```
If you type `:` with the cursor in this position, you get this:

```
Panic context:
> 
version: 996300f4a 2021-08-23 stable
request: textDocument/completion CompletionParams {
    text_document_position: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                cannot_be_a_base: false,
                username: "",
                password: None,
                host: None,
                port: None,
                path: "/home/andrius/Desktop/error.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 1,
            character: 16,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    context: Some(
        CompletionContext {
            trigger_kind: TriggerCharacter,
            trigger_character: Some(
                ":",
            ),
        },
    ),
}

thread '<unnamed>' panicked at 'byte index 3 is not a char boundary; it is inside '⊞' (bytes 1..4) of `"⊞:"`', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rowan-0.13.0-pre.8/src/syntax_text.rs:52:28
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::str::slice_error_fail
   3: rowan::syntax_text::SyntaxText::char_at
   4: rust_analyzer::handlers::handle_completion
   5: rust_analyzer::dispatch::RequestDispatcher::on::{{closure}}::{{closure}}
   6: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 12:13:14 PM] Request textDocument/completion failed.
  Message: server panicked: byte index 3 is not a char boundary; it is inside '⊞' (bytes 1..4) of `"⊞:"`
  Code: -32603 

```

**Comment by Veykril** [comment]
The problem here seems to be this code https://github.com/rust-analyzer/rust-analyzer/blob/c45792ae8f1e39aba86d2999482ee9f1a7c6e4a5/crates/rust-analyzer/src/handlers.rs#L735-L736

which tries to walk back to the char before the typed `:` which will then index one byte into the multibyte char as this assumes the char there to be a single byte one.
