### ISSUE TITLE
thread '<unnamed>' panicked at 'assertion failed: start <= end'

### ISSUE THREAD

**Issue by it0946** [rust-analyzer/rust-analyzer#10243]
When writing `as` for `as_ref()` I receive an error that rust-analyzer panics.
Snippet where it occurs:
```rust
impl std::fmt::Display for Position {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if let Some(_) = self.line {
            return write!(f, "file: {}, line: {}, col: {}, current: {}", 
                self.file.as_ref().unwrap(), self.line.as_ref().unwrap(), self.column, self.current);
               //          ^ panic here and                ^ here
        }
        write!(f, "col: {}, current: {}", self.column, self.current)
    }
}
```
rust-analyzer output:
```
Panic context:
> 
version: 516eb40ba 2021-09-13 stable
request: textDocument/completion CompletionParams {
    text_document_position: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                cannot_be_a_base: false,
                username: "",
                password: None,
                host: None,
                port: None,
                path: "/home/it/Dev/obpy/src/main.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 54,
            character: 57,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    context: Some(
        CompletionContext {
            trigger_kind: TriggerForIncompleteCompletions,
            trigger_character: None,
        },
    ),
}

thread '<unnamed>' panicked at 'assertion failed: start <= end', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/text-size-1.1.0/src/range.rs:48:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:50:5
   3: ide_completion::completions::postfix::postfix_snippet
   4: ide_completion::completions::postfix::complete_postfix
   5: ide_completion::completions
   6: std::panicking::try
   7: rust_analyzer::handlers::handle_completion
   8: std::panicking::try
   9: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 2:22:15 PM] Request textDocument/completion failed.
  Message: server panicked: assertion failed: start <= end
  Code: -32603 
  ```

**Comment by lnicola** [comment]
Can you also post the definition of `Position`? A self-contained test case would be great.

**Comment by it0946** [comment]
Sure, the definition is this:
```rs
struct Position {
    line: Option<usize>,
    column: usize,
    file: Option<String>,
    current: String,
}```

**Comment by iDawer** [comment]
Minimized

```rust
fn foo(bar: Option<String>) {
    format_args!("{}", bar.as$0().unwrap());
}
```

**Comment by it0946** [comment]
> 
> 
> Minimized
> 
> ```rust
> fn foo(bar: Option<String>) {
>     format_args!("{}", bar.as$0().unwrap());
> }
> ```

Oo, thanks I'll have a look at that

**Comment by Veykril** [comment]
The panic trigger should be this line https://github.com/rust-analyzer/rust-analyzer/blob/00b19846c9a50a2bd151375eaf22881f665e560d/crates/ide_completion/src/completions/postfix.rs#L319
