### ISSUE TITLE
Failed to Update

### ISSUE THREAD

**Issue by AurevoirXavier** [rust-analyzer/rust-analyzer#10341]
```
ERROR [9/25/2021, 10:22:16 AM]: Assertion failed: Bad release: {"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/50241099","assets_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/50241099/assets","upload_url":"https://uploads.github.com/repos/rust-analyzer/rust-analyzer/releases/50241099/assets{?name,label}","html_url":"https://github.com/rust-analyzer/rust-analyzer/releases/tag/nightly","id":50241099,"author":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"node_id":"RE_kwDOBttd2s4C_p5L","tag_name":"nightly","target_commitish":"9abea7492e8b83ccca14ba42565c0305c5e36a6c","name":"nightly","draft":false,"prerelease":true,"created_at":"2021-09-24T19:18:15Z","published_at":"2021-09-25T01:20:21Z","assets":[{"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/assets/45573172","id":45573172,"node_id":"RA_kwDOBttd2s4Ct2Q0","name":"rust-analyzer-aarch64-apple-darwin.gz","label":"","uploader":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"content_type":"application/octet-stream","state":"uploaded","size":8510387,"download_count":0,"created_at":"2021-09-25T01:20:22Z","updated_at":"2021-09-25T01:20:22Z","browser_download_url":"https://github.com/rust-analyzer/rust-analyzer/releases/download/nightly/rust-analyzer-aarch64-apple-darwin.gz"},{"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/assets/45573175","id":45573175,"node_id":"RA_kwDOBttd2s4Ct2Q3","name":"rust-analyzer-aarch64-pc-windows-msvc.gz","label":"","uploader":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"content_type":"application/octet-stream","state":"uploaded","size":8022121,"download_count":0,"created_at":"2021-09-25T01:20:23Z","updated_at":"2021-09-25T01:20:23Z","browser_download_url":"https://github.com/rust-analyzer/rust-analyzer/releases/download/nightly/rust-analyzer-aarch64-pc-windows-msvc.gz"}],"tarball_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/tarball/nightly","zipball_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/zipball/nightly","body":null}
ERROR [9/25/2021, 10:22:16 AM]: Bootstrap error AssertionError [ERR_ASSERTION]: Bad release: {"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/50241099","assets_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/50241099/assets","upload_url":"https://uploads.github.com/repos/rust-analyzer/rust-analyzer/releases/50241099/assets{?name,label}","html_url":"https://github.com/rust-analyzer/rust-analyzer/releases/tag/nightly","id":50241099,"author":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"node_id":"RE_kwDOBttd2s4C_p5L","tag_name":"nightly","target_commitish":"9abea7492e8b83ccca14ba42565c0305c5e36a6c","name":"nightly","draft":false,"prerelease":true,"created_at":"2021-09-24T19:18:15Z","published_at":"2021-09-25T01:20:21Z","assets":[{"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/assets/45573172","id":45573172,"node_id":"RA_kwDOBttd2s4Ct2Q0","name":"rust-analyzer-aarch64-apple-darwin.gz","label":"","uploader":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"content_type":"application/octet-stream","state":"uploaded","size":8510387,"download_count":0,"created_at":"2021-09-25T01:20:22Z","updated_at":"2021-09-25T01:20:22Z","browser_download_url":"https://github.com/rust-analyzer/rust-analyzer/releases/download/nightly/rust-analyzer-aarch64-apple-darwin.gz"},{"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/assets/45573175","id":45573175,"node_id":"RA_kwDOBttd2s4Ct2Q3","name":"rust-analyzer-aarch64-pc-windows-msvc.gz","label":"","uploader":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"content_type":"application/octet-stream","state":"uploaded","size":8022121,"download_count":0,"created_at":"2021-09-25T01:20:23Z","updated_at":"2021-09-25T01:20:23Z","browser_download_url":"https://github.com/rust-analyzer/rust-analyzer/releases/download/nightly/rust-analyzer-aarch64-pc-windows-msvc.gz"}],"tarball_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/tarball/nightly","zipball_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/zipball/nightly","body":null}
    at fn (/root/.vscode-server/extensions/matklad.rust-analyzer-0.2.751/out/main.js:50:2696)
    at m_ (/root/.vscode-server/extensions/matklad.rust-analyzer-0.2.751/out/main.js:96:2886)
    at g_ (/root/.vscode-server/extensions/matklad.rust-analyzer-0.2.751/out/main.js:96:1823)
    at p_ (/root/.vscode-server/extensions/matklad.rust-analyzer-0.2.751/out/main.js:95:6867)
    at bv (/root/.vscode-server/extensions/matklad.rust-analyzer-0.2.751/out/main.js:95:6698)
    at async Promise.all (index 0)
    at v.$activate (/root/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/out/vs/server/remoteExtensionHostProcess.js:99:20108) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

**Comment by AurevoirXavier** [comment]
Switch to `default` channel fixed.

**Comment by bjorn3** [comment]
There was a spurious connection error while uploading the latest release from CI: https://github.com/rust-analyzer/rust-analyzer/runs/3705985493?check_suite_focus=true#step:17:89

**Comment by jondo2010** [comment]
> Fix by switching to `default` channel.

Still not working for me on MacOS VSCode stable

**Comment by AurevoirXavier** [comment]
> > Fix by switching to `default` channel.
> 
> Still not working for me on MacOS VSCode stable

Stable-Rust-Analyzer

Not Stable-VSCode

**Comment by Veykril** [comment]
Triggered a new nightly release which should fix the update failure in a bit

**Comment by Veykril** [comment]
should work again now
