### ISSUE TITLE
Bootstrap error EntryExists (FileSystemError): Unable to move/copy '...' because target '...' already exists at destination.

### ISSUE THREAD

**Issue by samuela** [rust-analyzer/rust-analyzer#10379]
Just got this error today, and seems to happen every time I try to open up VSCode. I'm using VSCode Remote - SSH, connecting to a NixOS 21.05.3065.b3083bc6933 machine.

I haven't changed any configurations recently, so I'm not sure what could have caused this. Perhaps an extension version upgrade? Happy to provide any other diagnostics.

"Rust Analyzer Client" logs:
```
INFO [9/27/2021, 7:38:25 PM]: Extension version: 0.2.760
INFO [9/27/2021, 7:38:25 PM]: Using configuration {
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    smallerHints: true,
    chainingHints: true,
    maxLength: 25,
    parameterHints: true,
    typeHints: true
  },
  updates: { channel: 'stable', askBeforeDownload: false },
  server: { path: null, extraEnv: null },
  trace: { server: 'off', extension: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  assist: {
    importGranularity: 'crate',
    importEnforceGranularity: false,
    importPrefix: 'plain',
    importGroup: true,
    allowMergingIntoGlobImports: true
  },
  callInfo: { full: true },
  cargo: {
    autoreload: true,
    allFeatures: false,
    unsetTest: [ 'core' ],
    features: [],
    runBuildScripts: true,
    useRustcWrapperForBuildScripts: true,
    noDefaultFeatures: false,
    target: null,
    noSysroot: false
  },
  checkOnSave: {
    enable: true,
    allFeatures: null,
    allTargets: true,
    command: 'check',
    noDefaultFeatures: null,
    target: null,
    extraArgs: [],
    features: null,
    overrideCommand: null
  },
  completion: {
    addCallArgumentSnippets: true,
    addCallParenthesis: true,
    postfix: { enable: true },
    autoimport: { enable: true },
    autoself: { enable: true }
  },
  diagnostics: {
    enable: true,
    enableExperimental: true,
    disabled: [],
    remapPrefix: {},
    warningsAsHint: [],
    warningsAsInfo: []
  },
  experimental: { procAttrMacros: false },
  files: { watcher: 'client', excludeDirs: [] },
  highlightRelated: {
    references: true,
    exitPoints: true,
    breakPoints: true,
    yieldPoints: true
  },
  highlighting: { strings: true },
  hover: { documentation: true, linksInHover: true },
  hoverActions: {
    debug: true,
    enable: true,
    gotoTypeDef: true,
    implementations: true,
    references: false,
    run: true
  },
  joinLines: {
    joinElseIf: true,
    removeTrailingComma: true,
    unwrapTrivialBlock: true,
    joinAssignments: true
  },
  lens: {
    debug: true,
    enable: true,
    implementations: true,
    run: true,
    methodReferences: false,
    references: false,
    forceCustomCommands: true
  },
  linkedProjects: [],
  lruCapacity: null,
  notifications: { cargoTomlNotFound: true },
  procMacro: { enable: true, server: null },
  runnables: { overrideCargo: null, cargoExtraArgs: [] },
  rustcSource: null,
  rustfmt: {
    extraArgs: [],
    overrideCommand: null,
    enableRangeFormatting: false
  },
  workspace: { symbol: { search: { scope: 'workspace', kind: 'only_types' } } }
}
INFO [9/27/2021, 7:38:25 PM]: PersistentState: {
  lastCheck: undefined,
  nightlyReleaseId: undefined,
  serverVersion: undefined
}
INFO [9/27/2021, 7:38:28 PM]: Renamed old server binary /home/skainswo/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu to /home/skainswo/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu-stale-c30fce0c27
INFO [9/27/2021, 7:38:29 PM]: Removed old server binary /home/skainswo/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu-stale-c30fce0c27
ERROR [9/27/2021, 7:38:30 PM]: Bootstrap error EntryExists (FileSystemError): Unable to move/copy 'vscode-remote://ssh-remote+doodoo/home/skainswo/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu' because target 'vscode-remote://ssh-remote+doodoo/home/skainswo/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu-orig' already exists at destination.
    at _handleError (/home/skainswo/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/out/vs/server/remoteExtensionHostProcess.js:94:159993)
    at /home/skainswo/.vscode-server/extensions/matklad.rust-analyzer-0.2.760/out/main.js:108:47 {
  code: 'FileExists'
}
```

**Comment by lnicola** [comment]
On NixOS, we run `patchelf` on a temporary copy of the server binary and we didn't overwrite a previous copy if it was left there. If you haven't removed that file yet, you might want to give #10422 a try. It should be available in the next nightly and in the Monday release.
