### ISSUE TITLE
`Can't find MACRO_CALL@0..11 in AstIdMap` after #10305

### ISSUE THREAD

**Issue by cynecx** [rust-analyzer/rust-analyzer#10388]
Repro:

```rust
macro_rules! U32Inner {
    () => {
        u32
    };
}

macro_rules! U32 {
    () => {
        U32Inner!()
    };
}

fn mamba(a: U32!(), p: u32) {
    a
}
```

<details>
<summary>Panic logs</summary>

```
thread '<unnamed>' panicked at 'Can't find MACRO_CALL@0..11 in AstIdMap:
[SyntaxNodePtr { range: 0..56, kind: MACRO_RULES }, SyntaxNodePtr { range: 58..117, kind: MACRO_RULES }, SyntaxNodePtr { range: 119..156, kind: FN }, SyntaxNodePtr { range: 131..137, kind: MACRO_CALL }, SyntaxNodePtr { range: 147..156, kind: BLOCK_EXPR }]', crates/hir_expand/src/ast_id_map.rs:103:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8f8092cc32ec171becef8ceacec7dbb06c5d7d7e/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/8f8092cc32ec171becef8ceacec7dbb06c5d7d7e/library/std/src/panicking.rs:460:5
   2: hir_expand::ast_id_map::AstIdMap::erased_ast_id
   3: hir_def::type_ref::TypeRef::from_ast
   4: hir_def::type_ref::TypeRef::walk::go
   5: hir_def::generics::GenericParams::generic_params_query
   6: salsa::runtime::Runtime::execute_query_implementation
   7: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   8: salsa::derived::slot::Slot<Q,MP>::read
   9: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  10: <DB as hir_def::db::DefDatabase>::generic_params
  11: <hir_def::DefWithBodyId as hir_def::resolver::HasResolver>::resolver
  12: hir_ty::infer::infer_query
  13: salsa::runtime::Runtime::execute_query_implementation
  14: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  17: salsa::QueryTable<Q>::get
  18: <DB as hir_ty::db::HirDatabase>::infer_query
  19: hir_ty::db::infer_wait
  20: hir::DefWithBody::diagnostics
  21: hir::ModuleDef::diagnostics
  22: hir::Module::diagnostics
  23: ide_diagnostics::diagnostics
  24: salsa::Cancelled::catch
  25: rust_analyzer::handlers::publish_diagnostics
  26: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  27: alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  28: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 2b76d8781 2021-09-29 dev
request: textDocument/semanticTokens/full/delta SemanticTokensDeltaParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/cynecx/dev/testrust/src/ter.rs",
            query: None,
            fragment: None,
        },
    },
    previous_result_id: "43",
}

thread '<unnamed>' panicked at 'Can't find MACRO_CALL@0..11 in AstIdMap:
[SyntaxNodePtr { range: 0..56, kind: MACRO_RULES }, SyntaxNodePtr { range: 58..117, kind: MACRO_RULES }, SyntaxNodePtr { range: 119..156, kind: FN }, SyntaxNodePtr { range: 131..137, kind: MACRO_CALL }, SyntaxNodePtr { range: 147..156, kind: BLOCK_EXPR }]', crates/hir_expand/src/ast_id_map.rs:103:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8f8092cc32ec171becef8ceacec7dbb06c5d7d7e/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/8f8092cc32ec171becef8ceacec7dbb06c5d7d7e/library/std/src/panicking.rs:460:5
   2: hir_expand::ast_id_map::AstIdMap::erased_ast_id
   3: hir_def::type_ref::TypeRef::from_ast
   4: hir_def::type_ref::TypeRef::walk::go
   5: hir_def::generics::GenericParams::generic_params_query
   6: salsa::runtime::Runtime::execute_query_implementation
   7: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   8: salsa::derived::slot::Slot<Q,MP>::read
   9: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  10: <DB as hir_def::db::DefDatabase>::generic_params
  11: <hir_def::FunctionId as hir_def::resolver::HasResolver>::resolver
  12: <hir::Function as hir::HasVisibility>::visibility
  13: <hir::ModuleDef as hir::HasVisibility>::visibility
  14: ide::syntax_highlighting::highlight::highlight_def
  15: ide::syntax_highlighting::highlight::element
  16: ide::syntax_highlighting::traverse
  17: ide::syntax_highlighting::highlight
  18: std::panicking::try
  19: rust_analyzer::handlers::handle_semantic_tokens_full_delta
  20: std::panicking::try
  21: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 8:40:39 PM] Request textDocument/semanticTokens/full/delta failed.
  Message: server panicked: Can't find MACRO_CALL@0..11 in AstIdMap:
[SyntaxNodePtr { range: 0..56, kind: MACRO_RULES }, SyntaxNodePtr { range: 58..117, kind: MACRO_RULES }, SyntaxNodePtr { range: 119..156, kind: FN }, SyntaxNodePtr { range: 131..137, kind: MACRO_CALL }, SyntaxNodePtr { range: 147..156, kind: BLOCK_EXPR }]
  Code: -32603 
Panic context:
> 
version: 2b76d8781 2021-09-29 dev
request: rust-analyzer/inlayHints InlayHintsParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/cynecx/dev/testrust/src/ter.rs",
            query: None,
            fragment: None,
        },
    },
}

thread '<unnamed>' panicked at 'Can't find MACRO_CALL@0..11 in AstIdMap:
[SyntaxNodePtr { range: 0..56, kind: MACRO_RULES }, SyntaxNodePtr { range: 58..117, kind: MACRO_RULES }, SyntaxNodePtr { range: 119..156, kind: FN }, SyntaxNodePtr { range: 131..137, kind: MACRO_CALL }, SyntaxNodePtr { range: 147..156, kind: BLOCK_EXPR }]', crates/hir_expand/src/ast_id_map.rs:103:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8f8092cc32ec171becef8ceacec7dbb06c5d7d7e/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/8f8092cc32ec171becef8ceacec7dbb06c5d7d7e/library/std/src/panicking.rs:460:5
   2: hir_expand::ast_id_map::AstIdMap::erased_ast_id
   3: hir_def::type_ref::TypeRef::from_ast
   4: hir_def::type_ref::TypeRef::walk::go
   5: hir_def::generics::GenericParams::generic_params_query
   6: salsa::runtime::Runtime::execute_query_implementation
   7: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   8: salsa::derived::slot::Slot<Q,MP>::read
   9: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  10: <DB as hir_def::db::DefDatabase>::generic_params
  11: <hir_def::DefWithBodyId as hir_def::resolver::HasResolver>::resolver
  12: hir_def::resolver::resolver_for_scope
  13: hir::source_analyzer::SourceAnalyzer::new_for_body
  14: hir::semantics::SemanticsImpl::analyze_impl
  15: hir::semantics::SemanticsImpl::descend_node_into_attributes
  16: ide::inlay_hints::inlay_hints
  17: salsa::Cancelled::catch
  18: rust_analyzer::handlers::handle_inlay_hints
  19: std::panicking::try
  20: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 2b76d8781 2021-09-29 dev
request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/cynecx/dev/testrust/src/ter.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 14,
            character: 1,
        },
        end: Position {
            line: 14,
            character: 1,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'Can't find MACRO_CALL@0..11 in AstIdMap:
[SyntaxNodePtr { range: 0..56, kind: MACRO_RULES }, SyntaxNodePtr { range: 58..117, kind: MACRO_RULES }, SyntaxNodePtr { range: 119..156, kind: FN }, SyntaxNodePtr { range: 131..137, kind: MACRO_CALL }, SyntaxNodePtr { range: 147..156, kind: BLOCK_EXPR }]', crates/hir_expand/src/ast_id_map.rs:103:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8f8092cc32ec171becef8ceacec7dbb06c5d7d7e/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/8f8092cc32ec171becef8ceacec7dbb06c5d7d7e/library/std/src/panicking.rs:460:5
   2: hir_expand::ast_id_map::AstIdMap::erased_ast_id
   3: hir_def::type_ref::TypeRef::from_ast
   4: hir_def::type_ref::TypeRef::walk::go
   5: hir_def::generics::GenericParams::generic_params_query
   6: salsa::runtime::Runtime::execute_query_implementation
   7: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   8: salsa::derived::slot::Slot<Q,MP>::read
   9: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  10: <DB as hir_def::db::DefDatabase>::generic_params
  11: <hir_def::DefWithBodyId as hir_def::resolver::HasResolver>::resolver
  12: hir_ty::infer::infer_query
  13: salsa::runtime::Runtime::execute_query_implementation
  14: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  17: salsa::QueryTable<Q>::get
  18: <DB as hir_ty::db::HirDatabase>::infer_query
  19: hir_ty::db::infer_wait
  20: hir::DefWithBody::diagnostics
  21: hir::ModuleDef::diagnostics
  22: hir::Module::diagnostics
  23: ide_diagnostics::diagnostics
  24: std::panicking::try
  25: salsa::Cancelled::catch
  26: rust_analyzer::handlers::handle_code_action
  27: std::panicking::try
  28: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

rust-analyzer: 9e3e98db8ac9374916e76de42e6710dc23caacbc (Current master)

Reverting #10305 fixes this.

The position of the "macro type" (`U32!()`) is important (as param type) and triggers the panic, whereas putting it somewhere else (let binding) doesn't trigger the panic.

It works fine when `U32` doesn't have a nested macro call:

```rust
// doesn't panic with this
macro_rules! U32 {
    () => {
        u32
    };
}
```

~~It looks like the problem is that we are not expanding nested macro calls in #10388.~~

cc @SkiFire13, @flodiebold

**Comment by SkiFire13** [comment]
The problem is that nested macros were expanded, but using the wrong `HirFileId` for the `LowerCtx`. #10389 should fix this
