### ISSUE TITLE
nightly release does not work

### ISSUE THREAD

**Issue by jhgg** [rust-analyzer/rust-analyzer#10681]
i think nightly release is broken, upon trying to update, r-a's vscode extenion throws here: 

https://github.com/rust-analyzer/rust-analyzer/blob/c88277f67661957b9be5fd75a1cc1625e39746d7/editors/code/src/main.ts#L224

I think it is because it cannot find the `rust-analyzer.vsix` in https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/52561265

**Comment by jhgg** [comment]
looks like the GH action failed: https://github.com/rust-analyzer/rust-analyzer/runs/4087124282?check_suite_focus=true

Notably github 500'ed on uploading an asset to the release, so the release is incomplete.

**Comment by AurevoirXavier** [comment]
```
DEBUG [11/3/2021, 10:33:12 AM]: Issuing request for released artifacts metadata to https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/nightly
ERROR [11/3/2021, 10:33:13 AM]: Assertion failed: Bad release: {"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/52561265","assets_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/52561265/assets","upload_url":"https://uploads.github.com/repos/rust-analyzer/rust-analyzer/releases/52561265/assets{?name,label}","html_url":"https://github.com/rust-analyzer/rust-analyzer/releases/tag/nightly","id":52561265,"author":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"node_id":"RE_kwDOBttd2s4DIgVx","tag_name":"nightly","target_commitish":"04f03a360ab8fef3d9c0ff84de2d39b8a196c717","name":"nightly","draft":false,"prerelease":true,"created_at":"2021-10-31T10:16:59Z","published_at":"2021-11-03T00:32:27Z","assets":[{"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/assets/48481928","id":48481928,"node_id":"RA_kwDOBttd2s4C48aI","name":"rust-analyzer-aarch64-apple-darwin.gz","label":"","uploader":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"content_type":"application/octet-stream","state":"uploaded","size":8680056,"download_count":1,"created_at":"2021-11-03T00:32:27Z","updated_at":"2021-11-03T00:32:27Z","browser_download_url":"https://github.com/rust-analyzer/rust-analyzer/releases/download/nightly/rust-analyzer-aarch64-apple-darwin.gz"}],"tarball_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/tarball/nightly","zipball_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/zipball/nightly","body":null}
ERROR [11/3/2021, 10:33:13 AM]: Bootstrap error AssertionError [ERR_ASSERTION]: Bad release: {"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/52561265","assets_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/52561265/assets","upload_url":"https://uploads.github.com/repos/rust-analyzer/rust-analyzer/releases/52561265/assets{?name,label}","html_url":"https://github.com/rust-analyzer/rust-analyzer/releases/tag/nightly","id":52561265,"author":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"node_id":"RE_kwDOBttd2s4DIgVx","tag_name":"nightly","target_commitish":"04f03a360ab8fef3d9c0ff84de2d39b8a196c717","name":"nightly","draft":false,"prerelease":true,"created_at":"2021-10-31T10:16:59Z","published_at":"2021-11-03T00:32:27Z","assets":[{"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/assets/48481928","id":48481928,"node_id":"RA_kwDOBttd2s4C48aI","name":"rust-analyzer-aarch64-apple-darwin.gz","label":"","uploader":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"content_type":"application/octet-stream","state":"uploaded","size":8680056,"download_count":1,"created_at":"2021-11-03T00:32:27Z","updated_at":"2021-11-03T00:32:27Z","browser_download_url":"https://github.com/rust-analyzer/rust-analyzer/releases/download/nightly/rust-analyzer-aarch64-apple-darwin.gz"}],"tarball_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/tarball/nightly","zipball_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/zipball/nightly","body":null}
    at fn (/root/.vscode-server/extensions/matklad.rust-analyzer-0.2.801/out/main.js:50:2696)
    at v_ (/root/.vscode-server/extensions/matklad.rust-analyzer-0.2.801/out/main.js:96:2886)
    at m_ (/root/.vscode-server/extensions/matklad.rust-analyzer-0.2.801/out/main.js:96:1823)
    at h_ (/root/.vscode-server/extensions/matklad.rust-analyzer-0.2.801/out/main.js:95:6852)
    at Tv (/root/.vscode-server/extensions/matklad.rust-analyzer-0.2.801/out/main.js:95:6683)
    at async Promise.all (index 0) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

**Comment by AurevoirXavier** [comment]
Workaround: Use stable.

**Comment by lnicola** [comment]
Can you try again?

**Comment by AurevoirXavier** [comment]
> Can you try again?

Works.

**Comment by jhgg** [comment]
Works now!
