### ISSUE TITLE
Always fails on servo / does too much

### ISSUE THREAD

**Issue by Florian-Schoenherr** [rust-analyzer/rust-analyzer#10730]
I'm getting this error on servo:
```
[ERROR rust_analyzer::reload] failed to switch build data: rust-analyzer failed to run build scripts:
error: failed to run custom build command for `simpleservo_jniapi v0.0.1 (D:\projects\servo\servo\ports\libsimpleservo\jniapi)`

Caused by:
  process didn't exit successfully: `d:\projects\servo\servo\target\debug\build\simpleservo_jniapi-33f3c5db101519e6\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Please set the ANDROID_NDK environment variable', ports\libsimpleservo\jniapi\build.rs:11:36
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/e249ce6b2345587d6e11052779c86adbad626dff\/library\std\src\panicking.rs:495
     1: core::panicking::panic_fmt
               at /rustc/e249ce6b2345587d6e11052779c86adbad626dff\/library\core\src\panicking.rs:106
     2: core::panicking::panic_display<str>
               at /rustc/e249ce6b2345587d6e11052779c86adbad626dff\/library\core\src\panicking.rs:62
     3: core::option::expect_failed
               at /rustc/e249ce6b2345587d6e11052779c86adbad626dff\/library\core\src\option.rs:1638
     4: enum$<core::option::Option<std::ffi::os_str::OsString>, 1, 18446744073709551615, Some>::expect<std::ffi::os_str::OsString>
               at /rustc/e249ce6b2345587d6e11052779c86adbad626dff\library\core\src\option.rs:709
     5: build_script_build::main
               at .\build.rs:11
     6: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
               at /rustc/e249ce6b2345587d6e11052779c86adbad626dff\library\core\src\ops\function.rs:227
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: build failed
```
- in servo's root directory
- tried using `"rust-analyzer.cargo.runBuildScripts": false`
- building servo does work
- uncommenting `"ports/libsimpleservo/jniapi/"` in the root Cargo.toml works, next error is:
```
failed to run custom build command for `openssl-sys v0.9.67`
[...]
note: vcpkg did not find openssl: Could not find Vcpkg tree: No vcpkg installation found. Set the VCPKG_ROOT environment variable or run 'vcpkg integrate install'
```
which happens in `servo/components/net`

Maybe it's more of a question why rust-analyzer seems to look through everything under the root dir?

If I switch to `servo/components/allocator`, which has it's own `Cargo.toml`, rust-analyzer will still try to index/run build scripts on the root `servo` dir.
I don't know how rust-analyzer works internally, but it seems to do a little "too much".
I'm mainly confused because building/running servo works, but this here doesn't

**Comment by bjorn3** [comment]
> Maybe it's more of a question why rust-analyzer seems to look through everything under the root dir?

It passes `--workspace` to cargo which builds the entire workspace: https://github.com/rust-analyzer/rust-analyzer/blob/bfb8f73fb3f8a1a7fadfa31bda98a17549a91093/crates/flycheck/src/lib.rs#L214

**Comment by bjorn3** [comment]
`servo/components/allocator` is part of the servo workspace: https://github.com/servo/servo/blob/9693111c9744407730d7fc971a33800a831d575e/Cargo.toml#L1 (it is not explicitly listed, but it is a part because it is an indirect dependency of one of the explicit workspace members and inside a subdir of the workspace root)

**Comment by Florian-Schoenherr** [comment]
I got that too, but let's just say I take a component like `allocator` and move it to a completely different location.
Now rust-analyzer works (due to the different target-folder and Cargo.lock) - but can that be achieved without moving?
The usecase might be very specific, but these modular sub-components, depending on nothing else, should be buildable without building the entire browser every time.

**Comment by matklad** [comment]
>I don't know how rust-analyzer works internally, but it seems to do a little "too much".

Yeah, that's a surprisingly deep thing. This is needed to make "find usages" and refactorings work. Say, you invoke "rename" on some method in the crate you are working on. The IDE should then update all usages,  which are in *reverse* dependencies. That is, we need direct dependencies to analyze a particular crate, but we need reverse deps to make refactors useful.

Today, rust-analyzer assumes that "Cargo workspace" is the unit of code you are working on. I can see us providing some extra toggles to tweak this behavior. This is something we need to think about long-term anyway -- if you workspace is google-scale monorepo, you probably don't *want* a refactor to update the code across monorepo. Though, you might want "find usages" to still work.

**Comment by Florian-Schoenherr** [comment]
@matklad iirc the most confusing part was when I went into one of servos sub-crate folders and ran rust-analyzer, I thought the sub-crate's Cargo.toml would be "used".
This would be a nice default, or maybe another config-option?
Although now I just remembered that the current default is coupled to how Cargo works, right?

**Comment by matklad** [comment]
Yeah, this all is true. I've opened https://github.com/rust-analyzer/rust-analyzer/issues/11181 for that.
