### ISSUE TITLE
Unable to Update Rust Analyzer With Nightly Channel on Visual Studio Code

### ISSUE THREAD

**Issue by ShabbirHasan1** [rust-analyzer/rust-analyzer#10814]
When I opened vscode today (2021-11-20 07:12:10 AM IST)  i've got a New version of rust-analyzer (nightly) is available (requires reload). message. I've clicked on it and got the following error: Cannot activate rust-analyzer: bootstrap error.

The "Rust Analyzer Client" trace are as follows:

```INFO [11/20/2021, 7:12:10 AM]: Extension version: 0.3.821
INFO [11/20/2021, 7:12:10 AM]: Using configuration {
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    smallerHints: true,
    chainingHints: true,
    maxLength: 25,
    parameterHints: true,
    typeHints: true,
    hideNamedConstructorHints: false
  },
  updates: { channel: 'nightly', askBeforeDownload: false },
  server: { path: null, extraEnv: null },
  trace: { server: 'off', extension: true },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: true,
    engineSettings: {}
  },
  assist: {
    importGranularity: 'crate',
    importEnforceGranularity: false,
    importPrefix: 'plain',
    importGroup: true,
    allowMergingIntoGlobImports: true
  },
  callInfo: { full: true },
  cargo: {
    autoreload: true,
    allFeatures: true,
    unsetTest: [ 'core' ],
    features: [],
    runBuildScripts: true,
    useRustcWrapperForBuildScripts: true,
    noDefaultFeatures: false,
    target: null,
    noSysroot: false
  },
  checkOnSave: {
    enable: true,
    allFeatures: null,
    allTargets: true,
    command: 'check',
    noDefaultFeatures: null,
    target: null,
    extraArgs: [],
    features: null,
    overrideCommand: null
  },
  completion: {
    addCallArgumentSnippets: true,
    addCallParenthesis: true,
    snippets: {},
    postfix: { enable: true },
    autoimport: { enable: true },
    autoself: { enable: true }
  },
  diagnostics: {
    enable: true,
    enableExperimental: true,
    disabled: [],
    remapPrefix: {},
    warningsAsHint: [],
    warningsAsInfo: []
  },
  experimental: { procAttrMacros: true },
  files: { watcher: 'client', excludeDirs: [] },
  highlightRelated: {
    references: true,
    exitPoints: true,
    breakPoints: true,
    yieldPoints: true
  },
  highlighting: { strings: true },
  hover: { documentation: true, linksInHover: true },
  hoverActions: {
    debug: true,
    enable: true,
    gotoTypeDef: true,
    implementations: true,
    references: true,
    run: true
  },
  joinLines: {
    joinElseIf: true,
    removeTrailingComma: true,
    unwrapTrivialBlock: true,
    joinAssignments: true
  },
  lens: {
    debug: true,
    enable: true,
    implementations: true,
    run: true,
    methodReferences: true,
    references: true,
    enumVariantReferences: true,
    forceCustomCommands: true
  },
  linkedProjects: [],
  lruCapacity: null,
  notifications: { cargoTomlNotFound: true },
  procMacro: { enable: true, server: null },
  runnables: { overrideCargo: null, cargoExtraArgs: [] },
  rustcSource: null,
  rustfmt: { extraArgs: [], overrideCommand: null, enableRangeFormatting: true },
  workspace: { symbol: { search: { scope: 'workspace', kind: 'only_types' } } }
}
INFO [11/20/2021, 7:12:10 AM]: PersistentState: {
  lastCheck: 1637286890029,
  nightlyReleaseId: 53684944,
  serverVersion: '0.3.821'
}
DEBUG [11/20/2021, 7:12:11 AM]: Issuing request for released artifacts metadata to https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/nightly
ERROR [11/20/2021, 7:12:15 AM]: Assertion failed: Bad release: {"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/53758884","assets_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/53758884/assets","upload_url":"https://uploads.github.com/repos/rust-analyzer/rust-analyzer/releases/53758884/assets{?name,label}","html_url":"https://github.com/rust-analyzer/rust-analyzer/releases/tag/nightly","id":53758884,"author":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"node_id":"RE_kwDOBttd2s4DNEuk","tag_name":"nightly","target_commitish":"14dff25107cec4473fde8c999256a3484a7ef1d0","name":"nightly","draft":false,"prerelease":true,"created_at":"2021-11-19T20:02:26Z","published_at":"2021-11-20T00:37:06Z","assets":[],"tarball_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/tarball/nightly","zipball_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/zipball/nightly","body":null}
ERROR [11/20/2021, 7:12:15 AM]: Bootstrap error AssertionError [ERR_ASSERTION]: Bad release: {"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/53758884","assets_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/53758884/assets","upload_url":"https://uploads.github.com/repos/rust-analyzer/rust-analyzer/releases/53758884/assets{?name,label}","html_url":"https://github.com/rust-analyzer/rust-analyzer/releases/tag/nightly","id":53758884,"author":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"node_id":"RE_kwDOBttd2s4DNEuk","tag_name":"nightly","target_commitish":"14dff25107cec4473fde8c999256a3484a7ef1d0","name":"nightly","draft":false,"prerelease":true,"created_at":"2021-11-19T20:02:26Z","published_at":"2021-11-20T00:37:06Z","assets":[],"tarball_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/tarball/nightly","zipball_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/zipball/nightly","body":null}
    at fn (/home/n0ak95/.vscode-remote/extensions/matklad.rust-analyzer-0.3.821/out/main.js:50:2696)
    at v_ (/home/n0ak95/.vscode-remote/extensions/matklad.rust-analyzer-0.3.821/out/main.js:96:2886)
    at m_ (/home/n0ak95/.vscode-remote/extensions/matklad.rust-analyzer-0.3.821/out/main.js:96:1823)
    at h_ (/home/n0ak95/.vscode-remote/extensions/matklad.rust-analyzer-0.3.821/out/main.js:95:6927)
    at Tv (/home/n0ak95/.vscode-remote/extensions/matklad.rust-analyzer-0.3.821/out/main.js:95:6758)
    at async Promise.all (index 1) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```
@matklad, please take a look.

**Comment by kassens** [comment]
Some artifact was missing and seems like a second attempt that @Veykril kicked off fixed the release: https://github.com/rust-analyzer/rust-analyzer/runs/4271494886?check_suite_focus=true

**Comment by lnicola** [comment]
This happens from time to time with the nightly version when either the GitHub or Marketplace upload fails. If it stops working, you can switch back to the stable version.

**Comment by ShabbirHasan1** [comment]
> This happens from time to time with the nightly version when either the GitHub or Marketplace upload fails. If it stops working, you can switch back to the stable version.

Thanks, Will do the same if it fails next time. For now, with the fix its working as intended.

**Comment by ShabbirHasan1** [comment]
> Some artifact was missing and seems like a second attempt that @Veykril kicked off fixed the release: https://github.com/rust-analyzer/rust-analyzer/runs/4271494886?check_suite_focus=true

Thank You for such a prompt fix.
