### ISSUE TITLE
 bootstrap error. i cannot solve it, i am terribly upset

### ISSUE THREAD

**Issue by Qyanjia** [rust-analyzer/rust-analyzer#10983]
ERROR [2021/12/11下午4:13:08]: Bootstrap error [kr: request to https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/2021-12-06 failed, reason: connect ECONNREFUSED 127.0.0.1
	at ClientRequest.<anonymous> (/home/qinyanjia/.vscode/extensions/matklad.rust-analyzer-0.2.842/out/main.js:106:19695)
	at ClientRequest.emit (events.js:315:20)
	at g (/home/qinyanjia/.vscode/extensions/matklad.rust-analyzer-0.2.842/out/main.js:55:1343)
	at b (/home/qinyanjia/.vscode/extensions/matklad.rust-analyzer-0.2.842/out/main.js:55:1541)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  erroredSysCall: 'connect'
}

**Comment by lnicola** [comment]
Are you you using a proxy?

**Comment by Qyanjia** [comment]
> Are you using a proxy?

yes, i use the proxy. 
But i solved the problem by loading last version v0.2.834, rather than latest version

**Comment by lnicola** [comment]
Is your proxy 127.0.0.1? The error was "Connection refused", meaning that the proxy server was not running.

**Comment by Veykril** [comment]
Closing as it sounds like this has been solved.

**Comment by lnicola** [comment]
We should no longer download any binaries for stable releases so yes, this should have been fixed.
