### ISSUE TITLE
Cannot activate rust-analyzer

### ISSUE THREAD

**Issue by Andy-Python-Programmer** [rust-analyzer/rust-analyzer#11055]
When trying to update to the latest rust-analyser version I get the following: 

```
Cannot activate rust-analyzer: bootstrap error. See the logs in "OUTPUT > Rust Analyzer Client" (should open automatically). To enable verbose logs use { "rust-analyzer.trace.extension": true }
```

Logs:
```
INFO [12/19/2021, 1:33:40 PM]: Extension version: 0.3.861
INFO [12/19/2021, 1:33:40 PM]: Using configuration {
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    smallerHints: true,
    chainingHints: true,
    maxLength: 25,
    parameterHints: true,
    typeHints: true,
    hideNamedConstructorHints: false
  },
  updates: { channel: 'nightly', askBeforeDownload: false },
  server: { path: null, extraEnv: null },
  trace: { server: 'off', extension: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  assist: {
    importGranularity: 'crate',
    importEnforceGranularity: false,
    importPrefix: 'plain',
    importGroup: true,
    allowMergingIntoGlobImports: true
  },
  cache: { warmup: true },
  callInfo: { full: true },
  cargo: {
    autoreload: true,
    allFeatures: false,
    unsetTest: [ 'core' ],
    features: [],
    runBuildScripts: true,
    useRustcWrapperForBuildScripts: true,
    noDefaultFeatures: false,
    target: null,
    noSysroot: false
  },
  checkOnSave: {
    enable: true,
    allFeatures: null,
    allTargets: false,
    command: 'check',
    noDefaultFeatures: null,
    target: null,
    extraArgs: [ '-Zbuild-std=core,alloc' ],
    features: null,
    overrideCommand: null
  },
  completion: {
    addCallArgumentSnippets: true,
    addCallParenthesis: true,
    snippets: {
      'Arc::new': {
        postfix: 'arc',
        body: 'Arc::new(${receiver})',
        requires: 'std::sync::Arc',
        description: 'Put the expression into an `Arc`',
        scope: 'expr'
      },
      'Rc::new': {
        postfix: 'rc',
        body: 'Rc::new(${receiver})',
        requires: 'std::rc::Rc',
        description: 'Put the expression into an `Rc`',
        scope: 'expr'
      },
      'Box::pin': {
        postfix: 'pinbox',
        body: 'Box::pin(${receiver})',
        requires: 'std::boxed::Box',
        description: 'Put the expression into a pinned `Box`',
        scope: 'expr'
      },
      Ok: {
        postfix: 'ok',
        body: 'Ok(${receiver})',
        description: 'Wrap the expression in a `Result::Ok`',
        scope: 'expr'
      },
      Err: {
        postfix: 'err',
        body: 'Err(${receiver})',
        description: 'Wrap the expression in a `Result::Err`',
        scope: 'expr'
      },
      Some: {
        postfix: 'some',
        body: 'Some(${receiver})',
        description: 'Wrap the expression in an `Option::Some`',
        scope: 'expr'
      }
    },
    postfix: { enable: true },
    autoimport: { enable: true },
    autoself: { enable: true }
  },
  diagnostics: {
    enable: true,
    enableExperimental: true,
    disabled: [],
    remapPrefix: {},
    warningsAsHint: [],
    warningsAsInfo: []
  },
  experimental: { procAttrMacros: true },
  files: { watcher: 'client', excludeDirs: [] },
  highlightRelated: {
    references: true,
    exitPoints: true,
    breakPoints: true,
    yieldPoints: true
  },
  highlighting: { strings: true },
  hover: { documentation: true, linksInHover: true },
  hoverActions: {
    debug: true,
    enable: true,
    gotoTypeDef: true,
    implementations: true,
    references: false,
    run: true
  },
  joinLines: {
    joinElseIf: true,
    removeTrailingComma: true,
    unwrapTrivialBlock: true,
    joinAssignments: true
  },
  lens: {
    debug: true,
    enable: true,
    implementations: true,
    run: true,
    methodReferences: false,
    references: false,
    enumVariantReferences: false,
    forceCustomCommands: true
  },
  linkedProjects: [ './src/Cargo.toml', './userland/Cargo.toml' ],
  lruCapacity: null,
  notifications: { cargoTomlNotFound: true },
  procMacro: { enable: true, server: null },
  runnables: { overrideCargo: null, cargoExtraArgs: [] },
  rustcSource: null,
  rustfmt: {
    extraArgs: [],
    overrideCommand: null,
    enableRangeFormatting: false
  },
  workspace: { symbol: { search: { scope: 'workspace', kind: 'only_types' } } }
}
INFO [12/19/2021, 1:33:40 PM]: PersistentState: {
  lastCheck: 1639815021546,
  nightlyReleaseId: 55583095,
  serverVersion: '0.3.861'
}
ERROR [12/19/2021, 1:33:45 PM]: Assertion failed: Bad release: {"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/55609849","assets_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/55609849/assets","upload_url":"https://uploads.github.com/repos/rust-analyzer/rust-analyzer/releases/55609849/assets{?name,label}","html_url":"https://github.com/rust-analyzer/rust-analyzer/releases/tag/nightly","id":55609849,"author":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"node_id":"RE_kwDOBttd2s4DUIn5","tag_name":"nightly","target_commitish":"638cc3e59f09b20e6ca6965ab1f3936e2467c497","name":"nightly","draft":false,"prerelease":true,"created_at":"2021-12-19T00:17:01Z","published_at":"2021-12-19T01:44:26Z","assets":[{"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/assets/52110842","id":52110842,"node_id":"RA_kwDOBttd2s4DGyX6","name":"rust-analyzer-aarch64-apple-darwin.gz","label":"","uploader":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"content_type":"application/octet-stream","state":"uploaded","size":8856890,"download_count":0,"created_at":"2021-12-19T01:44:26Z","updated_at":"2021-12-19T01:44:27Z","browser_download_url":"https://github.com/rust-analyzer/rust-analyzer/releases/download/nightly/rust-analyzer-aarch64-apple-darwin.gz"},{"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/assets/52110843","id":52110843,"node_id":"RA_kwDOBttd2s4DGyX7","name":"rust-analyzer-aarch64-pc-windows-msvc.gz","label":"","uploader":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"content_type":"application/octet-stream","state":"uploaded","size":8318265,"download_count":0,"created_at":"2021-12-19T01:44:27Z","updated_at":"2021-12-19T01:44:28Z","browser_download_url":"https://github.com/rust-analyzer/rust-analyzer/releases/download/nightly/rust-analyzer-aarch64-pc-windows-msvc.gz"},{"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/assets/52110844","id":52110844,"node_id":"RA_kwDOBttd2s4DGyX8","name":"rust-analyzer-aarch64-unknown-linux-gnu.gz","label":"","uploader":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"content_type":"application/octet-stream","state":"uploaded","size":11597202,"download_count":0,"created_at":"2021-12-19T01:44:28Z","updated_at":"2021-12-19T01:44:29Z","browser_download_url":"https://github.com/rust-analyzer/rust-analyzer/releases/download/nightly/rust-analyzer-aarch64-unknown-linux-gnu.gz"},{"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/assets/52110845","id":52110845,"node_id":"RA_kwDOBttd2s4DGyX9","name":"rust-analyzer-alpine-x64.vsix","label":"","uploader":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"content_type":"application/octet-stream","state":"uploaded","size":11898392,"download_count":0,"created_at":"2021-12-19T01:44:29Z","updated_at":"2021-12-19T01:44:30Z","browser_download_url":"https://github.com/rust-analyzer/rust-analyzer/releases/download/nightly/rust-analyzer-alpine-x64.vsix"}],"tarball_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/tarball/nightly","zipball_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/zipball/nightly","body":null}
ERROR [12/19/2021, 1:33:45 PM]: Bootstrap error [AssertionError [ERR_ASSERTION]: Bad release: {"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/55609849","assets_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/55609849/assets","upload_url":"https://uploads.github.com/repos/rust-analyzer/rust-analyzer/releases/55609849/assets{?name,label}","html_url":"https://github.com/rust-analyzer/rust-analyzer/releases/tag/nightly","id":55609849,"author":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"node_id":"RE_kwDOBttd2s4DUIn5","tag_name":"nightly","target_commitish":"638cc3e59f09b20e6ca6965ab1f3936e2467c497","name":"nightly","draft":false,"prerelease":true,"created_at":"2021-12-19T00:17:01Z","published_at":"2021-12-19T01:44:26Z","assets":[{"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/assets/52110842","id":52110842,"node_id":"RA_kwDOBttd2s4DGyX6","name":"rust-analyzer-aarch64-apple-darwin.gz","label":"","uploader":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"content_type":"application/octet-stream","state":"uploaded","size":8856890,"download_count":0,"created_at":"2021-12-19T01:44:26Z","updated_at":"2021-12-19T01:44:27Z","browser_download_url":"https://github.com/rust-analyzer/rust-analyzer/releases/download/nightly/rust-analyzer-aarch64-apple-darwin.gz"},{"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/assets/52110843","id":52110843,"node_id":"RA_kwDOBttd2s4DGyX7","name":"rust-analyzer-aarch64-pc-windows-msvc.gz","label":"","uploader":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"content_type":"application/octet-stream","state":"uploaded","size":8318265,"download_count":0,"created_at":"2021-12-19T01:44:27Z","updated_at":"2021-12-19T01:44:28Z","browser_download_url":"https://github.com/rust-analyzer/rust-analyzer/releases/download/nightly/rust-analyzer-aarch64-pc-windows-msvc.gz"},{"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/assets/52110844","id":52110844,"node_id":"RA_kwDOBttd2s4DGyX8","name":"rust-analyzer-aarch64-unknown-linux-gnu.gz","label":"","uploader":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"content_type":"application/octet-stream","state":"uploaded","size":11597202,"download_count":0,"created_at":"2021-12-19T01:44:28Z","updated_at":"2021-12-19T01:44:29Z","browser_download_url":"https://github.com/rust-analyzer/rust-analyzer/releases/download/nightly/rust-analyzer-aarch64-unknown-linux-gnu.gz"},{"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/assets/52110845","id":52110845,"node_id":"RA_kwDOBttd2s4DGyX9","name":"rust-analyzer-alpine-x64.vsix","label":"","uploader":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"content_type":"application/octet-stream","state":"uploaded","size":11898392,"download_count":0,"created_at":"2021-12-19T01:44:29Z","updated_at":"2021-12-19T01:44:30Z","browser_download_url":"https://github.com/rust-analyzer/rust-analyzer/releases/download/nightly/rust-analyzer-alpine-x64.vsix"}],"tarball_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/tarball/nightly","zipball_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/zipball/nightly","body":null}
	at cn (/home/andy/.vscode-server/extensions/matklad.rust-analyzer-0.3.861/out/main.js:61:2727)
	at I0 (/home/andy/.vscode-server/extensions/matklad.rust-analyzer-0.3.861/out/main.js:109:2928)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async F0 (/home/andy/.vscode-server/extensions/matklad.rust-analyzer-0.3.861/out/main.js:109:1867)
	at async O0 (/home/andy/.vscode-server/extensions/matklad.rust-analyzer-0.3.861/out/main.js:108:3977)
	at async lC (/home/andy/.vscode-server/extensions/matklad.rust-analyzer-0.3.861/out/main.js:108:3808)
	at async Promise.all (index 0)
	at async Promise.all (index 27)
	at async Promise.all (index 1)] {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

**Comment by iDawer** [comment]
https://github.com/rust-analyzer/rust-analyzer/issues/10961#issuecomment-997308071
> The release workflow failed in the middle again, I kicked off a new run. It should work after this runs through again https://github.com/rust-analyzer/rust-analyzer/actions/runs/1597301399

The workflow has succeeded now, try

> Reopen VSCode or use `Reload Window` in command palette

**Comment by Andy-Python-Programmer** [comment]
That works, thanks @iDawer!
