### ISSUE TITLE
Getting a bootstrap error

### ISSUE THREAD

**Issue by superyu1337** [rust-analyzer/rust-analyzer#11101]
Rust analyzer doesn't work for me anymore (since only some hours I believe), throws some javascript async error.

Im running the newest arch stable linux kernel.
I tried:
 - Fully system update
 - Updating vscodium
 - Redownloading rust-analyzer from marketplace
 - Changing kernel

Sadly, I don't know how to reproduce the error on other systems.
I'm going to do some more testing to isolate what's going on, but at the moment I have no idea what caused this.
It worked fine a few days ago.

**rust-analyzer version**: 0.2.867
**rustc version**: rustc 1.54.0 (a178d0322 2021-07-26)

Logs:
```
INFO [12/22/2021, 12:59:01 PM]: PersistentState: {
  lastCheck: undefined,
  nightlyReleaseId: undefined,
  serverVersion: '0.2.867'
}
INFO [12/22/2021, 12:59:01 PM]: Using server binary at /home/assel/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/server/rust-analyzer
ERROR [12/22/2021, 12:59:01 PM]: Bootstrap error [Error: Failed to execute /home/assel/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/server/rust-analyzer --version
	at j0 (/home/assel/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/out/main.js:109:4032)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async N0 (/home/assel/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/out/main.js:109:1881)
	at async I0 (/home/assel/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/out/main.js:108:3977)
	at async lC (/home/assel/.vscode-oss/extensions/matklad.rust-analyzer-0.2.867/out/main.js:108:3808)
	at async Promise.all (index 0)
	at async v.$activate (/opt/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:100:20806)]
```

**Comment by bjorn3** [comment]
Probably a duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/11080

**Comment by superyu1337** [comment]
> Probably a duplicate of #11080

Yeah, I didn't see that one, I also can't execute it manually.

**Comment by lnicola** [comment]
@superyu1337 try installing https://github.com/rust-analyzer/rust-analyzer/releases/download/2021-12-20/rust-analyzer-linux-x64.vsix (or the proper version from https://github.com/rust-analyzer/rust-analyzer/releases/tag/2021-12-20).

**Comment by superyu1337** [comment]
It works now, seems like the marketplace version is broken or something. Thanks!
