### ISSUE TITLE
`assertion failed: start <= end` in `complete_postfix`

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#11233]
```
thread '<unnamed>' panicked at 'assertion failed: start <= end', /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/text-size-1.1.0/src/range.rs:48:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/0e07bcb68b82b54c0c4ec6fe076e9d75b02109cf/library/core/src/panicking.rs:48:5
   3: ide_completion::completions::postfix::complete_postfix
   4: ide_completion::completions
   5: std::panicking::try
   6: ide::Analysis::completions
   7: rust_analyzer::handlers::handle_completion
   8: std::panicking::try
   9: <F as threadpool::FnBox>::call_box
```

**Comment by Veykril** [comment]
I imagine its this one https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide_completion/src/completions/postfix.rs#L228
