### ISSUE TITLE
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', crates/hir/src/semantics.rs:934:36

### ISSUE THREAD

**Issue by f32by** [rust-analyzer/rust-analyzer#11298]
**rust-analyzer version**: 7a52f8370 2022-01-16 nightly

**rustc version**: rustc 1.60.0-nightly (ec4bcaac4 2022-01-15)

What's happening: VSCode keeps saying `A request has failed. See the output for more information.` when scrolling or triggering highlight in a file containg some code snippet.

Code to reproduce this:
```rust
#[cfg_attr(feature = "whatever", repr(C))]
#[derive(Clone)]
pub struct Test;
```

Backtrace:
```
[Error - 7:08:07 PM] Request textDocument/semanticTokens/full failed.
  Message: server panicked: index out of bounds: the len is 1 but the index is 1
  Code: -32603 
Panic context:
> 
version: 7a52f8370 2022-01-16 nightly
request: textDocument/semanticTokens/range SemanticTokensRangeParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "************",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 7,
            character: 0,
        },
    },
}

thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', crates/hir/src/semantics.rs:934:36
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: hir::semantics::SemanticsImpl::resolve_derive_ident
   4: ide::syntax_highlighting::highlight::token
   5: ide::syntax_highlighting::highlight
   6: std::panicking::try
   7: rust_analyzer::handlers::handle_semantic_tokens_range
   8: std::panicking::try
   9: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Information maybe useful:

This panic only happens when `#[cfg_attr]` is placed in front of a `#[derive]`. If the order is reversed then everything works. I also found a colorized tokenization difference:
1. `#[derive]` is placed in front of `#[cfg_attr]`. Everything works and VSCode's `Inspect editor tokens and scopes` works properly.
![work](https://user-images.githubusercontent.com/12209857/149657684-02f2aed2-6aa7-4c5b-ad6b-ca322bbc7480.png)

2. `#[cfg_attr]` is placed in front of `#[derive]`. This will cause a panic and `Inspect editor tokens and scopes` does not work either.
![notwork](https://user-images.githubusercontent.com/12209857/149657754-f5cbc39e-0941-4e7f-b5eb-0b7316297a6a.png)
![CleanShot 2022-01-16 at 19 19 56](https://user-images.githubusercontent.com/12209857/149657783-bb829cfd-6ef3-49dc-853a-4e524dacdbfa.png)

**Comment by Veykril** [comment]
Ah, ye this seems to happen with `cfg_attr`s that have their feature flag not set, that brings indices out of order in a specific code path...

**Comment by Veykril** [comment]
Ye the problem is this here https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/hir_def/src/attr.rs#L87-L93
we index via the ast_index into the attribute slice, but the attribute slice doesn't contain the attributes behind a `cfg_attr` if they a disabled obviously

**Comment by jonas-schievink** [comment]
The panic was fixed by https://github.com/rust-analyzer/rust-analyzer/pull/11334
