### ISSUE TITLE
rust-analyzer is ignoring "server.path" (either because of "remote" workspace, or NixOS, or both)

### ISSUE THREAD

**Issue by colemickens** [rust-analyzer/rust-analyzer#11559]
On NixOS, with `code-server`, `rust-analyzer` blows up before it even get a chance:

```
INFO [2/25/2022, 9:23:22 PM]: PersistentState: { serverVersion: undefined }
ERROR [2/25/2022, 9:23:22 PM]: Bootstrap error [Error: error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «stdin»:2:36:

            1|
            2|             {srcStr, pkgs ? import <nixpkgs> {}}:
             |                                    ^
            3|                 pkgs.stdenv.mkDerivation {
(use '--show-trace' to show detailed location information)

	at /home/cole/.local/share/code-server/extensions/matklad.rust-analyzer-0.3.939/out/main.js:97:291
	at ChildProcess.exithandler (child_process.js:390:5)
	at ChildProcess.emit (events.js:400:28)
	at maybeClose (internal/child_process.js:1058:16)
	at Socket.<anonymous> (internal/child_process.js:443:11)
	at Socket.emit (events.js:400:28)
	at Pipe.<anonymous> (net.js:686:12)]
```

1) The patching that it does is rather brittle, has no escape hatch, requires NIX_PATH be set.
2) It seems that `rust-analyzer.server.path` is ignored when `rust-analyzer` is used on a remote workspace. I've done this in the past, I'm pretty sure things will just work if this were respected and used instead of the patching path.

**Comment by matthiasdebernardini** [comment]
I'm also having this issue with a project that has a large workspace and uses nix to manage all the other non-rust dependencies.

![image](https://user-images.githubusercontent.com/32387851/212561440-efcbbafa-0148-47be-b39b-e8b342868b41.png)

I have set the cargo extra env to whatever `which cargo` points to in my remote VM but that doesn't seem to be enough.
```json
{
    "rust-analyzer.cargo.extraEnv": {
        "CARGO": "/nix/store/mipm4ac23cy5qckwhmh3mfx10dx5wf8n-rust-stable-with-components-2022-12-15/bin/cargo",
    }
}
```

When I click on `rust-analyzer` icon to rescan, it just hangs like so;
![image](https://user-images.githubusercontent.com/32387851/212561530-1a5eaf03-ef7f-4764-ad0e-857f4b70c7f3.png)

Any tips on working with nix and rust-analyzer on vscode would be welcome. Which env vars should I be setting?

I am assuming there is an extra env flag in the setting.json that I have to set but I don't know which one it should be.  

Thank you in advance.

**Comment by JakeCooper** [comment]
Also running into this sadly

Only way I've found around is to directly set the language server path

`    "rust-analyzer.server.path": "/nix/store/vqyh3lpwllr9jnvk0f555mk8a3m6yiaf-rust-analyzer-2023-09-04/bin/rust-analyzer"`
