### ISSUE TITLE
vscode Bootstrap error

### ISSUE THREAD

**Issue by jcdc404** [rust-analyzer/rust-analyzer#11583]
I just started receiving this error this morning. I have no idea what to do about it:
```
ERROR [2/28/2022, 8:46:56 AM]: Bootstrap error [Error: Failed to execute /home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.956/server/rust-analyzer --version
	at Xb (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.956/out/main.js:85:2121)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Bb (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.956/out/main.js:84:3252)
	at async Vm (/home/newuser/.vscode/extensions/matklad.rust-analyzer-0.2.956/out/main.js:84:3083)]
```

**Comment by lnicola** [comment]
Can you run that file? Are you on Ubuntu 18.04?

**Comment by cameron-martin** [comment]
I also started receiving this error this morning. When I execute the command mentioned, I get an error about GLIBC:

```
cameronm@6r3myd3:~$ /home/cameronm/.vscode/extensions/matklad.rust-analyzer-0.2.956/server/rust-analyzer --version
/home/cameronm/.vscode/extensions/matklad.rust-analyzer-0.2.956/server/rust-analyzer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /home/cameronm/.vscode/extensions/matklad.rust-analyzer-0.2.956/server/rust-analyzer)
/home/cameronm/.vscode/extensions/matklad.rust-analyzer-0.2.956/server/rust-analyzer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/cameronm/.vscode/extensions/matklad.rust-analyzer-0.2.956/server/rust-analyzer)

```

**Comment by icyJoseph** [comment]
Started to get this as well. Any leads? Everything was working swell, this morning. I reckon something has been released?

**Comment by jcdc404** [comment]
I am running Debian 10
