### ISSUE TITLE
Execute binary failed

### ISSUE THREAD

**Issue by KaoImin** [rust-analyzer/rust-analyzer#11590]
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
rust-analyzer-0.2.956

**rustc version**: (eg. output of `rustc -V`)
rustc 1.60.0-nightly (777bb86bc 2022-01-20)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

Firstly, the binary exists. 
The output is shown below:

```log
ERROR [3/1/2022, 10:05:00 AM]: Bootstrap error [Error: Failed to execute /home/.vscode-server-insiders/extensions/matklad.rust-analyzer-0.2.956/server/rust-analyzer --version
	at Xb (/home/.vscode-server-insiders/extensions/matklad.rust-analyzer-0.2.956/out/main.js:19000:9)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Bb (/home/.vscode-server-insiders/extensions/matklad.rust-analyzer-0.2.956/out/main.js:18888:9)
	at async Vm (/home/.vscode-server-insiders/extensions/matklad.rust-analyzer-0.2.956/out/main.js:18876:3)]
```

The `main.js` code is this:

```js
async function Xb(n, e, t) {
  let r = await Qb(n, e, t);
  if (!r)
    throw new Error(
      "Rust Analyzer Language Server is not available. Please, ensure its [proper installation](https://rust-analyzer.github.io/manual.html#installation)."
    );
  if ((ve.info("Using server binary at", r), !$g(r)))
    throw e.serverPath
      ? new Error(
          `Failed to execute ${r} --version. \`config.server.path\` or \`config.serverPath\` has been set explicitly.            Consider removing this config or making a valid server binary available at that path.`
        )
      : new Error(`Failed to execute ${r} --version`);
  return r;
}
```

**Comment by KaoImin** [comment]
I guess it is a problem of access authority.

**Comment by jhgg** [comment]
This is probably  #11558
