### ISSUE TITLE
Inlay Hints Broken

### ISSUE THREAD

**Issue by AxeR21** [rust-analyzer/rust-analyzer#11706]
Hi, I think the new inlay hints feature is somewhat broken.

I'm currently running the extension in remote developement downloading the component from the rust nightly toolchain, since the OS is CentOS 7 and ships with GLIBC 2.17

To keep using the extension I disabled the feauture in settings.json on the remote side.

As a side note I cannot share the project I'm currently working on in it's entirety but if you need some snippets I'll try to post them.

Let me know if you need anything else!

Below some logs:

```
Rust Analyzer Client

INFO [14/03/2022, 17:05:48]: PersistentState: { serverVersion: '0.3.973' }
INFO [14/03/2022, 17:05:48]: Using server binary at /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rust-analyzer
INFO [14/03/2022, 17:07:03]: Extension version: 0.3.973
INFO [14/03/2022, 17:07:03]: Using configuration {
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    renderColons: true,
    chainingHints: true,
    maxLength: 25,
    parameterHints: true,
    typeHints: true,
    hideNamedConstructorHints: false
  },
  server: {
    path: '/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rust-analyzer',
    extraEnv: null
  },
  trace: { server: 'off', extension: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  assist: {
    exprFillDefault: 'todo',
    importGranularity: 'crate',
    importEnforceGranularity: false,
    importPrefix: 'plain',
    importGroup: true,
    allowMergingIntoGlobImports: true
  },
  cache: { warmup: true },
  callInfo: { full: true },
  cargo: {
    autoreload: true,
    allFeatures: true,
    unsetTest: [ 'core' ],
    features: [],
    runBuildScripts: true,
    useRustcWrapperForBuildScripts: true,
    noDefaultFeatures: false,
    target: null,
    noSysroot: false
  },
  checkOnSave: {
    enable: true,
    allFeatures: null,
    allTargets: true,
    command: 'check',
    noDefaultFeatures: null,
    target: null,
    extraArgs: [],
    features: null,
    overrideCommand: null
  },
  completion: {
    addCallArgumentSnippets: true,
    addCallParenthesis: true,
    snippets: {
      'Arc::new': {
        postfix: 'arc',
        body: 'Arc::new(${receiver})',
        requires: 'std::sync::Arc',
        description: 'Put the expression into an `Arc`',
        scope: 'expr'
      },
      'Rc::new': {
        postfix: 'rc',
        body: 'Rc::new(${receiver})',
        requires: 'std::rc::Rc',
        description: 'Put the expression into an `Rc`',
        scope: 'expr'
      },
      'Box::pin': {
        postfix: 'pinbox',
        body: 'Box::pin(${receiver})',
        requires: 'std::boxed::Box',
        description: 'Put the expression into a pinned `Box`',
        scope: 'expr'
      },
      Ok: {
        postfix: 'ok',
        body: 'Ok(${receiver})',
        description: 'Wrap the expression in a `Result::Ok`',
        scope: 'expr'
      },
      Err: {
        postfix: 'err',
        body: 'Err(${receiver})',
        description: 'Wrap the expression in a `Result::Err`',
        scope: 'expr'
      },
      Some: {
        postfix: 'some',
        body: 'Some(${receiver})',
        description: 'Wrap the expression in an `Option::Some`',
        scope: 'expr'
      }
    },
    postfix: { enable: true },
    autoimport: { enable: true },
    autoself: { enable: true },
    privateEditable: { enable: false }
  },
  diagnostics: {
    enable: true,
    enableExperimental: true,
    disabled: [],
    remapPrefix: {},
    warningsAsHint: [],
    warningsAsInfo: []
  },
  experimental: { procAttrMacros: true },
  files: { watcher: 'client', excludeDirs: [] },
  highlightRelated: {
    references: true,
    exitPoints: true,
    breakPoints: true,
    yieldPoints: true
  },
  highlighting: { strings: true },
  hover: { documentation: true, linksInHover: true },
  hoverActions: {
    debug: true,
    enable: true,
    gotoTypeDef: true,
    implementations: true,
    references: false,
    run: true
  },
  joinLines: {
    joinElseIf: true,
    removeTrailingComma: true,
    unwrapTrivialBlock: true,
    joinAssignments: true
  },
  lens: {
    debug: true,
    enable: true,
    implementations: true,
    run: true,
    methodReferences: false,
    references: false,
    enumVariantReferences: false,
    forceCustomCommands: true
  },
  linkedProjects: [],
  lruCapacity: null,
  notifications: { cargoTomlNotFound: true },
  primeCaches: { numThreads: 0 },
  procMacro: { enable: true, server: null, ignored: {} },
  runnables: { overrideCargo: null, cargoExtraArgs: [] },
  rustcSource: null,
  rustfmt: {
    extraArgs: [],
    overrideCommand: null,
    enableRangeFormatting: false
  },
  workspace: { symbol: { search: { scope: 'workspace', kind: 'only_types' } } }
}
WARN [14/03/2022, 17:07:10]: LSP request failed {
  method: 'experimental/inlayHints',
  param: {
    textDocument: { uri: 'file:///opt/evoloop-sds-cli/src/commands/pool.rs' },
    range: {
      start: S { _line: 648, _character: 0 },
      end: S { _line: 805, _character: 33 }
    }
  },
  error: [po [Error]: unknown request
  	at tr (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.973/out/main.js:7:223)
  	at er (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.973/out/main.js:6:6722)
  	at Immediate.<anonymous> (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.973/out/main.js:6:6572)
  	at processImmediate (internal/timers.js:461:21)] {
    code: -32601,
    data: undefined
  }
}
```

```
Rust Analyzer Language Server

[ERROR rust_analyzer::dispatch] unknown request: Request { id: RequestId(I32(81)), method: "experimental/inlayHints", params: Object({"textDocument": Object({"uri": String("file:///opt/evoloop-sds-cli/src/commands/pool.rs")}), "range": Object({"start": Object({"line": Number(648), "character": Number(0)}), "end": Object({"line": Number(805), "character": Number(33)})})}) }
```

**Comment by jacderida** [comment]
After updating, I completely lost inlay hints in Neovim with coc-rust-analyzer. I'm using stable, not nightly.

**Comment by chen244** [comment]
Same

**Comment by lnicola** [comment]
@chen244 `coc-rust-analyzer` was updated in https://github.com/fannheyward/coc-rust-analyzer/commit/896477ebce46ccbf143d5181ef2959355ed4f919.

The `rustup` `rust-analyzer` will probably be update in the next nightly.

**Comment by chen244** [comment]
> @chen244 `coc-rust-analyzer` was updated in [fannheyward/coc-rust-analyzer@896477e](https://github.com/fannheyward/coc-rust-analyzer/commit/896477ebce46ccbf143d5181ef2959355ed4f919).
> 
> The `rustup` `rust-analyzer` will probably be update in the next nightly.

But I am confused why is "experiment"?

**Comment by lnicola** [comment]
> But I am confused why is "experiment"?

Inlay hints in Code have two parts: the client one (API for Code extensions) and the LSP requests (sent to the language servers). Currently, the API is available, but they haven't been standardized in LSP.

So the request went from `rust-analyzer/` (our RA-specific LSP extension) to `experimental/` (something we hope ends up standardized).

**Comment by lnicola** [comment]
@AxeR21 can you update your nightly and test?

**Comment by AxeR21** [comment]
I've just updated the toolchain and it seems to be working as excpected.
@lnicola there's something I can do to let you know with 100% certainty  that everything's ok?

**Comment by lnicola** [comment]
Not everything is ok, neither in RA nor in the world, but I'm pretty certain that inlay hints are now working in the `rustup` component. Thanks for testing, though.

**Comment by dreamerlzl** [comment]
The same problem until I upgrade my ra to the latest version (3.28).
