### ISSUE TITLE
`tried adding a runnable pointing to a different file` panic

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#11746]
```
thread '<unnamed>' panicked at 'tried adding a runnable pointing to a different file: DocTest { test_id: Path("macros::point") } for FileId(63)', crates/ide/src/runnables.rs:132:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: ide::runnables::runnables::{{closure}}
   3: ide::runnables::runnables::{{closure}}
   4: ide_db::helpers::visit_file_defs
   5: ide::runnables::runnables
   6: ide::annotations::annotations
   7: ide::Analysis::annotations
   8: rust_analyzer::handlers::handle_code_lens
   9: std::panicking::try
  10: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Veykril** [comment]
`macros::point` do you have the source for this part perhaps? ( sounds like this might be happening since I've merged ModuleDefs and MacroDefs now )

**Comment by lnicola** [comment]
Yeah, somewhere in https://github.com/georust/geo/, in the `geo-types` crate, possibility on a test. I don't know how easy it is to reproduce.

**Comment by lnicola** [comment]
I think this happens when opening `geo-types/src/lib.rs`.

**Comment by Veykril** [comment]
Oh this might be triggered by `#[macro_export]` macros.
