### ISSUE TITLE
Crash when using generic associated types + const generics

### ISSUE THREAD

**Issue by spookyvision** [rust-analyzer/rust-analyzer#11769]
the code below causes crashes on hover, text change, or RA startup.
Some additional findings:
- GATs without const generics seem unaffected
- removing the `fn` also gets rid of the crashy

```rust
#![feature(generic_associated_types)]
trait ATrait {}

trait Crash {
    type Member<const N: usize>: ATrait;
    fn new<const N: usize>() -> Self::Member<N>;
}
```

**rust-analyzer version**: `a82caff58 2022-03-20 nightly`

**rustc version**: `rustc 1.61.0-nightly (f103b2969 2022-03-12)`

crash log:

```code
Panic context:
> 
version: a82caff58 2022-03-20 nightly
request: textDocument/semanticTokens/full/delta SemanticTokensDeltaParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/private/tmp/aec.22_03_12_04_01_53.Ue/gat-ra/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    previous_result_id: "1",
}

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/chalk-ir-0.79.0/src/lib.rs:1447:27
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::impls_for_trait
   4: chalk_solve::clauses::program_clauses_that_could_match
   5: chalk_recursive::solve::SolveIteration::solve_iteration
   6: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
   7: chalk_recursive::fulfill::Fulfill<I,Solver>::prove
   8: chalk_recursive::fulfill::Fulfill<I,Solver>::solve
   9: chalk_recursive::solve::SolveIteration::solve_iteration
  10: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  11: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  12: <hir_ty::db::TraitSolveQueryQuery as salsa::plumbing::QueryFunction>::execute
  13: salsa::runtime::Runtime::execute_query_implementation
  14: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: salsa::QueryTable<Q>::get
  17: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  18: hir_ty::db::trait_solve_wait
  19: <DB as hir_ty::db::HirDatabase>::trait_solve
  20: hir_ty::infer::unify::InferenceTable::register_obligation_in_env
  21: hir_ty::infer::unify::InferenceTable::normalize_projection_ty
  22: <hir_ty::fold_tys_and_consts::TyFolder<F> as chalk_ir::fold::Folder<hir_ty::interner::Interner>>::fold_ty
  23: hir_ty::infer::InferenceContext::make_ty_with_mode
  24: hir_ty::infer::infer_query
  25: salsa::runtime::Runtime::execute_query_implementation
  26: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  27: salsa::derived::slot::Slot<Q,MP>::read
  28: salsa::QueryTable<Q>::get
  29: <DB as hir_ty::db::HirDatabase>::infer_query
  30: hir_ty::db::infer_wait
  31: hir::source_analyzer::SourceAnalyzer::new_for_body
  32: hir::semantics::SemanticsImpl::analyze_impl
  33: ide_db::defs::NameRefClass::classify
  34: ide::syntax_highlighting::highlight::name_like
  35: ide::syntax_highlighting::highlight
  36: std::panicking::try
  37: rust_analyzer::handlers::handle_semantic_tokens_full_delta
  38: std::panicking::try
  39: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 2:19:55 AM] Request textDocument/semanticTokens/full/delta failed.
  Message: server panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
```

**Comment by flodiebold** [comment]
@spookyvision I can't reproduce the crash, so maybe it's fixed. I have some doubts though, since the crash is in `infer_query`, but your example code contains no actual functions that inference could be called on. Are you still seeing this crash?

**Comment by spookyvision** [comment]
> @spookyvision I can't reproduce the crash, so maybe it's fixed. I have some doubts though, since the crash is in `infer_query`, but your example code contains no actual functions that inference could be called on. Are you still seeing this crash?

it still happens unfortunately.

specifically the problem seems to only occur when I hover over the `usize` or `Self::Member<N>` parts in the function definition (`const N:` is fine...).
Want me to run some specific diagnostics?

**Comment by spookyvision** [comment]
- enabling `rust-analyzer.trace.server` doesn't seem to give more insight (output below)
- I've also attached another crash log, this time with `RUST_BACKTRACE=full`


trace:
```

[Trace - 4:19:41 AM] Sending request 'textDocument/hover - (234)'.
Params: {
    "textDocument": {
        "uri": "file:///private/tmp/aec.22_03_29_15_37_25.wP/racrash/src/lib.rs"
    },
    "position": {
        "line": 5,
        "character": 41
    }
}


[Trace - 4:19:41 AM] Received response 'textDocument/hover - (234)' in 4ms. Request failed: server panicked: called `Option::unwrap()` on a `None` value (-32603).
```


crash log:
```

Panic context:
> 
version: 259182b50 2022-03-31 nightly
request: textDocument/hover HoverParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/private/tmp/aec.22_03_29_15_37_25.wP/racrash/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    position: Position(
        Position {
            line: 5,
            character: 41,
        },
    ),
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
}

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/chalk-ir-0.81.0/src/lib.rs:1447:27
stack backtrace:
   0:        0x10386f4bf - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4f26ffad025fdbe8
   1:        0x1029aec7b - core::fmt::write::h0a9937d83d3944c1
   2:        0x103868dba - std::io::Write::write_fmt::hfaf2e2e92eda8127
   3:        0x103875028 - std::panicking::default_hook::{{closure}}::hc11e9b8d348e68b0
   4:        0x103874cc1 - std::panicking::default_hook::h1d26ec4d0d63be04
   5:        0x1038852de - std::thread::local::LocalKey<T>::with::h09ecf2e6740ffe6d
   6:        0x103875704 - std::panicking::rust_panic_with_hook::hef4f5e524db188b3
   7:        0x1038753ba - std::panicking::begin_panic_handler::{{closure}}::h6e8805ea2351af89
   8:        0x103872547 - std::sys_common::backtrace::__rust_end_short_backtrace::hd383ade987b76f63
   9:        0x103875100 - _rust_begin_unwind
  10:        0x10392525f - core::panicking::panic_fmt::hb58956db718d5b79
  11:        0x1039251b7 - core::panicking::panic::h709cad72bd37e428
  12:        0x102ec1716 - hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::impls_for_trait::h147ad0889ed91ec3
  13:        0x102f40489 - chalk_solve::clauses::program_clauses_that_could_match::h6d883beb056fdf73
  14:        0x102de8a16 - chalk_recursive::solve::SolveIteration::solve_iteration::h8b0a5eb2f706e578
  15:        0x102ddaad1 - chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal::h89ac76a5d1353f1e
  16:        0x102ea3e2c - chalk_recursive::fulfill::Fulfill<I,Solver>::prove::h91bccaf2f7fe6826
  17:        0x102e93dc5 - chalk_recursive::fulfill::Fulfill<I,Solver>::solve::h156564263a37ac63
  18:        0x102de912a - chalk_recursive::solve::SolveIteration::solve_iteration::h8b0a5eb2f706e578
  19:        0x102ddaad1 - chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal::h89ac76a5d1353f1e
  20:        0x102dd0110 - chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal::h0da1762229cc2432
  21:        0x102ed8016 - <hir_ty::db::TraitSolveQueryQuery as salsa::plumbing::QueryFunction>::execute::h9eae72076994cf72
  22:        0x102d82478 - salsa::runtime::Runtime::execute_query_implementation::hac29d73d0849b148
  23:        0x102d0ba43 - salsa::derived::slot::Slot<Q,MP>::read_upgrade::h92c2fcf9ab69b9b0
  24:        0x102cef4ac - salsa::derived::slot::Slot<Q,MP>::read::he748400c64e05c5e
  25:        0x102e2ac9a - salsa::QueryTable<Q>::get::h3580e104cd6b6555
  26:        0x103033e7f - <DB as hir_ty::db::HirDatabase>::trait_solve_query::h51096367c6cf67d7
  27:        0x102ec7c17 - hir_ty::db::trait_solve_wait::h41908e1278f89250
  28:        0x103033de7 - <DB as hir_ty::db::HirDatabase>::trait_solve::h5b9fb651a4e889c4
  29:        0x102f15a16 - hir_ty::infer::unify::InferenceTable::register_obligation_in_env::h9ebc78bb23f2cb7e
  30:        0x102f14294 - hir_ty::infer::unify::InferenceTable::normalize_projection_ty::haa02b7d71902bfb1
  31:        0x102f450b5 - <hir_ty::fold_tys_and_consts::TyFolder<F> as chalk_ir::fold::Folder<hir_ty::interner::Interner>>::fold_ty::hd95b1c76c7f09bcb
  32:        0x102e02e04 - hir_ty::infer::InferenceContext::make_ty_with_mode::h31a8ddbcfe4bb704
  33:        0x102e012bb - hir_ty::infer::infer_query::hcb17ebe99970f8d3
  34:        0x102d83943 - salsa::runtime::Runtime::execute_query_implementation::hdcd19e4d3fd87ae9
  35:        0x102d19ecb - salsa::derived::slot::Slot<Q,MP>::read_upgrade::hf077fea52b1d5d9f
  36:        0x102ceda15 - salsa::derived::slot::Slot<Q,MP>::read::hc15eb05957c13d9e
  37:        0x102e2a56b - salsa::QueryTable<Q>::get::h24ee31d51674fd58
  38:        0x1030330d4 - <DB as hir_ty::db::HirDatabase>::infer_query::h6f3565f5b5c822b5
  39:        0x102ec79f4 - hir_ty::db::infer_wait::h9854a2220dda7e9e
  40:        0x102a685ef - hir::source_analyzer::SourceAnalyzer::new_for_body::h9aa34610c462dad4
  41:        0x102a2bcac - hir::semantics::SemanticsImpl::analyze_impl::h452a10a6fc10bfaa
  42:        0x103205f04 - ide_db::defs::NameRefClass::classify::ha98ea6faf4de6a37
  43:        0x103203d6c - ide_db::defs::IdentClass::classify_node::ha4617f44ce2e3f2e
  44:        0x102fd235d - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h4afc50b1c8878215
  45:        0x102fe4b9d - <itertools::unique_impl::UniqueBy<I,V,F> as core::iter::traits::iterator::Iterator>::next::hb6ff53ae757d53c4
  46:        0x102fcd5ff - ide::hover::hover::h3727a4ed478f1306
  47:        0x102f6b846 - std::panicking::try::h80ba0f5035e29f61
  48:        0x1037313f2 - rust_analyzer::handlers::handle_hover::h00ab609973d74069
  49:        0x103628dd9 - std::panicking::try::h0479c90029494581
  50:        0x1036078d8 - <F as threadpool::FnBox>::call_box::ha879014e3dde3ce9
  51:        0x1038ce7f4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h290a9d1833a35037
  52:        0x1038cdfe7 - core::ops::function::FnOnce::call_once{{vtable.shim}}::ha6fefd0a5801fd14
  53:        0x10387d4d9 - std::sys::unix::thread::Thread::new::thread_start::hcccd55275f17da3c
  54:     0x7ff8135624e1 - __pthread_start
[Error - 4:19:41 AM] Request textDocument/hover failed.
  Message: server panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
```
