### ISSUE TITLE
Rust-Analyzer often crashes when several files change at once (e.g., when I switch to another branch in git)

### ISSUE THREAD

**Issue by umanwizard** [rust-analyzer/rust-analyzer#11909]
rust-analyzer version: `rust-analyzer f5c069c9d 2022-04-04 dev`

Example log output:
```
thread 'main' panicked at 'no value set for FileSourceRootQuery(FileId(14144))', /home/brennan/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.2/src/input.rs:106:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: <salsa::input::InputStorage<Q> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   3: salsa::QueryTable<Q>::get
   4: <DB as base_db::SourceDatabaseExt>::file_source_root::__shim
   5: <core::iter::adapters::copied::Copied<I> as core::iter::traits::iterator::Iterator>::fold
   6: <base_db::SourceRootCratesQuery as salsa::plumbing::QueryFunction>::execute
   7: salsa::runtime::Runtime::execute_query_implementation
   8: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   9: salsa::derived::slot::Slot<Q,MP>::read
  10: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  11: salsa::QueryTable<Q>::get
  12: <DB as base_db::SourceDatabaseExt>::source_root_crates::__shim
  13: <base_db::FileLoaderDelegate<&T> as base_db::FileLoader>::relevant_crates
  14: <ide_db::RootDatabase as base_db::FileLoader>::relevant_crates
  15: rust_analyzer::global_state::GlobalState::process_changes
  16: rust_analyzer::reload::<impl rust_analyzer::global_state::GlobalState>::switch_workspaces
  17: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::handle_event
  18: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
  19: rust_analyzer::main_loop::main_loop
  20: rust_analyzer::run_server
  21: rust_analyzer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /home/brennan/.cargo/registry/src/github.com-1ecc6299db9ec823/lsp-server-0.5.2/src/stdio.rs:29:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process rust-analyzer stderr<1> finished

Process rust-analyzer stderr finished
```

**Comment by umanwizard** [comment]
Seems to be a dupe of #11357
