### ISSUE TITLE
vfs: crash with non-UTF-8 filenames

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#1416]
```bash
touch $'\240'$'\241'
```

Error:

```
thread 'vfs' panicked at 'called `Result::unwrap()` on an `Err` value: FromPathError { kind: NonUtf8 }', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:212
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:382
   8: rust_begin_unwind
             at src/libstd/panicking.rs:309
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at /rustc/b25ee644971a168287ee166edbd11642dbcfeab8/src/libcore/macros.rs:18
  11: core::result::Result<T,E>::unwrap
             at /rustc/b25ee644971a168287ee166edbd11642dbcfeab8/src/libcore/result.rs:800
  12: ra_vfs::roots::rel_path
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_vfs-0.2.4/src/roots.rs:157
  13: ra_vfs::roots::to_relative_path
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_vfs-0.2.4/src/roots.rs:168
  14: ra_vfs::roots::Roots::contains::{{closure}}
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_vfs-0.2.4/src/roots.rs:113
  15: core::iter::traits::iterator::Iterator::find_map::{{closure}}
             at /rustc/b25ee644971a168287ee166edbd11642dbcfeab8/src/libcore/iter/traits/iterator.rs:1861
  16: core::iter::traits::iterator::Iterator::try_for_each::{{closure}}
             at /rustc/b25ee644971a168287ee166edbd11642dbcfeab8/src/libcore/iter/traits/iterator.rs:1610
  17: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/b25ee644971a168287ee166edbd11642dbcfeab8/src/libcore/ops/function.rs:269
  18: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/b25ee644971a168287ee166edbd11642dbcfeab8/src/libcore/iter/traits/iterator.rs:1573
  19: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/b25ee644971a168287ee166edbd11642dbcfeab8/src/libcore/iter/adapters/chain.rs:88
  20: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/b25ee644971a168287ee166edbd11642dbcfeab8/src/libcore/iter/traits/iterator.rs:1610
  21: core::iter::traits::iterator::Iterator::find_map
             at /rustc/b25ee644971a168287ee166edbd11642dbcfeab8/src/libcore/iter/traits/iterator.rs:1860
  22: ra_vfs::roots::Roots::contains
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_vfs-0.2.4/src/roots.rs:111
  23: ra_vfs::roots::Roots::find::{{closure}}
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_vfs-0.2.4/src/roots.rs:88
  24: core::iter::traits::iterator::Iterator::find_map::{{closure}}
             at /rustc/b25ee644971a168287ee166edbd11642dbcfeab8/src/libcore/iter/traits/iterator.rs:1861
  25: core::iter::traits::iterator::Iterator::try_for_each::{{closure}}
             at /rustc/b25ee644971a168287ee166edbd11642dbcfeab8/src/libcore/iter/traits/iterator.rs:1610
  26: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::{{closure}}
             at /rustc/b25ee644971a168287ee166edbd11642dbcfeab8/src/libcore/iter/adapters/mod.rs:582
  27: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/b25ee644971a168287ee166edbd11642dbcfeab8/src/libcore/iter/traits/iterator.rs:1573
  28: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/b25ee644971a168287ee166edbd11642dbcfeab8/src/libcore/iter/adapters/mod.rs:582
  29: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/b25ee644971a168287ee166edbd11642dbcfeab8/src/libcore/iter/traits/iterator.rs:1610
  30: core::iter::traits::iterator::Iterator::find_map
             at /rustc/b25ee644971a168287ee166edbd11642dbcfeab8/src/libcore/iter/traits/iterator.rs:1860
  31: ra_vfs::roots::Roots::find
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_vfs-0.2.4/src/roots.rs:87
  32: ra_vfs::io::handle_change
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_vfs-0.2.4/src/io.rs:224
  33: ra_vfs::io::start::{{closure}}
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_vfs-0.2.4/src/io.rs:152
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by lnicola** [comment]
Wrong repo.
