### ISSUE TITLE
internal error: cyclic dependency  checking actix-utils 0.3.5

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-analyzer/rust-analyzer#1802]
repro:
````
git clone https://github.com/actix/actix-net/ 
cd actix-net/actix-utils
git checkout utils-v0.3.5

RUST_BACKTRACE=full ra_cli analysis-stats
````
backtrace:
````
Database loaded, 192 roots, 237.448884ms
thread 'main' panicked at 'Internal error, cycle detected:
- __SalsaDatabaseKey { kind: DefDatabaseStorage(crate_def_map(Crate { crate_id: CrateId(119) })) }

', /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/runtime.rs:424:9
stack backtrace:
   0:     0x56505232ef32 - backtrace::backtrace::libunwind::trace::h8a645919789e8d0b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1:     0x56505232ef32 - backtrace::backtrace::trace_unsynchronized::h2b00fcd64a6db2a8
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2:     0x56505232ef32 - std::sys_common::backtrace::_print::hb48dd402e7e4ee13
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x56505232ef32 - std::sys_common::backtrace::print::h5afe7278b7ee9221
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x56505232ef32 - std::panicking::default_hook::{{closure}}::h06704ce56e3f2eb7
                               at src/libstd/panicking.rs:200
   5:     0x56505232ec16 - std::panicking::default_hook::h79bfafe0b6650e1b
                               at src/libstd/panicking.rs:214
   6:     0x56505232f685 - std::panicking::rust_panic_with_hook::h9fb440f8b04cb795
                               at src/libstd/panicking.rs:477
   7:     0x565051c407fc - std::panicking::begin_panic::h17001548f9bf8361
                               at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/panicking.rs:411
   8:     0x565051a1b9bf - salsa::runtime::Runtime<DB>::report_unexpected_cycle::h4ec05272645278dc
                               at /home/matthias/vcs/github/rust-analyzer/<::std::macros::panic macros>:3
   9:     0x565051b829cb - salsa::QueryTable<DB,Q>::get::{{closure}}::h17f358fdd32e7548
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:475
  10:     0x565051b829cb - core::result::Result<T,E>::unwrap_or_else::had3e059e1f8a6e0d
                               at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libcore/result.rs:818
  11:     0x565051b829cb - salsa::QueryTable<DB,Q>::get::h3110a9d02d84ebcb
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:471
  12:     0x565051c427ea - <T as ra_hir::db::DefDatabase>::crate_def_map::h7b0e87f29bd7167f
                               at /home/matthias/vcs/github/rust-analyzer/crates/ra_hir/src/db.rs:85
  13:     0x565051c427ea - ra_hir::code_model::Crate::root_module::hf24a4c82b9a72153
                               at /home/matthias/vcs/github/rust-analyzer/crates/ra_hir/src/code_model.rs:67
  14:     0x565051c427ea - ra_hir::nameres::collector::collect_defs::h4f0a72c8a1e58fd6
                               at /home/matthias/vcs/github/rust-analyzer/crates/ra_hir/src/nameres/collector.rs:25
  15:     0x565051b3b5eb - ra_hir::nameres::CrateDefMap::crate_def_map_query::hb1450d1230551d6a
                               at /home/matthias/vcs/github/rust-analyzer/crates/ra_hir/src/nameres.rs:276
  16:     0x565051a1d252 - <ra_hir::db::CrateDefMapQuery as salsa::plumbing::QueryFunction<DB>>::execute::h501b7c2117ab5e05
                               at /home/matthias/vcs/github/rust-analyzer/crates/ra_hir/src/db.rs:85
  17:     0x565051a1d252 - salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}::hb9e0c2e8a8165ce5
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:203
  18:     0x565051a1d252 - salsa::runtime::Runtime<DB>::execute_query_implementation::h2887138a4f0eeed7
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/runtime.rs:351
  19:     0x565051bdea09 - salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::hc16829c5b99ed992
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:200
  20:     0x565051bfe0d5 - salsa::derived::slot::Slot<DB,Q,MP>::read::h9207048c619eb378
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:140
  21:     0x565051b0bc81 - <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch::h37ca25c0e6dbb68b
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived.rs:140
  22:     0x565051b82940 - salsa::QueryTable<DB,Q>::get::h3110a9d02d84ebcb
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:471
  23:     0x565051c427ea - <T as ra_hir::db::DefDatabase>::crate_def_map::h7b0e87f29bd7167f
                               at /home/matthias/vcs/github/rust-analyzer/crates/ra_hir/src/db.rs:85
  24:     0x565051c427ea - ra_hir::code_model::Crate::root_module::hf24a4c82b9a72153
                               at /home/matthias/vcs/github/rust-analyzer/crates/ra_hir/src/code_model.rs:67
  25:     0x565051c427ea - ra_hir::nameres::collector::collect_defs::h4f0a72c8a1e58fd6
                               at /home/matthias/vcs/github/rust-analyzer/crates/ra_hir/src/nameres/collector.rs:25
  26:     0x565051b3b5eb - ra_hir::nameres::CrateDefMap::crate_def_map_query::hb1450d1230551d6a
                               at /home/matthias/vcs/github/rust-analyzer/crates/ra_hir/src/nameres.rs:276
  27:     0x565051a1d252 - <ra_hir::db::CrateDefMapQuery as salsa::plumbing::QueryFunction<DB>>::execute::h501b7c2117ab5e05
                               at /home/matthias/vcs/github/rust-analyzer/crates/ra_hir/src/db.rs:85
  28:     0x565051a1d252 - salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}::hb9e0c2e8a8165ce5
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:203
  29:     0x565051a1d252 - salsa::runtime::Runtime<DB>::execute_query_implementation::h2887138a4f0eeed7
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/runtime.rs:351
  30:     0x565051bdea09 - salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::hc16829c5b99ed992
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:200
  31:     0x565051bfe0d5 - salsa::derived::slot::Slot<DB,Q,MP>::read::h9207048c619eb378
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:140
  32:     0x565051b0bc81 - <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch::h37ca25c0e6dbb68b
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived.rs:140
  33:     0x565051b82940 - salsa::QueryTable<DB,Q>::get::h3110a9d02d84ebcb
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:471
  34:     0x565051a26f00 - <T as ra_hir::db::DefDatabase>::crate_def_map::h7b0e87f29bd7167f
                               at /home/matthias/vcs/github/rust-analyzer/crates/ra_hir/src/db.rs:85
  35:     0x565051a26f00 - ra_hir::code_model::Crate::root_module::hf24a4c82b9a72153
                               at /home/matthias/vcs/github/rust-analyzer/crates/ra_hir/src/code_model.rs:67
  36:     0x565051a26f00 - ra_cli::analysis_stats::run::h518809e351baefc7
                               at crates/ra_cli/src/analysis_stats.rs:23
  37:     0x565051c4bf43 - ra_cli::main::h849f7fc1807464aa
                               at crates/ra_cli/src/main.rs:78
  38:     0x565051a30743 - std::rt::lang_start::{{closure}}::h52a534bb4d1482c4
                               at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/rt.rs:64
  39:     0x56505232f0b3 - std::rt::lang_start_internal::{{closure}}::h886ba8710662e0ce
                               at src/libstd/rt.rs:49
  40:     0x56505232f0b3 - std::panicking::try::do_call::hf9383917f63fc317
                               at src/libstd/panicking.rs:296
  41:     0x56505233703a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  42:     0x56505232fc3d - std::panicking::try::h3bb4caf318c2ef30
                               at src/libstd/panicking.rs:275
  43:     0x56505232fc3d - std::panic::catch_unwind::h6458650ce45ec87a
                               at src/libstd/panic.rs:394
  44:     0x56505232fc3d - std::rt::lang_start_internal::h2228998aafc0f6b1
                               at src/libstd/rt.rs:48
  45:     0x565051c4ca48 - main
  46:     0x7f02f199bee3 - __libc_start_main
  47:     0x565051a0202e - _start
  48:                0x0 - <unknown>
````

repo @ 5fbdf57c4fe7ee99ba94549766a2644431f61b26

**Comment by matthiaskrgr** [comment]
I can't reproduce this anymore, closing.
