### ISSUE TITLE
'The parser seems stuck' while macro-expanding RA

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#1819]
`analysis-stats` on current RA master seems to fail during macro expansion:
```> $ RUST_BACKTRACE=1 target/release/ra_cli analysis-stats
Database loaded, 214 roots, 262.782938ms
thread 'main' panicked at 'the parser seems stuck', crates/ra_parser/src/parser.rs:49:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:411
   8: ra_parser::parser::Parser::nth
             at crates/ra_parser/src/parser.rs:49
   9: ra_parser::parser::Parser::current
             at crates/ra_parser/src/parser.rs:40
  10: ra_parser::grammar::opt_visibility
             at crates/ra_parser/src/grammar.rs:179
  11: ra_parser::grammar::items::nominal::record_field_def_list::record_field_def
             at crates/ra_parser/src/grammar/items/nominal.rs:119
  12: ra_parser::grammar::items::nominal::record_field_def_list
             at crates/ra_parser/src/grammar/items/nominal.rs:103
  13: ra_parser::grammar::items::nominal::struct_def
             at crates/ra_parser/src/grammar/items/nominal.rs:26
  14: ra_parser::grammar::items::items_without_modifiers
             at crates/ra_parser/src/grammar/items.rs:248
  15: ra_parser::grammar::items::maybe_item
             at crates/ra_parser/src/grammar/items.rs:82
  16: ra_parser::grammar::items::item_or_macro
             at crates/ra_parser/src/grammar/items.rs:40
  17: core::ops::function::FnOnce::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:231
  18: ra_parser::parse_from_tokens
             at crates/ra_parser/src/lib.rs:76
  19: ra_parser::parse_fragment
             at crates/ra_parser/src/lib.rs:121
  20: ra_mbe::subtree_parser::Parser::parse_fragment::{{closure}}
             at crates/ra_mbe/src/subtree_parser.rs:57
  21: ra_mbe::subtree_parser::Parser::parse
             at crates/ra_mbe/src/subtree_parser.rs:69
  22: ra_mbe::subtree_parser::Parser::parse_fragment
             at crates/ra_mbe/src/subtree_parser.rs:56
  23: ra_mbe::tt_cursor::TtCursor::eat_fragment
             at crates/ra_mbe/src/tt_cursor.rs:104
  24: ra_mbe::mbe_expander::match_meta_var
             at crates/ra_mbe/src/mbe_expander.rs:332
  25: ra_mbe::mbe_expander::match_lhs
             at crates/ra_mbe/src/mbe_expander.rs:202
  26: ra_mbe::mbe_expander::expand_rule
             at crates/ra_mbe/src/mbe_expander.rs:22
  27: ra_mbe::mbe_expander::expand::{{closure}}
             at crates/ra_mbe/src/mbe_expander.rs:17
  28: core::iter::traits::iterator::Iterator::find_map::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:1861
  29: core::iter::traits::iterator::Iterator::try_for_each::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:1610
  30: <core::slice::Iter<T> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/slice/mod.rs:3161
  31: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:1610
  32: core::iter::traits::iterator::Iterator::find_map
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:1860
  33: ra_mbe::mbe_expander::expand
             at crates/ra_mbe/src/mbe_expander.rs:17
  34: ra_mbe::MacroRules::expand
             at crates/ra_mbe/src/lib.rs:62
  35: ra_hir::ids::macro_expand_query
             at ./crates/ra_hir/src/ids.rs:156
  36: <ra_hir::db::MacroExpandQuery as salsa::plumbing::QueryFunction<DB>>::execute
             at ./crates/ra_hir/src/db.rs:80
  37: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:203
  38: salsa::runtime::Runtime<DB>::execute_query_implementation
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/runtime.rs:351
  39: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:200
  40: salsa::derived::slot::Slot<DB,Q,MP>::read
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:140
  41: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived.rs:140
  42: salsa::QueryTable<DB,Q>::get
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:471
  43: <T as ra_hir::db::AstDatabase>::macro_expand
             at ./crates/ra_hir/src/db.rs:58
  44: ra_hir::ids::HirFileId::parse_macro_query
             at ./crates/ra_hir/src/ids.rs:79
  45: <ra_hir::db::ParseMacroQuery as salsa::plumbing::QueryFunction<DB>>::execute
             at ./crates/ra_hir/src/db.rs:71
  46: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:203
  47: salsa::runtime::Runtime<DB>::execute_query_implementation
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/runtime.rs:351
  48: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:200
  49: salsa::derived::slot::Slot<DB,Q,MP>::read
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:140
  50: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived.rs:140
  51: salsa::QueryTable<DB,Q>::get
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:471
  52: <T as ra_hir::db::AstDatabase>::parse_macro
             at ./crates/ra_hir/src/db.rs:58
  53: ra_hir::ids::HirFileId::parse_or_expand_query
             at ./crates/ra_hir/src/ids.rs:68
  54: <T as ra_hir::db::AstDatabase>::parse_or_expand
             at ./crates/ra_hir/src/db.rs:58
  55: ra_hir::source_id::AstIdMap::ast_id_map_query
             at ./crates/ra_hir/src/source_id.rs:95
  56: <ra_hir::db::AstIdMapQuery as salsa::plumbing::QueryFunction<DB>>::execute
             at ./crates/ra_hir/src/db.rs:60
  57: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:203
  58: salsa::runtime::Runtime<DB>::execute_query_implementation
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/runtime.rs:351
  59: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:200
  60: salsa::derived::slot::Slot<DB,Q,MP>::read
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:140
  61: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived.rs:140
  62: salsa::QueryTable<DB,Q>::get
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:471
  63: <T as ra_hir::db::AstDatabase>::ast_id_map
             at ./crates/ra_hir/src/db.rs:58
  64: ra_hir::nameres::raw::RawItems::raw_items_with_source_map_query
             at ./crates/ra_hir/src/nameres/raw.rs:75
  65: <ra_hir::db::RawItemsWithSourceMapQuery as salsa::plumbing::QueryFunction<DB>>::execute
             at ./crates/ra_hir/src/db.rs:85
  66: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:203
  67: salsa::runtime::Runtime<DB>::execute_query_implementation
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/runtime.rs:351
  68: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:200
  69: salsa::derived::slot::Slot<DB,Q,MP>::read
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:140
  70: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived.rs:140
  71: salsa::QueryTable<DB,Q>::get
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:471
  72: <T as ra_hir::db::DefDatabase>::raw_items_with_source_map
             at ./crates/ra_hir/src/db.rs:85
  73: ra_hir::nameres::raw::RawItems::raw_items_query
             at ./crates/ra_hir/src/nameres/raw.rs:66
  74: <ra_hir::db::RawItemsQuery as salsa::plumbing::QueryFunction<DB>>::execute
             at ./crates/ra_hir/src/db.rs:85
  75: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:203
  76: salsa::runtime::Runtime<DB>::execute_query_implementation
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/runtime.rs:351
  77: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:200
  78: salsa::derived::slot::Slot<DB,Q,MP>::read
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:140
  79: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived.rs:140
  80: salsa::QueryTable<DB,Q>::get
             at /home/florian/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:471
  81: <T as ra_hir::db::DefDatabase>::raw_items
             at ./crates/ra_hir/src/db.rs:85
  82: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
             at ./crates/ra_hir/src/nameres/collector.rs:503
  83: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect_macro
             at ./crates/ra_hir/src/nameres/collector.rs:706
  84: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
             at ./crates/ra_hir/src/nameres/collector.rs:568
  85: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
             at ./crates/ra_hir/src/nameres/collector.rs:504
  86: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect_macro
             at ./crates/ra_hir/src/nameres/collector.rs:706
  87: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
             at ./crates/ra_hir/src/nameres/collector.rs:568
  88: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
             at ./crates/ra_hir/src/nameres/collector.rs:504
  89: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect_macro
             at ./crates/ra_hir/src/nameres/collector.rs:706
  90: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
             at ./crates/ra_hir/src/nameres/collector.rs:568
  91: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
             at ./crates/ra_hir/src/nameres/collector.rs:504
  92: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect_macro
             at ./crates/ra_hir/src/nameres/collector.rs:706
  93: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
             at ./crates/ra_hir/src/nameres/collector.rs:568
  94: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
             at ./crates/ra_hir/src/nameres/collector.rs:504
  95: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect_macro
             at ./crates/ra_hir/src/nameres/collector.rs:706
  96: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
             at ./crates/ra_hir/src/nameres/collector.rs:568
  97: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
             at ./crates/ra_hir/src/nameres/collector.rs:504
  98: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect_macro
             at ./crates/ra_hir/src/nameres/collector.rs:706
  99: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
             at ./crates/ra_hir/src/nameres/collector.rs:568
  100: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect_module
             at ./crates/ra_hir/src/nameres/collector.rs:608
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by matklad** [comment]
Most likely due to recent parser refactorings, I’ll look into his tomorrow

**Comment by flodiebold** [comment]
@matklad yeah, some manual bisecting points to #1810.

**Comment by davyzhang** [comment]
Also here

```
[1;38;5;196mERROR[0m [ra_lsp_server::main_loop] [1;38;5;196munhandled notification: Notification { method: "$/setTraceNotification", params: Object({"value": String("off")}) }[0m
thread '<unnamed>' panicked at 'the parser seems stuck', crates/ra_parser/src/parser.rs:49:9
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic
   4: ra_parser::grammar::opt_visibility
   5: ra_parser::grammar::items::nominal::record_field_def_list
   6: ra_parser::grammar::items::nominal::struct_def
   7: ra_parser::grammar::items::maybe_item
   8: ra_parser::grammar::items::item_or_macro
   9: ra_parser::parse_fragment
  10: ra_mbe::subtree_parser::Parser::parse
  11: ra_mbe::mbe_expander::match_lhs
  12: core::iter::traits::iterator::Iterator::try_for_each::{{closure}}
  13: ra_mbe::mbe_expander::expand
  14: ra_mbe::MacroRules::expand
  15: ra_hir::ids::macro_expand_query
  16: salsa::runtime::Runtime<DB>::execute_query_implementation
  17: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  18: salsa::derived::slot::Slot<DB,Q,MP>::read
  19: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  20: ra_hir::ids::HirFileId::parse_macro_query
  21: salsa::runtime::Runtime<DB>::execute_query_implementation
  22: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  23: salsa::derived::slot::Slot<DB,Q,MP>::read
  24: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  25: ra_hir::ids::HirFileId::parse_or_expand_query
  26: ra_hir::source_id::AstIdMap::ast_id_map_query
  27: salsa::runtime::Runtime<DB>::execute_query_implementation
  28: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  29: salsa::derived::slot::Slot<DB,Q,MP>::read
  30: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  31: ra_hir::nameres::raw::RawItems::raw_items_with_source_map_query
  32: salsa::runtime::Runtime<DB>::execute_query_implementation
  33: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  34: salsa::derived::slot::Slot<DB,Q,MP>::read
  35: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  36: salsa::QueryTable<DB,Q>::get
  37: salsa::runtime::Runtime<DB>::execute_query_implementation
  38: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  39: salsa::derived::slot::Slot<DB,Q,MP>::read
  40: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  41: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
  42: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
  43: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
  44: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
  45: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
  46: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
  47: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
  48: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
  49: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
  50: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
  51: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
  52: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
  53: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
  54: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
  55: ra_hir::nameres::collector::collect_defs
  56: ra_hir::nameres::CrateDefMap::crate_def_map_query
  57: salsa::runtime::Runtime<DB>::execute_query_implementation
  58: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  59: salsa::derived::slot::Slot<DB,Q,MP>::read
  60: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  61: ra_hir::code_model::Crate::root_module
  62: ra_hir::nameres::collector::collect_defs
  63: ra_hir::nameres::CrateDefMap::crate_def_map_query
  64: salsa::runtime::Runtime<DB>::execute_query_implementation
  65: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  66: salsa::derived::slot::Slot<DB,Q,MP>::read
  67: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  68: ra_hir::code_model::Crate::root_module
  69: ra_hir::nameres::collector::collect_defs
  70: ra_hir::nameres::CrateDefMap::crate_def_map_query
  71: salsa::runtime::Runtime<DB>::execute_query_implementation
  72: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  73: salsa::derived::slot::Slot<DB,Q,MP>::read
  74: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  75: ra_hir::code_model::Crate::root_module
  76: ra_hir::nameres::collector::collect_defs
  77: ra_hir::nameres::CrateDefMap::crate_def_map_query
  78: salsa::runtime::Runtime<DB>::execute_query_implementation
  79: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  80: salsa::derived::slot::Slot<DB,Q,MP>::read
  81: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  82: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  83: ra_hir::source_binder::module_from_source
  84: ra_ide_api::diagnostics::diagnostics
  85: std::panicking::try::do_call
  86: __rust_maybe_catch_panic
  87: ra_db::CheckCanceled::catch_canceled
  88: ra_ide_api::Analysis::diagnostics
  89: ra_lsp_server::main_loop::handlers::publish_diagnostics
  90: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[1;38;5;196mERROR[0m [ra_lsp_server::main_loop] [1;38;5;196munhandled notification: Notification { method: "$/setTraceNotification", params: Object({"value": String("off")}) }[0m
thread '<unnamed>' panicked at 'the parser seems stuck', crates/ra_parser/src/parser.rs:49:9
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic
   4: ra_parser::grammar::opt_visibility
   5: ra_parser::grammar::items::nominal::record_field_def_list
   6: ra_parser::grammar::items::nominal::struct_def
   7: ra_parser::grammar::items::maybe_item
   8: ra_parser::grammar::items::item_or_macro
   9: ra_parser::parse_fragment
  10: ra_mbe::subtree_parser::Parser::parse
  11: ra_mbe::mbe_expander::match_lhs
  12: core::iter::traits::iterator::Iterator::try_for_each::{{closure}}
  13: ra_mbe::mbe_expander::expand
  14: ra_mbe::MacroRules::expand
  15: ra_hir::ids::macro_expand_query
  16: salsa::runtime::Runtime<DB>::execute_query_implementation
  17: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  18: salsa::derived::slot::Slot<DB,Q,MP>::read
  19: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  20: ra_hir::ids::HirFileId::parse_macro_query
  21: salsa::runtime::Runtime<DB>::execute_query_implementation
  22: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  23: salsa::derived::slot::Slot<DB,Q,MP>::read
  24: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  25: ra_hir::ids::HirFileId::parse_or_expand_query
  26: ra_hir::source_id::AstIdMap::ast_id_map_query
  27: salsa::runtime::Runtime<DB>::execute_query_implementation
  28: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  29: salsa::derived::slot::Slot<DB,Q,MP>::read
  30: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  31: ra_hir::nameres::raw::RawItems::raw_items_with_source_map_query
  32: salsa::runtime::Runtime<DB>::execute_query_implementation
  33: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  34: salsa::derived::slot::Slot<DB,Q,MP>::read
  35: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  36: salsa::QueryTable<DB,Q>::get
  37: salsa::runtime::Runtime<DB>::execute_query_implementation
  38: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  39: salsa::derived::slot::Slot<DB,Q,MP>::read
  40: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  41: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
  42: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
  43: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
  44: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
  45: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
  46: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
  47: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
  48: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
  49: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
  50: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
  51: ra_hir::nameres::collector::DefCollector<&DB>::collect_macro_expansion
  52: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
  53: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
  54: ra_hir::nameres::collector::ModCollector<&mut ra_hir::nameres::collector::DefCollector<&DB>>::collect
  55: ra_hir::nameres::collector::collect_defs
  56: ra_hir::nameres::CrateDefMap::crate_def_map_query
  57: salsa::runtime::Runtime<DB>::execute_query_implementation
  58: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  59: salsa::derived::slot::Slot<DB,Q,MP>::read
  60: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  61: ra_hir::code_model::Crate::root_module
  62: ra_hir::nameres::collector::collect_defs
  63: ra_hir::nameres::CrateDefMap::crate_def_map_query
  64: salsa::runtime::Runtime<DB>::execute_query_implementation
  65: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  66: salsa::derived::slot::Slot<DB,Q,MP>::read
  67: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  68: ra_hir::code_model::Crate::root_module
  69: ra_hir::nameres::collector::collect_defs
  70: ra_hir::nameres::CrateDefMap::crate_def_map_query
  71: salsa::runtime::Runtime<DB>::execute_query_implementation
  72: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  73: salsa::derived::slot::Slot<DB,Q,MP>::read
  74: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  75: ra_hir::code_model::Crate::root_module
  76: ra_hir::nameres::collector::collect_defs
  77: ra_hir::nameres::CrateDefMap::crate_def_map_query
  78: salsa::runtime::Runtime<DB>::execute_query_implementation
  79: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  80: salsa::derived::slot::Slot<DB,Q,MP>::read
  81: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  82: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  83: ra_hir::source_binder::module_from_source
  84: ra_ide_api::diagnostics::diagnostics
  85: std::panicking::try::do_call
  86: __rust_maybe_catch_panic
  87: ra_db::CheckCanceled::catch_canceled
  88: ra_ide_api::Analysis::diagnostics
  89: ra_lsp_server::main_loop::handlers::publish_diagnostics
  90: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
