### ISSUE TITLE
Chalks hangs and panics

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1927]
I see the following today:

```
      42458ms - diagnostics
         59ms - highlight
         16ms - main_loop_inner/loop-turn
         18ms - highlight
         49ms - main_loop_inner/loop-turn
      40261ms - diagnostics
            218ms - trait_solve_query
          39939ms - trait_solve_query
              1ms - parse_query (1 calls)
             29ms - trait_solve_query (32 calls)
      37974ms - diagnostics
      37974ms - diagnostics
      37720ms - diagnostics
thread '<unnamed>' panicked at 'assertion failed: self.stack.is_empty()', /home/matklad/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/df09cc6/chalk-engine/src/logic.rs:106:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:411
   8: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::ensure_root_answer
             at /home/matklad/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/df09cc6/chalk-solve/<::std::macros::panic macros>:3
   9: <chalk_engine::forest::ForestSolver<C,CO> as chalk_engine::context::AnswerStream<C>>::peek_answer
             at /home/matklad/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/df09cc6/chalk-engine/src/forest.rs:160
  10: chalk_solve::solve::slg::aggregate::<impl chalk_engine::context::AggregateOps<chalk_solve::solve::slg::SlgContext> for chalk_solve::solve::slg::SlgContextOps>::make_solution
             at /home/matklad/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/df09cc6/chalk-solve/src/solve/slg/aggregate.rs:23
  11: chalk_engine::forest::Forest<C>::solve
             at /home/matklad/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/df09cc6/chalk-engine/src/forest.rs:99
  12: chalk_solve::solve::Solver::solve
             at /home/matklad/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/df09cc6/chalk-solve/src/solve.rs:128
  13: ra_hir::ty::traits::TraitSolver::solve
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/ty/traits.rs:41
  14: ra_hir::ty::traits::trait_solve_query
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/ty/traits.rs:188
  15: <ra_hir::db::TraitSolveQuery as salsa::plumbing::QueryFunction<DB>>::execute
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/db.rs:149
  16: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:203
  17: salsa::runtime::Runtime<DB>::execute_query_implementation
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/runtime.rs:351
  18: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:200
  19: <salsa::derived::slot::Slot<DB,Q,MP> as salsa::dependency::DatabaseSlot<DB>>::maybe_changed_since
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:873
  20: salsa::dependency::Dependency<DB>::maybe_changed_since
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/dependency.rs:36
  21: salsa::derived::slot::Memo<DB,Q>::validate_memoized_value::{{closure}}
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:692
  22: <core::iter::adapters::Filter<I,P> as core::iter::traits::iterator::Iterator>::try_fold::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/adapters/mod.rs:750
  23: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/traits/iterator.rs:1671
  24: <core::iter::adapters::Filter<I,P> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/adapters/mod.rs:750
  25: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/traits/iterator.rs:1708
  26: <core::iter::adapters::Filter<I,P> as core::iter::traits::iterator::Iterator>::next
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/adapters/mod.rs:719
  27: salsa::derived::slot::Memo<DB,Q>::validate_memoized_value
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:690
  28: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:182
  29: salsa::derived::slot::Slot<DB,Q,MP>::read
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:140
  30: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived.rs:140
  31: salsa::QueryTable<DB,Q>::get
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:471
  32: <T as ra_hir::db::HirDatabase>::infer
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/db.rs:149
  33: <ra_hir::code_model::DefWithBody as ra_hir::code_model::HasBody>::infer
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/code_model.rs:589
  34: ra_hir::source_binder::SourceAnalyzer::new
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/source_binder.rs:147
  35: ra_ide_api::references::find_all_refs::find_binding
             at crates/ra_ide_api/src/references.rs:77
  36: ra_ide_api::references::find_all_refs
             at crates/ra_ide_api/src/references.rs:53
  37: ra_ide_api::Analysis::find_all_refs::{{closure}}
             at crates/ra_ide_api/src/lib.rs:477
  38: ra_db::CheckCanceled::catch_canceled::{{closure}}
             at /home/matklad/projects/rust-analyzer/crates/ra_db/src/lib.rs:39
  39: std::panicking::try::do_call
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:296
  40: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  41: std::panicking::try
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:275
  42: std::panic::catch_unwind
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panic.rs:394
  43: ra_db::CheckCanceled::catch_canceled
             at /home/matklad/projects/rust-analyzer/crates/ra_db/src/lib.rs:39
  44: ra_ide_api::Analysis::with_db
             at crates/ra_ide_api/src/lib.rs:556
  45: ra_ide_api::Analysis::find_all_refs
             at crates/ra_ide_api/src/lib.rs:477
  46: ra_lsp_server::main_loop::handlers::handle_document_highlight
             at crates/ra_lsp_server/src/main_loop/handlers.rs:734
  47: ra_lsp_server::main_loop::PoolDispatcher::on::{{closure}}
             at crates/ra_lsp_server/src/main_loop.rs:591
  48: <F as threadpool::FnBox>::call_box
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.7.1/src/lib.rs:95
  49: threadpool::spawn_in_pool::{{closure}}
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.7.1/src/lib.rs:767
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
      39705ms - trait_solve_query
thread '<unnamed>' panicked at 'assertion failed: self.stack.is_empty()', /home/matklad/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/df09cc6/chalk-engine/src/logic.rs:106:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:411
   8: chalk_engine::logic::<impl chalk_engine::forest::Forest<C>>::ensure_root_answer
             at /home/matklad/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/df09cc6/chalk-solve/<::std::macros::panic macros>:3
   9: <chalk_engine::forest::ForestSolver<C,CO> as chalk_engine::context::AnswerStream<C>>::peek_answer
             at /home/matklad/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/df09cc6/chalk-engine/src/forest.rs:160
  10: chalk_solve::solve::slg::aggregate::<impl chalk_engine::context::AggregateOps<chalk_solve::solve::slg::SlgContext> for chalk_solve::solve::slg::SlgContextOps>::make_solution
             at /home/matklad/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/df09cc6/chalk-solve/src/solve/slg/aggregate.rs:23
  11: chalk_engine::forest::Forest<C>::solve
             at /home/matklad/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/df09cc6/chalk-engine/src/forest.rs:99
  12: chalk_solve::solve::Solver::solve
             at /home/matklad/.cargo/git/checkouts/chalk-7b02fa8caa2cec94/df09cc6/chalk-solve/src/solve.rs:128
  13: ra_hir::ty::traits::TraitSolver::solve
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/ty/traits.rs:41
  14: ra_hir::ty::traits::trait_solve_query
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/ty/traits.rs:188
  15: <ra_hir::db::TraitSolveQuery as salsa::plumbing::QueryFunction<DB>>::execute
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/db.rs:149
  16: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:203
  17: salsa::runtime::Runtime<DB>::execute_query_implementation
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/runtime.rs:351
  18: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:200
  19: <salsa::derived::slot::Slot<DB,Q,MP> as salsa::dependency::DatabaseSlot<DB>>::maybe_changed_since
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:873
  20: salsa::dependency::Dependency<DB>::maybe_changed_since
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/dependency.rs:36
  21: salsa::derived::slot::Memo<DB,Q>::validate_memoized_value::{{closure}}
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:692
  22: <core::iter::adapters::Filter<I,P> as core::iter::traits::iterator::Iterator>::try_fold::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/adapters/mod.rs:750
  23: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/traits/iterator.rs:1671
  24: <core::iter::adapters::Filter<I,P> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/adapters/mod.rs:750
  25: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/traits/iterator.rs:1708
  26: <core::iter::adapters::Filter<I,P> as core::iter::traits::iterator::Iterator>::next
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/adapters/mod.rs:719
  27: salsa::derived::slot::Memo<DB,Q>::validate_memoized_value
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:690
  28: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:182
  29: salsa::derived::slot::Slot<DB,Q,MP>::read
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived/slot.rs:140
  30: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/derived.rs:140
  31: salsa::QueryTable<DB,Q>::get
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.13.0/src/lib.rs:471
  32: <T as ra_hir::db::HirDatabase>::infer
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/db.rs:149
  33: ra_hir::code_model::Function::infer
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/code_model.rs:707
  34: ra_hir::code_model::Function::diagnostics
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/code_model.rs:743
  35: ra_hir::code_model::Module::diagnostics
             at /home/matklad/projects/rust-analyzer/crates/ra_hir/src/code_model.rs:273
  36: ra_ide_api::diagnostics::diagnostics
             at crates/ra_ide_api/src/diagnostics.rs:94
  37: ra_ide_api::Analysis::diagnostics::{{closure}}
             at crates/ra_ide_api/src/lib.rs:533
  38: ra_db::CheckCanceled::catch_canceled::{{closure}}
             at /home/matklad/projects/rust-analyzer/crates/ra_db/src/lib.rs:39
  39: std::panicking::try::do_call
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:296
  40: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  41: std::panicking::try
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:275
  42: std::panic::catch_unwind
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panic.rs:394
  43: ra_db::CheckCanceled::catch_canceled
             at /home/matklad/projects/rust-analyzer/crates/ra_db/src/lib.rs:39
  44: ra_ide_api::Analysis::with_db
             at crates/ra_ide_api/src/lib.rs:556
  45: ra_ide_api::Analysis::diagnostics
             at crates/ra_ide_api/src/lib.rs:533
  46: ra_lsp_server::main_loop::handlers::handle_code_action
             at crates/ra_lsp_server/src/main_loop/handlers.rs:567
  47: ra_lsp_server::main_loop::PoolDispatcher::on::{{closure}}
             at crates/ra_lsp_server/src/main_loop.rs:591
  48: <F as threadpool::FnBox>::call_box
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.7.1/src/lib.rs:95
  49: threadpool::spawn_in_pool::{{closure}}
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.7.1/src/lib.rs:767
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
         17ms - diagnostics
      37740ms - handle_code_action
          37740ms - diagnostics
      39463ms - handle_code_action
```

Note how we need > 30 seconds to do anything, as well as a chalk's stack trace. I observed this when reading https://github.com/salsa-rs/salsa/pull/197

cc @flodiebold

**Comment by lnicola** [comment]
Similar to #1741?

**Comment by matklad** [comment]
Yeah, it seems pretty similar, but it definitely looks like a recent regression: I didn't see this problem a couple of days ago.

**Comment by matklad** [comment]
Hm, I can't reproduce this at all now :-( Could it be some issue which depends on ordering of the things? Ie, some unsound caching inside chalk?

**Comment by matklad** [comment]
Ok, I think I can somewhat reproduce it, if I open `derived/slot.rs` and ask for copmletions and change whitespace several times around here:

![image](https://user-images.githubusercontent.com/1711539/65764440-4f7f5180-e12e-11e9-88c1-8a05b0079662.png)

Note that I am much more successful in reproducing slowness than in reproducing the panic. Perhaps these are independent issues?

**Comment by matklad** [comment]
Ok, and now I've reproduced a panic:

* first, I go to input.rs and invoke completion around here:

![image](https://user-images.githubusercontent.com/1711539/65764645-cc123000-e12e-11e9-9417-1b480d97edbe.png)

It succeeds.

* second, I go to `derived/slot.rs`, and invoce copmletion s in the previous comment. After that, I get "panicked at 'assertion failed: self.stack.is_empty()'"

**Comment by matklad** [comment]
See https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/Logic.20panics

Chalk is not panic safe, and we panic through chalk during cancellation. And that wasn't caught because https://github.com/rust-analyzer/rust-analyzer/commit/fcffa6ba6bfc8647a8f3aa858b05981d12a6e74f was never implemented properly...

**Comment by matklad** [comment]
This was worked around by using a mutex with poisoning. Upstream bug is https://github.com/rust-lang/chalk/issues/260
