### ISSUE TITLE
dies without error message

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-analyzer/rust-analyzer#2416]
Sometimes when running `ra_cli  analysis-stats .` on the rustc repo, it seems to terminate without any kind of error message or panic.
Exit code is `101`.

````
ERROR [ra_project_model] cyclic dependency libc -> rustc-std-workspace-core
ERROR [ra_project_model] cyclic dependency cargo-test-support -> cargo
ERROR [ra_project_model] cyclic dependency cfg-if -> compiler_builtins
ERROR [ra_project_model] cyclic dependency getrandom -> cfg-if
ERROR [ra_project_model] cyclic dependency getrandom -> wasi
Database loaded, 504 roots, 734.093554ms
Crates in this dir: 155
Total modules found: 2190
Total declarations: 87893
Total functions: 35291
Item Collection: 35.253001282s, 0b allocated 0b resident
████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 28367/35291
processing: compare_inputs
````
ra @ 6560e4ff2eae4e54384896d6ae100f1d2df20518

**Comment by lnicola** [comment]
What's the exit code? (echo $?)

**Comment by matthiaskrgr** [comment]
101

**Comment by lnicola** [comment]
Sorry, I didn't notice that in your original post. 101 should be a panic exit code. Maybe the progress bar hides `stderr` -- does anything change if you add `-q`?

**Comment by matklad** [comment]
Ideally, we should just replace indicatiff with a simpler progress
indicator (just printing x out of y). It just doesn't pull its weight for
our use case

**Comment by edwin0cheng** [comment]
Yeah, and indicatiff with that block glyph do not work in Windows Cmder Console too. Let me take this task ;)

**Comment by marcogroppo** [comment]
Probably chalk related: 

```
thread 'main' panicked at 'truncate extracted a pending value that references internal binder: 
Ty(StructId(7331)<^0>)', 
checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-solve\src\solve\slg\resolvent.rs:292:17

stack backtrace:
  [...]
  11: std::panicking::begin_panic_fmt
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:335
  12: core::result::Result<chalk_ir::ParameterKind<chalk_ir::Ty<chalk_ir::family::ChalkIr>, chalk_ir::Lifetime<chalk_ir::family::ChalkIr>>, chalk_engine::fallible::NoSolution>::unwrap_or_else
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libcore\result.rs:818
  13: chalk_solve::solve::slg::resolvent::AnswerSubstitutor<chalk_ir::family::ChalkIr>::unify_free_answer_var<chalk_ir::family::ChalkIr>
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-solve\src\solve\slg\resolvent.rs:289
  14: chalk_solve::solve::slg::resolvent::{{impl}}::zip_tys<chalk_ir::family::ChalkIr>
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-solve\src\solve\slg\resolvent.rs:335
  15: chalk_ir::zip::{{impl}}::zip_with
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-ir\src\zip.rs:171
  16: chalk_ir::zip::{{impl}}::zip_with
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-ir\src\zip.rs:174
  17: chalk_ir::zip::{{impl}}::zip_with
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-ir\src\zip.rs:174
  18: chalk_solve::solve::slg::resolvent::{{impl}}::zip_binders<chalk_ir::family::ChalkIr,chalk_ir::WhereClause<chalk_ir::family::ChalkIr>>
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-solve\src\solve\slg\resolvent.rs:425
  19: chalk_ir::zip::{{impl}}::zip_with
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-ir\src\zip.rs:171
  20: chalk_ir::zip::{{impl}}::zip_with
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-ir\src\zip.rs:176
  21: chalk_ir::zip::{{impl}}::zip_with
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-ir\src\zip.rs:171
  22: chalk_solve::solve::slg::resolvent::{{impl}}::zip_binders
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-solve\src\solve\slg\resolvent.rs:425
  23: chalk_ir::zip::{{impl}}::zip_with
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-ir\src\zip.rs:171
  24: chalk_solve::solve::slg::resolvent::{{impl}}::zip_tys<chalk_ir::family::ChalkIr>
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-solve\src\solve\slg\resolvent.rs:351
  25: chalk_ir::zip::{{impl}}::zip_with
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-ir\src\zip.rs:303
  26: chalk_ir::zip::{{impl}}::zip_with
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-ir\src\zip.rs:304
  27: chalk_ir::zip::{{impl}}::zip_with
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-ir\src\zip.rs:303
  28: chalk_ir::zip::{{impl}}::zip_with
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-ir\src\zip.rs:308
  29: chalk_ir::zip::{{impl}}::zip_with
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-ir\src\zip.rs:303
  30: chalk_ir::zip::{{impl}}::zip_with
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-ir\src\zip.rs:306
  31: chalk_ir::zip::{{impl}}::zip_with<chalk_ir::family::ChalkIr,chalk_solve::solve::slg::resolvent::AnswerSubstitutor<chalk_ir::family::ChalkIr>>
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-ir\src\zip.rs:224
  32: chalk_ir::zip::{{impl}}::zip_with
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-ir\src\zip.rs:306
  33: chalk_ir::zip::{{impl}}::zip_with<chalk_ir::family::ChalkIr,chalk_solve::solve::slg::resolvent::AnswerSubstitutor<chalk_ir::family::ChalkIr>>
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-ir\src\zip.rs:274
  34: chalk_solve::solve::slg::resolvent::AnswerSubstitutor<chalk_ir::family::ChalkIr>::substitute
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-solve\src\solve\slg\resolvent.rs:272
  35: chalk_solve::solve::slg::resolvent::{{impl}}::apply_answer_subst<chalk_ir::family::ChalkIr>
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-solve\src\solve\slg\resolvent.rs:233
  36: chalk_engine::forest::Forest<chalk_solve::solve::slg::SlgContext<chalk_ir::family::ChalkIr>>::pursue_strand<chalk_solve::solve::slg::SlgContext<chalk_ir::family::ChalkIr>,chalk_solve::solve::slg::SlgContextOps<chalk_ir::family::ChalkIr>>
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-engine\src\logic.rs:480
  37: chalk_engine::logic::{{impl}}::pursue_next_strand::{{closure}}
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-engine\src\logic.rs:260
  38: chalk_solve::solve::slg::{{impl}}::instantiate_ex_clause<chalk_ir::family::ChalkIr,core::result::Result<(), chalk_engine::logic::StrandFail<chalk_solve::solve::slg::SlgContext<chalk_ir::family::ChalkIr>>>,closure-0>
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-solve\src\solve\slg.rs:220
  39: chalk_engine::forest::Forest<chalk_solve::solve::slg::SlgContext<chalk_ir::family::ChalkIr>>::pursue_next_strand<chalk_solve::solve::slg::SlgContext<chalk_ir::family::ChalkIr>,chalk_solve::solve::slg::SlgContextOps<chalk_ir::family::ChalkIr>>
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-engine\src\logic.rs:251
  40: chalk_engine::logic::{{impl}}::ensure_answer_recursively::{{closure}}
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-engine\src\logic.rs:213
  41: stacker::maybe_grow
             at \rust\cargo\registry\src\github.com-1ecc6299db9ec823\stacker-0.1.6\src\lib.rs:52
  42: chalk_engine::maybe_grow_stack
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-engine\src\lib.rs:305
  43: chalk_engine::forest::Forest<chalk_solve::solve::slg::SlgContext<chalk_ir::family::ChalkIr>>::ensure_answer_recursively<chalk_solve::solve::slg::SlgContext<chalk_ir::family::ChalkIr>,chalk_solve::solve::slg::SlgContextOps<chalk_ir::family::ChalkIr>>
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-engine\src\logic.rs:213
  44: chalk_engine::forest::{{impl}}::peek_answer<chalk_solve::solve::slg::SlgContext<chalk_ir::family::ChalkIr>,chalk_solve::solve::slg::SlgContextOps<chalk_ir::family::ChalkIr>>
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-engine\src\forest.rs:194
  45: chalk_solve::solve::slg::aggregate::{{impl}}::make_solution<chalk_ir::family::ChalkIr,chalk_engine::forest::ForestSolver<chalk_solve::solve::slg::SlgContext<chalk_ir::family::ChalkIr>, chalk_solve::solve::slg::SlgContextOps<chalk_ir::family::ChalkIr>>>
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-solve\src\solve\slg\aggregate.rs:24
  46: chalk_engine::forest::Forest<chalk_solve::solve::slg::SlgContext<chalk_ir::family::ChalkIr>>::solve<chalk_solve::solve::slg::SlgContext<chalk_ir::family::ChalkIr>,chalk_solve::solve::slg::SlgContextOps<chalk_ir::family::ChalkIr>>
             at checkouts\chalk-af2ed8365b2aac89\095cd38\chalk-engine\src\forest.rs:112
  47: ra_hir::ty::traits::trait_solve_query<ra_ide_api::db::RootDatabase>
             at src\rust-analyzer\crates\ra_hir\src\ty\traits.rs:197
  48: salsa::runtime::Runtime<ra_ide_api::db::RootDatabase>::execute_query_implementation<ra_ide_api::db::RootDatabase,core::option::Option<ra_hir::ty::traits::Solution>,closure-1>
             at \rust\cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.14.1\src\runtime.rs:352
  49: salsa::derived::slot::Slot<ra_ide_api::db::RootDatabase, ra_hir::db::TraitSolveQuery, salsa::derived::AlwaysMemoizeValue>::read_upgrade<ra_ide_api::db::RootDatabase,ra_hir::db::TraitSolveQuery,salsa::derived::AlwaysMemoizeValue>
             at \rust\cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.14.1\src\derived\slot.rs:217
  50: salsa::derived::slot::Slot<ra_ide_api::db::RootDatabase, ra_hir::db::TraitSolveQuery, salsa::derived::AlwaysMemoizeValue>::read<ra_ide_api::db::RootDatabase,ra_hir::db::TraitSolveQuery,salsa::derived::AlwaysMemoizeValue>
             at \rust\cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.14.1\src\derived\slot.rs:149
  51: salsa::derived::{{impl}}::try_fetch<ra_ide_api::db::RootDatabase,ra_hir::db::TraitSolveQuery,salsa::derived::AlwaysMemoizeValue>
             at \rust\cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.14.1\src\derived.rs:140
  52: salsa::QueryTable<ra_ide_api::db::RootDatabase, ra_hir::db::TraitSolveQuery>::try_get
             at \rust\cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.14.1\src\lib.rs:483
  53: salsa::QueryTable<ra_ide_api::db::RootDatabase, ra_hir::db::TraitSolveQuery>::get<ra_ide_api::db::RootDatabase,ra_hir::db::TraitSolveQuery>
             at \rust\cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.14.1\src\lib.rs:479
  54: ra_hir::db::{{impl}}::trait_solve
             at src\rust-analyzer\crates\ra_hir\src\db.rs:34
  55: ra_hir::ty::method_resolution::iterate_trait_method_candidates
             at src\rust-analyzer\crates\ra_hir\src\ty\method_resolution.rs:268
  56: ra_hir::ty::method_resolution::iterate_method_candidates
             at src\rust-analyzer\crates\ra_hir\src\ty\method_resolution.rs:206
  57: ra_hir::ty::method_resolution::lookup_method<ra_ide_api::db::RootDatabase>
             at src\rust-analyzer\crates\ra_hir\src\ty\method_resolution.rs:152
  58: ra_hir::ty::infer::InferenceContext<ra_ide_api::db::RootDatabase>::infer_method_call<ra_ide_api::db::RootDatabase>
             at src\rust-analyzer\crates\ra_hir\src\ty\infer\expr.rs:551
  59: ra_hir::ty::infer::InferenceContext<ra_ide_api::db::RootDatabase>::infer_expr_inner<ra_ide_api::db::RootDatabase>
             at src\rust-analyzer\crates\ra_hir\src\ty\infer\expr.rs:168
  60: ra_hir::ty::infer::InferenceContext<ra_ide_api::db::RootDatabase>::infer_expr<ra_ide_api::db::RootDatabase>
             at src\rust-analyzer\crates\ra_hir\src\ty\infer\expr.rs:30
  61: ra_hir::ty::infer::InferenceContext<ra_ide_api::db::RootDatabase>::infer_method_call<ra_ide_api::db::RootDatabase>
             at src\rust-analyzer\crates\ra_hir\src\ty\infer\expr.rs:549
  62: ra_hir::ty::infer::InferenceContext<ra_ide_api::db::RootDatabase>::infer_expr_inner<ra_ide_api::db::RootDatabase>
             at src\rust-analyzer\crates\ra_hir\src\ty\infer\expr.rs:168
  63: ra_hir::ty::infer::InferenceContext<ra_ide_api::db::RootDatabase>::infer_expr<ra_ide_api::db::RootDatabase>
             at src\rust-analyzer\crates\ra_hir\src\ty\infer\expr.rs:30
  64: ra_hir::ty::infer::InferenceContext<ra_ide_api::db::RootDatabase>::infer_expr_inner<ra_ide_api::db::RootDatabase>
             at src\rust-analyzer\crates\ra_hir\src\ty\infer\expr.rs:301
  65: ra_hir::ty::infer::InferenceContext<ra_ide_api::db::RootDatabase>::infer_expr_coerce<ra_ide_api::db::RootDatabase>
             at src\rust-analyzer\crates\ra_hir\src\ty\infer\expr.rs:45
  66: ra_hir::ty::infer::InferenceContext<ra_ide_api::db::RootDatabase>::infer_expr_inner<ra_ide_api::db::RootDatabase>
             at src\rust-analyzer\crates\ra_hir\src\ty\infer\expr.rs:78
  67: ra_hir::ty::infer::InferenceContext<ra_ide_api::db::RootDatabase>::infer_expr<ra_ide_api::db::RootDatabase>
             at src\rust-analyzer\crates\ra_hir\src\ty\infer\expr.rs:30
  68: ra_hir::ty::infer::InferenceContext<ra_ide_api::db::RootDatabase>::infer_body
             at src\rust-analyzer\crates\ra_hir\src\ty\infer.rs:557
  69: ra_hir::ty::infer::infer_query<ra_ide_api::db::RootDatabase>
             at src\rust-analyzer\crates\ra_hir\src\ty\infer.rs:76
  70: salsa::runtime::Runtime<ra_ide_api::db::RootDatabase>::execute_query_implementation<ra_ide_api::db::RootDatabase,alloc::sync::Arc<ra_hir::ty::infer::InferenceResult>,closure-1>
             at \rust\cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.14.1\src\runtime.rs:352
  71: salsa::derived::slot::Slot<ra_ide_api::db::RootDatabase, ra_hir::db::InferQuery, salsa::derived::AlwaysMemoizeValue>::read_upgrade<ra_ide_api::db::RootDatabase,ra_hir::db::InferQuery,salsa::derived::AlwaysMemoizeValue>
             at \rust\cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.14.1\src\derived\slot.rs:217
  72: salsa::derived::slot::Slot<ra_ide_api::db::RootDatabase, ra_hir::db::InferQuery, salsa::derived::AlwaysMemoizeValue>::read<ra_ide_api::db::RootDatabase,ra_hir::db::InferQuery,salsa::derived::AlwaysMemoizeValue>
             at \rust\cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.14.1\src\derived\slot.rs:149
  73: salsa::derived::{{impl}}::try_fetch<ra_ide_api::db::RootDatabase,ra_hir::db::InferQuery,salsa::derived::AlwaysMemoizeValue>
             at \rust\cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.14.1\src\derived.rs:140
  74: salsa::QueryTable<ra_ide_api::db::RootDatabase, ra_hir::db::InferQuery>::try_get
             at \rust\cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.14.1\src\lib.rs:483
  75: salsa::QueryTable<ra_ide_api::db::RootDatabase, ra_hir::db::InferQuery>::get<ra_ide_api::db::RootDatabase,ra_hir::db::InferQuery>
             at \rust\cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.14.1\src\lib.rs:479
  76: ra_hir::db::{{impl}}::infer
             at src\rust-analyzer\crates\ra_hir\src\db.rs:34
  77: ra_hir::code_model::Function::infer
             at src\rust-analyzer\crates\ra_hir\src\code_model.rs:623
  78: ra_cli::analysis_stats::run
             at src\rust-analyzer\crates\ra_cli\src\analysis_stats.rs:111
  79: ra_cli::main
             at src\rust-analyzer\crates\ra_cli\src\main.rs:108
```

**Comment by matthiaskrgr** [comment]
Ok so the underlying crash is probably https://github.com/rust-analyzer/rust-analyzer/issues/2380 then, except that RA no longer prints stacktraces now?

**Comment by marcogroppo** [comment]
@matthiaskrgr yes, this looks like the same issue

**Comment by matklad** [comment]
I think this can be closed now, as we removed indicatiff which was buffering the error .
