### ISSUE TITLE
Random assist Option::unwrap panic

### ISSUE THREAD

**Issue by CAD97** [rust-analyzer/rust-analyzer#2464]
Was hacking on rustc and noticed this panic in the rust-analyzer tool output. Sorry, I don't have a more minimal repro than "something something rustc" 😓

```
[1;38;5;196mERROR[0m [ra_project_model] [1;38;5;196mcyclic dependency cargo -> cargo-test-support[0m
[1;38;5;196mERROR[0m [ra_project_model] [1;38;5;196mcyclic dependency compiler_builtins -> cc[0m
[1;38;5;196mERROR[0m [ra_project_model] [1;38;5;196mcyclic dependency alloc -> rand_xorshift[0m
[1;38;5;196mERROR[0m [ra_project_model] [1;38;5;196mcyclic dependency rand -> getrandom[0m
[1;38;5;196mERROR[0m [ra_project_model] [1;38;5;196mcyclic dependency rand -> libc[0m
[1;38;5;196mERROR[0m [ra_project_model] [1;38;5;196mcyclic dependency rand -> rand_chacha[0m
[1;38;5;196mERROR[0m [ra_project_model] [1;38;5;196mcyclic dependency rand -> rand_core[0m
[1;38;5;196mERROR[0m [ra_project_model] [1;38;5;196mcyclic dependency rand -> rand_hc[0m
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:378:21
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\sys_common\backtrace.rs:77
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\sys_common\backtrace.rs:61
   3: core::fmt::write
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libcore\fmt\mod.rs:1028
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\io\mod.rs:1412
   5: std::sys_common::backtrace::_print
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\sys_common\backtrace.rs:65
   6: std::sys_common::backtrace::print
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\sys_common\backtrace.rs:50
   7: std::panicking::default_hook::{{closure}}
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\panicking.rs:188
   8: std::panicking::default_hook
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\panicking.rs:205
   9: std::panicking::rust_panic_with_hook
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\panicking.rs:464
  10: std::panicking::continue_panic_fmt
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\panicking.rs:373
  11: std::panicking::rust_begin_panic
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\panicking.rs:302
  12: core::panicking::panic_fmt
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libcore\panicking.rs:139
  13: core::panicking::panic
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libcore\panicking.rs:70
  14: ra_assists::assists::add_new::add_new
  15: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  16: ra_assists::assist_ctx::AssistCtx<DB>::with_ctx
  17: ra_ide_api::assists::assists
  18: std::panicking::try::do_call
  19: panic_unwind::__rust_maybe_catch_panic
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libpanic_unwind\lib.rs:78
  20: ra_db::CheckCanceled::catch_canceled
  21: ra_ide_api::Analysis::assists
  22: ra_lsp_server::main_loop::handlers::handle_code_action
  23: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:378:21
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\sys_common\backtrace.rs:77
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\sys_common\backtrace.rs:61
   3: core::fmt::write
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libcore\fmt\mod.rs:1028
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\io\mod.rs:1412
   5: std::sys_common::backtrace::_print
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\sys_common\backtrace.rs:65
   6: std::sys_common::backtrace::print
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\sys_common\backtrace.rs:50
   7: std::panicking::default_hook::{{closure}}
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\panicking.rs:188
   8: std::panicking::default_hook
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\panicking.rs:205
   9: std::panicking::rust_panic_with_hook
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\panicking.rs:464
  10: std::panicking::continue_panic_fmt
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\panicking.rs:373
  11: std::panicking::rust_begin_panic
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libstd\panicking.rs:302
  12: core::panicking::panic_fmt
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libcore\panicking.rs:139
  13: core::panicking::panic
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libcore\panicking.rs:70
  14: ra_assists::assists::add_new::add_new
  15: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  16: ra_assists::assist_ctx::AssistCtx<DB>::with_ctx
  17: ra_ide_api::assists::assists
  18: std::panicking::try::do_call
  19: panic_unwind::__rust_maybe_catch_panic
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1\/src\libpanic_unwind\lib.rs:78
  20: ra_db::CheckCanceled::catch_canceled
  21: ra_ide_api::Analysis::assists
  22: ra_lsp_server::main_loop::handlers::handle_code_action
  23: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by kjeremy** [comment]
Looks like it might be a dup of #2414

**Comment by lnicola** [comment]
The backtrace seems to point to the `add_new` assist, which does have a number of `unwrap`s. Maybe it could be made more robust?
