### ISSUE TITLE
unify: index out of bounds during batch analysis

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#2467]
Happens on the RA repo:

```
6/4176 0% processing: from_sourcethread 'main' panicked at 'index out of bounds: the len is 1 but the index is 8', /rustc/5c5b8afd80e6fa1d24632153cb2257c686041d41/src/libcore/slice/mod.rs:2797:10
stack backtrace:
[snip]
  14: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
  15: <usize as core::slice::SliceIndex<[T]>>::index
             at /rustc/5c5b8afd80e6fa1d24632153cb2257c686041d41/src/libcore/slice/mod.rs:2797
  16: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/5c5b8afd80e6fa1d24632153cb2257c686041d41/src/libcore/slice/mod.rs:2648
  17: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /rustc/5c5b8afd80e6fa1d24632153cb2257c686041d41/src/liballoc/vec.rs:1851
  18: ena::snapshot_vec::SnapshotVec<D>::get
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.13.1/src/snapshot_vec.rs:126
  19: <ena::snapshot_vec::SnapshotVec<D> as core::ops::index::Index<usize>>::index
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.13.1/src/snapshot_vec.rs:255
  20: <ena::unify::backing_vec::InPlace<K> as core::ops::index::Index<usize>>::index
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.13.1/src/unify/backing_vec.rs:124
  21: ena::unify::UnificationTable<S>::value
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.13.1/src/unify/mod.rs:315
  22: ena::unify::UnificationTable<S>::inlined_get_root_key
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.13.1/src/unify/mod.rs:330
  23: ena::unify::UnificationTable<S>::inlined_probe_value
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.13.1/src/unify/mod.rs:535
  24: ra_hir_ty::infer::unify::InferenceTable::resolve_ty_shallow
             at crates/ra_hir_ty/src/infer/unify.rs:298
  25: ra_hir_ty::infer::unify::InferenceTable::unify_inner
             at crates/ra_hir_ty/src/infer/unify.rs:239
  26: ra_hir_ty::infer::unify::InferenceTable::unify_substs::{{closure}}
             at crates/ra_hir_ty/src/infer/unify.rs:226
  27: core::iter::traits::iterator::Iterator::all::check::{{closure}}
             at /rustc/5c5b8afd80e6fa1d24632153cb2257c686041d41/src/libcore/iter/traits/iterator.rs:1880
  28: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/5c5b8afd80e6fa1d24632153cb2257c686041d41/src/libcore/iter/traits/iterator.rs:1710
  29: core::iter::traits::iterator::Iterator::all
             at /rustc/5c5b8afd80e6fa1d24632153cb2257c686041d41/src/libcore/iter/traits/iterator.rs:1884
  30: ra_hir_ty::infer::unify::InferenceTable::unify_substs
             at crates/ra_hir_ty/src/infer/unify.rs:226
  31: ra_hir_ty::infer::unify::InferenceTable::unify_inner
             at crates/ra_hir_ty/src/infer/unify.rs:242
  32: ra_hir_ty::infer::unify::InferenceTable::unify
             at crates/ra_hir_ty/src/infer/unify.rs:222
  33: ra_hir_ty::infer::unify::unify
             at crates/ra_hir_ty/src/infer/unify.rs:175
  34: ra_hir_ty::method_resolution::inherent_impl_substs
             at ./crates/ra_hir_ty/src/method_resolution.rs:445
  35: ra_hir_ty::infer::path::<impl ra_hir_ty::infer::InferenceContext<D>>::resolve_ty_assoc_item::{{closure}}
             at ./crates/ra_hir_ty/src/infer/path.rs:210
  36: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/5c5b8afd80e6fa1d24632153cb2257c686041d41/src/libcore/ops/function.rs:265
  37: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/5c5b8afd80e6fa1d24632153cb2257c686041d41/src/libcore/ops/function.rs:265
  38: ra_hir_ty::method_resolution::iterate_inherent_methods
             at ./crates/ra_hir_ty/src/method_resolution.rs:391
  39: ra_hir_ty::method_resolution::iterate_method_candidates_for_self_ty
             at ./crates/ra_hir_ty/src/method_resolution.rs:318
  40: ra_hir_ty::method_resolution::iterate_method_candidates
             at ./crates/ra_hir_ty/src/method_resolution.rs:223
  41: ra_hir_ty::infer::path::<impl ra_hir_ty::infer::InferenceContext<D>>::resolve_ty_assoc_item
             at ./crates/ra_hir_ty/src/infer/path.rs:194
  42: ra_hir_ty::infer::path::<impl ra_hir_ty::infer::InferenceContext<D>>::resolve_assoc_item
             at ./crates/ra_hir_ty/src/infer/path.rs:131
  43: ra_hir_ty::infer::path::<impl ra_hir_ty::infer::InferenceContext<D>>::resolve_value_path
             at ./crates/ra_hir_ty/src/infer/path.rs:52
  44: ra_hir_ty::infer::path::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_path
             at ./crates/ra_hir_ty/src/infer/path.rs:21
  45: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
             at ./crates/ra_hir_ty/src/infer/expr.rs:192
  46: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr
             at ./crates/ra_hir_ty/src/infer/expr.rs:27
  47: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
             at ./crates/ra_hir_ty/src/infer/expr.rs:151
  48: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_coerce
             at ./crates/ra_hir_ty/src/infer/expr.rs:42
  49: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_block
             at ./crates/ra_hir_ty/src/infer/expr.rs:568
  50: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr_inner
             at ./crates/ra_hir_ty/src/infer/expr.rs:75
  51: ra_hir_ty::infer::expr::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_expr
             at ./crates/ra_hir_ty/src/infer/expr.rs:27
  52: ra_hir_ty::infer::InferenceContext<D>::infer_body
             at ./crates/ra_hir_ty/src/infer.rs:403
  53: ra_hir_ty::infer::infer_query
             at ./crates/ra_hir_ty/src/infer.rs:73
  54: <ra_hir_ty::db::InferQuery as salsa::plumbing::QueryFunction<DB>>::execute
             at ./crates/ra_hir_ty/src/db.rs:18
  55: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.14.1/src/derived/slot.rs:220
  56: salsa::runtime::Runtime<DB>::execute_query_implementation
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.14.1/src/runtime.rs:352
  57: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.14.1/src/derived/slot.rs:217
  58: salsa::derived::slot::Slot<DB,Q,MP>::read
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.14.1/src/derived/slot.rs:149
  59: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.14.1/src/derived.rs:140
  60: salsa::QueryTable<DB,Q>::try_get
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.14.1/src/lib.rs:483
  61: salsa::QueryTable<DB,Q>::get
             at /home/grayshade/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.14.1/src/lib.rs:479
  62: <T as ra_hir_ty::db::HirDatabase>::infer
             at ./crates/ra_hir_ty/src/db.rs:18
  63: ra_hir::code_model::Function::infer
             at ./crates/ra_hir/src/code_model.rs:609
  64: ra_cli::analysis_stats::run
             at crates/ra_cli/src/analysis_stats.rs:105
  65: ra_cli::main
             at crates/ra_cli/src/main.rs:108
  66: std::rt::lang_start::{{closure}}
             at /rustc/5c5b8afd80e6fa1d24632153cb2257c686041d41/src/libstd/rt.rs:61
  67: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  68: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  69: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  70: std::panicking::try
             at src/libstd/panicking.rs:265
  71: std::panic::catch_unwind
             at src/libstd/panic.rs:395
  72: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  73: main
  74: __libc_start_main
  75: _start
```

**Comment by lnicola** [comment]
Regressed by #2463 cc @flodiebold

**Comment by flodiebold** [comment]
Of course, I did a 'simple' refactoring during cleanup and didn't check analysis-stats again...

**Comment by lnicola** [comment]
It's too bad we can't run it on CI.

**Comment by matklad** [comment]
We can, but I am not sure if its worth it.
