### ISSUE TITLE
thread '<unknown>' has overflowed its stack

### ISSUE THREAD

**Issue by gentoid** [rust-analyzer/rust-analyzer#2631]
From the `cargo xtask install`:
```
will run: cargo --version
cargo 1.41.0-nightly (626f0f40e 2019-12-03)
...
will run: cmd.exe /c npm --version
6.9.0
...
will run: cmd.exe /c code.cmd --version
1.41.1
26076a4de974ead31f97692a0d32f90d735645c0
x64
```

The `rustup show` output:
```
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\vlz\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.42.0-nightly (0de96d37f 2019-12-19)
```

I'm getting these errors after updating to the latest `master`:

```

thread '<unknown>' has overflowed its stack

thread '<unknown>' has overflowed its stack

thread '<unknown>' has overflowed its stack

thread '<unknown>' has overflowed its stack
[Info  - 2:32:18 PM] Connection to server got closed. Server will restart.
[Error - 2:32:18 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:4103:25)
	at Object.dispose (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:8629:35)
	at LanguageClient.handleConnectionClosed (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:10864:42)
	at LanguageClient.handleConnectionClosed (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:13713:15)
	at closeHandler (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:10851:18)
	at CallbackList.invoke (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:2217:39)
	at Emitter.fire (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:2276:36)
	at closeHandler (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:3439:26)
	at CallbackList.invoke (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:2217:39)
	at Emitter.fire (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:2276:36)
	at StreamMessageReader.fireClose (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:2401:27)
	at Socket.<anonymous> (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:2441:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
[Error - 2:32:18 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:4103:25)
	at Object.dispose (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:8629:35)
	at LanguageClient.handleConnectionClosed (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:10864:42)
	at LanguageClient.handleConnectionClosed (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:13713:15)
	at closeHandler (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:10851:18)
	at CallbackList.invoke (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:2217:39)
	at Emitter.fire (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:2276:36)
	at closeHandler (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:3439:26)
	at CallbackList.invoke (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:2217:39)
	at Emitter.fire (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:2276:36)
	at StreamMessageReader.fireClose (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:2401:27)
	at Socket.<anonymous> (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:2441:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
[Error - 2:32:18 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:4103:25)
	at Object.dispose (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:8629:35)
	at LanguageClient.handleConnectionClosed (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:10864:42)
	at LanguageClient.handleConnectionClosed (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:13713:15)
	at closeHandler (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:10851:18)
	at CallbackList.invoke (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:2217:39)
	at Emitter.fire (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:2276:36)
	at closeHandler (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:3439:26)
	at CallbackList.invoke (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:2217:39)
	at Emitter.fire (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:2276:36)
	at StreamMessageReader.fireClose (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:2401:27)
	at Socket.<anonymous> (c:\Users\vlz\.vscode\extensions\matklad.ra-lsp-0.0.1\bundle\extension.js:2441:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
```

And after `git bisect`ing I've found the commit introduced that:

```
» git bisect bad
ab7a70fb14d281507b6e6726b47614035b073a28 is the first bad commit
commit ab7a70fb14d281507b6e6726b47614035b073a28
Author: Aleksey Kladov <aleksey.kladov@gmail.com>
Date:   Sat Dec 21 12:38:40 2019 +0100

    Don't track imports

 crates/ra_hir_def/src/item_scope.rs        | 35 ++++++++-------------------
 crates/ra_hir_def/src/nameres/collector.rs | 39 ++++++++++++------------------
 2 files changed, 26 insertions(+), 48 deletions(-)
```

**Comment by matklad** [comment]
This is a recent regression investigating it right now, 90ef070db3dce0a7acb9cd11d0b0d72de13c9d79 is a known-good version
