### ISSUE TITLE
Panic on infer local generic function with trait

### ISSUE THREAD

**Issue by edwin0cheng** [rust-analyzer/rust-analyzer#2669]
A minimal example (master 97f0139): 
```rust
trait A {}
trait Write {}
struct Response<T> {}

trait D {
    fn foo();
}

impl<T:A> D for Response<T> {
    fn foo() {
        end();
        fn end<W: Write>() {}
    }
}
```
Stack trace:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:378:21
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:77
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:61
   3: core::fmt::write
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\fmt\mod.rs:1028
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\io\mod.rs:1412
   5: std::sys_common::backtrace::_print
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:65
   6: std::sys_common::backtrace::print
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:50
   7: std::panicking::default_hook::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:188
   8: std::panicking::default_hook
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:205
   9: std::panicking::rust_panic_with_hook
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:464
  10: std::panicking::continue_panic_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:373
  11: std::panicking::rust_begin_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:302
  12: core::panicking::panic_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\panicking.rs:139
  13: core::panicking::panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\panicking.rs:70
  14: ra_hir_ty::utils::Generics::param_name
  15: ra_hir_ty::utils::Generics::param_idx
  16: ra_hir_ty::lower::<impl ra_hir_ty::Ty>::from_partly_resolved_hir_path
  17: ra_hir_ty::lower::<impl ra_hir_ty::Ty>::from_hir
  18: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,alloc::vec::IntoIter<T>>>::from_iter
  19: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  20: <alloc::sync::Arc<[T]> as core::iter::traits::collect::FromIterator<T>>::from_iter
  21: ra_hir_ty::lower::generic_predicates_query
  22: salsa::runtime::Runtime<DB>::execute_query_implementation
  23: core::ptr::real_drop_in_place
  24: salsa::derived::slot::Slot<DB,Q,MP>::read
  25: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  26: salsa::QueryTable<DB,Q>::get
  27: ra_hir_ty::infer::pat::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_pat
  28: ra_hir_ty::infer::pat::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_pat
  29: ra_hir_ty::infer::pat::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_pat
  30: ra_hir_ty::infer::pat::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_pat
  31: ra_hir_ty::infer::pat::<impl ra_hir_ty::infer::InferenceContext<D>>::infer_pat
  32: ra_hir_ty::infer::infer_query
  33: salsa::runtime::Runtime<DB>::execute_query_implementation
  34: core::ptr::real_drop_in_place
  35: salsa::derived::slot::Slot<DB,Q,MP>::read
  36: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  37: ra_hir::code_model::Struct::fields
  38: ra_hir::code_model::Module::diagnostics
  39: ra_ide::diagnostics::diagnostics
  40: std::panicking::try::do_call
  41: panic_unwind::__rust_maybe_catch_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libpanic_unwind\lib.rs:78
  42: ra_db::CheckCanceled::catch_canceled
  43: ra_ide::Analysis::diagnostics
  44: ra_lsp_server::main_loop::handlers::publish_diagnostics
  45: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by edwin0cheng** [comment]
Fixed, thanks
