### ISSUE TITLE
ra-lsp crashes after new Changelog #5

### ISSUE THREAD

**Issue by schungx** [rust-analyzer/rust-analyzer#2700]
Did a `git pull` and `cargo xtask install` on the latest commit `9cad88d`.  Using VS Code.

When starting, the server crashes with the following:

~~~
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: map, expected a string representing an URL", line: 0, column: 0)', src\libcore\result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:77
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:61
   3: core::fmt::write
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\fmt\mod.rs:1028
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\io\mod.rs:1412
   5: std::sys_common::backtrace::_print
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:65
   6: std::sys_common::backtrace::print
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:50
   7: std::panicking::default_hook::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:188
   8: std::panicking::default_hook
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:205
   9: std::panicking::rust_panic_with_hook
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:464
  10: std::panicking::continue_panic_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:373
  11: std::panicking::rust_begin_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:302
  12: core::panicking::panic_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\panicking.rs:139
  13: core::result::unwrap_failed
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\result.rs:1165
  14: lsp_server::msg::Request::extract
  15: ra_lsp_server::main_loop::PoolDispatcher::on
  16: ra_lsp_server::main_loop::on_task
  17: <ra_lsp_server::main_loop::Event as core::fmt::Debug>::fmt
  18: ra_lsp_server::main_loop::main_loop
  19: core::ptr::real_drop_in_place
  20: <T as core::any::Any>::type_id
  21: std::rt::lang_start_internal::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\rt.rs:48
  22: std::panicking::try::do_call<closure-0,i32>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:287
  23: panic_unwind::__rust_maybe_catch_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libpanic_unwind\lib.rs:78
  24: std::panicking::try
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:265
  25: std::panic::catch_unwind
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panic.rs:396
  26: std::rt::lang_start_internal
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\rt.rs:47
  27: main
  28: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  29: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  30: BaseThreadInitThunk
  31: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src\libcore\result.rs:1165:5
stack backtrace:
[Info  - 4:56:07 PM] Connection to server got closed. Server will restart.
[Error - 4:56:07 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:3927:25)
	at Object.dispose (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:8453:35)
	at LanguageClient.handleConnectionClosed (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:10688:42)
	at LanguageClient.handleConnectionClosed (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:13537:15)
	at closeHandler (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:10675:18)
	at CallbackList.invoke (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2041:39)
	at Emitter.fire (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2100:36)
	at closeHandler (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:3263:26)
	at CallbackList.invoke (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2041:39)
	at Emitter.fire (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2100:36)
	at StreamMessageReader.fireClose (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2225:27)
	at Socket.<anonymous> (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2265:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
[Error - 4:56:07 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:3927:25)
	at Object.dispose (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:8453:35)
	at LanguageClient.handleConnectionClosed (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:10688:42)
	at LanguageClient.handleConnectionClosed (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:13537:15)
	at closeHandler (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:10675:18)
	at CallbackList.invoke (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2041:39)
	at Emitter.fire (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2100:36)
	at closeHandler (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:3263:26)
	at CallbackList.invoke (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2041:39)
	at Emitter.fire (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2100:36)
	at StreamMessageReader.fireClose (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2225:27)
	at Socket.<anonymous> (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2265:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
[Error - 4:56:07 PM] Request textDocument/foldingRange failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:3927:25)
	at Object.dispose (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:8453:35)
	at LanguageClient.handleConnectionClosed (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:10688:42)
	at LanguageClient.handleConnectionClosed (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:13537:15)
	at closeHandler (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:10675:18)
	at CallbackList.invoke (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2041:39)
	at Emitter.fire (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2100:36)
	at closeHandler (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:3263:26)
	at CallbackList.invoke (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2041:39)
	at Emitter.fire (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2100:36)
	at StreamMessageReader.fireClose (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2225:27)
	at Socket.<anonymous> (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2265:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
[Error - 4:56:07 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:3927:25)
	at Object.dispose (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:8453:35)
	at LanguageClient.handleConnectionClosed (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:10688:42)
	at LanguageClient.handleConnectionClosed (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:13537:15)
	at closeHandler (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:10675:18)
	at CallbackList.invoke (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2041:39)
	at Emitter.fire (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2100:36)
	at closeHandler (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:3263:26)
	at CallbackList.invoke (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2041:39)
	at Emitter.fire (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2100:36)
	at StreamMessageReader.fireClose (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2225:27)
	at Socket.<anonymous> (c:\Users\schun\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2265:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
~~~

**Comment by schungx** [comment]
Reverting back to Changelog #4  commit `ce07a2daa9e53aa86a769f8641b14c2878444fbc` it now works.

So something within the new change set break VS Code.

**Comment by schungx** [comment]
I can confirm that the current commit works fine with VS Code under Windows.  Thanks!
