### ISSUE TITLE
Enter key doesn't work in *.rs and *.toml files

### ISSUE THREAD

**Issue by poland-can-into-space** [rust-analyzer/rust-analyzer#2770]
Enter key stops working (I can't break lines).
Enter key will start working again if I disable this.
So I think rust-analyzer is causing the problem.

VS code 
```
Version: 1.41
Node.js: 12.4.0
```
Error Message
```
[Error - 2:02:36] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\MyPC\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:3928:25)
	at Object.dispose (c:\Users\MyPC\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:8454:35)
	at LanguageClient.handleConnectionClosed (c:\Users\MyPC\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:10689:42)
	at LanguageClient.handleConnectionClosed (c:\Users\MyPC\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:13538:15)
	at closeHandler (c:\Users\MyPC\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:10676:18)
	at CallbackList.invoke (c:\Users\MyPC\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2042:39)
	at Emitter.fire (c:\Users\MyPC\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2101:36)
	at closeHandler (c:\Users\MyPC\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:3264:26)
	at CallbackList.invoke (c:\Users\MyPC\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2042:39)
	at Emitter.fire (c:\Users\MyPC\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2101:36)
	at StreamMessageReader.fireClose (c:\Users\MyPC\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2226:27)
	at Socket.<anonymous> (c:\Users\MyPC\.vscode\extensions\matklad.ra-lsp-0.0.1\out\main.js:2266:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
```

**Comment by pearzl** [comment]
I met this problem once, but I can't reproduce it any more.

**Comment by kiljacken** [comment]
Disabling `rust-analyzer.enableEnhancedTyping` should alleviate the problem. It's sometimes slow, especially on large projects, and we've still not honed in on exactly why.

**Comment by matklad** [comment]
>It's sometimes slow, especially on large projects, and we've still not honed in on exactly why.

This might be a recent regression? I think we haven't seen these bugs since we fixed the backtrace problem on windows quite a while ago

**Comment by kiljacken** [comment]
I've been having the problem sporadically on my work project, but I always assumed that it was due to it simply having a lot of deps (482 rust dependencies). I should probably try to get some profiling traces on it at some point

**Comment by matklad** [comment]
In theory, the architecture is such that handling typing events can't be
blocked by any background processing.

In practice, there might be some wholes to this approach! See
PoolDispatcher::on_sync method and diagnostics_do_not_block_typing method

**Comment by poland-can-into-space** [comment]
I solved the problem. Thanks a lot!

**Comment by lnicola** [comment]
@poland-can-into-space can you say how you fixed it, in case [someone from the future](https://xkcd.com/979/) stumbles upon this?
