### ISSUE TITLE
VSCode highlighting broken

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#2969]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 23,
		"activateCallTime": 104,
		"activateResolvedTime": 33,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "matklad.rust-analyzer",
				"_lower": "matklad.rust-analyzer"
			},
			"activationEvent": "workspaceContains:**/Cargo.toml"
		}
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "scopes is not iterable"
		}
	]
}
```

**Comment by bjorn3** [comment]
```
stack trace: TypeError: scopes is not iterable
	at Function.fromRules (~/.vscode/extensions/matklad.rust-analyzer-0.1.0/out/main.js:15051:33
	at loadThemeFile (~/.vscode/extensions/matklad.rust-analyzer-0.1.0/out/main.js:15108:28)
	at loadThemeNamed (~/.vscode/extensions/matklad.rust-analyzer-0.1.0/out/main.js:15091:23)
	at Function.load (~/.vscode/extensions/matklad.rust-analyzer-0.1.0/out/main.js:15043:16)
	at initDecorations (~/.vscode/extensions/matklad.rust-analyzer-0.1.0/out/main.js:15237:30)
	at Highlighter.setHighlights (~/.vscode/extensions/matklad.rust-analyzer-0.1.0/out/main.js:15194:32)
	at Array.<anonymous> (~/.vscode/extensions/matklad.rust-analyzer-0.1.0/out/main.js:15156:21)
```
