### ISSUE TITLE
Incremental reparse panics on invalid char bondary

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#314]
```
thread '<unnamed>' panicked at 'assertion failed: self.is_char_boundary(n)', liballoc/string.rs:1557:30
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::panicking::panic
             at libcore/panicking.rs:52
   9: alloc::string::String::replace_range
             at ./<::core::macros::panic macros>:3
  10: ra_syntax::reparsing::get_text_after_edit
             at crates/ra_syntax/src/text_utils.rs:16
             at crates/ra_syntax/src/reparsing.rs:65
  11: ra_syntax::reparsing::incremental_reparse
             at crates/ra_syntax/src/reparsing.rs:30
             at crates/ra_syntax/src/reparsing.rs:17
  12: ra_syntax::<impl ra_syntax::ast::generated::SourceFileNode>::incremental_reparse
             at crates/ra_syntax/src/lib.rs:76
  13: ra_syntax::<impl ra_syntax::ast::generated::SourceFileNode>::reparse
             at crates/ra_syntax/src/lib.rs:72
  14: ra_analysis::completion::completions
             at crates/ra_analysis/src/completion.rs:32
  15: ra_analysis::imp::AnalysisImpl::completions
             at crates/ra_analysis/src/imp.rs:226
  16: ra_analysis::Analysis::completions
             at crates/ra_analysis/src/lib.rs:355
  17: ra_lsp_server::main_loop::handlers::handle_completion
             at crates/ra_lsp_server/src/main_loop/handlers.rs:418
  18: <F as threadpool::FnBox>::call_box
             at crates/ra_lsp_server/src/main_loop.rs:380
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.7.1/src/lib.rs:95
INFO [ra_analysis::imp] apply_change AnalysisChange { files_changed: 1, crate_graph: None }
INFO [ra_analysis::imp] apply_change AnalysisChange { files_changed: 1, crate_graph: None }
thread '<unnamed>' panicked at 'assertion failed: self.is_char_boundary(n)', liballoc/string.rs:1557:30
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::panicking::panic
             at libcore/panicking.rs:52
   9: alloc::string::String::replace_range
             at ./<::core::macros::panic macros>:3
  10: ra_syntax::<impl ra_syntax::ast::generated::SourceFileNode>::reparse
             at crates/ra_syntax/src/text_utils.rs:16
             at crates/ra_syntax/src/lib.rs:81
             at crates/ra_syntax/src/lib.rs:73
             at libcore/option.rs:396
             at crates/ra_syntax/src/lib.rs:72
  11: ra_analysis::completion::completions
             at crates/ra_analysis/src/completion.rs:32
  12: ra_analysis::imp::AnalysisImpl::completions
             at crates/ra_analysis/src/imp.rs:226
  13: ra_analysis::Analysis::completions
             at crates/ra_analysis/src/lib.rs:355
  14: ra_lsp_server::main_loop::handlers::handle_completion
             at crates/ra_lsp_server/src/main_loop/handlers.rs:418
  15: <F as threadpool::FnBox>::call_box
             at crates/ra_lsp_server/src/main_loop.rs:380
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.7.1/src/lib.rs:95
```

**Comment by DJMcNab** [comment]
Do you know if you can still reproduce this? I've never had this happen, and don't know if it is still an issue.

**Comment by matklad** [comment]
I think it's fine to close: have not seen this again! Though, perhaps it makes sense to check if we have fuzz tests for incremental reparse?

**Comment by lnicola** [comment]
Let's close this.

> Though, perhaps it makes sense to check if we have fuzz tests for incremental reparse?

I assume that's `ra_syntax/fuzz/fuzz_targets/reparse.rs`.
