### ISSUE TITLE
Panic from unwrapping None

### ISSUE THREAD

**Issue by rakanalh** [rust-analyzer/rust-analyzer#3393]
I noticed the following panic from the rust-analyzer:stderr buffer in emacs & lsp-mode:

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `Some('\n')`,
 right: `Some('.')`', crates/ra_ide/src/typing.rs:97:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
   8: ra_ide::typing::on_char_typed
   9: std::panicking::try::do_call
  10: __rust_maybe_catch_panic
  11: ra_db::CheckCanceled::catch_canceled
  12: ra_ide::Analysis::on_char_typed
  13: rust_analyzer::main_loop::handlers::handle_on_type_formatting
  14: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: ra_assists::ast_transform::path_to_ast
  10: <ra_assists::ast_transform::QualifyPaths as ra_assists::ast_transform::AstTransform>::get_substitution
  11: ra_assists::ast_transform::apply::{{closure}}
  12: ra_syntax::algo::_replace_descendants::go
  13: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  14: ra_syntax::algo::_replace_descendants::go
  15: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  16: ra_syntax::algo::_replace_descendants::go
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  18: ra_syntax::algo::_replace_descendants::go
  19: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  20: ra_syntax::algo::_replace_descendants::go
  21: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  22: ra_syntax::algo::_replace_descendants::go
  23: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  24: ra_syntax::algo::_replace_descendants::go
  25: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  26: ra_syntax::algo::_replace_descendants::go
  27: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  28: ra_syntax::algo::_replace_descendants
  29: ra_assists::ast_transform::apply
  30: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  31: ra_syntax::ast::edit::<impl ra_syntax::ast::generated::ItemList>::append_items
  32: ra_assists::assist_ctx::AssistCtx::add_assist
  33: ra_assists::handlers::add_missing_impl_members::add_missing_impl_members_inner
  34: ra_assists::handlers::add_missing_impl_members::add_missing_default_members
  35: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  36: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  37: ra_assists::resolved_assists
  38: ra_ide::assists::assists
  39: std::panicking::try::do_call
  40: __rust_maybe_catch_panic
  41: ra_db::CheckCanceled::catch_canceled
  42: ra_ide::Analysis::assists
  43: rust_analyzer::main_loop::handlers::handle_code_action
  44: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: ra_assists::ast_transform::path_to_ast
  10: <ra_assists::ast_transform::QualifyPaths as ra_assists::ast_transform::AstTransform>::get_substitution
  11: ra_assists::ast_transform::apply::{{closure}}
  12: ra_syntax::algo::_replace_descendants::go
  13: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  14: ra_syntax::algo::_replace_descendants::go
  15: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  16: ra_syntax::algo::_replace_descendants::go
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  18: ra_syntax::algo::_replace_descendants::go
  19: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  20: ra_syntax::algo::_replace_descendants::go
  21: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  22: ra_syntax::algo::_replace_descendants::go
  23: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  24: ra_syntax::algo::_replace_descendants::go
  25: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  26: ra_syntax::algo::_replace_descendants::go
  27: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  28: ra_syntax::algo::_replace_descendants
  29: ra_assists::ast_transform::apply
  30: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  31: ra_syntax::ast::edit::<impl ra_syntax::ast::generated::ItemList>::append_items
  32: ra_assists::assist_ctx::AssistCtx::add_assist
  33: ra_assists::handlers::add_missing_impl_members::add_missing_impl_members_inner
  34: ra_assists::handlers::add_missing_impl_members::add_missing_default_members
  35: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  36: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  37: ra_assists::resolved_assists
  38: ra_ide::assists::assists
  39: std::panicking::try::do_call
  40: __rust_maybe_catch_panic
  41: ra_db::CheckCanceled::catch_canceled
  42: ra_ide::Analysis::assists
  43: rust_analyzer::main_loop::handlers::handle_code_action
  44: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: ra_assists::ast_transform::path_to_ast
  10: <ra_assists::ast_transform::QualifyPaths as ra_assists::ast_transform::AstTransform>::get_substitution
  11: ra_assists::ast_transform::apply::{{closure}}
  12: ra_syntax::algo::_replace_descendants::go
  13: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  14: ra_syntax::algo::_replace_descendants::go
  15: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  16: ra_syntax::algo::_replace_descendants::go
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  18: ra_syntax::algo::_replace_descendants::go
  19: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  20: ra_syntax::algo::_replace_descendants::go
  21: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  22: ra_syntax::algo::_replace_descendants::go
  23: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  24: ra_syntax::algo::_replace_descendants::go
  25: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  26: ra_syntax::algo::_replace_descendants::go
  27: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  28: ra_syntax::algo::_replace_descendants
  29: ra_assists::ast_transform::apply
  30: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  31: ra_syntax::ast::edit::<impl ra_syntax::ast::generated::ItemList>::append_items
  32: ra_assists::assist_ctx::AssistCtx::add_assist
  33: ra_assists::handlers::add_missing_impl_members::add_missing_impl_members_inner
  34: ra_assists::handlers::add_missing_impl_members::add_missing_default_members
  35: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  36: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  37: ra_assists::resolved_assists
  38: ra_ide::assists::assists
  39: std::panicking::try::do_call
  40: __rust_maybe_catch_panic
  41: ra_db::CheckCanceled::catch_canceled
  42: ra_ide::Analysis::assists
  43: rust_analyzer::main_loop::handlers::handle_code_action
  44: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: ra_assists::ast_transform::path_to_ast
  10: <ra_assists::ast_transform::QualifyPaths as ra_assists::ast_transform::AstTransform>::get_substitution
  11: ra_assists::ast_transform::apply::{{closure}}
  12: ra_syntax::algo::_replace_descendants::go
  13: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  14: ra_syntax::algo::_replace_descendants::go
  15: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  16: ra_syntax::algo::_replace_descendants::go
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  18: ra_syntax::algo::_replace_descendants::go
  19: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  20: ra_syntax::algo::_replace_descendants::go
  21: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  22: ra_syntax::algo::_replace_descendants::go
  23: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  24: ra_syntax::algo::_replace_descendants::go
  25: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  26: ra_syntax::algo::_replace_descendants::go
  27: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  28: ra_syntax::algo::_replace_descendants
  29: ra_assists::ast_transform::apply
  30: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  31: ra_syntax::ast::edit::<impl ra_syntax::ast::generated::ItemList>::append_items
  32: ra_assists::assist_ctx::AssistCtx::add_assist
  33: ra_assists::handlers::add_missing_impl_members::add_missing_impl_members_inner
  34: ra_assists::handlers::add_missing_impl_members::add_missing_default_members
  35: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  36: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  37: ra_assists::resolved_assists
  38: ra_ide::assists::assists
  39: std::panicking::try::do_call
  40: __rust_maybe_catch_panic
  41: ra_db::CheckCanceled::catch_canceled
  42: ra_ide::Analysis::assists
  43: rust_analyzer::main_loop::handlers::handle_code_action
  44: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: ra_assists::ast_transform::path_to_ast
  10: <ra_assists::ast_transform::QualifyPaths as ra_assists::ast_transform::AstTransform>::get_substitution
  11: ra_assists::ast_transform::apply::{{closure}}
  12: ra_syntax::algo::_replace_descendants::go
  13: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  14: ra_syntax::algo::_replace_descendants::go
  15: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  16: ra_syntax::algo::_replace_descendants::go
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  18: ra_syntax::algo::_replace_descendants::go
  19: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  20: ra_syntax::algo::_replace_descendants::go
  21: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  22: ra_syntax::algo::_replace_descendants::go
  23: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  24: ra_syntax::algo::_replace_descendants::go
  25: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  26: ra_syntax::algo::_replace_descendants::go
  27: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  28: ra_syntax::algo::_replace_descendants
  29: ra_assists::ast_transform::apply
  30: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  31: ra_syntax::ast::edit::<impl ra_syntax::ast::generated::ItemList>::append_items
  32: ra_assists::assist_ctx::AssistCtx::add_assist
  33: ra_assists::handlers::add_missing_impl_members::add_missing_impl_members_inner
  34: ra_assists::handlers::add_missing_impl_members::add_missing_default_members
  35: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  36: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  37: ra_assists::resolved_assists
  38: ra_ide::assists::assists
  39: std::panicking::try::do_call
  40: __rust_maybe_catch_panic
  41: ra_db::CheckCanceled::catch_canceled
  42: ra_ide::Analysis::assists
  43: rust_analyzer::main_loop::handlers::handle_code_action
  44: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: ra_assists::ast_transform::path_to_ast
  10: <ra_assists::ast_transform::QualifyPaths as ra_assists::ast_transform::AstTransform>::get_substitution
  11: ra_assists::ast_transform::apply::{{closure}}
  12: ra_syntax::algo::_replace_descendants::go
  13: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  14: ra_syntax::algo::_replace_descendants::go
  15: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  16: ra_syntax::algo::_replace_descendants::go
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  18: ra_syntax::algo::_replace_descendants::go
  19: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  20: ra_syntax::algo::_replace_descendants::go
  21: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  22: ra_syntax::algo::_replace_descendants::go
  23: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  24: ra_syntax::algo::_replace_descendants::go
  25: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  26: ra_syntax::algo::_replace_descendants::go
  27: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  28: ra_syntax::algo::_replace_descendants
  29: ra_assists::ast_transform::apply
  30: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  31: ra_syntax::ast::edit::<impl ra_syntax::ast::generated::ItemList>::append_items
  32: ra_assists::assist_ctx::AssistCtx::add_assist
  33: ra_assists::handlers::add_missing_impl_members::add_missing_impl_members_inner
  34: ra_assists::handlers::add_missing_impl_members::add_missing_default_members
  35: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  36: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  37: ra_assists::resolved_assists
  38: ra_ide::assists::assists
  39: std::panicking::try::do_call
  40: __rust_maybe_catch_panic
  41: ra_db::CheckCanceled::catch_canceled
  42: ra_ide::Analysis::assists
  43: rust_analyzer::main_loop::handlers::handle_code_action
  44: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

This is while working on the [substrate codebase](https://github.com/paritytech/substrate).

I would be happy to provide more information upon request.

**Comment by matklad** [comment]
I think there are two different panics here! 

The first assert relates to the onTypeFormatting feature. I've never seen a similar assert fire with VS Code, so my guess here would be that VSCode and lsp-mode interpret the protocol differently with respect to offsets and state of the editor. 

Specifically, in VS Code:

* on type formatting is called *after* the corresponding file change is communicated to the editor, but before any other change interjects. That way, the server can be sure that it can use offset from parameters to index the current contents of the text document.
* position points to just after the inserted text.

cc @brotzeit, I wonder if you can quickly confirm/reject the hypothesis that LSP mode does something different?

The following unwrap failures is definitely our fault

**Comment by brotzeit** [comment]
Unfortunately I didn't really touch the lsp-mode core. I will try to reproduce this. Maybe @yyoncho can help here.

**Comment by yyoncho** [comment]
I quickly tested with clagnd and I can confirm that we send onTypeFormatting after didChange:

```
[Trace - 04:20:03 PM] Sending notification 'textDocument/didChange'.
Params: {
  "textDocument": {
    "uri": "file:///home/kyoncho/Sources/CPP/testCPP/chars.cpp",
    "version": 281
  },
  "contentChanges": [
    {
      "range": {
        "start": {
          "line": 6,
          "character": 11
        },
        "end": {
          "line": 6,
          "character": 11
        }
      },
      "rangeLength": 0,
      "text": "}"
    }
  ]
}


[Trace - 04:20:03 PM] Sending request 'textDocument/onTypeFormatting - (1217)'.
Params: {
  "textDocument": {
    "uri": "file:///home/kyoncho/Sources/CPP/testCPP/chars.cpp"
  },
  "options": {
    "tabSize": 2,
    "insertSpaces": true
  },
  "ch": "}",
  "position": {
    "line": 6,
    "character": 12
  }
}
```

Maybe @rakanalh can provide the client-server logs(refer to lsp-mode troubleshooting guide on how to obtain them).

**Comment by rakanalh** [comment]
I was able to reproduce it to the following:
```
[ERROR rust_analyzer::main_loop] overly long loop turn: 152.578692ms
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `Some('\n')`,
 right: `Some('.')`', crates/ra_ide/src/typing.rs:97:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
   8: ra_ide::typing::on_char_typed
   9: std::panicking::try::do_call
  10: __rust_maybe_catch_panic
  11: ra_db::CheckCanceled::catch_canceled
  12: ra_ide::Analysis::on_char_typed
  13: rust_analyzer::main_loop::handlers::handle_on_type_formatting
  14: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[ERROR rust_analyzer::main_loop] overly long loop turn: 139.642353ms
```
The client-server communication logs:
[client-server.log](https://github.com/rust-analyzer/rust-analyzer/files/4277647/client-server.log)

**Comment by yyoncho** [comment]
@rakanalh we had a regression in lsp-mode related fullSync events fixed with https://github.com/emacs-lsp/lsp-mode/commit/279fd672de29a3ae80fbb52201b0c41e838938ca

**Comment by matklad** [comment]
Thanks for digging into this and a quick fix @yyoncho !

**Comment by rakanalh** [comment]
Yea i realized that i was running the old ra_lsp_server for the logs i just posted and deleted. Compiling the latest rust-analyzer to be able to provide latest logs.

**Comment by yyoncho** [comment]
> Thanks for digging into this and a quick fix @yyoncho !

@matklad you welcome, sorry for the noise!

**Comment by rakanalh** [comment]
I used rust-analyzer all day long compiled from: 1eeb7a79bb0d47566c82c70e424084fb0dfec1bc and could not reproduce the panic logs. Will reopen once/if i have more useful information.
