### ISSUE TITLE
Invalid type: boolean `true`, expected a string

### ISSUE THREAD

**Issue by rakanalh** [rust-analyzer/rust-analyzer#3449]
Noticed this panic in emacs, lsp-mode:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: boolean `true`, expected a string", line: 0, column: 0)', src/libcore/result.rs:1188:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: lsp_server::msg::Notification::extract
  10: rust_analyzer::main_loop::loop_turn
  11: rust_analyzer::main_loop::main_loop
  12: rust_analyzer::main
  13: std::rt::lang_start::{{closure}}
  14: std::panicking::try::do_call
  15: __rust_maybe_catch_panic
  16: std::rt::lang_start_internal
  17: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:1188:5
stack backtrace:
```

rust-analyzer compiled from: 1eeb7a79bb0d47566c82c70e424084fb0dfec1bc
LSP client-server log: [rust-analyzer-log.txt](https://github.com/rust-analyzer/rust-analyzer/files/4287694/rust-analyzer-log.txt)

**Comment by matklad** [comment]
closing as unactionable, it's unclear how to debug this.
