### ISSUE TITLE
Cannot install published extension: language server not available

### ISSUE THREAD

**Issue by xobs** [rust-analyzer/rust-analyzer#3563]
When trying to install `rust-analyzer` using the recommended method (i.e. going through the extension repository in vs code), I am prompted to install the language server.

However, in doing so I am presented with two errors:

```
Failed to download language server from rust-analyzer GitHub repository: Cannot destructure property `releaseName` of 'undefined' or 'null'.
```

and

```
Rust Analyzer Language Server is not available. Please, ensure its proper installation
```

The "Log (Extension Host)" has this output:

```
[2020-03-12 14:45:05.786] [exthost] [error] [rust-lang.rust] provider FAILED
[2020-03-12 14:45:05.786] [exthost] [error] TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (c:\Users\smcro\.vscode\extensions\rust-lang.rust-0.7.0\out\src\providers\signatureHelpProvider.js:75:41)
	at c:\Users\smcro\.vscode\extensions\rust-lang.rust-0.7.0\out\src\providers\signatureHelpProvider.js:15:105
[2020-03-12 14:45:49.136] [exthost] [error] [rust-lang.rust] provider FAILED
[2020-03-12 14:45:49.136] [exthost] [error] TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (c:\Users\smcro\.vscode\extensions\rust-lang.rust-0.7.0\out\src\providers\signatureHelpProvider.js:75:41)
	at c:\Users\smcro\.vscode\extensions\rust-lang.rust-0.7.0\out\src\providers\signatureHelpProvider.js:15:105
[2020-03-12 14:46:02.785] [exthost] [error] [rust-lang.rust] provider FAILED
[2020-03-12 14:46:02.785] [exthost] [error] TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (c:\Users\smcro\.vscode\extensions\rust-lang.rust-0.7.0\out\src\providers\signatureHelpProvider.js:75:41)
	at c:\Users\smcro\.vscode\extensions\rust-lang.rust-0.7.0\out\src\providers\signatureHelpProvider.js:15:105
[2020-03-12 14:46:06.019] [exthost] [error] [rust-lang.rust] provider FAILED
[2020-03-12 14:46:06.019] [exthost] [error] TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (c:\Users\smcro\.vscode\extensions\rust-lang.rust-0.7.0\out\src\providers\signatureHelpProvider.js:75:41)
	at c:\Users\smcro\.vscode\extensions\rust-lang.rust-0.7.0\out\src\providers\signatureHelpProvider.js:15:105
[2020-03-12 14:52:13.351] [exthost] [info] ExtensionService#_doActivateExtension matklad.rust-analyzer {"startup":false,"extensionId":{"value":"matklad.rust-analyzer","_lower":"matklad.rust-analyzer"},"activationEvent":"onLanguage:rust"}
[2020-03-12 14:52:13.353] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/smcro/.vscode/extensions/matklad.rust-analyzer-0.1.20200211/out/main
```

To the best of my knowledge I'm running the latest version of vscode:

```
[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

[OK] [Copy]
```

I have been using rls on this machine up until now.

This is the latest version, downloaded just today from vscode:

![image](https://user-images.githubusercontent.com/238325/76495717-644c6900-6472-11ea-93bd-d6d39d1502e7.png)

**Comment by lnicola** [comment]
> Version: 1.41.1 (system setup)

Can you try updating Code? The Marketplace detects you're running an older version and serves you an older version of the extension.

**Comment by xobs** [comment]
That fixes it.  Strange how it didn't update itself.  Thanks for the support.

**Comment by Veetaha** [comment]
Hmm, so this is how people end up downloading `2020-02-11` version of the extension. Thanks for the info lnicola!
