### ISSUE TITLE
VS Code Extension Is Broken

### ISSUE THREAD

**Issue by HymanZHAN** [rust-analyzer/rust-analyzer#3600]
Thank you for making the rust analyzer! I've enjoyed it a lot but yesterday as I was trying to use it on my main work machine, it did not work and some error messages popped up.

- Rust Version: 1.42
- VS Code Version: 1.43
- Extension Version: 0.1.20200309

- Tasks Output
```
Error: [matklad.rust-analyzer]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api matklad.rust-analyzer
	at a (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:515:620)
	at Object.t.checkProposedApiEnabled (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:515:982)
	at Object.registerDocumentSemanticTokensProvider (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:796:600)
	at SemanticTokensFeature.registerLanguageProvider (/home/xzhan/.vscode/extensions/matklad.rust-analyzer-0.1.20200309/out/main.js:12036:43)
	at SemanticTokensFeature.register (/home/xzhan/.vscode/extensions/matklad.rust-analyzer-0.1.20200309/out/main.js:9269:33)
	at SemanticTokensFeature.initialize (/home/xzhan/.vscode/extensions/matklad.rust-analyzer-0.1.20200309/out/main.js:11960:14)
	at LanguageClient.initializeFeatures (/home/xzhan/.vscode/extensions/matklad.rust-analyzer-0.1.20200309/out/main.js:11022:21)
	at /home/xzhan/.vscode/extensions/matklad.rust-analyzer-0.1.20200309/out/main.js:10707:18
[Error - 1:43:01 PM] Starting client failed
Error: [matklad.rust-analyzer]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api matklad.rust-analyzer
	at a (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:515:620)
	at Object.t.checkProposedApiEnabled (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:515:982)
	at Object.registerDocumentSemanticTokensProvider (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:796:600)
	at SemanticTokensFeature.registerLanguageProvider (/home/xzhan/.vscode/extensions/matklad.rust-analyzer-0.1.20200309/out/main.js:12036:43)
	at SemanticTokensFeature.register (/home/xzhan/.vscode/extensions/matklad.rust-analyzer-0.1.20200309/out/main.js:9269:33)
	at SemanticTokensFeature.initialize (/home/xzhan/.vscode/extensions/matklad.rust-analyzer-0.1.20200309/out/main.js:11960:14)
	at LanguageClient.initializeFeatures (/home/xzhan/.vscode/extensions/matklad.rust-analyzer-0.1.20200309/out/main.js:11022:21)
	at /home/xzhan/.vscode/extensions/matklad.rust-analyzer-0.1.20200309/out/main.js:10707:1
```

- Rust Analyzer Language Server

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:1188:5
stack backtrace:
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:1188:5
Error: ProtocolError("unexpected message during shutdown: Ok(Response(Response { id: RequestId(U64(1)), result: None, error: None }))")
   0: 
```

**Comment by lnicola** [comment]
Did you enable rust-analyzer.highlighting.semanticTokens? It needs to be disabled for the extension to work with the stable Code version.

**Comment by eaglgenes101** [comment]
For me, the same error happens, even when I run the insiders version, and even when I specifically pass `--enable-proposed-api matklad.rust-analyzer` to the vscode-insiders invocation as suggested by the error message.

**Comment by HymanZHAN** [comment]
Thank you @lnicola ! That seems to be the problem. It's working now.

**Comment by lnicola** [comment]
@eaglgenes101 you might need to enable editor.semanticHighlighting.enabled.

**Comment by eaglgenes101** [comment]
@lnicola Already enabled as well.
