### ISSUE TITLE
crashes running on chalk: no value set for FileTextQuery(FileId(2276))

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-analyzer/rust-analyzer#3888]
```
git clone https://github.com/rust-lang/chalk
cd chalk
git checkout 73a74be3bc1d0cdef3f76fa529a112a0d8367ddb
rust-analyzer analysis-stats .
```
crashes:
````
Database loaded, 144 roots, 1.014336344s
thread 'main' panicked at 'no value set for FileTextQuery(FileId(2276))', /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1439
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:373
  13: <salsa::input::InputStorage<DB,Q> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch::{{closure}}
  14: core::option::Option<T>::unwrap_or_else
  15: <salsa::input::InputStorage<DB,Q> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  16: salsa::QueryTable<DB,Q>::try_get
  17: salsa::QueryTable<DB,Q>::get
  18: <T as ra_db::SourceDatabaseExt>::file_text
  19: <ra_db::FileLoaderDelegate<&T> as ra_db::FileLoader>::file_text
  20: <ra_ide_db::RootDatabase as ra_db::FileLoader>::file_text
  21: ra_db::parse_query
  22: <ra_db::ParseQuery as salsa::plumbing::QueryFunction<DB>>::execute
  23: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
  24: salsa::runtime::Runtime<DB>::execute_query_implementation
  25: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  26: salsa::derived::slot::Slot<DB,Q,MP>::read
  27: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  28: salsa::QueryTable<DB,Q>::try_get
  29: salsa::QueryTable<DB,Q>::get
  30: <T as ra_db::SourceDatabase>::parse
  31: ra_hir_expand::db::parse_or_expand
  32: <T as ra_hir_expand::db::AstDatabase>::parse_or_expand
  33: ra_hir_expand::db::ast_id_map
  34: <ra_hir_expand::db::AstIdMapQuery as salsa::plumbing::QueryFunction<DB>>::execute
  35: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
  36: salsa::runtime::Runtime<DB>::execute_query_implementation
  37: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  38: salsa::derived::slot::Slot<DB,Q,MP>::read
  39: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  40: salsa::QueryTable<DB,Q>::try_get
  41: salsa::QueryTable<DB,Q>::get
  42: <T as ra_hir_expand::db::AstDatabase>::ast_id_map
  43: ra_hir_def::nameres::raw::RawItems::raw_items_query
  44: <ra_hir_def::db::RawItemsQuery as salsa::plumbing::QueryFunction<DB>>::execute
  45: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
  46: salsa::runtime::Runtime<DB>::execute_query_implementation
  47: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  48: salsa::derived::slot::Slot<DB,Q,MP>::read
  49: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  50: salsa::QueryTable<DB,Q>::try_get
  51: salsa::QueryTable<DB,Q>::get
  52: <T as ra_hir_def::db::DefDatabase>::raw_items
  53: ra_hir_def::nameres::collector::DefCollector::collect
  54: ra_hir_def::nameres::collector::collect_defs
  55: ra_hir_def::nameres::CrateDefMap::crate_def_map_query
  56: <ra_hir_def::db::CrateDefMapQueryQuery as salsa::plumbing::QueryFunction<DB>>::execute
  57: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
  58: salsa::runtime::Runtime<DB>::execute_query_implementation
  59: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  60: salsa::derived::slot::Slot<DB,Q,MP>::read
  61: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  62: salsa::QueryTable<DB,Q>::try_get
  63: salsa::QueryTable<DB,Q>::get
  64: <T as ra_hir_def::db::DefDatabase>::crate_def_map_query
  65: ra_hir_def::db::crate_def_map_wait
  66: <T as ra_hir_def::db::DefDatabase>::crate_def_map
  67: ra_hir::code_model::Crate::root_module
  68: rust_analyzer::cli::analysis_stats::analysis_stats
  69: rust_analyzer::main
  70: std::rt::lang_start::{{closure}}
  71: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  72: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  73: std::panicking::try
             at src/libstd/panicking.rs:274
  74: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  75: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  76: std::rt::lang_start
  77: main
  78: __libc_start_main
  79: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
````
RA @ d89c189ad1efe87e54855e6488184d7a3825a534

**Comment by matthiaskrgr** [comment]
Perhaps related to https://github.com/rust-analyzer/rust-analyzer/issues/2272 ?

**Comment by matthiaskrgr** [comment]
Similar crash when running on backtrace-rs git repo
```
Database loaded, 50 roots, 2.335650937s
thread 'main' panicked at 'no value set for FileTextQuery(FileId(1567))', /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1439
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:373
  13: <salsa::input::InputStorage<DB,Q> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch::{{closure}}
  14: <salsa::input::InputStorage<DB,Q> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  15: <ra_ide_db::RootDatabase as ra_db::FileLoader>::file_text
  16: <ra_db::ParseQuery as salsa::plumbing::QueryFunction<DB>>::execute
  17: salsa::runtime::Runtime<DB>::execute_query_implementation
  18: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  19: salsa::derived::slot::Slot<DB,Q,MP>::read
  20: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  21: <T as ra_db::SourceDatabase>::parse
  22: ra_hir_expand::db::parse_or_expand
  23: <T as ra_hir_expand::db::AstDatabase>::parse_or_expand
  24: ra_hir_expand::db::ast_id_map
  25: salsa::runtime::Runtime<DB>::execute_query_implementation
  26: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  27: salsa::derived::slot::Slot<DB,Q,MP>::read
  28: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  29: <T as ra_hir_expand::db::AstDatabase>::ast_id_map
  30: ra_hir_def::nameres::raw::RawItems::raw_items_query
  31: salsa::runtime::Runtime<DB>::execute_query_implementation
  32: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  33: salsa::derived::slot::Slot<DB,Q,MP>::read
  34: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  35: <T as ra_hir_def::db::DefDatabase>::raw_items
  36: ra_hir_def::nameres::collector::collect_defs
  37: ra_hir_def::nameres::CrateDefMap::crate_def_map_query
  38: salsa::runtime::Runtime<DB>::execute_query_implementation
  39: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  40: salsa::derived::slot::Slot<DB,Q,MP>::read
  41: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  42: ra_hir_def::db::crate_def_map_wait
  43: ra_hir::code_model::Crate::root_module
  44: rust_analyzer::cli::analysis_stats::analysis_stats
  45: rust_analyzer::main
  46: std::rt::lang_start::{{closure}}
  47: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  48: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  49: std::panicking::try
             at src/libstd/panicking.rs:274
  50: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  51: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  52: main
  53: __libc_start_main
  54: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by flodiebold** [comment]
I think this is fixed, right?

**Comment by matthiaskrgr** [comment]
Looks like it :) , thanks!
