### ISSUE TITLE
`Unexpected token import` during vscode extension install

### ISSUE THREAD

**Issue by 0x7CFE** [rust-analyzer/rust-analyzer#3982]
Revision is b495e56b0d3f7a72494d002a69440563e8394574

```
korvin@pi:~/work/rust-analyzer$ cargo xtask install
    Finished dev [unoptimized] target(s) in 0.07s
     Running `target/debug/xtask install`
> cargo --version
cargo 1.44.0-nightly (390e8f245 2020-04-07)
> cargo install --path crates/rust-analyzer --locked --force 
  Installing rust-analyzer v0.1.0 (/home/korvin/work/rust-analyzer/crates/rust-analyzer)
    Updating crates.io index
   Compiling rust-analyzer v0.1.0 (/home/korvin/work/rust-analyzer/crates/rust-analyzer)
   Compiling ra_hir v0.1.0 (/home/korvin/work/rust-analyzer/crates/ra_hir)
   Compiling ra_ide_db v0.1.0 (/home/korvin/work/rust-analyzer/crates/ra_ide_db)
   Compiling ra_assists v0.1.0 (/home/korvin/work/rust-analyzer/crates/ra_assists)
   Compiling ra_ide v0.1.0 (/home/korvin/work/rust-analyzer/crates/ra_ide)
    Finished release [optimized] target(s) in 2m 31s
   Replacing /home/korvin/.cargo/bin/rust-analyzer
    Replaced package `rust-analyzer v0.1.0 (/home/korvin/work/rust-analyzer/crates/rust-analyzer)` with `rust-analyzer v0.1.0 (/home/korvin/work/rust-analyzer/crates/rust-analyzer)` (executable `rust-analyzer`)
> npm --version
6.13.4
> npm install
npm WARN @rollup/plugin-commonjs@11.0.2 requires a peer of rollup@^1.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN @rollup/plugin-node-resolve@7.1.1 requires a peer of rollup@^1.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN @rollup/pluginutils@3.0.8 requires a peer of rollup@^1.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 424 packages in 1.716s

13 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> npm run package --scripts-prepend-node-path
 ERROR  Command failed: npm run vscode:prepublish
/home/korvin/work/rust-analyzer/editors/code/node_modules/rollup/dist/bin/rollup:1580
        ? (await import(url.pathToFileURL(fileName).href)).default
                 ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rust-analyzer@0.4.0-dev vscode:prepublish: `tsc && rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rust-analyzer@0.4.0-dev vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/korvin/.npm/_logs/2020-04-15T05_58_31_756Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rust-analyzer@0.4.0-dev package: `vsce package -o rust-analyzer.vsix`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rust-analyzer@0.4.0-dev package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/korvin/.npm/_logs/2020-04-15T05_58_31_786Z-debug.log

> rust-analyzer@0.4.0-dev package /home/korvin/work/rust-analyzer/editors/code
> vsce package -o rust-analyzer.vsix

Executing prepublish script 'npm run vscode:prepublish'...
Error: install client

Caused by:
    0: process `npm run package --scripts-prepend-node-path` failed
    1: exit code: 1
```

**Comment by matklad** [comment]
Hm, seems to work locally with 

```
λ node --version
v10.19.0
```

I'd hazard a guess that you need to update node.

**Comment by 0x7CFE** [comment]
> I'd hazard a guess that you need to update node.

Good catch! Indeed, it was a different installation with an outdated node. Sorry for the noise.
