### ISSUE TITLE
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/ra_mbe/src/subtree_source.rs:155:16

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#4001]
I tried to play around with the proc macro support and I noticed that a lot of stuff is now broken, e.g. "go to definition" in `dylib.rs`.

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/ra_mbe/src/subtree_source.rs:155:16
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::panicking::panic
             at src/libcore/panicking.rs:54
  14: ra_mbe::subtree_source::SubtreeTokenSource::get
  15: <ra_mbe::subtree_source::SubtreeTokenSource as ra_parser::TokenSource>::lookahead_nth
  16: ra_parser::grammar::items::traits::impl_def
  17: ra_parser::grammar::items::maybe_item
  18: ra_parser::grammar::expressions::stmt
  19: ra_parser::grammar::expressions::naked_block
  20: ra_parser::grammar::expressions::atom::block_expr
  21: ra_parser::grammar::expressions::atom::atom_expr
  22: ra_parser::grammar::expressions::lhs
  23: ra_parser::grammar::expressions::expr_bp
  24: ra_parser::grammar::items::consts::const_or_static
  25: ra_parser::grammar::items::maybe_item
  26: ra_parser::grammar::items::item_or_macro
  27: ra_parser::grammar::items::mod_contents
  28: ra_parser::grammar::fragments::macro_items
  29: ra_parser::parse_fragment
  30: ra_mbe::syntax_bridge::token_tree_to_syntax_node
  31: ra_hir_expand::db::parse_macro_with_arg
  32: ra_hir_expand::db::parse_macro
  33: salsa::runtime::Runtime<DB>::execute_query_implementation
  34: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  35: salsa::derived::slot::Slot<DB,Q,MP>::read
  36: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  37: <T as ra_hir_expand::db::AstDatabase>::parse_macro
  38: ra_hir_expand::db::parse_or_expand
  39: <T as ra_hir_expand::db::AstDatabase>::parse_or_expand
  40: ra_hir_expand::db::ast_id_map
  41: salsa::runtime::Runtime<DB>::execute_query_implementation
  42: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  43: salsa::derived::slot::Slot<DB,Q,MP>::read
  44: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  45: <T as ra_hir_expand::db::AstDatabase>::ast_id_map
  46: ra_hir_def::nameres::raw::RawItems::raw_items_query
  47: salsa::runtime::Runtime<DB>::execute_query_implementation
  48: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  49: salsa::derived::slot::Slot<DB,Q,MP>::read
  50: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  51: <T as ra_hir_def::db::DefDatabase>::raw_items
  52: ra_hir_def::nameres::collector::collect_defs
  53: ra_hir_def::nameres::CrateDefMap::crate_def_map_query
  54: salsa::runtime::Runtime<DB>::execute_query_implementation
  55: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  56: salsa::derived::slot::Slot<DB,Q,MP>::read
  57: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  58: ra_hir_def::db::crate_def_map_wait
  59: ra_hir_def::nameres::collector::collect_defs
  60: ra_hir_def::nameres::CrateDefMap::crate_def_map_query
  61: salsa::runtime::Runtime<DB>::execute_query_implementation
  62: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
  63: salsa::derived::slot::Slot<DB,Q,MP>::read
  64: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
  65: ra_hir_def::db::crate_def_map_wait
  66: ra_hir::semantics::source_to_def::SourceToDefCtx::file_to_def
  67: ra_ide::diagnostics::diagnostics
  68: std::panicking::try
  69: ra_ide::Analysis::diagnostics
  70: rust_analyzer::main_loop::handlers::handle_code_action
  71: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by edwin0cheng** [comment]
I will take a look. Which`identifier` in `dylib.rs` is causing the panic ?

**Comment by lnicola** [comment]
`Object` and `is_derive_registrar_symbol`, at least, if I'm not missing anything.

**Comment by edwin0cheng** [comment]
I am investigating this bug, it is quite interesting : the root cause of this bug is because the rustc token stream expect LIFETIME as a combination of punct and ident, but RA `tt:TokenTree` treat it as a single Ident.
