### ISSUE TITLE
panic in import quick action feature

### ISSUE THREAD

**Issue by leo-lb** [rust-analyzer/rust-analyzer#4122]
Hello!

I'm getting these every now and then, I think they happen when I add a new library to my Cargo.toml

I run rust-analyzer https://github.com/rust-analyzer/rust-analyzer/commit/4f0cb81a2e4364994d23474d7738125d1cb56573 with the VS Code extension built from the same tree.

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/ra_syntax/src/ast/make.rs:303:16
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::panicking::panic
             at src/libcore/panicking.rs:54
  14: ra_syntax::ast::make::ast_from_text
  15: ra_syntax::ast::make::path_unqualified
  16: ra_syntax::ast::edit::<impl ra_syntax::ast::generated::nodes::UseTree>::split_prefix::split_path_prefix
  17: ra_syntax::ast::edit::<impl ra_syntax::ast::generated::nodes::UseTree>::split_prefix
  18: ra_assists::handlers::split_import::split_import
  19: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  20: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  21: ra_assists::resolved_assists
  22: ra_ide::assists::assists
  23: std::panicking::try
  24: ra_ide::Analysis::assists
  25: rust_analyzer::main_loop::handlers::handle_code_action
  26: <F as threadpool::FnBox>::call_box
```

Keep up the amazing work!

**Comment by leo-lb** [comment]
I've applied this patch to my tree:

```diff
diff --git a/crates/ra_syntax/src/ast/make.rs b/crates/ra_syntax/src/ast/make.rs
index 0f4a50be4..03a664fbe 100644
--- a/crates/ra_syntax/src/ast/make.rs
+++ b/crates/ra_syntax/src/ast/make.rs
@@ -300,7 +300,14 @@ pub fn add_newlines(amount_of_newlines: usize, t: impl AstNode) -> ast::SourceFi
 
 fn ast_from_text<N: AstNode>(text: &str) -> N {
     let parse = SourceFile::parse(text);
-    let node = parse.tree().syntax().descendants().find_map(N::cast).unwrap();
+    let node = match parse.tree().syntax().descendants().find_map(N::cast) {
+        Some(node) => node,
+        x @ None => {
+            eprintln!("{}", text);
+            x.unwrap();
+            unreachable!();
+        }
+    };
     let node = node.syntax().clone();
     let node = unroot(node);
     let node = N::cast(node).unwrap();
```

We'll see how this goes!

**Comment by leo-lb** [comment]
@lnicola I have not been using rust-analyzer lately, so I really do not know.

**Comment by lnicola** [comment]
Let's close for now, then. I haven't seen any `split_prefix` panics in the last few months, and the code has changed significantly.
