### ISSUE TITLE
Possible race in cargo check

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#4266]
Take the following code save it, then delete from the cursor to the beginning of the file:

```rust
enum Enum {
    A,
    B,
}

struct Foo {
    f: Option<Enum>,
}

fn f(foo: &Foo) {
    match foo.f {
        None => (),
        Some(En) => (),
    }
}

<|>fn main() {}
```

You might get a panic like

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 2 but the index is 12', crates/ra_ide_db/src/line_index.rs:88:9
  14: ra_ide_db::line_index::LineIndex::offset
  15: rust_analyzer::main_loop::handlers::handle_code_action
```

What happens is that we delete the text:

```
[crates/rust-analyzer/src/main_loop.rs:705] &old_text = "fn main() {}\n"
[crates/rust-analyzer/src/main_loop.rs:706] LineIndex::new(&old_text) = LineIndex {
    newlines: [
        0,
        13,
    ],
    utf16_lines: {},
}
```

then call into the diagnostics for the start of the file:

```
[crates/rust-analyzer/src/main_loop/handlers.rs:728] &line_index = LineIndex {
    newlines: [
        0,
        13,
    ],
    utf16_lines: {},
}
[crates/rust-analyzer/src/main_loop/handlers.rs:729] &params.range = Range {
    start: Position {
        line: 0,
        character: 0,
    },
    end: Position {
        line: 0,
        character: 0,
    },
}
```

But the original code has an unused variable warning and we get it as a quick fix:

```
[crates/rust-analyzer/src/main_loop/handlers.rs:762] &fix = Fix {
    range: Range {
        start: Position {
            line: 12,
            character: 13,
        },
        end: Position {
            line: 12,
            character: 15,
        },
    },
    action: CodeAction(
        CodeAction {
            title: "if this is intentional, prefix it with an underscore",
            kind: Some(
                "quickfix",
            ),
```

The range here is incorrect, since line 12 no longer exists.

CC @kiljacken, @matklad.

**Comment by matklad** [comment]
Interesting! So this is a race between cargo-check diagnostics and our state. Given that we don’t guarantee that check sees the same files as we do in general, this is not something we can protect from reliably. 

I feel like we should just ignore check diagnostics which don’t map clearly to the current contents of the file.

For our own diagnostics, I believe we do guarantee strong consistencly.

**Comment by lnicola** [comment]
> I feel like we should just ignore check diagnostics which don’t map clearly to the current contents of the file.

Sounds like a good idea. I wonder if we could use the document version to ignore stale diagnostics. But we have per-file versions, so it might be harder.

**Comment by matklad** [comment]
I think we removed panics here, and we can't really guanratee consistence until we reimplement the whole of cargo check

**Comment by lnicola** [comment]
Actually, it crashes just like before:

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 2 but the index is 12', crates/ra_ide_db/src/line_index.rs:102:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:62
  14: ra_ide_db::line_index::LineIndex::offset
  15: rust_analyzer::handlers::handle_code_action
  16: <F as threadpool::FnBox>::call_box
```

**Comment by kjeremy** [comment]
I can reproduce this.

**Comment by Veykril** [comment]
Can't reproduce this anymore
