### ISSUE TITLE
"called `Option::unwrap()` on a `None` value" in src/ast/make.rs:303:16

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#4368]
I'm debugging the hang/crash I saw while hacking on rustc's MIR transforms with rust-analyzer enabled, and this backtrace shows up quite a few times in the output (I don't think it's what causes the hang/crash though):

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/ra_syntax/src/ast/make.rs:303:16
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic
             at src/libcore/panicking.rs:52
  14: ra_syntax::ast::make::path_from_text
  15: ra_syntax::ast::make::path_unqualified
  16: ra_syntax::ast::edit::<impl ra_syntax::ast::generated::nodes::UseTree>::split_prefix::split_path_prefix
  17: ra_syntax::ast::edit::<impl ra_syntax::ast::generated::nodes::UseTree>::split_prefix
  18: ra_assists::handlers::merge_imports::try_merge_trees
  19: <core::iter::adapters::Copied<I> as core::iter::traits::iterator::Iterator>::try_fold
  20: ra_assists::handlers::merge_imports::merge_imports
  21: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  22: ra_assists::resolved_assists
  23: std::panicking::try::do_call
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  25: ra_ide::Analysis::assists
  26: rust_analyzer::main_loop::handlers::handle_code_action
  27: <F as threadpool::FnBox>::call_box
```

I did not try to use the merge imports assist here.

**Comment by jonas-schievink** [comment]
Updated message after #4396 is:

> thread '<unnamed>' panicked at 'Failed to make ast node `ra_syntax::ast::generated::nodes::Path` from text use ', crates/ra_syntax/src/ast/make.rs:308:13

**Comment by lnicola** [comment]
Repro:

```rust
<|>
fn main() {}
```

and type `use std::`.
