### ISSUE TITLE
Index out of bounds in `_match::is_useful`

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#4416]
Happened when working on the rustc codebase.

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/slice/mod.rs:2842:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:63
  14: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  15: ra_hir_ty::_match::is_useful
  16: ra_hir_ty::_match::is_useful
  17: ra_hir_ty::_match::is_useful
  18: ra_hir_ty::_match::is_useful
  19: ra_hir_ty::expr::ExprValidator::validate_body
  20: ra_hir::code_model::Function::diagnostics
  21: ra_hir::code_model::Module::diagnostics
  22: ra_ide::diagnostics::diagnostics
  23: std::panicking::try::do_call
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  25: ra_ide::Analysis::diagnostics
  26: rust_analyzer::main_loop::handlers::publish_diagnostics
  27: <F as threadpool::FnBox>::call_box
```

**Comment by flodiebold** [comment]
Hmm I assume it's [this](https://github.com/rust-analyzer/rust-analyzer/blob/93eae6549eb5bb7cdb4f292a0798e5425e7f20e9/crates/ra_hir_ty/src/_match.rs#L632) call, but I have no idea how to construct an example where this would fail. Running `rust-analyzer diagnostics` on the rustc codebase might reproduce it and help pinpoint the function, I haven't tried yet.

**Comment by jonas-schievink** [comment]
Indeed it does! Fresh debug backtrace:

```
  13: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:63
  14: <usize as core::slice::SliceIndex<[T]>>::index
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/slice/mod.rs:2842
  15: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/slice/mod.rs:2707
  16: <smallvec::SmallVec<A> as core::ops::index::Index<I>>::index
             at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.4.0/lib.rs:1459
  17: ra_hir_ty::_match::PatStack::head
             at crates/ra_hir_ty/src/_match.rs:291
  18: ra_hir_ty::_match::Matrix::heads::{{closure}}
             at crates/ra_hir_ty/src/_match.rs:505
  19: core::iter::adapters::map_fold::{{closure}}
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/iter/adapters/mod.rs:772
  20: core::iter::traits::iterator::Iterator::fold::ok::{{closure}}
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/iter/traits/iterator.rs:2001
  21: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/iter/traits/iterator.rs:1877
  22: core::iter::traits::iterator::Iterator::fold
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/iter/traits/iterator.rs:2004
  23: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/iter/adapters/mod.rs:812
  24: core::iter::traits::iterator::Iterator::for_each
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/iter/traits/iterator.rs:658
  25: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/liballoc/vec.rs:2061
  26: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/liballoc/vec.rs:2041
  27: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/liballoc/vec.rs:1926
  28: core::iter::traits::iterator::Iterator::collect
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/iter/traits/iterator.rs:1659
  29: ra_hir_ty::_match::Matrix::heads
             at crates/ra_hir_ty/src/_match.rs:505
  30: ra_hir_ty::_match::is_useful
             at crates/ra_hir_ty/src/_match.rs:632
  31: ra_hir_ty::_match::is_useful
             at crates/ra_hir_ty/src/_match.rs:661
  32: ra_hir_ty::_match::is_useful
             at crates/ra_hir_ty/src/_match.rs:661
  33: ra_hir_ty::expr::ExprValidator::validate_match
             at crates/ra_hir_ty/src/expr.rs:197
  34: ra_hir_ty::expr::ExprValidator::validate_body
             at crates/ra_hir_ty/src/expr.rs:60
  35: ra_hir::code_model::Function::diagnostics
             at crates/ra_hir/src/code_model.rs:645
```

**Comment by jonas-schievink** [comment]
Reduced to:

```rust
pub enum Category {
    Infinity,
    NaN,
    Normal,
    Zero,
}

fn panic(a: Category, b: Category) {
    match (a, b) {
        (Category::NaN, _) => {}

        (_, Category::NaN) => {}

        (Category::Zero, Category::Infinity) | (Category::Infinity, Category::Zero) => {}

        (Category::Zero | Category::Infinity, _) => {}

        (_, Category::Zero | Category::Infinity) => {}

        (Category::Normal, Category::Normal) => {}
    }
}
```

**Comment by jonas-schievink** [comment]
Still reproduces with

```rust
pub enum Category {
    Infinity,
    Zero,
}

fn panic(a: Category, b: Category) {
    match (a, b) {
        (Category::Infinity, Category::Infinity) | (Category::Zero, Category::Zero) => {}

        (Category::Infinity | Category::Zero, _) => {}
    }
}
```
