### ISSUE TITLE
Rust analyzer language server crashed 

### ISSUE THREAD

**Issue by awh6al** [rust-analyzer/rust-analyzer#4435]
Reproduce the error: 
1 - git pull // fetch latest commit which is 93eae6549eb5bb7cdb4f292a0798e5425e7f20e9
2 - cargo xtask install
3 - code .  
-> Rust analyzer language server crashed 5 time
```
[2020-05-12 13:16:52.314] [renderer1] [error] Connection got disposed.: Error: Connection got disposed.
	at Object.dispose (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:3989:25)
	at Object.dispose (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:8810:35)
	at LanguageClient.handleConnectionClosed (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:11056:42)
	at LanguageClient.handleConnectionClosed (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:12433:15)
	at closeHandler (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:11043:18)
	at CallbackList.invoke (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2037:39)
	at Emitter.fire (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2100:36)
	at closeHandler (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:3310:26)
	at CallbackList.invoke (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2037:39)
	at Emitter.fire (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2100:36)
	at StreamMessageReader.fireClose (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2225:27)
	at Socket.<anonymous> (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2265:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[2020-05-12 13:16:53.950] [renderer1] [error] Connection got disposed.: Error: Connection got disposed.
	at Object.dispose (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:3989:25)
	at Object.dispose (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:8810:35)
	at LanguageClient.handleConnectionClosed (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:11056:42)
	at LanguageClient.handleConnectionClosed (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:12433:15)
	at closeHandler (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:11043:18)
	at CallbackList.invoke (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2037:39)
	at Emitter.fire (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2100:36)
	at closeHandler (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:3310:26)
	at CallbackList.invoke (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2037:39)
	at Emitter.fire (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2100:36)
	at StreamMessageWriter.fireClose (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2383:27)
	at Socket.<anonymous> (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2402:46)
	at Socket.emit (events.js:203:13)
	at Pipe.<anonymous> (net.js:588:12)
[2020-05-12 13:16:54.722] [renderer1] [error] Connection got disposed.: Error: Connection got disposed.
	at Object.dispose (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:3989:25)
	at Object.dispose (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:8810:35)
	at LanguageClient.handleConnectionClosed (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:11056:42)
	at LanguageClient.handleConnectionClosed (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:12433:15)
	at closeHandler (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:11043:18)
	at CallbackList.invoke (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2037:39)
	at Emitter.fire (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2100:36)
	at closeHandler (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:3310:26)
	at CallbackList.invoke (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2037:39)
	at Emitter.fire (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2100:36)
	at StreamMessageReader.fireClose (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2225:27)
	at Socket.<anonymous> (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2265:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[2020-05-12 13:16:55.781] [renderer1] [error] Connection got disposed.: Error: Connection got disposed.
	at Object.dispose (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:3989:25)
	at Object.dispose (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:8810:35)
	at LanguageClient.handleConnectionClosed (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:11056:42)
	at LanguageClient.handleConnectionClosed (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:12433:15)
	at closeHandler (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:11043:18)
	at CallbackList.invoke (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2037:39)
	at Emitter.fire (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2100:36)
	at closeHandler (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:3310:26)
	at CallbackList.invoke (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2037:39)
	at Emitter.fire (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2100:36)
	at StreamMessageReader.fireClose (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2225:27)
	at Socket.<anonymous> (/home/awh6al/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/main.js:2265:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)

```
OS: Manjaro 20.0 Lysia
Kernel: x86_64 Linux 5.4.38-1-MANJARO
WM: i3
CPU: Intel Core i5-2540M @ 4x 3.3GHz [56.0°C]

Rustc 1.45.0-nightly (7ced01a73 2020-04-30)
Cargo 1.45.0-nightly (90931d9b3 2020-04-28)

**Comment by awh6al** [comment]
Trying to go back to the older commits produce unfortunately the same error?

**Comment by awh6al** [comment]
fixed, maybe with latest commit?
