### ISSUE TITLE
VSCode extension fails to start on MacOs

### ISSUE THREAD

**Issue by bgrieder** [rust-analyzer/rust-analyzer#4546]
When loading the extension a pop-up proposes to download the latest version of the rust_analyzer server, but the download fails.

**Extension logs**
```
[2020-05-21 08:48:39.624] [exthost] [error] Activating extension matklad.rust-analyzer failed due to an error:
[2020-05-21 08:48:39.626] [exthost] [error] Error: Got response 403 when trying to fetch release info for 2020-05-18 release
	at Object.fetchRelease (/Users/bgrieder/.vscode/extensions/matklad.rust-analyzer-0.2.174/out/main.js:16538:15)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async getServer (/Users/bgrieder/.vscode/extensions/matklad.rust-analyzer-0.2.174/out/main.js:16899:21)
	at async bootstrapServer (/Users/bgrieder/.vscode/extensions/matklad.rust-analyzer-0.2.174/out/main.js:16847:18)
	at async bootstrap (/Users/bgrieder/.vscode/extensions/matklad.rust-analyzer-0.2.174/out/main.js:16805:18)
	at async activate (/Users/bgrieder/.vscode/extensions/matklad.rust-analyzer-0.2.174/out/main.js:16744:24)
```

**Comment by bgrieder** [comment]
Switched to a branch with

**Comment by bgrieder** [comment]
Switched to a branch with a different Cargo.toml file, the download tirggered automatically and succeeded. Maybe a temporary issue

**Comment by lnicola** [comment]
See https://github.com/rust-analyzer/rust-analyzer/issues/3094.

**Comment by bgrieder** [comment]
@lnicola thanks. But if it is an API limit, why did it suddenly work a few minutes later ?
The only possibility I see is that the Github counter is reset art midnight US West Coast which may be the time after which I re-attempted a download

**Comment by lnicola** [comment]
> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.

You can check on https://api.github.com/rate_limit. After a couple of API calls, my reset time is one hour after the first call, but they might use a fancier scheme than that.

**Comment by bgrieder** [comment]
Great Thanks. This helped find what I think is the culprit: an extension called Crates, that check if you have the latests crates installed in your project, and issue one request to Github per crate everytime you open the Cargo.toml file. This was likely what blew the limit

**Comment by lnicola** [comment]
Yeah, I use it too. I wonder if it could support authentication.

Also: https://github.com/serayuzgur/crates/pull/77
