### ISSUE TITLE
Immediate crash with various errors: `Failed to make ast node`, `LspError`, and numerous `Error: Connection got disposed`

### ISSUE THREAD

**Issue by joshhansen** [rust-analyzer/rust-analyzer#4645]
Using 0.2.18 in VSCode on Linux, I get no rust-analyzer annotations, but get this log output:

```
thread '<unnamed>' panicked at 'Failed to make ast node `ra_syntax::ast::generated::nodes::Path` from text use ', crates/ra_syntax/src/ast/make.rs:308:13
stack backtrace:
   0: <unknown>
   1: core::fmt::write
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
   8: <unknown>
   9: ra_syntax::ast::make::path_unqualified
  10: <unknown>
  11: ra_syntax::ast::edit::<impl ra_syntax::ast::generated::nodes::UseTree>::split_prefix
  12: <unknown>
  13: ra_assists::Assist::resolved
  14: <unknown>
  15: __rust_maybe_catch_panic
  16: ra_ide::Analysis::assists
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: __rust_maybe_catch_panic
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: start_thread
  25: __clone
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error: LspError { code: -32900, message: "Rust file outside current workspace is not supported yet." }
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lsp-server-0.3.2/src/stdio.rs:29:13
stack backtrace:
[Info  - 12:53:11 AM] Connection to server got closed. Server will restart.
[Error - 12:53:11 AM] Request textDocument/semanticTokens/range failed.
Error: Connection got disposed.
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3999:25)
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:8820:35)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11066:42)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:12443:15)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11053:18)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3320:26)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at StreamMessageReader.fireClose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2235:27)
	at Socket.<anonymous> (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2275:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 12:53:11 AM] Request textDocument/semanticTokens failed.
Error: Connection got disposed.
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3999:25)
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:8820:35)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11066:42)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:12443:15)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11053:18)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3320:26)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at StreamMessageReader.fireClose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2235:27)
	at Socket.<anonymous> (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2275:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 12:53:11 AM] Request textDocument/foldingRange failed.
Error: Connection got disposed.
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3999:25)
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:8820:35)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11066:42)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:12443:15)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11053:18)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3320:26)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at StreamMessageReader.fireClose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2235:27)
	at Socket.<anonymous> (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2275:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 12:53:11 AM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3999:25)
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:8820:35)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11066:42)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:12443:15)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11053:18)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3320:26)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at StreamMessageReader.fireClose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2235:27)
	at Socket.<anonymous> (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2275:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 12:53:11 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3999:25)
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:8820:35)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11066:42)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:12443:15)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11053:18)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3320:26)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at StreamMessageReader.fireClose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2235:27)
	at Socket.<anonymous> (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2275:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 12:53:11 AM] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3999:25)
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:8820:35)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11066:42)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:12443:15)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11053:18)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3320:26)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at StreamMessageReader.fireClose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2235:27)
	at Socket.<anonymous> (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2275:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 12:53:11 AM] Request textDocument/semanticTokens/range failed.
Error: Connection got disposed.
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3999:25)
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:8820:35)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11066:42)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:12443:15)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11053:18)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3320:26)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at StreamMessageReader.fireClose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2235:27)
	at Socket.<anonymous> (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2275:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 12:53:11 AM] Request textDocument/foldingRange failed.
Error: Connection got disposed.
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3999:25)
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:8820:35)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11066:42)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:12443:15)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11053:18)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3320:26)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at StreamMessageReader.fireClose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2235:27)
	at Socket.<anonymous> (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2275:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 12:53:11 AM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3999:25)
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:8820:35)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11066:42)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:12443:15)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11053:18)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3320:26)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at StreamMessageReader.fireClose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2235:27)
	at Socket.<anonymous> (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2275:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 12:53:11 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3999:25)
	at Object.dispose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:8820:35)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11066:42)
	at LanguageClient.handleConnectionClosed (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:12443:15)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:11053:18)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at closeHandler (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3320:26)
	at CallbackList.invoke (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2047:39)
	at Emitter.fire (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2110:36)
	at StreamMessageReader.fireClose (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2235:27)
	at Socket.<anonymous> (/home/josh/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:2275:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[ERROR rust_analyzer::main_loop] overly long loop turn: 156.150587ms
[ERROR rust_analyzer::main_loop] overly long loop turn: 125.734265ms
```

**Comment by bjorn3** [comment]
What project did this error occur on?

**Comment by joshhansen** [comment]
These projects were loaded:

* [joshhansen/Umpire](/joshhansen/Umpire)
* [tspooner/rsrl/rsrl](/tspooner/rsrl/tree/master/rsrl)
* [tspooner/rsrl/rsrl_domains](/tspooner/rsrl/tree/master/rsrl_domains)
* [tspooner/lfa](/tspooner/lfa)
* [LaurentMazare/tch-rs](/LaurentMazare/tch-rs)

However, I have been unable to reproduce the error. I opened a new window and loaded those projects one by one, and they seemed to get analyzed correctly. After doing that, my original workspace also began functioning correctly.

This is very strange as I had previously uninstalled rust-analyzer completely and even after reinstalling it I was getting this crash.

Anyway, I guess I'll close for now unless I can get this to reproduce.
