### ISSUE TITLE
Gracefully handle "Rust file outside current workspace is not supported yet"

### ISSUE THREAD

**Issue by repi** [rust-analyzer/rust-analyzer#4859]
In VS Code as soon as one opens and saves a file that is not in the Cargo workspace Rust Analyzer panics with "Rust file outside current workspace is not supported yet". 

This is somewhat annoying and distracting as VS Code switches to show the output view for Rust Analyzer and this type of log output, on every save / change:

```
	at closeHandler (/Users/johan/.vscode/extensions/matklad.rust-analyzer-0.2.199/out/src/main.js:3320:26)
	at CallbackList.invoke (/Users/johan/.vscode/extensions/matklad.rust-analyzer-0.2.199/out/src/main.js:2047:39)
	at Emitter.fire (/Users/johan/.vscode/extensions/matklad.rust-analyzer-0.2.199/out/src/main.js:2110:36)
	at StreamMessageReader.fireClose (/Users/johan/.vscode/extensions/matklad.rust-analyzer-0.2.199/out/src/main.js:2235:27)
	at Socket.<anonymous> (/Users/johan/.vscode/extensions/matklad.rust-analyzer-0.2.199/out/src/main.js:2275:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', crates/rust-analyzer/src/main_loop.rs:406:13
stack backtrace:
Error: LspError { code: -32900, message: "Rust file outside current workspace is not supported yet." }
[Info  - 1:03:16 PM] Connection to server got closed. Server will restart.
```

Would be nicer if it for this missing feature just silently logged that out instead of switching context and prompting the user. I've started to edit loose Rust files outside of VS Code just not to keep getting this.

**Comment by matklad** [comment]
Fixed couple of weeks ago.

Also, :heart: for Embark Studios :)

**Comment by repi** [comment]
Thanks!
