### ISSUE TITLE
Registering progress handler for token rustAnalyzer/startup failed.

### ISSUE THREAD

**Issue by lehtoj** [rust-analyzer/rust-analyzer#4871]
I've tried to use the rust-analyzer extension in VSCode for a while now, but I get following error. I am on Manjaro Linux and the OSS version of VSCode.

[Error - 8:16:53 AM] Registering progress handler for token rustAnalyzer/startup failed.
Error: Progress handler for token rustAnalyzer/startup already registered
	at Object.onProgress (/home/user/.vscode-oss/extensions/rust-lang.rust-0.7.8/node_modules/vscode-jsonrpc/lib/main.js:769:23)
	at LanguageClient.onProgress (/home/user/.vscode-oss/extensions/rust-lang.rust-0.7.8/node_modules/vscode-languageclient/lib/client.js:1842:45)
	at new ProgressPart (/home/user/.vscode-oss/extensions/rust-lang.rust-0.7.8/node_modules/vscode-languageclient/lib/progressPart.js:15:41)
	at createHandler (/home/user/.vscode-oss/extensions/rust-lang.rust-0.7.8/node_modules/vscode-languageclient/lib/progress.js:25:13)
	at handleRequest (/home/user/.vscode-oss/extensions/rust-lang.rust-0.7.8/node_modules/vscode-jsonrpc/lib/main.js:380:27)
	at processMessageQueue (/home/user/.vscode-oss/extensions/rust-lang.rust-0.7.8/node_modules/vscode-jsonrpc/lib/main.js:270:17)
	at Immediate._onImmediate (/home/user/.vscode-oss/extensions/rust-lang.rust-0.7.8/node_modules/vscode-jsonrpc/lib/main.js:260:13)
	at processImmediate (internal/timers.js:439:21)

**Comment by paulirotta** [comment]
I'm seeing the same on Windows after switching vscode from `rust-analyzer` to `Rust `

**Comment by Count-Count** [comment]
Same here.

**Comment by paulirotta** [comment]
@Count-Count Not sure how I eventually blasted past this. Perhaps `rustup default stable` then remove all related plugins, then start again?

**Comment by lnicola** [comment]
@paulirotta are you saying this happens with the Rust extension, but not with Rust Analyzer?

**Comment by paulirotta** [comment]
@lnicola I'm saying my environment got screwed up somehow while trying to transition to the Rust extension, around the same time I was forced to start using Rust nightly. I eventually got back to a working system by cleaning local files (I think the inital rust-analyzer plugin uninstall with nightly was where something did not complete correctly/recover gracefully), using stable Rust and re-installing rust-analyzer not Rust extension. Then I stopped.

**Comment by Count-Count** [comment]
This happens with Rust Extension + Rust Analyzer in VSCode on Windows:
`[Error - 16:58:56] Registering progress handler for token rustAnalyzer/startup failed.
Error: Progress handler for token rustAnalyzer/startup already registered
	at Object.onProgress (c:\Users\hans\.vscode\extensions\rust-lang.rust-0.7.8\node_modules\vscode-jsonrpc\lib\main.js:769:23)
	at LanguageClient.onProgress (c:\Users\hans\.vscode\extensions\rust-lang.rust-0.7.8\node_modules\vscode-languageclient\lib\client.js:1842:45)
	at new ProgressPart (c:\Users\hans\.vscode\extensions\rust-lang.rust-0.7.8\node_modules\vscode-languageclient\lib\progressPart.js:15:41)
	at createHandler (c:\Users\hans\.vscode\extensions\rust-lang.rust-0.7.8\node_modules\vscode-languageclient\lib\progress.js:25:13)
	at handleRequest (c:\Users\hans\.vscode\extensions\rust-lang.rust-0.7.8\node_modules\vscode-jsonrpc\lib\main.js:380:27)
	at processMessageQueue (c:\Users\hans\.vscode\extensions\rust-lang.rust-0.7.8\node_modules\vscode-jsonrpc\lib\main.js:270:17)
	at Immediate._onImmediate (c:\Users\hans\.vscode\extensions\rust-lang.rust-0.7.8\node_modules\vscode-jsonrpc\lib\main.js:260:13)
	at processImmediate (internal/timers.js:439:21)
[ERROR rust_analyzer::main_loop] overly long loop turn: 158.6329ms
`

**Comment by lnicola** [comment]
Are you using both Code extensions, or the Rust extension with the experimental `rust-analyzer` support?

**Comment by Count-Count** [comment]
I had both extension installed and enabled, "Rust-Client: Engine" in the settings is set to "rust-analyzer".

I just uninstalled the rust-analyzer extension, restarted, and the error message is still appears shortly after startup in the "Rust analyzer" Output window.

**Comment by ririsoft** [comment]
I encountered the bug on Windows with rust-analyser installed and activated and Rust extension installed and disabled.
I deinstalled the Rust extension, reloaded the window and things are back to normal since.

**Comment by lnicola** [comment]
This is a `vscode-rust` issue, closing. We now warn against using both extensions at once.
