### ISSUE TITLE
Assertion failed crates\ra_hir_ty\src\lib.rs:552:9

### ISSUE THREAD

**Issue by Speedy37** [rust-analyzer/rust-analyzer#4884]
rust-analyser keeps panicking (both on master and release version)

Here is the backtrace:

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', crates\ra_hir_ty\src\lib.rs:552:9
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at fake_path\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at fake_path\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:78
   3: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:59
   4: core::fmt::write
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libcore\fmt\mod.rs:1069
   5: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\io\mod.rs:1504
   6: std::sys_common::backtrace::_print
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:62
   7: std::sys_common::backtrace::print
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:198
   9: std::panicking::default_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:511
  11: std::panicking::begin_panic_handler
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:419
  12: std::panicking::begin_panic_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:373
  13: ra_hir_ty::Binders::subst
             at fake_path\rust-analyzer\crates\ra_hir_ty\src\lib.rs:552
  14: ra_hir_ty::infer::InferenceContext::resolve_value_path
             at fake_path\rust-analyzer\crates\ra_hir_ty\src\infer\path.rs:85
  15: ra_hir_ty::infer::InferenceContext::infer_path
             at fake_path\rust-analyzer\crates\ra_hir_ty\src\infer\path.rs:23
  16: ra_hir_ty::infer::InferenceContext::infer_expr_inner
             at fake_path\rust-analyzer\crates\ra_hir_ty\src\infer\expr.rs:249
  17: ra_hir_ty::infer::InferenceContext::infer_expr
             at fake_path\rust-analyzer\crates\ra_hir_ty\src\infer\expr.rs:31
  18: ra_hir_ty::infer::InferenceContext::infer_block
             at fake_path\rust-analyzer\crates\ra_hir_ty\src\infer\expr.rs:634
  19: ra_hir_ty::infer::InferenceContext::infer_expr_inner
             at fake_path\rust-analyzer\crates\ra_hir_ty\src\infer\expr.rs:91
  20: ra_hir_ty::infer::InferenceContext::infer_expr_coerce
             at fake_path\rust-analyzer\crates\ra_hir_ty\src\infer\expr.rs:49
  21: ra_hir_ty::infer::InferenceContext::infer_body
             at fake_path\rust-analyzer\crates\ra_hir_ty\src\infer.rs:548
  22: ra_hir_ty::infer::infer_query
             at fake_path\rust-analyzer\crates\ra_hir_ty\src\infer.rs:77
  23: salsa::runtime::Runtime::execute_query_implementation<ra_ide_db::RootDatabase,alloc::sync::Arc<ra_hir_ty::infer::InferenceResult>,closure-1>
             at fake_path\.cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.14.1\src\runtime.rs:352
  24: salsa::derived::slot::Slot::read_upgrade<ra_ide_db::RootDatabase,ra_hir_ty::db::InferQueryQuery,salsa::derived::AlwaysMemoizeValue>
             at fake_path\.cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.14.1\src\derived\slot.rs:217
  25: salsa::derived::slot::Slot::read<ra_ide_db::RootDatabase,ra_hir_ty::db::InferQueryQuery,salsa::derived::AlwaysMemoizeValue>
             at fake_path\.cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.14.1\src\derived\slot.rs:149
  26: salsa::derived::{{impl}}::try_fetch<ra_ide_db::RootDatabase,ra_hir_ty::db::InferQueryQuery,salsa::derived::AlwaysMemoizeValue>
             at fake_path\.cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.14.1\src\derived.rs:140
  27: salsa::QueryTable::try_get
             at fake_path\.cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.14.1\src\lib.rs:483
  28: salsa::QueryTable::get
             at fake_path\.cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.14.1\src\lib.rs:479
  29: ra_hir_ty::db::{{impl}}::infer_query
             at fake_path\rust-analyzer\crates\ra_hir_ty\src\db.rs:21
  30: ra_hir_ty::db::infer_wait<ra_ide_db::RootDatabase>
             at fake_path\rust-analyzer\crates\ra_hir_ty\src\db.rs:142
  31: ra_hir::source_analyzer::SourceAnalyzer::new_for_body
             at fake_path\rust-analyzer\crates\ra_hir\src\source_analyzer.rs:66
  32: ra_hir::semantics::Semantics::analyze2<ra_ide_db::RootDatabase>
             at fake_path\rust-analyzer\crates\ra_hir\src\semantics.rs:321
  33: ra_hir::semantics::Semantics::analyze
             at fake_path\rust-analyzer\crates\ra_hir\src\semantics.rs:308
  34: ra_hir::semantics::Semantics::resolve_path
             at fake_path\rust-analyzer\crates\ra_hir\src\semantics.rs:247
  35: ra_ide_db::defs::classify_name_ref
             at fake_path\rust-analyzer\crates\ra_ide_db\src\defs.rs:264
  36: ra_ide::syntax_highlighting::highlight_element
             at fake_path\rust-analyzer\crates\ra_ide\src\syntax_highlighting.rs:450
  37: ra_ide::syntax_highlighting::highlight
             at fake_path\rust-analyzer\crates\ra_ide\src\syntax_highlighting.rs:202
  38: ra_ide::prime_caches::prime_caches
             at fake_path\rust-analyzer\crates\ra_ide\src\prime_caches.rs:10
  39: ra_ide::{{impl}}::prime_caches::{{closure}}
             at fake_path\rust-analyzer\crates\ra_ide\src\lib.rs:245
  40: ra_db::CheckCanceled::catch_canceled::{{closure}}
             at fake_path\rust-analyzer\crates\ra_db\src\lib.rs:61
  41: std::panicking::try::do_call
             at fake_path\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:331
  42: std::panicking::try
             at fake_path\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:274
  43: std::panic::catch_unwind
             at fake_path\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
  44: ra_db::CheckCanceled::catch_canceled
             at fake_path\rust-analyzer\crates\ra_db\src\lib.rs:61
  45: ra_ide::Analysis::with_db
             at fake_path\rust-analyzer\crates\ra_ide\src\lib.rs:515
  46: ra_ide::Analysis::prime_caches
             at fake_path\rust-analyzer\crates\ra_ide\src\lib.rs:245
  47: rust_analyzer::main_loop::loop_turn::{{closure}}
             at fake_path\rust-analyzer\crates\rust-analyzer\src\main_loop.rs:439
  48: threadpool::{{impl}}::call_box<closure-1>
             at fake_path\.cargo\registry\src\github.com-1ecc6299db9ec823\threadpool-1.8.1\src\lib.rs:95
  49: threadpool::spawn_in_pool::{{closure}}
             at fake_path\.cargo\registry\src\github.com-1ecc6299db9ec823\threadpool-1.8.1\src\lib.rs:769
```

How can I figure out the code that is causing this?
I can catch the panic with the debugger.

**Comment by Speedy37** [comment]
I'm unable to catch the panic with `analysis-stats` as I can't workaround all occurrences of #4885

**Comment by Speedy37** [comment]
This is a duplicate of #4953
