### ISSUE TITLE
Panic in `ra_hir_ty::Binders<ra_hir_ty::Ty>::subst`

### ISSUE THREAD

**Issue by Speedy37** [rust-analyzer/rust-analyzer#4953]
This code panic:

Edit: smaller reproducer:

```rust
pub struct Foo<T>(pub T);
impl Foo<i64> {
    fn test() { Self(0i64) }
}
```

Original reproducer:
```rust
pub struct Foo<T>(pub T);

impl From<usize> for Foo<i64> {
    fn from(_u: usize) -> Self {
        Self(0)
    }
}
```

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', crates\ra_hir_ty\src\lib.rs:553:9
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:78
   3: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:59
   4: core::fmt::write
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\fmt\mod.rs:1069
   5: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\io\mod.rs:1504
   6: std::sys_common::backtrace::_print
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:62
   7: std::sys_common::backtrace::print
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:198
   9: std::panicking::default_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:511
  11: std::panicking::begin_panic_handler
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:419
  12: std::panicking::begin_panic_fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:373
  13: ra_hir_ty::Binders<ra_hir_ty::Ty>::subst
             at .\crates\ra_hir_ty\src\lib.rs:553
  14: ra_hir_ty::infer::InferenceContext::resolve_value_path
             at .\crates\ra_hir_ty\src\infer\path.rs:85
  15: ra_hir_ty::infer::InferenceContext::infer_path
             at .\crates\ra_hir_ty\src\infer\path.rs:23
  16: ra_hir_ty::infer::InferenceContext::infer_expr_inner
             at .\crates\ra_hir_ty\src\infer\expr.rs:249
  17: ra_hir_ty::infer::InferenceContext::infer_expr
             at .\crates\ra_hir_ty\src\infer\expr.rs:31
  18: ra_hir_ty::infer::InferenceContext::infer_expr_inner
             at .\crates\ra_hir_ty\src\infer\expr.rs:200
  19: ra_hir_ty::infer::InferenceContext::infer_expr_coerce
             at .\crates\ra_hir_ty\src\infer\expr.rs:49
  20: ra_hir_ty::infer::InferenceContext::infer_block
             at .\crates\ra_hir_ty\src\infer\expr.rs:640
  21: ra_hir_ty::infer::InferenceContext::infer_expr_inner
             at .\crates\ra_hir_ty\src\infer\expr.rs:91
  22: ra_hir_ty::infer::InferenceContext::infer_expr_coerce
             at .\crates\ra_hir_ty\src\infer\expr.rs:49
  23: ra_hir_ty::infer::InferenceContext::infer_body
             at .\crates\ra_hir_ty\src\infer.rs:548
  24: ra_hir_ty::infer::infer_query
             at .\crates\ra_hir_ty\src\infer.rs:77
  25: salsa::runtime::Runtime<ra_ide_db::RootDatabase>::execute_query_implementation<ra_ide_db::RootDatabase,alloc::sync::Arc<ra_hir_ty::infer::InferenceResult>,closure-1>
```

**Comment by Speedy37** [comment]
```
pub struct Foo<T>(pub T);
impl Foo<i64> {
    fn test() { Foo(0i64) }
}
```

doesn't fail

**Comment by Speedy37** [comment]
And it's does panic on master (90a5c4626a4c46f7d5973e79dc68ab734d3b9349).
