### ISSUE TITLE
Registering progress handler for token rustAnalyzer/cargo check failed

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#5060]
I'm on 9be0094b5c and vscode told me an error occurred:

> [Error - 9:05:57 AM] Registering progress handler for token rustAnalyzer/cargo check failed.
Error: Progress handler for token rustAnalyzer/cargo check already registered
	at Object.onProgress (c:\Users\jkolb\.vscode\extensions\matklad.rust-analyzer-0.4.0-dev\out\src\main.js:3851:23)
	at LanguageClient.onProgress (c:\Users\jkolb\.vscode\extensions\matklad.rust-analyzer-0.4.0-dev\out\src\main.js:10599:45)
	at new ProgressPart (c:\Users\jkolb\.vscode\extensions\matklad.rust-analyzer-0.4.0-dev\out\src\main.js:8681:41)
	at createHandler (c:\Users\jkolb\.vscode\extensions\matklad.rust-analyzer-0.4.0-dev\out\src\main.js:11904:13)
	at handleRequest (c:\Users\jkolb\.vscode\extensions\matklad.rust-analyzer-0.4.0-dev\out\src\main.js:3462:27)
	at processMessageQueue (c:\Users\jkolb\.vscode\extensions\matklad.rust-analyzer-0.4.0-dev\out\src\main.js:3350:17)
	at Immediate._onImmediate (c:\Users\jkolb\.vscode\extensions\matklad.rust-analyzer-0.4.0-dev\out\src\main.js:3340:13)
	at processImmediate (internal/timers.js:439:21)

**Comment by kjeremy** [comment]
@Veetaha ?

**Comment by Veetaha** [comment]
Yup, this is the instance of not freeing the handles, see my comment: https://github.com/rust-analyzer/rust-analyzer/pull/5046#discussion_r445460987

**Comment by Veetaha** [comment]
We should probably store the state of the progress somewhere

**Comment by matklad** [comment]
Closed by #5075.

Noticed an interesting pattern -- "meaningless" progress notification and meaningful state transition use the same messages. 

Still don't do rust-analyzer-side tracking of valid progress reporting, but it's probably fine to punt on this if the client errors.
