### ISSUE TITLE
rust-analyzer is not usable on project that uses specs crate

### ISSUE THREAD

**Issue by ondrowan** [rust-analyzer/rust-analyzer#5170]
The project I'm working on contains `specs` crate. If I edit any of the specs' systems (eg. if I edit `SystemData` type) and make any kind of mistake (eg. forget to use `&mut` instead of `&`), `rust-analyzer` doesn't let me to even save the file. It's stuck on "Formatting" in VSCode forever and uses 100% of CPU. Even if I exit VSCode, `rust-analyzer-mac` process doesn't stop and I have to kill it manually.

I was able to replicate this in `basic.rs` example in `specs` repo. Edit line `type SystemData = (WriteStorage<'a, Pos>, ReadStorage<'a, Vel>);` in `SysA` to contain `ReadStorage<'a, Vel>` one more time and rust-analyzer immediatelly does what I described above.

I'm using:

* rust-analyzer 0.2.224
* specs 0.16.1
* VSCode
* MacOS 10.15.5

**Comment by bjorn3** [comment]
Does `cargo fmt` work?

**Comment by ondrowan** [comment]
Yes, it does.

**Comment by jonas-schievink** [comment]
Can you check the output pane for panics?

**Comment by ondrowan** [comment]
If you mean Output -> Rust Analyzer Language Server Trace, then it's completely empty. I tried to let it hang for a couple of minutes and there was no change. CPU was at 100% and stuck on "Running 'rust-analyzer' Formatter" until it eventually formatted and saved the file.

**Comment by matklad** [comment]
A minimal reproducible example (preferably as a git repo with cargo.lock) would help us to debug this faster :)

**Comment by ondrowan** [comment]
@matklad I have mentioned in the original post how I was able to reproduce it. The example is located in [specs repo](https://github.com/amethyst/specs/blob/master/examples/basic.rs).

**Comment by matklad** [comment]
Ah, sorry, I've missed the link, thanks for pointing this out!

**Comment by roqvist** [comment]
Same problem on Windows, with rust-analyzer version 0.2.297. In projects using amethyst crate (that has dependencies on specs).

The extension resumes normal operations after restarting VScode.

Found this log, not sure if it helps/is relevant:

```
[2020-09-04 21:20:31.119] [renderer1] [error] content modified: Error: content modified
	at handleResponse (matklad.rust-analyzer-0.2.297\out\src\main.js:3413:48)
	at processMessageQueue (matklad.rust-analyzer-0.2.297\out\src\main.js:3238:17)
	at Immediate.<anonymous> (matklad.rust-analyzer-0.2.297\out\src\main.js:3222:13)
	at processImmediate (internal/timers.js:439:21)
[2020-09-04 21:40:42.085] [renderer1] [error] content modified: Error: content modified
	at handleResponse (matklad.rust-analyzer-0.2.297\out\src\main.js:3413:48)
	at processMessageQueue (matklad.rust-analyzer-0.2.297\out\src\main.js:3238:17)
	at Immediate.<anonymous> (matklad.rust-analyzer-0.2.297\out\src\main.js:3222:13)
	at processImmediate (internal/timers.js:439:21)
[2020-09-04 21:42:16.701] [renderer1] [error] read ECONNRESET: Error: read ECONNRESET
	at TLSWrap.onStreamRead (internal/stream_base_commons.js:183:27)
[2020-09-04 21:49:08.414] [renderer1] [error] content modified: Error: content modified
	at handleResponse (matklad.rust-analyzer-0.2.297\out\src\main.js:3413:48)
	at processMessageQueue (matklad.rust-analyzer-0.2.297\out\src\main.js:3238:17)
	at Immediate.<anonymous> (matklad.rust-analyzer-0.2.297\out\src\main.js:3222:13)
	at processImmediate (internal/timers.js:439:21) 
```

**Comment by lnicola** [comment]
@ondrowan can you test this again? I can't reproduce:

![image](https://user-images.githubusercontent.com/308347/103008545-f9ba7480-453d-11eb-8172-028b4d73a3bb.png)

![image](https://user-images.githubusercontent.com/308347/103008621-19ea3380-453e-11eb-80bc-343c5458d8b2.png)

**Comment by ondrowan** [comment]
I have tried it and it seems this has been already fixed. Thanks!
