### ISSUE TITLE
Can Not Activate rust-analyzer: Bootstrao Error

### ISSUE THREAD

**Issue by AurevoirXavier** [rust-analyzer/rust-analyzer#5257]
```
ERROR [7/8/2020, 10:37:58 AM]: [TypeError: node_fetch_1.default is not a function
	at Object.fetchRelease (/Users/xavier/.vscode-insiders/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:15902:48)
	at bootstrapExtension (/Users/xavier/.vscode-insiders/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:16118:31)
	at bootstrap (/Users/xavier/.vscode-insiders/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:16094:11)
	at async tryActivate (/Users/xavier/.vscode-insiders/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:16022:24)
	at async activate (/Users/xavier/.vscode-insiders/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:15996:5)
	at async Promise.all (index 0)]
ERROR [7/8/2020, 10:37:58 AM]: Bootstrap error [TypeError: node_fetch_1.default is not a function
	at Object.fetchRelease (/Users/xavier/.vscode-insiders/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:15902:48)
	at getServer (/Users/xavier/.vscode-insiders/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:16235:31)
	at async bootstrapServer (/Users/xavier/.vscode-insiders/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:16145:18)
	at async bootstrap (/Users/xavier/.vscode-insiders/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:16095:18)
	at async tryActivate (/Users/xavier/.vscode-insiders/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:16022:24)
	at async activate (/Users/xavier/.vscode-insiders/extensions/matklad.rust-analyzer-0.3.234-nightly/out/src/main.js:15996:5)
	at async Promise.all (index 0)]
```

**Comment by AurevoirXavier** [comment]
Fixed.

Reinstall.

**Comment by lnicola** [comment]
@Veetaha could this be related to the import changes?

**Comment by Veetaha** [comment]
@lnicola this is very strange, I do have the same problem when installing the new nightly.
But according to what I see in REPL, everything should work fine.
```
~/dev/rust-analyzer/editors/code (feat/gzip-binaries) $ node
Welcome to Node.js v14.4.0.
Type ".help" for more information.
> var fetch = require("node-fetch")
undefined
> fetch.default
<ref *1> [Function: fetch] {
  isRedirect: [Function (anonymous)],
  Promise: [Function: Promise],
  default: [Circular *1],
  Headers: [Function: Headers],
  Request: [Function: Request],
  Response: [Function: Response],
  FetchError: [Function: FetchError]
}
> fetch.default()
Promise {
  <rejected> TypeError: Only absolute URLs are supported
```
Maybe there is some problem with rollup?

**Comment by lnicola** [comment]
But why would reinstalling the extension fix it?

**Comment by Veetaha** [comment]
@AurevoirXavier have you switched to stable channel when reinstalling?

**Comment by Veetaha** [comment]
Yes, this is the problem with rollup, for some reason, it messes all up, god, I hate this...

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier have you switched to stable channel when reinstalling?

No, always nightly.
