### ISSUE TITLE
panic: overflow depth reached

### ISSUE THREAD

**Issue by olix0r** [rust-analyzer/rust-analyzer#5338]
rust-analyzer reliably panics when compiling [linkerd2-proxy@main](https://github.com/linkerd/linkerd2-proxy/tree/40e1a6224961878e1a2a3b48999f839888f6b599):

```
:; /home/ver/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux analysis-stats ./linkerd/service-profiles 
Database loaded 396.672681ms
Crates in this dir: 61
Total modules found: 257
Total declarations: 3295
Total functions: 1826
Item Collection: 18.686780996s, 0b allocated 0b resident
thread 'main' panicked at 'overflow depth reached', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/chalk-solve-0.15.0/src/recursive/stack.rs:51:13
stack backtrace:
   0: <unknown>
   1: core::fmt::write
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: std::panicking::rust_panic_with_hook
   6: <unknown>
   7: chalk_solve::recursive::stack::Stack::push
  ..: <unknown>
 100: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I also see intermittent assertion failures:
```
:; /home/ver/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux analysis-stats .                         
Database loaded 391.930197ms
Crates in this dir: 61
Total modules found: 257
Total declarations: 3295
Total functions: 1826
Item Collection: 18.588868086s, 0b allocated 0b resident
197/1826 10% processing: tests::first_datathread 'main' panicked at 'assertion failed: `(left == right)`
  left: `^1`,
 right: `^0`', /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/macros.rs:16:9
stack backtrace:
   0: <unknown>
   1: core::fmt::write
  ..: <unknown>
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
  ..: <unknown>
  37: ra_hir_ty::traits::trait_solve_query
  ..: <unknown>
  44: ra_hir_ty::autoderef::deref
  ..: <unknown>
  48: ra_hir_ty::method_resolution::iterate_method_candidates_impl
  ..: <unknown>
  64: ra_hir_ty::infer::infer_query
  ..: <unknown>
  70: rust_analyzer::cli::analysis_stats::analysis_stats
  ..: <unknown>
  73: std::rt::lang_start_internal
  74: <unknown>
  75: __libc_start_main
  76: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

```
:; rustc --version       
rustc 1.44.1 (c7087fe00 2020-06-17)
```

Is there anything I can tune to try to get this working properly?

**Comment by bjorn3** [comment]
cc @flodiebold

**Comment by cynecx** [comment]
On master:

```
% ~/dev/rust-analyzer/target/release/rust-analyzer analysis-stats .
Database loaded 37.783599992s
Crates in this dir: 64
Total modules found: 281
Total declarations: 3641
Total functions: 1957
Item Collection: 17.595072484s, 0b allocated 0b resident
44/1957 2% processing: certify::daemonthread 'main' panicked at 'overflow depth reached', /home/cynecx/.cargo/registry/src/github.com-1ecc6299db9ec823/chalk-recursive-0.17.0/src/stack.rs:51:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: std::panicking::begin_panic
  12: chalk_recursive::stack::Stack::push
  13: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  14: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  15: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  16: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  17: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  18: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  19: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  20: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  21: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  22: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  23: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  24: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  25: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  26: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  27: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  28: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  29: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  30: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  31: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  32: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  33: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  34: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  35: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  36: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  37: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  38: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  39: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  40: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  41: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  42: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  43: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  44: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  45: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  46: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  47: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  48: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  49: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  50: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  51: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  52: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  53: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  54: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  55: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  56: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  57: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  58: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  59: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  60: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  61: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  62: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  63: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  64: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  65: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  66: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  67: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  68: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  69: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  70: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  71: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  72: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  73: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  74: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  75: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  76: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  77: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  78: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  79: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  80: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  81: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  82: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  83: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  84: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  85: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  86: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  87: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  88: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  89: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  90: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  91: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  92: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  93: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  94: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  95: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  96: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  97: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  98: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  99: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
 100: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
 101: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
 102: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
 103: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
 104: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
 105: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by olix0r** [comment]
For what it's worth, this project now encounters a `not implemented` exception instead:

```
:; RUST_BACKTRACE=full ~/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux analysis-stats .
Database loaded 362.54ms, 439mi
Crates in this dir: 56
Total modules found: 287
Total declarations: 3500
Total functions: 1922
Item Collection: 17.93s, 131056mi
37/1922 1% processing: requests::layer::poll_readythread 'main' panicked at 'not implemented', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/macros.rs:13:23
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: std::panicking::begin_panic
  12: chalk_solve::clauses::push_auto_trait_impls
  13: chalk_solve::clauses::builder::ClauseBuilder<I>::push_binders
  14: chalk_solve::clauses::program_clauses_that_could_match
  15: chalk_solve::clauses::program_clauses_for_goal
  16: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  17: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  18: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  19: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  20: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  21: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  22: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  23: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  24: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  25: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  26: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  27: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  28: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  29: <chalk_recursive::recursive::RecursiveSolver<I> as chalk_solve::solve::Solver<I>>::solve_limited
  30: hir_ty::traits::trait_solve_query
  31: salsa::runtime::Runtime::execute_query_implementation
  32: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  33: salsa::derived::slot::Slot<Q,MP>::read
  34: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  35: salsa::QueryTable<Q>::get
  36: <DB as hir_ty::db::HirDatabase>::trait_solve::__shim
  37: <DB as hir_ty::db::HirDatabase>::trait_solve
  38: hir_ty::infer::InferenceContext::resolve_ty_as_possible
  39: hir_ty::infer::path::<impl hir_ty::infer::InferenceContext>::infer_path
  40: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  41: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  42: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  43: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_method_call
  44: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  45: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  46: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_method_call
  47: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  48: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  49: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  50: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  51: hir_ty::infer::infer_query
  52: salsa::runtime::Runtime::execute_query_implementation
  53: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  54: salsa::derived::slot::Slot<Q,MP>::read
  55: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  56: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  57: hir_ty::db::infer_wait
  58: rust_analyzer::cli::analysis_stats::AnalysisStatsCmd::run
  59: rust_analyzer::main
  60: std::rt::lang_start::{{closure}}
  61: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  62: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  63: std::panicking::try
             at src/libstd/panicking.rs:325
  64: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  65: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  66: main
  67: __libc_start_main
  68: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by lnicola** [comment]
Which version are you running? This should have been fixed by https://github.com/rust-analyzer/rust-analyzer/pull/6161.

**Comment by olix0r** [comment]
@lnicola ah hah. i was on `rust-analyzer e5f252a`. after updating i'm back to an overflow depth reached error:

```
252/1929 13% processing: do_sendthread 'main' panicked at 'overflow depth reached', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/chalk-recursive-0.33.0/src/stack.rs:51:13
stack backtrace:
   0: std::panicking::begin_panic
   1: chalk_recursive::stack::Stack::push
   2: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
   3: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
   4: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
   5: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
   6: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
   7: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
   8: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
   9: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  10: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  11: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  12: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  13: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  14: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  15: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  16: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  17: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  18: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  19: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  20: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  21: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  22: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  23: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  24: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  25: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  26: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  27: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  28: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  29: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  30: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  31: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  32: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  33: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  34: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  35: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  36: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  37: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  38: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  39: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  40: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  41: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  42: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  43: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  44: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  45: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  46: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  47: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  48: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  49: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  50: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  51: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  52: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  53: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  54: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  55: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  56: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  57: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  58: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  59: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  60: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  61: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  62: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  63: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  64: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  65: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  66: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  67: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  68: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  69: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  70: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  71: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  72: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  73: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  74: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  75: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  76: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  77: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  78: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  79: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  80: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  81: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  82: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  83: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  84: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  85: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  86: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  87: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  88: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  89: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  90: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  91: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  92: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by olix0r** [comment]
I no longer see this error on recent versions of rust-analyzer! 🎉 Thanks for fixing ;)
