### ISSUE TITLE
"A request has failed" every time I add a dependency in my Cargo.toml [VSCode] 

### ISSUE THREAD

**Issue by Gogopex** [rust-analyzer/rust-analyzer#5436]
Hi!

**Background:**
VS Code: v1.47.2
rust-analyzer: v0.2.240

**Issue:**
Every time I add a dependency and save my Cargo.toml, a popup appears saying:
`A request has failed. See the output for more information.`
<img width="448" alt="Screen Shot 2020-07-19 at 11 25 23 AM" src="https://user-images.githubusercontent.com/178568/87871706-fc270a00-c9b2-11ea-9a70-97c3d7a14108.png">

The output looks like this:
```
[Error - 11:22:48 AM] Registering progress handler for token rustAnalyzer/cargo check failed.
Error: Progress handler for token rustAnalyzer/cargo check already registered
	at Object.onProgress (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:3733:23)
	at LanguageClient.onProgress (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:10225:45)
	at new ProgressPart (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:8310:41)
	at createHandler (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:11496:13)
	at handleRequest (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:3344:27)
	at processMessageQueue (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:3232:17)
	at Immediate._onImmediate (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:3222:13)
	at processImmediate (internal/timers.js:439:21)
[Error - 11:22:54 AM] Registering progress handler for token rustAnalyzer/cargo check failed.
Error: Progress handler for token rustAnalyzer/cargo check already registered
	at Object.onProgress (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:3733:23)
	at LanguageClient.onProgress (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:10225:45)
	at new ProgressPart (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:8310:41)
	at createHandler (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:11496:13)
	at handleRequest (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:3344:27)
	at processMessageQueue (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:3232:17)
	at Immediate._onImmediate (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:3222:13)
	at processImmediate (internal/timers.js:439:21)
[Error - 11:22:54 AM] Registering progress handler for token rustAnalyzer/cargo check failed.
Error: Progress handler for token rustAnalyzer/cargo check already registered
	at Object.onProgress (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:3733:23)
	at LanguageClient.onProgress (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:10225:45)
	at new ProgressPart (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:8310:41)
	at createHandler (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:11496:13)
	at handleRequest (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:3344:27)
	at processMessageQueue (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:3232:17)
	at Immediate._onImmediate (/Users/ludwig/.vscode/extensions/matklad.rust-analyzer-0.2.240/out/src/main.js:3222:13)
	at processImmediate (internal/timers.js:439:21)
```

Nothing gets visibly broken by this: I usually simply ignore the output and can continue working with no issues.

If needed, here's my Cargo.toml:
```
[package]
name = "xxx"
version = "0.1.0"
authors = ["yyy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt="0.3.15"
reqwest={ version = "0.10.6", features = ["blocking"] }
serde_json="1.0.56"
serde="1.0.114"
serde_derive="1.0.114"
tokio = "0.2.21"
chrono = "0.4"
```

**Comment by lnicola** [comment]
The progress handler error was fixed in #8606 and I don't see any other error in a quick test. Please reopen or file a new issue if you still have problems.
