### ISSUE TITLE
thread 'main' panicked at 'assertion failed: start <= end'

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#5450]
Before this the semantic highlighting was shifted a bit. I think it was 1 character. I did not type any non-unicode characters. This problem has happened twice today.

```
thread 'main' panicked at 'assertion failed: start <= end', /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/macros.rs:13:23
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: std::panicking::begin_panic
  12: rust_analyzer::lsp_utils::apply_document_changes
  13: core::ops::function::FnOnce::call_once
  14: rust_analyzer::dispatch::NotificationDispatcher::on
  15: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::handle_event
  16: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
  17: rust_analyzer::main_loop::main_loop
  18: rust_analyzer::main
  19: std::rt::lang_start::{{closure}}
  20: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  21: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  22: std::panicking::try
             at src/libstd/panicking.rs:274
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  25: main
  26: __libc_start_main
  27: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by lnicola** [comment]
Oof, it could be the incremental sync.

**Comment by bjorn3** [comment]
I think I tried to complete a `use`, then edited `Cargo.toml` to add the crate for which the `use` was meant and then tried to complete the `use` again while it was still loading.

**Comment by bjorn3** [comment]
No
