### ISSUE TITLE
fail installation of rust-analyzer on Ec2 instance using Vs Code remote

### ISSUE THREAD

**Issue by sehz** [rust-analyzer/rust-analyzer#5529]
```
INFO [7/24/2020, 11:45:34 PM]: Extension version: 0.2.248
INFO [7/24/2020, 11:45:34 PM]: Using configuration {
  diagnostics: { enable: true, warningsAsInfo: [], warningsAsHint: [] },
  lruCapacity: null,
  files: { watcher: 'client', exclude: [] },
  notifications: { cargoTomlNotFound: true },
  cargo: {
    autoreload: true,
    noDefaultFeatures: false,
    allFeatures: true,
    features: [],
    loadOutDirsFromCheck: false,
    target: null
  },
  rustfmt: { extraArgs: [], overrideCommand: null },
  checkOnSave: {
    enable: true,
    extraArgs: [],
    command: 'check',
    overrideCommand: null,
    allTargets: true,
    allFeatures: null,
    features: null
  },
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    typeHints: true,
    chainingHints: true,
    parameterHints: true,
    maxLength: 20
  },
  completion: {
    addCallParenthesis: true,
    addCallArgumentSnippets: true,
    postfix: { enable: true }
  },
  callInfo: { full: true },
  updates: { channel: 'stable', askBeforeDownload: true },
  serverPath: null,
  trace: { server: 'off', extension: false },
  procMacro: { enable: true },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  lens: { enable: true, run: true, debug: true, implementations: true },
  hoverActions: {
    enable: true,
    implementations: true,
    run: true,
    debug: true,
    gotoTypeDef: true
  },
  linkedProjects: null,
  withSysroot: true,
  highlightingOn: true,
  featureFlags: { 'notifications.cargo-toml-not-found': false }
}
INFO [7/24/2020, 11:45:34 PM]: PersistentState: {
  lastCheck: 1593133242497,
  releaseId: 27940635,
  serverVersion: '0.2.248'
}
INFO [7/24/2020, 11:45:44 PM]: Using server binary at /home/ec2-user/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux
ERROR [7/24/2020, 11:45:44 PM]: Bootstrap error [Error: Failed to execute /home/ec2-user/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux --version
	at bootstrapServer (/home/ec2-user/.vscode-server/extensions/matklad.rust-analyzer-0.2.248/out/src/main.js:16154:15)
	at processTicksAndRejections (internal/process/task_queues.js:89:5)
	at async bootstrap (/home/ec2-user/.vscode-server/extensions/matklad.rust-analyzer-0.2.248/out/src/main.js:16097:18)
	at async tryActivate (/home/ec2-user/.vscode-server/extensions/matklad.rust-analyzer-0.2.248/out/src/main.js:16024:24)
	at async activate (/home/ec2-user/.vscode-server/extensions/matklad.rust-analyzer-0.2.248/out/src/main.js:15998:5)
	at async Promise.all (index 0)
	at async Promise.all (index 1)
	at async Promise.all (index 27)
	at async Promise.all (index 1)]
```

**Comment by lnicola** [comment]
@Veetaha wasn't the binary supposed to be called `rust-analyzer`?

@sehz do you have an executable under `~/.vscode-server/data/User/globalStorage/matklad.rust-analyzer`? Does it run?

**Comment by bjorn3** [comment]
> `@Veetaha` wasn't the binary supposed to be called rust-analyzer?

It is called `rust-analyzer-linux` on my system.

**Comment by Veetaha** [comment]
No, it is `rust-analyzer-linux`, @sehz, aren't there any additional logs? I'd suggest turning on `"rust-analyzer.trace.extension": true`

**Comment by sehz** [comment]
it seems glibc is required:
```
./rust-analyzer-linux 
./rust-analyzer-linux: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./rust-analyzer-linux)
```

**Comment by lnicola** [comment]
You should try building from source of using the version available in rustup. The GitHub binaries don't work in CentOS 7 and related versions.

**Comment by sehz** [comment]
When will CentOS binary be supported?

**Comment by lnicola** [comment]
It is already supported by the rustup version, available in the nightly toolchain, but you can install it only for rust-analyzer and use the stable compiler.

Other than that, I don't think there are immediate plans to build on an older distro (the GitHub binaries are compiled on Ubuntu 16.04) and rustup will probably become the main distribution method in the long run.

**Comment by sehz** [comment]
Sucessful  install using was linux-2 image.
