### ISSUE TITLE
Ctrl + F5 (Run without debugging) and F5 (Start debugging)

### ISSUE THREAD

**Issue by bugproof** [rust-analyzer/rust-analyzer#5616]
Is it possible to bind these shortcuts to "Rust Analyzer: Run" and "Rust Analyzer: Debug" ?

**Comment by bjorn3** [comment]
You should be able to edit the keynapping in vscode.

**Comment by bugproof** [comment]
@bjorn3 it worked but the only disadvantage is you have to select the project manually each time like there's no way to make it build and run always the current project. I guess `launch.json` can be an option. But it would be a cool addition if it came out of the box, or some tasks to configure launch.json for you. It's a very common workflow for people coming from full-blown IDEs like Jetbrains or Visual Studio. 

- Set a breakpoint, tap F5 to start debugging
- Ctrl + F5 to build and run

**Comment by Zerowalker** [comment]
would love this as well.
what's the difference in how Rust Analyzer does the debug compared to the "default?" way?
as i assume it's a difference and that's the core issue here?

**Comment by gruvw** [comment]
Started learning Rust and I also wish F5 would trigger `cargo run`.

**Comment by mide1337** [comment]
This post did it for me:
https://users.rust-lang.org/t/error-theres-no-debug-target-with-rust-analyzer-vscode/47177/2

**Comment by eduarddejong** [comment]
Things like these are why I do not always like VS Code, because debugging/running/building experience is very unreliable and depending on individual extensions and situations.

I use the CoreLLDB config for my projects, but it does not work the same as clicking on the "Debug" hyperlink above the main function.
It's a lot slower and also quite buggy, when I press F5 with a non compiling issue in my code the debugger just crashes with an ugly stack trace and failure.
But also the Rust Analyzer hyperlinks have problems.

A simple test case:
![afbeelding](https://github.com/rust-lang/rust-analyzer/assets/86660027/4b50d4a8-b783-401f-b1c0-27d5351a3db8)

**1**
So I press F5:

```
Running `cargo build --bin=random-password-generator --package=random-password-generator --message-format=json`...
   Compiling random-password-generator v0.1.0 (/media/Data/Development/Rust/random-password-generator)
error[E0425]: cannot find value `foobar` in this scope
 --> src/main.rs:3:5
  |
3 |     foobar
  |     ^^^^^^ not found in this scope

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0425`.
error: could not compile `random-password-generator` (bin "random-password-generator") due to 2 previous errors
Error: Cargo invocation failed.
    at t.Cargo.getCargoArtifacts (/home/eduard/.vscode-oss/extensions/vadimcn.vscode-lldb-1.10.0/extension.js:1:14943)
    at Object.open (/home/eduard/.vscode-oss/extensions/vadimcn.vscode-lldb-1.10.0/extension.js:1:13253)
Caused by: Error: exit code: 101.
    at ChildProcess.<anonymous> (/home/eduard/.vscode-oss/extensions/vadimcn.vscode-lldb-1.10.0/extension.js:1:16610)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:322:12)
 *  The terminal process failed to launch (exit code: 1). 
 *  Terminal will be reused by tasks, press any key to close it. 
```
😢😢

**2**
Then I click "Debug":
```
error[E0425]: cannot find value `foobar` in this scope
 --> src/main.rs:3:5
  |
3 |     foobar
  |     ^^^^^^ not found in this scope

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0425`.
error: could not compile `random-password-generator` (bin "random-password-generator") due to 2 previous errors
```
![afbeelding](https://github.com/rust-lang/rust-analyzer/assets/86660027/4e890337-f687-4280-a2d0-d5ecce40e61e)

Much, cleaner no stacktrace, although I still see no colors. 🙄

**3**
And then I click "Run" instead:

![afbeelding](https://github.com/rust-lang/rust-analyzer/assets/86660027/9a05405e-86a0-40ee-b376-228b55d9ca86)

Colors!! 🙂🙂

So actually only "Run" works the way it should. The other ones have problems.
I think this should be pretty much a priority issue. Unless I am doing something really silly here, but then I have no idea what exactly.
