### ISSUE TITLE
Bootstrap error: Failed to execute rust-analyzer --version

### ISSUE THREAD

**Issue by Razican** [rust-analyzer/rust-analyzer#5650]
Hello, I started working on my old computer again this weekend, where I had an old version of rust analyzer installed, and when updating it, I got this error:

<details>
<summary>Error</summary>

```
INFO [8/3/2020, 12:12:05 PM]: Extension version: 0.4.0-dev
INFO [8/3/2020, 12:12:05 PM]: Using configuration {
  diagnostics: { enable: true, warningsAsInfo: [], warningsAsHint: [] },
  lruCapacity: null,
  files: { watcher: 'client', exclude: [] },
  notifications: { cargoTomlNotFound: true },
  cargo: {
    noDefaultFeatures: false,
    allFeatures: true,
    features: [],
    loadOutDirsFromCheck: true,
    target: null
  },
  rustfmt: { extraArgs: [], overrideCommand: null },
  checkOnSave: {
    enable: true,
    extraArgs: [],
    command: 'clippy',
    overrideCommand: null,
    allTargets: true,
    allFeatures: null,
    features: null
  },
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: false,
    typeHints: true,
    chainingHints: true,
    parameterHints: true,
    maxLength: 20
  },
  completion: {
    addCallParenthesis: true,
    addCallArgumentSnippets: true,
    postfix: { enable: true }
  },
  callInfo: { full: true },
  updates: { channel: 'stable', askBeforeDownload: true },
  serverPath: null,
  trace: { server: 'off', extension: false },
  procMacro: { enable: true },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  lens: { enable: true, run: true, debug: true, implementations: true },
  hoverActions: {
    enable: true,
    implementations: true,
    run: true,
    debug: true,
    gotoTypeDef: true
  },
  linkedProjects: null,
  withSysroot: true
}
INFO [8/3/2020, 12:12:05 PM]: PersistentState: {
  lastCheck: undefined,
  releaseId: undefined,
  serverVersion: '0.2.199'
}
INFO [8/3/2020, 12:12:05 PM]: Using server binary at rust-analyzer
ERROR [8/3/2020, 12:12:05 PM]: Bootstrap error [Error: Failed to execute rust-analyzer --version
	at bootstrapServer (/home/razican/.vscode-oss/extensions/matklad.rust-analyzer-0.4.0-dev/out/src/main.js:16154:15)
	at async bootstrap (/home/razican/.vscode-oss/extensions/matklad.rust-analyzer-0.4.0-dev/out/src/main.js:16097:18)
	at async tryActivate (/home/razican/.vscode-oss/extensions/matklad.rust-analyzer-0.4.0-dev/out/src/main.js:16024:24)
	at async activate (/home/razican/.vscode-oss/extensions/matklad.rust-analyzer-0.4.0-dev/out/src/main.js:15998:5)
	at async Promise.all (index 0)
	at async h.$activate (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:843:297)]
```

</details>

I tried uninstalling and re-installing the extension. Removing it from the cache in my computer, but without luck. It seems there is something wrong with my configuration.

I'm using VSCodium 1.47.3 (VSCode without the telemetry):
```
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-28T10:50:43.978Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.7.11-200.fc32.x86_64
```

This on an up-to-date Fedora 32.

**Comment by lnicola** [comment]
Do you have an executable in `~/.config/Code/User/globalStorage/matklad.rust-analyzer`? what happens if you run it with `--version`?

Also, I'm not sure what extension you're using. VSCodium switched to https://open-vsx.org/, and while the extension is published there, it's not officially supported, and seems to be a couple of releases old. Can you try building from source instead?

**Comment by Veetaha** [comment]
`0.4.0-dev` is in no way intended to be published, only for building from source.
I recommend you to uninstall the extension and install it again so that vscode switches to what is on the marketplace

**Comment by lnicola** [comment]
-- and install it again from source.

VSCodium doesn't install anything from the Code Marketplace.

**Comment by Razican** [comment]
Installing the non-dev version worked :) thanks!
