### ISSUE TITLE
reduce binary size

### ISSUE THREAD

**Issue by woodsmur** [rust-analyzer/rust-analyzer#5667]
Hi,

Rust-analyzer works quite well in my daily work. However, upgrade often failed in bad network environment.

Here is the log from vscode.

```
INFO [8/5/2020, 3:41:26 PM]: Extension version: 0.2.266
INFO [8/5/2020, 3:41:26 PM]: Using configuration {
  lruCapacity: null,
  files: { watcher: 'client', exclude: [] },
  notifications: { cargoTomlNotFound: true },
  cargo: {
    autoreload: true,
    noDefaultFeatures: false,
    allFeatures: false,
    features: [],
    loadOutDirsFromCheck: false,
    target: null
  },
  rustfmt: { extraArgs: [], overrideCommand: null },
  checkOnSave: {
    enable: true,
    extraArgs: [],
    command: 'check',
    overrideCommand: null,
    allTargets: true,
    noDefaultFeatures: null,
    allFeatures: null,
    features: null
  },
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    typeHints: true,
    chainingHints: true,
    parameterHints: true,
    maxLength: 20
  },
  completion: {
    addCallParenthesis: true,
    addCallArgumentSnippets: true,
    postfix: { enable: true }
  },
  callInfo: { full: true },
  updates: { channel: 'stable', askBeforeDownload: true },
  serverPath: null,
  trace: { server: 'off', extension: true },
  procMacro: { enable: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  lens: { enable: true, run: true, debug: true, implementations: true },
  hoverActions: {
    enable: true,
    implementations: true,
    run: true,
    debug: true,
    gotoTypeDef: true
  },
  linkedProjects: null,
  withSysroot: true,
  diagnostics: {
    enable: true,
    enableExperimental: true,
    warningsAsInfo: [],
    warningsAsHint: []
  }
}
DEBUG [8/5/2020, 3:41:27 PM]: Issuing request for released artifacts metadata to https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/2020-08-04
DEBUG [8/5/2020, 3:41:40 PM]: Downloading file of 6072910 bytes size from https://github.com/rust-analyzer/rust-analyzer/releases/download/2020-08-04/rust-analyzer-mac.gz to /Users/dudu/Library/Application Support/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-macae42334b42
ERROR [8/5/2020, 3:46:16 PM]: Bootstrap error [Error: unexpected end of file
	at Zlib.zlibOnError [as onerror] (zlib.js:170:17)] {
  errno: -5,
  code: 'Z_BUF_ERROR'
}
```

Reducing binary size using tools like [upx](https://upx.github.io/) could be a good way to improve the development experience .

```shell
⋊> ~/Library/Application Support/Code/User/globalStorage/matklad.rust-analyzer upx rust-analyzer-mac            15:51:34
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  17729580 ->   5996560   33.82%   macho/amd64   rust-analyzer-mac

Packed 1 file.
```

**Comment by lnicola** [comment]
I'm not sure I see the point. The binary is compressed with `gzip`, and after UPX and `gzip -9` the file size is 5.6 MB (vs. 5.8 MB for the GitHub release). Do you think that reducing the binary size by 200 KB would improve the experience on unreliable networks?

**Comment by lnicola** [comment]
Stripping the debug symbols from the Linux build yields 5.7 MB after `gzip -9`, vs. the 7.4 MB file on GitHub. But we've recently stopped stripping the releases to make it easier to debug any crashes reported by the users.

**Comment by woodsmur** [comment]
Thanks for reply.

I'm using Mac OS, but I noticed the binary size was increasing during the upgrade(17M after upgrade finished). Was it the gzip file that'd been downloaded from the [releases page](https://github.com/rust-analyzer/rust-analyzer/releases), which is around 7M?

```
⋊> ~/Library/Application Support/code/User/globalStorage/matklad.rust-analyzer ll                                                                                                                                        16:17:40
total 81568
-rwxr-xr-x  1 dudu  staff    17M Aug  4 16:27 rust-analyzer-mac.origin*
-rwxr-xr-x  1 dudu  staff    15M Aug  5 16:17 rust-analyzer-mac0c4c8035a9*
⋊> ~/Library/Application Support/code/User/globalStorage/matklad.rust-analyzer ll                                                                                                                                        16:17:47
total 85664
-rwxr-xr-x  1 dudu  staff    17M Aug  4 16:27 rust-analyzer-mac.origin*
-rwxr-xr-x  1 dudu  staff    16M Aug  5 16:17 rust-analyzer-mac0c4c8035a9*
⋊> ~/Library/Application Support/code/User/globalStorage/matklad.rust-analyzer ll                                                                                                                                        16:17:48
total 85664
-rwxr-xr-x  1 dudu  staff    17M Aug  4 16:27 rust-analyzer-mac.origin*
-rwxr-xr-x  1 dudu  staff    16M Aug  5 16:17 rust-analyzer-mac0c4c8035a9*
⋊> ~/Library/Application Support/code/User/globalStorage/matklad.rust-analyzer ll                                                                                                                                        16:17:49
total 85664
-rwxr-xr-x  1 dudu  staff    17M Aug  4 16:27 rust-analyzer-mac.origin*
-rwxr-xr-x  1 dudu  staff    16M Aug  5 16:17 rust-analyzer-mac0c4c8035a9*
⋊> ~/Library/Application Support/code/User/globalStorage/matklad.rust-analyzer ll                                                                                                                                        16:17:50
total 85664
-rwxr-xr-x  1 dudu  staff    17M Aug  4 16:27 rust-analyzer-mac.origin*
-rwxr-xr-x  1 dudu  staff    16M Aug  5 16:17 rust-analyzer-mac0c4c8035a9*
⋊> ~/Library/Application Support/code/User/globalStorage/matklad.rust-analyzer ll                                                                                                                                        16:18:00
total 85664
-rwxr-xr-x  1 dudu  staff    17M Aug  4 16:27 rust-analyzer-mac.origin*
-rwxr-xr-x  1 dudu  staff    17M Aug  5 16:17 rust-analyzer-mac*
```

**Comment by lnicola** [comment]
Yes, we download the compressed files. We can see that in the log you've posted:

```
DEBUG [8/5/2020, 3:41:40 PM]: Downloading file of 6072910 bytes size from https://github.com/rust-analyzer/rust-analyzer/releases/download/2020-08-04/rust-analyzer-mac.gz to /Users/dudu/Library/Application Support/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-macae42334b42
ERROR [8/5/2020, 3:46:16 PM]: Bootstrap error [Error: unexpected end of file
	at Zlib.zlibOnError [as onerror] (zlib.js:170:17)] {
  errno: -5,
  code: 'Z_BUF_ERROR'
}
```

(Look at the URL and the `zlib.js` error.)

I'm not sure why it's uncompressing so slow in your case. It takes about 130 ms for me. Maybe the Node implementation is slower?

**Comment by woodsmur** [comment]
Thanks @lnicola 

I thinks the http proxy in vscode I used didn't work well, which caused that error. I change another proxy and it works.

BTW, is there anyway I can download and unzip it manually to make rust-analyzer work normally?

**Comment by lnicola** [comment]
Sure, you can download the binary from GitHub, uncompress it, and either:

 - put it in `~/Library/Application Support/code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-mac`
 - put it somewhere else (like `~/.cargo/bin`) and configure the path in your Code settings

**Comment by woodsmur** [comment]
Thanks for your kindly reply. 😄
