### ISSUE TITLE
thread 'main' panicked at `assertion failed: self.is_char_boundary(n)'

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#5742]
```
~                                         │  122 thread 'main' panicked at 'assertion failed: self.is_char_boundary(n)', /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libcore/macros/mod
~                                         │    1 stack backtrace:
~                                         │    2    0: backtrace::backtrace::libunwind::trace
~                                         │    3              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
~                                         │    4    1: backtrace::backtrace::trace_unsynchronized
~                                         │    5              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
~                                         │    6    2: std::sys_common::backtrace::_print_fmt
~                                         │    7              at src/libstd/sys_common/backtrace.rs:78
~                                         │    8    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
~                                         │    9              at src/libstd/sys_common/backtrace.rs:59
~                                         │   10    4: core::fmt::write
~                                         │   11              at src/libcore/fmt/mod.rs:1076
~                                         │   12    5: std::io::Write::write_fmt
~                                         │   13              at src/libstd/io/mod.rs:1537
~                                         │   14    6: std::sys_common::backtrace::_print
~                                         │   15              at src/libstd/sys_common/backtrace.rs:62
~                                         │   16    7: std::sys_common::backtrace::print
~                                         │   17              at src/libstd/sys_common/backtrace.rs:49
~                                         │   18
~                                         │   19 8: std::panicking::default_hook::{{closure}}
~                                         │   20              at src/libstd/panicking.rs:198
~                                         │   21    9: std::panicking::default_hook
~                                         │   22              at src/libstd/panicking.rs:218
~                                         │   23   10: std::panicking::rust_panic_with_hook
~                                         │   24              at src/libstd/panicking.rs:486
~                                         │   25   11: rust_begin_unwind
~                                         │   26              at src/libstd/panicking.rs:388
~                                         │   27   12: core::panicking::panic_fmt
~                                         │   28              at src/libcore/panicking.rs:101
~                                         │   29   13: core::panicking::panic
~                                         │   30
~                                         │   31              at src/libcore/panicking.rs:56
~                                         │   32   14: alloc::string::String::replace_range
~                                         │   33   15: rust_analyzer::lsp_utils::apply_document_changes
~                                         │   34
~                                         │   35  16: core::ops::function::FnOnce::call_once
~                                         │   36   17: rust_analyzer::dispatch::NotificationDispatcher::on
~                                         │   37   18: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::handle_event
~                                         │   38

```

**Comment by lnicola** [comment]
Do you have non-ASCII characters in that file? Can you share a repository where this happens?

**Comment by GopherJ** [comment]
environments:

- coc-rust-analyzer: 0.7.14
- rust-analyzer: f277ec2


Test program:

```
  1   fn main() {   ▶︎ Run | Debug
    1     println!("Hello, world!");
⚠   2     let s = "s";
    3 }

```

**Comment by GopherJ** [comment]
@lnicola Indeed I'm not sure how to reproduce this, the program is as above, I do have some chinese chracter while typing. It crashed so I believe there is a program but hard to reproduce.

**Comment by lnicola** [comment]
I think I can reproduce this with ASCII code by typing while the extension is starting.

**Comment by lnicola** [comment]
Also got a:

```
thread '<unnamed>' panicked at 'Bad range: node range 0..35, range 37..37', /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/rowan-0.10.0/src/cursor.rs:488:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/285fc7d704fcdd7b2a37d475d04d5d955490e000/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/285fc7d704fcdd7b2a37d475d04d5d955490e000/library/std/src/panicking.rs:437
   2: rowan::cursor::SyntaxNode::covering_element
   3: syntax::parsing::reparsing::incremental_reparse
   4: syntax::Parse<syntax::ast::generated::nodes::SourceFile>::reparse
   5: ide::completion::completion_context::CompletionContext::new
   6: ide::completion::completions
   7: std::panicking::try
   8: ide::Analysis::completions
   9: rust_analyzer::handlers::handle_completion
  10: <F as threadpool::FnBox>::call_box
```

**Comment by lnicola** [comment]
It looks like the VFS text is wrong. When loading an unsaved file, we first get a `textDocument/didOpen` notification:

```
[Trace - 21:43:32] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///home/me/Projects/hello/src/main.rs",
        "languageId": "rust",
        "version": 1,
        "text": "struct S;\n\nimpl Iterator for S {}\n"
    }
}
```

On the RA side, we write it to the VFS:

```
[crates/rust-analyzer/src/main_loop.rs:442] &params.text_document.text = "struct S;\n\nimpl Iterator for S {}\n"
```

Then I type a letter:

```
[Trace - 21:43:32] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///home/me/Projects/hello/src/main.rs",
        "version": 2
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 2,
                    "character": 22
                },
                "end": {
                    "line": 2,
                    "character": 22
                }
            },
            "rangeLength": 0,
            "text": "x"
        }
    ]
}
```

In RA we first retrieve the VFS text:

```
[crates/rust-analyzer/src/main_loop.rs:456] &text = "struct S;\n\nimpl Iterator for S\n" # look, no {}
```

Then try to apply the change to the wrong file:

```
[crates/rust-analyzer/src/main_loop.rs:457] &params.content_changes = [
    TextDocumentContentChangeEvent {
        range: Some(
            Range {
                start: Position {
                    line: 2,
                    character: 22,
                },
                end: Position {
                    line: 2,
                    character: 22,
                },
            },
        ),
        range_length: Some(
            0,
        ),
        text: "x",
    },
]
```
