### ISSUE TITLE
Server fails to start

### ISSUE THREAD

**Issue by bheisler** [rust-analyzer/rust-analyzer#5788]
I'm running VSCode on Windows and connecting by SSH to a remote Linux machine. When VSCode tries to start the remote language server, I see this error:

`Cannot activate rust-analyzer: bootstrap error`

Logs:

```
INFO [8/17/2020, 12:47:15 PM]: Extension version: 0.2.281
INFO [8/17/2020, 12:47:15 PM]: Using configuration {
  lruCapacity: null,
  files: { watcher: 'client', exclude: [] },
  notifications: { cargoTomlNotFound: true },
  cargo: {
    autoreload: true,
    noDefaultFeatures: false,
    allFeatures: false,
    features: [],
    loadOutDirsFromCheck: false,
    target: null
  },
  rustfmt: { extraArgs: [], overrideCommand: null },
  checkOnSave: {
    enable: true,
    extraArgs: [],
    command: 'check',
    overrideCommand: null,
    allTargets: true,
    noDefaultFeatures: null,
    allFeatures: null,
    features: null
  },
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    typeHints: true,
    chainingHints: true,
    parameterHints: true,
    maxLength: 20
  },
  completion: {
    addCallParenthesis: true,
    addCallArgumentSnippets: true,
    postfix: { enable: true }
  },
  callInfo: { full: true },
  updates: { channel: 'stable', askBeforeDownload: true },
  serverPath: null,
  trace: { server: 'off', extension: false },
  procMacro: { enable: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  lens: { enable: true, run: true, debug: true, implementations: true },
  hoverActions: {
    enable: true,
    implementations: true,
    run: true,
    debug: true,
    gotoTypeDef: true
  },
  linkedProjects: null,
  withSysroot: true,
  diagnostics: {
    enable: true,
    enableExperimental: true,
    warningsAsInfo: [],
    warningsAsHint: []
  }
}
INFO [8/17/2020, 12:47:15 PM]: PersistentState: {
  lastCheck: undefined,
  releaseId: undefined,
  serverVersion: '0.2.281'
}
INFO [8/17/2020, 12:47:15 PM]: Using server binary at /home/bheisler/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux
ERROR [8/17/2020, 12:47:15 PM]: Bootstrap error [Error: Failed to execute /home/bheisler/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux --version
	at bootstrapServer (/home/bheisler/.vscode-server/extensions/matklad.rust-analyzer-0.2.281/out/src/main.js:16169:15)
	at async bootstrap (/home/bheisler/.vscode-server/extensions/matklad.rust-analyzer-0.2.281/out/src/main.js:16112:18)
	at async tryActivate (/home/bheisler/.vscode-server/extensions/matklad.rust-analyzer-0.2.281/out/src/main.js:16039:24)
	at async activate (/home/bheisler/.vscode-server/extensions/matklad.rust-analyzer-0.2.281/out/src/main.js:16013:5)
	at async Promise.all (index 0)]
```

I don't know if there's any additional logging I can enable to get more details.

**Comment by bjorn3** [comment]
What is the output of running `/home/bheisler/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux --version` on the remote Linux machine?

**Comment by bheisler** [comment]
```
/home/bheisler/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/bheisler/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux)
```

I guess that suggests the pre-built binaries are expecting a newer version of libc. It is an old version of linux. Is there a way to compile the server myself?

**Comment by bjorn3** [comment]
https://rust-analyzer.github.io/manual.html#building-from-source

**Comment by flodiebold** [comment]
There doesn't seem to be anything left to do here.
