### ISSUE TITLE
[VSCode] getaddrinfo EAI_AGAIN

### ISSUE THREAD

**Issue by mominul** [rust-analyzer/rust-analyzer#6003]
Hi,
When the rust-analyzer extension was updating its server, I got thrown an error:
```
INFO [9/14/2020, 9:05:52 PM]: Extension version: 0.2.313
INFO [9/14/2020, 9:05:52 PM]: Using configuration {
  lruCapacity: null,
  files: { watcher: 'client', exclude: [] },
  notifications: { cargoTomlNotFound: true },
  cargo: {
    autoreload: true,
    noDefaultFeatures: false,
    allFeatures: false,
    features: [],
    loadOutDirsFromCheck: false,
    target: null
  },
  rustfmt: { extraArgs: [], overrideCommand: null },
  checkOnSave: {
    enable: true,
    extraArgs: [],
    command: 'check',
    overrideCommand: null,
    allTargets: true,
    noDefaultFeatures: null,
    allFeatures: null,
    features: null,
    target: null
  },
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    typeHints: true,
    chainingHints: true,
    parameterHints: true,
    maxLength: 20
  },
  completion: {
    addCallParenthesis: true,
    addCallArgumentSnippets: true,
    postfix: { enable: true }
  },
  callInfo: { full: true },
  updates: { channel: 'stable', askBeforeDownload: true },
  serverPath: null,
  trace: { server: 'off', extension: false },
  procMacro: { enable: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  lens: { enable: true, run: true, debug: true, implementations: true },
  hoverActions: {
    enable: true,
    implementations: true,
    run: true,
    debug: true,
    gotoTypeDef: true
  },
  linkedProjects: null,
  withSysroot: true,
  diagnostics: {
    enable: true,
    enableExperimental: true,
    disabled: [],
    warningsAsInfo: [],
    warningsAsHint: []
  }
}
INFO [9/14/2020, 9:05:52 PM]: PersistentState: {
  lastCheck: undefined,
  releaseId: undefined,
  serverVersion: '0.2.305'
}
ERROR [9/14/2020, 9:06:14 PM]: Bootstrap error [FetchError: request to https://github.com/rust-analyzer/rust-analyzer/releases/download/2020-09-14/rust-analyzer-linux.gz failed, reason: getaddrinfo EAI_AGAIN github.com
	at ClientRequest.<anonymous> (/home/mominul/.vscode/extensions/matklad.rust-analyzer-0.2.313/out/src/main.js:16545:11)
	at ClientRequest.emit (events.js:228:7)
	at TLSSocket.socketErrorListener (_http_client.js:406:9)
	at TLSSocket.emit (events.js:223:5)
	at emitErrorNT (internal/streams/destroy.js:92:8)
	at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)] {
  message: 'request to https://github.com/rust-analyzer/rust-analyzer/releases/download/2020-09-14/rust-analyzer-linux.gz failed, reason: getaddrinfo EAI_AGAIN github.com',
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}
```
My internet connection was acting pretty bad at that time, so it's not the extension's fault I think. But I am posting here if this kind of error should be handled gracefully.

Thanks!

cc @Veetaha

**Comment by Veetaha** [comment]
Not sure we can act more gracefully here, if the server download failed, the extension is pretty useless without it.

We may add code to retry the download with exponential backoff and provide a more specialized error message.
Anyone interested may try to tackle this here: https://github.com/rust-analyzer/rust-analyzer/blob/7ba578ab1413505e960dda305cc322a29bc00ab3/editors/code/src/net.ts#L1-L151

**Comment by matklad** [comment]
I am inclined to close this: it is true that we should handle this gracefully, but:

* this is low-priority relative to other stuff
* I imagine our distribution strategy changing before we get to this
