### ISSUE TITLE
Panic bad offset in goto_implementation for symbols from include!()

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#6012]
goto_implementation seems to panic when the symbol target comes from a file included via a macro `include!("foo")`:

In the following log, the offset `10835` most likely refers to the offset with all the macros expanded (i.e. `include!()` call replaced with the file contents), but for some reason `goto_implementation::goto_implementation` tries to look up a node in an unexpanded AST.

<details>
<summary>Log</summary>

```
thread '<unnamed>' panicked at 'Bad offset: range 0..632 offset 10835', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rowan-0.10.0/src/cursor.rs:449:9
stack backtrace:
thread '<unnamed>' panicked at 'Bad offset: range 0..632 offset 10835', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rowan-0.10.0/src/cursor.rs:449:9
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:391
  13: rowan::cursor::SyntaxNode::token_at_offset
  14: syntax::algo::ancestors_at_offset
  15: syntax::algo::find_node_at_offset
  16: ide::goto_implementation::goto_implementation
  17: ide::Analysis::goto_implementation
  18: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  19: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  20: rust_analyzer::handlers::handle_hover
  21: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

**Comment by Veykril** [comment]
Can't reproduce anymore, I assume this has been fixed
