### ISSUE TITLE
rust-analyer-mac hangs starting

### ISSUE THREAD

**Issue by elvizlai** [rust-analyzer/rust-analyzer#6022]
I downloaded nightly release, still not working, need any more information?

VS Code log
```
INFO [2020/9/17 上午9:28:46]: Extension version: 0.2.313
INFO [2020/9/17 上午9:28:46]: Using configuration {
  lruCapacity: null,
  files: { watcher: 'client', exclude: [] },
  notifications: { cargoTomlNotFound: true },
  cargo: {
    autoreload: true,
    noDefaultFeatures: false,
    allFeatures: false,
    features: [],
    loadOutDirsFromCheck: false,
    target: null
  },
  rustfmt: { extraArgs: [], overrideCommand: null },
  checkOnSave: {
    enable: true,
    extraArgs: [],
    command: 'check',
    overrideCommand: null,
    allTargets: true,
    noDefaultFeatures: null,
    allFeatures: null,
    features: null,
    target: null
  },
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    typeHints: true,
    chainingHints: true,
    parameterHints: true,
    maxLength: 20
  },
  completion: {
    addCallParenthesis: true,
    addCallArgumentSnippets: true,
    postfix: { enable: true }
  },
  callInfo: { full: true },
  updates: { channel: 'stable', askBeforeDownload: true },
  serverPath: null,
  trace: { server: 'off', extension: false },
  procMacro: { enable: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  lens: { enable: true, run: true, debug: true, implementations: true },
  hoverActions: {
    enable: true,
    implementations: true,
    run: true,
    debug: true,
    gotoTypeDef: true
  },
  linkedProjects: null,
  withSysroot: true,
  diagnostics: {
    enable: true,
    enableExperimental: true,
    disabled: [],
    warningsAsInfo: [],
    warningsAsHint: []
  }
}
INFO [2020/9/17 上午9:28:46]: PersistentState: {
  lastCheck: undefined,
  releaseId: undefined,
  serverVersion: '0.2.313'
}
INFO [2020/9/17 上午9:28:46]: Using server binary at /Users/elvizlai/Library/Application Support/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-mac
WARN [2020/9/17 上午9:29:05]: LSP request timed out {
  method: 'rust-analyzer/inlayHints',
  param: {
    textDocument: {
      uri: 'file:///Users/elvizlai/workspace/github/pingcap/tikv/src/lib.rs'
    }
  },
  error: ResponseError: Rust Analyzer is still loading...
      at handleResponse (/Users/elvizlai/.vscode/extensions/matklad.rust-analyzer-0.2.313/out/src/main.js:3779:48)
      at processMessageQueue (/Users/elvizlai/.vscode/extensions/matklad.rust-analyzer-0.2.313/out/src/main.js:3594:17)
      at Immediate.<anonymous> (/Users/elvizlai/.vscode/extensions/matklad.rust-analyzer-0.2.313/out/src/main.js:3578:13)
      at processImmediate (internal/timers.js:439:21) {
    code: -32801,
    data: undefined
  }
}
WARN [2020/9/17 上午9:30:52]: LSP request timed out {
  method: 'rust-analyzer/inlayHints',
  param: {
    textDocument: {
      uri: 'file:///Users/elvizlai/workspace/github/pingcap/tikv/src/lib.rs'
    }
  },
  error: ResponseError: Rust Analyzer is still loading...
      at handleResponse (/Users/elvizlai/.vscode/extensions/matklad.rust-analyzer-0.2.313/out/src/main.js:3779:48)
      at processMessageQueue (/Users/elvizlai/.vscode/extensions/matklad.rust-analyzer-0.2.313/out/src/main.js:3594:17)
      at Immediate.<anonymous> (/Users/elvizlai/.vscode/extensions/matklad.rust-analyzer-0.2.313/out/src/main.js:3578:13)
      at processImmediate (internal/timers.js:439:21) {
    code: -32801,
    data: undefined
  }
}
WARN [2020/9/17 上午9:30:56]: LSP request timed out {
  method: 'rust-analyzer/inlayHints',
  param: {
    textDocument: {
      uri: 'file:///Users/elvizlai/workspace/github/pingcap/tikv/src/lib.rs'
    }
  },
  error: ResponseError: Rust Analyzer is still loading...
      at handleResponse (/Users/elvizlai/.vscode/extensions/matklad.rust-analyzer-0.2.313/out/src/main.js:3779:48)
      at processMessageQueue (/Users/elvizlai/.vscode/extensions/matklad.rust-analyzer-0.2.313/out/src/main.js:3594:17)
      at Immediate.<anonymous> (/Users/elvizlai/.vscode/extensions/matklad.rust-analyzer-0.2.313/out/src/main.js:3578:13)
      at processImmediate (internal/timers.js:439:21) {
    code: -32801,
    data: undefined
  }
}
WARN [2020/9/17 上午9:30:56]: LSP request timed out {
  method: 'rust-analyzer/inlayHints',
  param: {
    textDocument: {
      uri: 'file:///Users/elvizlai/workspace/github/pingcap/tikv/src/lib.rs'
    }
  },
  error: ResponseError: Rust Analyzer is still loading...
      at handleResponse (/Users/elvizlai/.vscode/extensions/matklad.rust-analyzer-0.2.313/out/src/main.js:3779:48)
      at processMessageQueue (/Users/elvizlai/.vscode/extensions/matklad.rust-analyzer-0.2.313/out/src/main.js:3594:17)
      at Immediate.<anonymous> (/Users/elvizlai/.vscode/extensions/matklad.rust-analyzer-0.2.313/out/src/main.js:3578:13)
      at processImmediate (internal/timers.js:439:21) {
    code: -32801,
    data: undefined
  }
}
```

**Comment by elvizlai** [comment]
GFW related, need index cargo toml first
