### ISSUE TITLE
Thread 'main' panicked (when exiting vi on a brand new rust file)

### ISSUE THREAD

**Issue by sbromberger** [rust-analyzer/rust-analyzer#6060]
Versions:

- rustc 1.46.0 (04488afe3 2020-08-24)
- rust-analyzer e96bfd8
- NVIM v0.5.0-709-g4f8d98e58 with neovim-lsp, rust-lang/rust.vim, nvim-lua/completion-nvim, and nvim-lua/diagnostic-nvim plugins

To reproduce:
`cargo init --bin rt1`, then `nvim rt1/src/main.rs`. Exit vi.

Error:
```
[ ERROR ] 2020-09-22T23:00:37-0700 ] /home/seth/.local/share/nvim/runtime/lua/vim/lsp/rpc.lua:428 ]     "rpc"   "rust-analyzer" "stderr"        "thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/seth/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/lsp-server-0.3.3/src/req_queue.rs:60:9\nstack backtrace:\n"
[ ERROR ] 2020-09-22T23:00:37-0700 ] /home/seth/.local/share/nvim/runtime/lua/vim/lsp/rpc.lua:428 ]     "rpc"   "rust-analyzer" "stderr"        "   0: backtrace::backtrace::libunwind::trace\n             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86\n   1: backtrace::backtrace::trace_unsynchronized\n             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:"
[ ERROR ] 2020-09-22T23:00:37-0700 ] /home/seth/.local/share/nvim/runtime/lua/vim/lsp/rpc.lua:428 ]     "rpc"   "rust-analyzer" "stderr"        "66\n   2: std::sys_common::backtrace::_print_fmt\n             at src/libstd/sys_common/backtrace.rs:78\n   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt\n             at src/libstd/sys_common/backtrace.rs:59\n"
[ ERROR ] 2020-09-22T23:00:37-0700 ] /home/seth/.local/share/nvim/runtime/lua/vim/lsp/rpc.lua:428 ]     "rpc"   "rust-analyzer" "stderr"        "   4: core::fmt::write\n             at src/libcore/fmt/mod.rs:1076\n"
[ ERROR ] 2020-09-22T23:00:37-0700 ] /home/seth/.local/share/nvim/runtime/lua/vim/lsp/rpc.lua:428 ]     "rpc"   "rust-analyzer" "stderr"        "   5: std::io::Write::write_fmt\n             at src/libstd/io/mod.rs:1537\n   6: std::sys_common::backtrace::_print\n             at src/libstd/sys_common/backtrace.rs:62\n   7: std::sys_common::backtrace::print\n             at src/libstd/sys_common/backtrace.rs:49\n   8: std::panicking::default_hook::{{closure}}\n             at src/libstd/panicking.rs:198\n   9: std::panicking::default_hook\n             at src/libstd/panicking.rs:218\n  10: std::panicking::rust_panic_with_hook\n             at src/libstd/panicking.rs:486\n  11: rust_begin_unwind\n             at src/libstd/panicking.rs:388\n  12: core::panicking::panic_fmt\n             at src/libcore/panicking.rs:101\n  13: core::panicking::panic\n             at src/libcore/panicking.rs"
[ ERROR ] 2020-09-22T23:00:37-0700 ] /home/seth/.local/share/nvim/runtime/lua/vim/lsp/rpc.lua:428 ]     "rpc"   "rust-analyzer" "stderr"        ":56\n  14: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::handle_event\n  15: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run\n  16: rust_analyzer::main_loop::main_loop\n  17: rust_analyzer::main\n  18: std::rt::lang_start::{{closure}}\n  19: std::rt::lang_start_internal::{{closure}}\n             at src/libstd/rt.rs:52\n  20"
[ ERROR ] 2020-09-22T23:00:37-0700 ] /home/seth/.local/share/nvim/runtime/lua/vim/lsp/rpc.lua:428 ]     "rpc"   "rust-analyzer" "stderr"        ": std::panicking::try::do_call\n             at src/libstd/panicking.rs:297\n  21: std::panicking::try\n             at src/libstd/panicking.rs:274\n  22: std::panic::catch_unwind\n             at src/libstd/panic.rs:394\n  23: std::rt::lang_start_internal\n             at src/libstd/rt.rs:51\n  24: main\n  25: __libc_start_main\n"
[ ERROR ] 2020-09-22T23:00:37-0700 ] /home/seth/.local/share/nvim/runtime/lua/vim/lsp/rpc.lua:428 ]     "rpc"   "rust-analyzer" "stderr"        "  26: _start\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"     
```

**Comment by sbromberger** [comment]
I noticed that I was running an older version of rust-analyzer. I updated to `rust-analyzer e70cf70` and this problem no longer occurs.
