### ISSUE TITLE
Chalk assertion failed: (left == right)

### ISSUE THREAD

**Issue by cynecx** [rust-analyzer/rust-analyzer#6078]
```toml
[dependencies]
crossbeam = "0.7"
```

```rust
use crossbeam::thread::scope;
fn main() {
    scope(|scope| {
        scope.spawn(|x| {})
    });
}
```

rust-analyzer: 662ed41ebcb1cd221b32be95d08b5bf5f10ae525

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `^1`,
 right: `^0`', /home/cynecx/dev/chalk/chalk-ir/src/lib.rs:2540:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8b4085359ae798dedb05c95ad42520557bd25320/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/8b4085359ae798dedb05c95ad42520557bd25320/library/std/src/panicking.rs:437
   2: <&chalk_ir::SubstFolder<I> as chalk_ir::fold::Folder<I>>::fold_free_var_ty
   3: <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I,TI>>::super_fold_with
   4: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I,TI> for chalk_ir::GenericArg<I>>::fold_with
   5: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
   6: <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I,TI>>::super_fold_with
   7: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I,TI> for chalk_ir::GenericArg<I>>::fold_with
   8: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
   9: <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I,TI>>::super_fold_with
  10: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I,TI> for chalk_ir::GenericArg<I>>::fold_with
  11: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
  12: chalk_ir::_DERIVE_chalk_ir_fold_Fold_I_TI_FOR_WhereClause::<impl chalk_ir::fold::Fold<I,_TI> for chalk_ir::WhereClause<I>>::fold_with
  13: chalk_ir::_DERIVE_chalk_ir_fold_Fold_I_TI_FOR_DomainGoal::<impl chalk_ir::fold::Fold<I,_TI> for chalk_ir::DomainGoal<I>>::fold_with
  14: chalk_ir::_DERIVE_chalk_ir_fold_Fold_I_TI_FOR_ProgramClauseImplication::<impl chalk_ir::fold::Fold<I,_TI> for chalk_ir::ProgramClauseImplication<I>>::fold_with
  15: chalk_solve::infer::instantiate::<impl chalk_solve::infer::InferenceTable<I>>::instantiate_binders_existentially
  16: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::new_with_clause
  17: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  18: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  19: <chalk_recursive::recursive::RecursiveSolver<I> as chalk_solve::solve::Solver<I>>::solve_limited
  20: hir_ty::traits::trait_solve_query
  21: salsa::runtime::Runtime::execute_query_implementation
  22: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  23: salsa::derived::slot::Slot<Q,MP>::read
  24: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  25: <DB as hir_ty::db::HirDatabase>::trait_solve::__shim
  26: <DB as hir_ty::db::HirDatabase>::trait_solve
  27: hir_ty::infer::InferenceContext::resolve_ty_as_possible
  28: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  29: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  30: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
  31: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_method_call
  32: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  33: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  34: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  35: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  36: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  37: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  38: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
  39: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  40: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  41: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  42: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  43: hir_ty::infer::infer_query
  44: salsa::runtime::Runtime::execute_query_implementation
  45: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  46: salsa::derived::slot::Slot<Q,MP>::read
  47: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  48: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  49: hir_ty::db::infer_wait
  50: hir::source_analyzer::SourceAnalyzer::new_for_body
  51: hir::semantics::SemanticsImpl::analyze2
  52: hir::semantics::SemanticsImpl::descend_into_macros
  53: ide::hover::hover
  54: std::panicking::try
  55: ide::Analysis::hover
  56: rust_analyzer::handlers::handle_hover
  57: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by kjeremy** [comment]
@flodiebold?
