### ISSUE TITLE
No Completion - LSP request timed out 

### ISSUE THREAD

**Issue by xsoheilalizadeh** [rust-analyzer/rust-analyzer#6141]
Issue Type: <b>Bug</b>

1) Clone https://github.com/mitsuhiko/redis-rs
2) Start coding 
3) Completion doesn't work

<details>
<summary>Rust Analyzer Client Output</summary>

```
INFO [10/5/2020, 9:01:03 PM]: Extension version: 0.2.336
INFO [10/5/2020, 9:01:03 PM]: Using configuration {
  lruCapacity: null,
  files: { watcher: 'client', exclude: [] },
  notifications: { cargoTomlNotFound: true },
  cargo: {
    autoreload: true,
    noDefaultFeatures: false,
    allFeatures: false,
    features: [],
    loadOutDirsFromCheck: false,
    target: null
  },
  rustfmt: { extraArgs: [], overrideCommand: null },
  checkOnSave: {
    enable: true,
    extraArgs: [],
    command: 'check',
    overrideCommand: null,
    allTargets: true,
    noDefaultFeatures: null,
    allFeatures: null,
    features: null,
    target: null
  },
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    typeHints: true,
    chainingHints: true,
    parameterHints: true,
    maxLength: 20
  },
  completion: {
    addCallParenthesis: true,
    addCallArgumentSnippets: true,
    postfix: { enable: true }
  },
  callInfo: { full: true },
  updates: { channel: 'stable', askBeforeDownload: true },
  serverPath: null,
  trace: { server: 'off', extension: false },
  procMacro: { enable: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  lens: {
    enable: true,
    run: true,
    debug: true,
    implementations: true,
    methodReferences: false
  },
  hoverActions: {
    enable: true,
    implementations: true,
    run: true,
    debug: true,
    gotoTypeDef: true
  },
  linkedProjects: null,
  withSysroot: true,
  diagnostics: {
    enable: true,
    enableExperimental: true,
    disabled: [],
    warningsAsInfo: [],
    warningsAsHint: []
  },
  assist: { importMergeBehaviour: 'full' },
  runnables: { overrideCargo: null, cargoExtraArgs: [] }
}
INFO [10/5/2020, 9:01:03 PM]: PersistentState: {
  lastCheck: undefined,
  releaseId: undefined,
  serverVersion: '0.2.336'
}
INFO [10/5/2020, 9:01:03 PM]: Using server binary at c:\Users\sohei\AppData\Roaming\Code - Insiders\User\globalStorage\matklad.rust-analyzer\rust-analyzer-windows.exe
WARN [10/5/2020, 9:01:17 PM]: LSP request timed out {
  method: 'rust-analyzer/inlayHints',
  param: {
    textDocument: { uri: 'file:///c%3A/code/rust/redis-rs/src/r2d2.rs' }
  },
  error: [ResponseError: Rust Analyzer is still loading...
  	at handleResponse (c:\Users\sohei\.vscode-insiders\extensions\matklad.rust-analyzer-0.2.336\out\src\main.js:3779:48)
  	at processMessageQueue (c:\Users\sohei\.vscode-insiders\extensions\matklad.rust-analyzer-0.2.336\out\src\main.js:3594:17)
  	at Immediate.<anonymous> (c:\Users\sohei\.vscode-insiders\extensions\matklad.rust-analyzer-0.2.336\out\src\main.js:3578:13)
  	at processImmediate (internal/timers.js:439:21)
  	at process.topLevelDomainCallback (domain.js:130:23)] {
    code: -32801,
    data: undefined
  }
}
WARN [10/5/2020, 9:01:47 PM]: LSP request timed out {
  method: 'rust-analyzer/inlayHints',
  param: {
    textDocument: { uri: 'file:///c%3A/code/rust/redis-rs/src/cluster.rs' }
  },
  error: [ResponseError: Rust Analyzer is still loading...
  	at handleResponse (c:\Users\sohei\.vscode-insiders\extensions\matklad.rust-analyzer-0.2.336\out\src\main.js:3779:48)
  	at processMessageQueue (c:\Users\sohei\.vscode-insiders\extensions\matklad.rust-analyzer-0.2.336\out\src\main.js:3594:17)
  	at Immediate.<anonymous> (c:\Users\sohei\.vscode-insiders\extensions\matklad.rust-analyzer-0.2.336\out\src\main.js:3578:13)
  	at processImmediate (internal/timers.js:439:21)
  	at process.topLevelDomainCallback (domain.js:130:23)] {
    code: -32801,
    data: undefined
  }
}
WARN [10/5/2020, 9:01:49 PM]: LSP request timed out {
  method: 'rust-analyzer/inlayHints',
  param: {
    textDocument: { uri: 'file:///c%3A/code/rust/redis-rs/src/lib.rs' }
  },
  error: [ResponseError: Rust Analyzer is still loading...
  	at handleResponse (c:\Users\sohei\.vscode-insiders\extensions\matklad.rust-analyzer-0.2.336\out\src\main.js:3779:48)
  	at processMessageQueue (c:\Users\sohei\.vscode-insiders\extensions\matklad.rust-analyzer-0.2.336\out\src\main.js:3594:17)
  	at Immediate.<anonymous> (c:\Users\sohei\.vscode-insiders\extensions\matklad.rust-analyzer-0.2.336\out\src\main.js:3578:13)
  	at processImmediate (internal/timers.js:439:21)
  	at process.topLevelDomainCallback (domain.js:130:23)] {
    code: -32801,
    data: undefined
  }
}
WARN [10/5/2020, 9:01:55 PM]: LSP request timed out {
  method: 'rust-analyzer/inlayHints',
  param: {
    textDocument: { uri: 'file:///c%3A/code/rust/redis-rs/src/acl.rs' }
  },
  error: [ResponseError: Rust Analyzer is still loading...
  	at handleResponse (c:\Users\sohei\.vscode-insiders\extensions\matklad.rust-analyzer-0.2.336\out\src\main.js:3779:48)
  	at processMessageQueue (c:\Users\sohei\.vscode-insiders\extensions\matklad.rust-analyzer-0.2.336\out\src\main.js:3594:17)
  	at Immediate.<anonymous> (c:\Users\sohei\.vscode-insiders\extensions\matklad.rust-analyzer-0.2.336\out\src\main.js:3578:13)
  	at processImmediate (internal/timers.js:439:21)
  	at process.topLevelDomainCallback (domain.js:130:23)] {
    code: -32801,
    data: undefined
  }
}
```
</details>
Extension version: 0.2.336
VS Code version: Code - Insiders 1.50.0-insider (0ecb64a2c8945dd1193967019f0734af539ca9c3, 2020-10-02T11:16:33.984Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.01GB free)|
|Process Argv|--crash-reporter-id 8a985542-2c5f-4c41-b1bc-7bb2abf68e7b|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bjorn3** [comment]
It says that rust-analyzer is still loading. You may need to wait longer. Try to wait until the rust-analyzer-windows.exe process doesn't consume a full cpu core anymore.

**Comment by joncarr** [comment]
I'm having a similar issue on windows only. I receive an error in emacs that states `LSP :: Error from the Language Server: Rust Analyzer is still loading... (Unknown Error)` and it just sits there. Not sure what the deal is but I know that I never get completion.

**Comment by matklad** [comment]
We now properly display all project loading related errors, which I think are the underlying issue here.
