### ISSUE TITLE
index out of bounds: not reproducable

### ISSUE THREAD

**Issue by zhiburt** [rust-analyzer/rust-analyzer#6169]
```log
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', crates/hir_def/src/nameres/path_resolution.rs:283:33
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::thread::local::LocalKey<T>::with
  11: stdx::panic_context::PanicContext::init::{{closure}}
  12: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:530
  13: rust_begin_unwind
             at src/libstd/panicking.rs:437
  14: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  15: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:62
  16: hir_def::nameres::path_resolution::<impl hir_def::nameres::CrateDefMap>::resolve_path_fp_with_macro
  17: hir_def::resolver::Resolver::resolve_path_in_type_ns
  18: hir_ty::lower::<impl hir_ty::Ty>::from_hir_ext
  19: <hir_ty::db::ImplSelfTyQuery as salsa::plumbing::QueryFunction>::execute
  20: salsa::runtime::Runtime::execute_query_implementation
  21: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  22: salsa::derived::slot::Slot<Q,MP>::read
  23: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  24: <DB as hir_ty::db::HirDatabase>::impl_self_ty::__shim
  25: <DB as hir_ty::db::HirDatabase>::impl_self_ty
  26: <hir_ty::db::ImplTraitQuery as salsa::plumbing::QueryFunction>::execute
  27: salsa::runtime::Runtime::execute_query_implementation
  28: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  29: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  30: hir_ty::db::HirDatabaseGroupStorage__::maybe_changed_since
  31: salsa::derived::slot::MemoRevisions::validate_memoized_value
  32: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  33: salsa::derived::slot::Slot<Q,MP>::read
  34: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  35: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate::__shim
  36: hir_ty::method_resolution::TraitImpls::trait_impls_in_deps_query
  37: salsa::runtime::Runtime::execute_query_implementation
  38: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  39: salsa::derived::slot::Slot<Q,MP>::read
  40: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  41: <DB as hir_ty::db::HirDatabase>::trait_impls_in_deps::__shim
  42: hir_ty::traits::chalk::<impl chalk_solve::RustIrDatabase<hir_ty::traits::chalk::interner::Interner> for hir_ty::traits::ChalkContext>::impls_for_trait
  43: chalk_solve::clauses::program_clauses_that_could_match
  44: chalk_solve::clauses::program_clauses_for_goal
  45: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  46: <chalk_recursive::recursive::RecursiveSolver<I> as chalk_solve::solve::Solver<I>>::solve_limited
  47: hir_ty::traits::trait_solve_query
  48: salsa::runtime::Runtime::execute_query_implementation
  49: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  50: salsa::derived::slot::Slot<Q,MP>::read
  51: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  52: salsa::QueryTable<Q>::get
  53: <DB as hir_ty::db::HirDatabase>::trait_solve::__shim
  54: <DB as hir_ty::db::HirDatabase>::trait_solve
  55: hir_ty::autoderef::deref
  56: core::iter::traits::iterator::Iterator::find_map
  57: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  58: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  59: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  60: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  61: hir_ty::infer::infer_query
  62: salsa::runtime::Runtime::execute_query_implementation
  63: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  64: salsa::derived::slot::Slot<Q,MP>::read
  65: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  66: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  67: hir_ty::db::infer_wait
  68: hir_ty::diagnostics::validate_body
  69: hir::code_model::Module::diagnostics
  70: ide::diagnostics::diagnostics
  71: ide::Analysis::diagnostics
  72: rust_analyzer::handlers::publish_diagnostics
  73: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  74: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  75: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', crates/hir_def/src/nameres/path_resolution.rs:283:33
```

```log
thread '<unnamed>' panicked at 'MacroDef without ast_id', crates/hir/src/has_source.rs:117:37
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::thread::local::LocalKey<T>::with
  11: stdx::panic_context::PanicContext::init::{{closure}}
  12: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:530
  13: rust_begin_unwind
             at src/libstd/panicking.rs:437
  14: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  15: core::option::expect_failed
             at src/libcore/option.rs:1261
  16: hir::code_model::MacroDef::name
  17: ide_db::defs::Definition::name
  18: ide_db::search::FindUsages::search
  19: ide_db::search::FindUsages::at_least_one
  20: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  21: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  22: assists::handlers::expand_glob_import::expand_glob_import
  23: assists::Assist::unresolved
  24: ide::Analysis::unresolved_assists
  25: rust_analyzer::handlers::handle_code_action
  26: <F as threadpool::FnBox>::call_box
```

version: `rust-analyzer version: 2020-10-05 (e5f252a)`

**Comment by matklad** [comment]
Probably needs minimal reproducible example to become actionable. But eyeballing the trace might reveal a bug as well!

**Comment by jonas-schievink** [comment]
Same panic location as https://github.com/rust-analyzer/rust-analyzer/issues/5366, so closing as a duplicate. A reproduction is still needed there.
