### ISSUE TITLE
ResponseError: Rust Analyzer is still loading...

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#6285]
I just updated to 9b65646 and am seeing the following in the "Rust Analyzer Client" log in vscode.

```
WARN [10/19/2020, 10:25:19 AM]: LSP request timed out {
  method: 'rust-analyzer/inlayHints',
  param: {
    textDocument: {
      uri: 'file:///c%3A/projects/test/rust-analyzer/crates/syntax/src/ast/generated.rs'
    }
  },
  error: ResponseError: Rust Analyzer is still loading...
      at handleResponse (c:\Users\jkolb\.vscode\extensions\matklad.rust-analyzer-0.4.0-dev\out\src\main.js:3779:48)
      at processMessageQueue (c:\Users\jkolb\.vscode\extensions\matklad.rust-analyzer-0.4.0-dev\out\src\main.js:3594:17)
      at Immediate.<anonymous> (c:\Users\jkolb\.vscode\extensions\matklad.rust-analyzer-0.4.0-dev\out\src\main.js:3578:13)
      at processImmediate (internal/timers.js:439:21) {
    code: -32801,
    data: undefined
  }
}
```

**Comment by lnicola** [comment]
Does it never finish loading? CC #6285

**Comment by kjeremy** [comment]
It never seems to finish. In fact I don't see anything in the status bar about it even starting. I'm at work so I haven't flipped tried a debug build with verbose logging. I might be able to get to that tonight.

**Comment by kjeremy** [comment]
After closing some stale files in the editor I can't reproduce this even when loading those files back up.
