### ISSUE TITLE
Rust analyzer panicked while editing a file

### ISSUE THREAD

**Issue by saveriomiroddi** [rust-analyzer/rust-analyzer#6291]
Hello!

I've experienced a few panics while editing a file. This is a sample:

```
Panic context:
> request: textDocument/documentHighlight DocumentHighlightParams {
    text_document_position_params: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: "file:///path/to/src/tuple_test.rs",
        },
        position: Position {
            line: 8,
            character: 4,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'MacroDef without ast_id', crates/hir/src/has_source.rs:117:37
stack backtrace:
    0: rust_begin_unwind
              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
    1: core::panicking::panic_fmt
              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
    2: core::option::expect_failed
              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1213
    3: hir::code_model::MacroDef::name
    4: ide_db::defs::Definition::name
    5: ide_db::search::FindUsages::search
    6: ide_db::search::FindUsages::all
    7: ide::references::find_all_refs
    8: ide::Analysis::find_all_refs::{{closure}}
    9: std::panicking::try
  10: ide::Analysis::find_all_refs
  11: rust_analyzer::handlers::handle_document_highlight
  12: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Now, since the file is using a macro (from the `demonstrate` crate), I don't know if this panic is expected or not.

Since it happened a few times while editing the file, I suppose (hope) I can reproduce it, if needed.

I've taken a snapshot of the project at the time of the panic, which you can find [here](https://github.com/saveriomiroddi/ray_tracer_challenge-progress/blob/rust_analyzer_panic/src/tuple_test.rs).

**Comment by matklad** [comment]
Seems like we no longer have expect there, so this should be ok.
