### ISSUE TITLE
VS Code: rust-analyzer failed to discover workspace

### ISSUE THREAD

**Issue by Trapacid** [rust-analyzer/rust-analyzer#6533]
Hello! I'm trying to use the VS Code extension, but I get this error after downloading the server binary:
`rust-analyzer failed to discover workspace`
I'm currently on macOS Catalina 10.15.7 and I do not have the official Rust extension installed.

Looking at the output of Rust Analyzer Client doesn't help much:
```
INFO [11/11/2020, 3:33:24 PM]: Extension version: 0.2.376
INFO [11/11/2020, 3:33:24 PM]: Using configuration {
  lruCapacity: null,
  files: { watcher: 'client', exclude: [] },
  notifications: { cargoTomlNotFound: true },
  cargo: {
    autoreload: true,
    noDefaultFeatures: false,
    allFeatures: false,
    features: [],
    loadOutDirsFromCheck: false,
    target: null
  },
  rustfmt: { extraArgs: [], overrideCommand: null },
  checkOnSave: {
    enable: true,
    extraArgs: [],
    command: 'check',
    overrideCommand: null,
    allTargets: true,
    noDefaultFeatures: null,
    allFeatures: null,
    features: null,
    target: null
  },
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    typeHints: true,
    chainingHints: true,
    parameterHints: true,
    maxLength: 20
  },
  completion: {
    addCallParenthesis: true,
    addCallArgumentSnippets: true,
    postfix: { enable: true }
  },
  callInfo: { full: true },
  updates: { channel: 'stable', askBeforeDownload: true },
  serverPath: null,
  trace: { server: 'off', extension: false },
  procMacro: { enable: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  lens: {
    enable: true,
    run: true,
    debug: true,
    implementations: true,
    methodReferences: false
  },
  hoverActions: {
    enable: true,
    implementations: true,
    run: true,
    debug: true,
    gotoTypeDef: true
  },
  linkedProjects: null,
  withSysroot: true,
  diagnostics: {
    enable: true,
    enableExperimental: true,
    disabled: [],
    warningsAsInfo: [],
    warningsAsHint: []
  },
  assist: { importMergeBehaviour: 'full', importPrefix: 'plain' },
  runnables: { overrideCargo: null, cargoExtraArgs: [] }
}
INFO [11/11/2020, 3:33:24 PM]: PersistentState: {
  lastCheck: 1605126120041,
  releaseId: 33761860,
  serverVersion: '0.2.376'
}
INFO [11/11/2020, 3:33:24 PM]: Using server binary at /Users/ashleyz/Library/Application Support/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-mac
WARN [11/11/2020, 3:33:38 PM]: LSP request timed out {
  method: 'rust-analyzer/inlayHints',
  param: {
    textDocument: {
      uri: 'file:///Users/ashleyz/rustpain/passwordgen/password_gen.rs'
    }
  },
  error: [ResponseError: Rust Analyzer is still loading...
  	at handleResponse (/Users/ashleyz/.vscode/extensions/matklad.rust-analyzer-0.2.376/out/src/main.js:3904:48)
  	at processMessageQueue (/Users/ashleyz/.vscode/extensions/matklad.rust-analyzer-0.2.376/out/src/main.js:3719:17)
  	at Immediate.<anonymous> (/Users/ashleyz/.vscode/extensions/matklad.rust-analyzer-0.2.376/out/src/main.js:3703:13)
  	at processImmediate (internal/timers.js:439:21)] {
    code: -32801,
    data: undefined
  }
}
```

I've checked if I have the variable `RUST_SRC_PATH` set at all and I don't.
```
 ~                                                                 at 15:28:59
> echo $RUST_SRC_PATH

```

Any ideas?

**Comment by Trapacid** [comment]
Found the issue. I guess you need to create a new project with `cargo` beforehand.

Maybe for new users this should be mentioned in the output of Rust Analyzer Client or the docs?

**Comment by bjorn3** [comment]
Do you have a `Cargo.toml` file at the root of your project?

**Comment by guillem** [comment]
Man, this sucks when you're a beginner because most books, courses, tutorials, etc. will give you a GIT repository with dozens of small projects inside, but without a Cargo.toml in the root xD
