### ISSUE TITLE
Panic when trying to rename a local variable

### ISSUE THREAD

**Issue by jyn514** [rust-analyzer/rust-analyzer#6560]
```
thread '<unnamed>' panicked at 'expected substs of len 1, got Substs([Apply(ApplicationTy { ctor: Adt(EnumId(EnumId(524))), parameters: Substs([]) }), Apply(ApplicationTy { ctor: Adt(StructId(StructId(234))), parameters: Substs([]) })])', crates/hir_ty/src/lib.rs:397:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: std::panicking::begin_panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:429
   2: hir_ty::infer::pat::<impl hir_ty::infer::InferenceContext>::infer_pat
   3: hir_ty::infer::pat::<impl hir_ty::infer::InferenceContext>::infer_pat
   4: hir_ty::infer::pat::<impl hir_ty::infer::InferenceContext>::infer_pat
   5: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
   6: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
   7: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
   8: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
   9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
  10: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_method_call
  11: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  12: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  13: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  14: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  15: hir_ty::infer::infer_query
  16: salsa::runtime::Runtime::execute_query_implementation
  17: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  18: salsa::derived::slot::Slot<Q,MP>::read
  19: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  20: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  21: hir_ty::db::infer_wait
  22: hir_ty::diagnostics::validate_body
  23: hir::code_model::Module::diagnostics
  24: ide::diagnostics::diagnostics
  25: ide::Analysis::diagnostics
  26: rust_analyzer::handlers::handle_code_action
  27: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: rust-analyzer/inlayHints InlayHintsParams {
    text_document: TextDocumentIdentifier {
        uri: "file:///home/joshua/rustc/src/librustdoc/clean/inline.rs",
    },
}

thread '<unnamed>' panicked at 'expected substs of len 1, got Substs([Apply(ApplicationTy { ctor: Adt(EnumId(EnumId(524))), parameters: Substs([]) }), Apply(ApplicationTy { ctor: Adt(StructId(StructId(234))), parameters: Substs([]) })])', crates/hir_ty/src/lib.rs:397:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: std::panicking::begin_panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:429
   2: hir_ty::infer::pat::<impl hir_ty::infer::InferenceContext>::infer_pat
   3: hir_ty::infer::pat::<impl hir_ty::infer::InferenceContext>::infer_pat
   4: hir_ty::infer::pat::<impl hir_ty::infer::InferenceContext>::infer_pat
   5: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
   6: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
   7: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
   8: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
   9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
  10: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_method_call
  11: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  12: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  13: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  14: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  15: hir_ty::infer::infer_query
  16: salsa::runtime::Runtime::execute_query_implementation
  17: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  18: salsa::derived::slot::Slot<Q,MP>::read
  19: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  20: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  21: hir_ty::db::infer_wait
  22: hir::source_analyzer::SourceAnalyzer::new_for_body
  23: hir::semantics::SemanticsImpl::analyze2
  24: hir::semantics::SemanticsImpl::scope
  25: ide::inlay_hints::inlay_hints
  26: ide::Analysis::inlay_hints
  27: rust_analyzer::handlers::handle_inlay_hints
  28: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 1:55:31 PM] Request textDocument/prepareRename failed.
  Message: No references found at position
  Code: -32603 
```

This happened while trying to rename the `inner` variable at https://github.com/jyn514/rust/blob/2d2ba508a2a2c29c3be32b25341ffdf79e31922d/src/librustdoc/clean/mod.rs#L1288. I have not yet tried to reproduce the bug in something smaller.

**Comment by jyn514** [comment]
I did confirm that closing and re-opening VSCode reproduced the bug, so hopefully this is at least reproducible even if it's not an MCVE.

**Comment by jonas-schievink** [comment]
Hmm, I just got this, which might be related:

```
Panic context:
> request: textDocument/semanticTokens/full/delta SemanticTokensDeltaParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: "file:///home/jonas/dev/bxcan/src/registers.rs",
    },
    previous_result_id: "4155",
}

thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/chalk-ir-0.37.0/src/fold/subst.rs:62:19
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::panicking::panic_bounds_check
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:62
   3: <chalk_ir::fold::subst::Subst<I> as chalk_ir::fold::Folder<I>>::fold_free_var_ty
   4: <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I,TI>>::super_fold_with
   5: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I,TI> for chalk_ir::GenericArg<I>>::fold_with
   6: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
   7: core::iter::adapters::process_results
   8: <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I,TI>>::super_fold_with
   9: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I,TI> for chalk_ir::GenericArg<I>>::fold_with
  10: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  11: core::iter::adapters::process_results
  12: chalk_ir::_DERIVE_chalk_ir_fold_Fold_I_TI_FOR_WhereClause::<impl chalk_ir::fold::Fold<I,_TI> for chalk_ir::WhereClause<I>>::fold_with
  13: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I,TI> for &T>::fold_with
  14: chalk_solve::clauses::builder::ClauseBuilder<I>::push_binders
  15: chalk_solve::clauses::dyn_ty::build_dyn_self_ty_clauses
  16: chalk_solve::clauses::program_clauses_that_could_match
  17: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  18: <chalk_recursive::recursive::RecursiveSolver<I> as chalk_solve::solve::Solver<I>>::solve_limited
  19: hir_ty::traits::solve::{{closure}}
  20: hir_ty::traits::trait_solve_query
  21: salsa::runtime::Runtime::execute_query_implementation
  22: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  23: salsa::derived::slot::Slot<Q,MP>::read
  24: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  25: salsa::QueryTable<Q>::get
  26: <DB as hir_ty::db::HirDatabase>::trait_solve::__shim
  27: <DB as hir_ty::db::HirDatabase>::trait_solve
  28: hir_ty::method_resolution::implements_trait_unique
  29: hir::code_model::Type::impls_fnonce
  30: ide::syntax_highlighting::highlight_def
  31: ide::syntax_highlighting::highlight_element
  32: ide::syntax_highlighting::highlight
  33: ide::Analysis::highlight
  34: rust_analyzer::handlers::handle_semantic_tokens_full_delta
  35: <F as threadpool::FnBox>::call_box
```

**Comment by yotamofek** [comment]
Here's an MCVE,
Seems to trigger the same exception, though I'm not sure it share the root cause with this issue. Also, it requires use of the nightly `box_patterns` features. The upside of this MCVE is that it happens for any RLS request pertaining to this file (i.e. doesn't need to be triggered by a rename operation). The `box` seems to completely break `rust-analyzer` for me.

```
#![feature(box_patterns)]

pub struct A {
    a: ()
}

pub enum B {
    A(Box<A>)
}

pub fn test(b: B) {
    match &b {
        B::A(box A { a: _ }) => {
            todo!();
        }
    };
}
```

**Comment by jyn514** [comment]
Rustdoc definitely uses `box_patterns`, so it might be the same root cause.

**Comment by jonas-schievink** [comment]
Not my code, so I guess it's a different issue
