### ISSUE TITLE
add_missing_impl_members panic

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#6593]
```rust
trait Foo<T> {
    fn foo(&self, t: T);
}

impl Foo for u32 {
    <|>
}
```
Note the missing type parameter.
Trying to trigger code actions in the above code results in:
```
Panic context:
> request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            host: None,
            port: None,
            path: "/home/florian/Projekte/opensource/rust-analyzer/crates/hir_ty/src/traits/chalk.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 360,
            character: 3,
        },
        end: Position {
            line: 360,
            character: 3,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'Failed to make ast node `syntax::ast::generated::nodes::Type` from text impl {unknown} for D {};', crates/syntax/src/ast/make.rs:445:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
   2: syntax::ast::make::ast_from_text
   3: syntax::ast::make::ty
   4: <hashbrown::map::HashMap<K,V,S> as core::iter::traits::collect::Extend<(K,V)>>::extend
   5: assists::ast_transform::SubstituteTypeParams::for_trait_impl
   6: assists::utils::add_trait_assoc_items_to_impl
   7: assists::assist_context::Assists::add
   8: assists::handlers::add_missing_impl_members::add_missing_impl_members_inner
   9: assists::Assist::resolved
  10: std::panicking::try
  11: ide::Analysis::resolved_assists
  12: rust_analyzer::handlers::handle_code_action
  13: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
This probably just requires a check somewhere that makes the code action not apply in this case (or alternatively don't try to substitute?)

**Comment by kinnison** [comment]
I tested this just now with master (53e2cdf18e155ad61262fed5dcd3d73ef343c042) and rather than panicing, It expanded as:

```rust
trait Foo<T> {
    fn foo(&self, t: T);
}

impl Foo for u32 {
    fn foo(&self, t: T) {
        ${0:todo!()}
    }
}
```

Obviously not ideal, but also not panicing.

**Comment by Veykril** [comment]
The `${0:todo!()}` comes from a bug in the vscode extension which has already been fixed but since you probably run the stable extension with the master server you still have that output there.

**Comment by kinnison** [comment]
Aha, okay, so given that, is this issue effectively already solved?

**Comment by flodiebold** [comment]
Yeah, seems it got fixed somewhere along the way.
