### ISSUE TITLE
registering process handler panic when movig file to folder

### ISSUE THREAD

**Issue by Kungitoo** [rust-analyzer/rust-analyzer#6741]
Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

WHEN: Moving test.rs file into test folder 

![image](https://user-images.githubusercontent.com/6378638/101349493-bc8f8a80-388d-11eb-98d8-8826b006e306.png)

Cannot repro

```
[Error - 10:42:31 AM] Registering progress handler for token rustAnalyzer/indexing failed.
Error: Progress handler for token rustAnalyzer/indexing already registered
	at Object.onProgress (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:4302:23)
	at LanguageClient.onProgress (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:11915:45)
	at new ProgressPart (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:9950:41)
	at createHandler (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:13237:34)
	at handleRequest (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:3832:41)
	at processMessageQueue (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:3713:17)
	at Immediate._onImmediate (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:3703:13)
	at processImmediate (internal/timers.js:439:21)
	at process.topLevelDomainCallback (domain.js:130:23)
Warning: Unknown configuration option `single_line_if_else_max_width`
Warning: Unknown configuration option `single_line_if_else_max_width`
Warning: Unknown configuration option `single_line_if_else_max_width`
thread '<unnamed>' panicked at 'no value set for FileTextQuery(FileId(6478))', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.0/src/input.rs:104:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
   2: <salsa::input::InputStorage<Q> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch::{{closure}}
   3: <salsa::input::InputStorage<Q> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   4: <DB as base_db::SourceDatabaseExt>::file_text::__shim
   5: salsa::runtime::Runtime::execute_query_implementation
   6: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   7: salsa::derived::slot::Slot<Q,MP>::read
   8: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   9: <DB as ide_db::LineIndexDatabase>::line_index::__shim
  10: ide::Analysis::file_line_index
  11: rust_analyzer::handlers::publish_diagnostics
  12: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  13: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
  14: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Warning: Unknown configuration option `single_line_if_else_max_width`
[Error - 11:49:47 AM] Registering progress handler for token rustAnalyzer/indexing failed.
Error: Progress handler for token rustAnalyzer/indexing already registered
	at Object.onProgress (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:4302:23)
	at LanguageClient.onProgress (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:11915:45)
	at new ProgressPart (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:9950:41)
	at createHandler (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:13237:34)
	at handleRequest (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:3832:41)
	at processMessageQueue (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:3713:17)
	at Immediate._onImmediate (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:3703:13)
	at processImmediate (internal/timers.js:439:21)
	at process.topLevelDomainCallback (domain.js:130:23)
[Error - 11:49:50 AM] Registering progress handler for token rustAnalyzer/indexing failed.
Error: Progress handler for token rustAnalyzer/indexing already registered
	at Object.onProgress (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:4302:23)
	at LanguageClient.onProgress (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:11915:45)
	at new ProgressPart (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:9950:41)
	at createHandler (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:13237:34)
	at handleRequest (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:3832:41)
	at processMessageQueue (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:3713:17)
	at Immediate._onImmediate (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:3703:13)
	at processImmediate (internal/timers.js:439:21)
	at process.topLevelDomainCallback (domain.js:130:23)
[Error - 11:49:52 AM] Registering progress handler for token rustAnalyzer/indexing failed.
Error: Progress handler for token rustAnalyzer/indexing already registered
	at Object.onProgress (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:4302:23)
	at LanguageClient.onProgress (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:11915:45)
	at new ProgressPart (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:9950:41)
	at createHandler (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:13237:34)
	at handleRequest (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:3832:41)
	at processMessageQueue (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:3713:17)
	at Immediate._onImmediate (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:3703:13)
	at processImmediate (internal/timers.js:439:21)
	at process.topLevelDomainCallback (domain.js:130:23)
[Error - 11:49:53 AM] Registering progress handler for token rustAnalyzer/indexing failed.
Error: Progress handler for token rustAnalyzer/indexing already registered
	at Object.onProgress (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:4302:23)
	at LanguageClient.onProgress (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:11915:45)
	at new ProgressPart (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:9950:41)
	at createHandler (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:13237:34)
	at handleRequest (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:3832:41)
	at processMessageQueue (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:3713:17)
	at Immediate._onImmediate (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:3703:13)
	at processImmediate (internal/timers.js:439:21)
	at process.topLevelDomainCallback (domain.js:130:23)
thread '<unnamed>' panicked at 'no value set for FileTextQuery(FileId(6483))', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.0/src/input.rs:104:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
   2: <salsa::input::InputStorage<Q> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch::{{closure}}
   3: <salsa::input::InputStorage<Q> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   4: <DB as base_db::SourceDatabaseExt>::file_text::__shim
   5: salsa::runtime::Runtime::execute_query_implementation
   6: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   7: salsa::derived::slot::Slot<Q,MP>::read
   8: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   9: <DB as ide_db::LineIndexDatabase>::line_index::__shim
  10: ide::Analysis::file_line_index
  11: rust_analyzer::handlers::publish_diagnostics
  12: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  13: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
  14: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: textDocument/completion CompletionParams {
    text_document_position: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                host: None,
                port: None,
                path: "/home/divosevic/git/ae/src/alerting/src/influx/mod.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 0,
            character: 2,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    context: Some(
        CompletionContext {
            trigger_kind: Invoked,
            trigger_character: None,
        },
    ),
}

thread '<unnamed>' panicked at 'assertion failed: source_range.intersect(indel.delete).is_none()', crates/rust-analyzer/src/to_proto.rs:187:13
stack backtrace:
   0: std::panicking::begin_panic
   1: rust_analyzer::to_proto::completion_item
   2: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
   3: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
   4: rust_analyzer::handlers::handle_completion
   5: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 12:09:12 PM] Registering progress handler for token rustAnalyzer/indexing failed.
Error: Progress handler for token rustAnalyzer/indexing already registered
	at Object.onProgress (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:4302:23)
	at LanguageClient.onProgress (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:11915:45)
	at new ProgressPart (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:9950:41)
	at createHandler (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:13237:34)
	at handleRequest (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:3832:41)
	at processMessageQueue (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:3713:17)
	at Immediate._onImmediate (/home/divosevic/.vscode-server/extensions/matklad.rust-analyzer-0.2.400/out/src/main.js:3703:13)
	at processImmediate (internal/timers.js:439:21)
	at process.topLevelDomainCallback (domain.js:130:23)

```

**Comment by lnicola** [comment]
Does it still happen with today's release?

**Comment by Kungitoo** [comment]
I didn't manage to repro it later on the same version

**Comment by lnicola** [comment]
Might have been fixed in https://github.com/rust-analyzer/rust-analyzer/pull/6701 (which was released only today).

**Comment by jonas-schievink** [comment]
Yeah this should be fixed in today's release, so closing. Please let us know if it's still an issue.
