### ISSUE TITLE
Chalk stuck

### ISSUE THREAD

**Issue by cynecx** [rust-analyzer/rust-analyzer#6812]
```rust
use std::io::{BufRead, StdinLock};

fn part1(stdin: &mut StdinLock) {
    a.map(Result::unwrap)
    .fold(arr, |(mut arr, size), line| {
        arr
    });
}
```

Stuck at 100% cpu.

rust-analyzer: 41321d96789ed918eebda02ada76758765d19d16

<details>
<summary>gdb backtrace</summary>

```
Thread 6 (Thread 0x7ff1473dc640 (LWP 36329) "rust-analyzer"):
#0  0x000055b871ba0c6b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
--Type <RET> for more, q to quit, c to continue without paging--
#1  0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#2  0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#3  0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#4  0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#5  0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#6  0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#7  0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#8  0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#9  0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#10 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#11 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#12 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#13 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#14 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#15 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#16 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#17 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#18 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#19 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#20 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#21 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#22 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#23 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
--Type <RET> for more, q to quit, c to continue without paging--
#24 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#25 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#26 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#27 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#28 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#29 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#30 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#31 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#32 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#33 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#34 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#35 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#36 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#37 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#38 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#39 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#40 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#41 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#42 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#43 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#44 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#45 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#46 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_wi--Type <RET> for more, q to quit, c to continue without paging--
th ()
#47 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#48 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#49 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#50 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#51 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#52 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#53 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#54 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#55 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#56 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#57 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#58 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#59 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#60 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#61 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#62 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#63 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#64 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#65 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#66 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#67 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#68 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
--Type <RET> for more, q to quit, c to continue without paging--c
#69 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#70 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#71 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#72 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#73 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#74 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#75 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#76 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#77 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#78 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#79 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#80 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#81 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#82 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#83 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#84 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#85 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#86 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#87 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#88 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#89 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#90 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#91 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#92 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#93 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#94 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#95 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#96 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#97 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#98 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#99 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#100 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#101 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#102 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#103 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#104 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#105 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#106 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#107 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#108 0x000055b871ba0c7b in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with ()
#109 0x000055b871bbe10a in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#110 0x000055b871ba0fe5 in chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with ()
#111 0x000055b871b93ae9 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#112 0x000055b871c4b87f in <chalk_solve::infer::canonicalize::Canonicalizer<I> as chalk_ir::fold::Folder<I>>::fold_inference_ty ()
#113 0x000055b871b93f47 in <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#114 0x000055b871b948b2 in <chalk_ir::Goal<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with ()
#115 0x000055b871b9e7fe in chalk_ir::_DERIVE_chalk_ir_fold_Fold_I_FOR_InEnvironment::<impl chalk_ir::fold::Fold<_I> for chalk_ir::InEnvironment<G>>::fold_with ()
#116 0x000055b871c3dd82 in chalk_solve::infer::canonicalize::<impl chalk_solve::infer::InferenceTable<I>>::canonicalize ()
#117 0x000055b871cc2b13 in <chalk_recursive::solve::RecursiveInferenceTableImpl<I> as chalk_recursive::fulfill::RecursiveInferenceTable<I>>::canonicalize ()
#118 0x000055b871cbdcad in chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove ()
#119 0x000055b871cbe81c in chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve ()
#120 0x000055b871c1e283 in <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal ()
#121 0x000055b871c1c1ba in <chalk_recursive::recursive::RecursiveSolver<I> as chalk_solve::solve::Solver<I>>::solve_limited ()
#122 0x000055b871b2e5ab in hir_ty::traits::trait_solve_query ()
#123 0x000055b871b24da9 in salsa::runtime::Runtime::execute_query_implementation ()
#124 0x000055b871ac6dc1 in salsa::derived::slot::Slot<Q,MP>::read_upgrade ()
#125 0x000055b871ae8240 in salsa::derived::slot::Slot<Q,MP>::read ()
#126 0x000055b871b0ce38 in <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch ()
#127 0x000055b871bd4435 in <DB as hir_ty::db::HirDatabase>::trait_solve::__shim ()
#128 0x000055b87177f3e9 in <DB as hir_ty::db::HirDatabase>::trait_solve ()
#129 0x000055b871c03805 in hir_ty::infer::InferenceContext::resolve_ty_as_possible::h41755105dd3b7cbd ()
#130 0x000055b871be79a6 in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce ()
#131 0x000055b871be9b96 in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner ()
#132 0x000055b871be72ea in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce ()
#133 0x000055b871bee99f in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner ()
#134 0x000055b871be72ea in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce ()
#135 0x000055b871bf84ff in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments ()
#136 0x000055b871bf70f1 in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_method_call ()
#137 0x000055b871be9161 in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner ()
#138 0x000055b871be6cb7 in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr ()
#139 0x000055b871be8279 in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner ()
#140 0x000055b871be72ea in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce ()
#141 0x000055b871c0134c in hir_ty::infer::infer_query ()
#142 0x000055b871b21440 in salsa::runtime::Runtime::execute_query_implementation ()
#143 0x000055b871abadb9 in salsa::derived::slot::Slot<Q,MP>::read_upgrade ()
#144 0x000055b871ae2b86 in salsa::derived::slot::Slot<Q,MP>::read ()
#145 0x000055b871b0ae8e in <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch ()
#146 0x000055b871bd32cf in <DB as hir_ty::db::HirDatabase>::infer_query::__shim ()
#147 0x000055b871798b3d in hir_ty::db::infer_wait ()
#148 0x000055b871c22edd in hir_ty::diagnostics::validate_body ()
#149 0x000055b871a76288 in hir::code_model::Module::diagnostics ()
#150 0x000055b8716ea3b9 in ide::diagnostics::diagnostics ()
#151 0x000055b8717613d3 in std::panicking::try ()
#152 0x000055b871731477 in ide::Analysis::diagnostics ()
#153 0x000055b87150d901 in rust_analyzer::handlers::publish_diagnostics ()
#154 0x000055b87152a950 in core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut ()
#155 0x000055b87143e516 in <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter ()
#156 0x000055b871419adb in <F as threadpool::FnBox>::call_box ()
#157 0x000055b87158bc65 in std::sys_common::backtrace::__rust_begin_short_backtrace::h9b7ee015a3f59630 ()
#158 0x000055b871589f26 in core::ops::function::FnOnce::call_once{{vtable-shim}} ()
#159 0x000055b87204dc3a in alloc::boxed::{{impl}}::call_once<(),FnOnce<()>,alloc::alloc::Global> () at /rustc/f0f68778f798d6d34649745b41770829b17ba5b8/library/alloc/src/boxed.rs:1328
#160 alloc::boxed::{{impl}}::call_once<(),alloc::boxed::Box<FnOnce<()>, alloc::alloc::Global>,alloc::alloc::Global> () at /rustc/f0f68778f798d6d34649745b41770829b17ba5b8/library/alloc/src/boxed.rs:1328
#161 std::sys::unix::thread::{{impl}}::new::thread_start () at library/std/src/sys/unix/thread.rs:71
#162 0x00007ff147efe3e9 in start_thread () from /usr/lib/libpthread.so.0
#163 0x00007ff147ce6293 in clone () from /usr/lib/libc.so.6
```

</details>

**Comment by cynecx** [comment]
Related https://github.com/rust-analyzer/rust-analyzer/issues/6945. I can confirm that https://github.com/rust-lang/chalk/issues/667 fixes this.
