### ISSUE TITLE
"unresolved import" and other errors with bindgen on remote workspaces

### ISSUE THREAD

**Issue by dfarley1** [rust-analyzer/rust-analyzer#6899]
I'm using bindgen and cbindgen in unison to create C->Rust->C bindings for our project so we can start using Rust. I finally got the build happy and everything works, but in VSCode I'm getting "unresolved import" errors in my Rust files for all imports coming from bindgen. For example, the line `use crate::bindings::foo;` claims that `foo` is unresolved.

Similar to #6289 I'm using an `include!` macro to bring in stuff from bindgen:
```
include!(concat!(env!("OUT_DIR"), "/rust_bindgen.rs"));
```

From that issue I tried enabling the correct extension settings:
```
...
        "[rust]": {"editor.formatOnSave": true},
        "rust-analyzer.linkedProjects": [
            "/depot/project/rust/Cargo.toml"
        ],
        "rust-analyzer.cargo.loadOutDirsFromCheck": true,
        "rust-analyzer.procMacro.enable": true,
        "rust-analyzer.debug.engine": "ms-vscode.cpptools",
        "rust-analyzer.debug.openDebugPane": true,
        "rust-analyzer.rustfmt.extraArgs": ["--config-path", "/depot/build/rustfmt.toml"],
...
```

But the issue persists. I'm running VSCode attached to a Container running on a remote host (using the VSCode Remote Container extenion). I'm getting the following panic from `Rust Analyzer Language Server` log:
```
thread 'main' panicked at 'internal error: entered unreachable code', crates/proc_macro_srv/src/proc_macro/bridge/mod.rs:256:5
stack backtrace:
   0: std::panicking::begin_panic
   1: <proc_macro_srv::proc_macro::bridge::api_tags::Method as proc_macro_srv::proc_macro::bridge::rpc::DecodeMut<S>>::decode
   2: <proc_macro_srv::proc_macro::bridge::server::Dispatcher<proc_macro_srv::proc_macro::bridge::server::MarkedTypes<S>> as proc_macro_srv::proc_macro::bridge::server::DispatcherTrait>::dispatch
   3: <proc_macro_srv::proc_macro::bridge::closure::Closure<A,R> as core::convert::From<&mut F>>::from::call
   4: proc_macro::bridge::scoped_cell::ScopedCell<T>::replace
   5: std::thread::local::LocalKey<T>::with
   6: <proc_macro2::imp::TokenStream as core::iter::traits::collect::IntoIterator>::into_iter
             at /home/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.24/src/wrapper.rs:292
   7: proc_macro2::token_stream::<impl core::iter::traits::collect::IntoIterator for proc_macro2::TokenStream>::into_iter
             at /home/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.24/src/lib.rs:1229
   8: syn::buffer::TokenBuffer::inner_new
             at /home/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.54/src/buffer.rs:53
   9: syn::buffer::TokenBuffer::new2
             at /home/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.54/src/buffer.rs:112
  10: <F as syn::parse::Parser>::parse2
             at /home/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.54/src/parse.rs:1207
  11: syn::parse::Parser::parse
             at /home/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.54/src/parse.rs:1161
  12: syn::parse_macro_input::parse
             at /home/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.54/src/parse_macro_input.rs:139
  13: serde_derive::derive_deserialize
             at /home/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.118/src/lib.rs:89
  14: core::ops::function::FnOnce::call_once
             at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libcore/ops/function.rs:232
  15: proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run::{{closure}}
             at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libproc_macro/bridge/client.rs:394
  16: proc_macro::bridge::client::run_client::{{closure}}::{{closure}}
             at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libproc_macro/bridge/client.rs:362
  17: proc_macro::bridge::scoped_cell::ScopedCell<T>::set::{{closure}}
             at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libproc_macro/bridge/scoped_cell.rs:79
  18: proc_macro::bridge::scoped_cell::ScopedCell<T>::replace
             at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libproc_macro/bridge/scoped_cell.rs:74
  19: proc_macro::bridge::scoped_cell::ScopedCell<T>::set
             at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libproc_macro/bridge/scoped_cell.rs:79
  20: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}
             at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libproc_macro/bridge/client.rs:310
  21: std::thread::local::LocalKey<T>::try_with
             at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libstd/thread/local.rs:262
  22: std::thread::local::LocalKey<T>::with
             at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libstd/thread/local.rs:239
  23: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter
             at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libproc_macro/bridge/client.rs:310
  24: proc_macro::bridge::client::run_client::{{closure}}
             at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libproc_macro/bridge/client.rs:355
  25: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libstd/panic.rs:318
  26: std::panicking::try::do_call
             at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libstd/panicking.rs:292
  27: __rust_maybe_catch_panic
  28: std::panicking::try
             at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libstd/panicking.rs:270
  29: std::panic::catch_unwind
             at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libstd/panic.rs:394
  30: proc_macro::bridge::client::run_client
             at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libproc_macro/bridge/client.rs:354
  31: proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run
             at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libproc_macro/bridge/client.rs:394
  32: proc_macro_srv::proc_macro::bridge::server::run_server
  33: proc_macro_srv::dylib::Expander::expand
  34: proc_macro_srv::cli::run
  35: rust_analyzer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: Rust panics must be rethrown
[ERROR proc_macro_api::process] proc macro server crashed, server process state: Ok(Some(ExitStatus(ExitStatus(134))))
```

I tried to create a minimal repro at https://github.com/dfarley1/rust_foo.

First I tried the repro locally, where the imports appear to resolve. For example hovering over `(*foo).bar` on `foo.rs:6` correctly shows that `bar` is a `c_int`, but "go to definition" (ctrl+click) on `crate::bindings::foo` gets me the following panic from `Rust Analyzer Language Server` log:
```
Panic context:
> request: textDocument/hover HoverParams {
    text_document_position_params: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                host: None,
                port: None,
                path: "/home/dan/rust_foo/rust/src/protocols/foo.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 0,
            character: 22,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
}

thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `HirFileId(MacroFile(MacroFile { macro_call_id: EagerMacro(EagerMacroId(13)) }))`,
 right: `HirFileId(FileId(FileId(870)))`', crates/hir_expand/src/lib.rs:467:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
   2: hir_expand::InFile<&rowan::api::SyntaxNode<syntax::syntax_node::RustLanguage>>::original_file_range
   3: ide::display::navigation_target::NavigationTarget::from_named
   4: <D as ide::display::navigation_target::ToNav>::to_nav
   5: ide::hover::hover
   6: std::panicking::try
   7: ide::Analysis::hover
   8: rust_analyzer::handlers::handle_hover
   9: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I copied the repo to my remote container to see what happens there and I get the same error as in my actual project: "unresolved import" on `crate::bindings::foo` and `'internal error: entered unreachable code', crates/proc_macro_srv/src/proc_macro/bridge/mod.rs:256:5`.

I've tried blowing away `target` directory in both environments as well as the entire `/home/dan/.vscode-server` in the container and restarting VSCode to make sure I'm not caching bad stuff. I'm using VSCode v1.52.0, rust-analyzer v0.2.416, and download whatever the latest language server is whenever VSCode prompts me to.

**Comment by edwin0cheng** [comment]
@dfarley1 I found that from your log , you are using rustc-1.41.1, right now we only support the latest stable version of rust, would you mind to try to update it and see if the problem is gone away ? 

And it will be nice to use nightly of rust-analyzer since we did fix some bugs related to proc-macro recently. (or waiting for next release in coming monday)

**Comment by dfarley1** [comment]
I updated to Rust v1.48 and the nightly Rust Analyzer. I'm experiencing the same issues except I'm not getting any logs from `Rust Analyzer Language Server` or the Trace (I guess I don't have it enabled though), just unresolved imports.

**Comment by edwin0cheng** [comment]
It seem to be fixed, feel free to reopen it if needed.

![bug6899](https://user-images.githubusercontent.com/11014119/110259086-d6ea1900-7fe0-11eb-8349-922e9c412372.png)
