### ISSUE TITLE
Rust Analyzer can't bootstrap after the latest update

### ISSUE THREAD

**Issue by RReverser** [rust-analyzer/rust-analyzer#7065]
After the latest extension update, getting this error in the log:

```
ERROR [28/12/2020, 15:25:54]: Bootstrap error [Error: Failed to execute c:\Users\me\AppData\Roaming\Code\User\globalStorage\matklad.rust-analyzer\rust-analyzer-x86_64-pc-windows-msvc.exe --version
	at bootstrapServer (c:\Users\me\.vscode\extensions\matklad.rust-analyzer-0.2.432\out\src\main.js:21081:15)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async bootstrap (c:\Users\me\.vscode\extensions\matklad.rust-analyzer-0.2.432\out\src\main.js:21019:18)
	at async tryActivate (c:\Users\me\.vscode\extensions\matklad.rust-analyzer-0.2.432\out\src\main.js:20940:24)
	at async activate (c:\Users\me\.vscode\extensions\matklad.rust-analyzer-0.2.432\out\src\main.js:20914:5)]
```

Looks like it tries to find `.exe` under invalid name now - it calls `rust-analyzer-x86_64-pc-windows-msvc.exe` but that folder only contains `rust-analyzer-windows.exe`.

**Comment by RReverser** [comment]
Deleting that folder and restarting the extension host seemed to help, Rust Analyzer asked whether to download a binary, I confirmed, and it downloaded it under correct name now. I suppose this will affect other users during the upgrade too though.

**Comment by lnicola** [comment]
I couldn't reproduce the problem using the following steps:

1. uninstall any existing `rust-analyzer` extension
2. reload Code
3. download the previous extension release from https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-12-21
4. install it using the "Install from VSIX" command
5. let it download the server binary
6. reload Code
7. update the extension
8. reload Code
9. let it download the new server binary

![image](https://user-images.githubusercontent.com/308347/103235411-c5cebd00-494a-11eb-8df7-ffb4d51ee41b.png)

10. reload Code

![image](https://user-images.githubusercontent.com/308347/103235427-d4b56f80-494a-11eb-8bf7-67088a3b5557.png)

Do these steps work for you?

**Comment by lnicola** [comment]
[`bootstrapServer`](https://github.com/rust-analyzer/rust-analyzer/blob/94f661c/editors/code/src/main.ts#L221) calls [`getServer`](https://github.com/rust-analyzer/rust-analyzer/blob/94f661c/editors/code/src/main.ts#L279) first, which `stat`s the binary and tries to download it.

I don't understand why it would be trying to run the correct binary without downloading it first.

**Comment by RReverser** [comment]
> download the previous extension release from 2020-12-21 (release)

Hmm, maybe I had older version before the update? Not sure if there's a way to check which versions VSCode upgraded extension from.

**Comment by RReverser** [comment]
Looking at the latest commit on that file, this change looks like a suspect: https://github.com/rust-analyzer/rust-analyzer/pull/7001/files

In particular, this bit:
```diff
-     const ext = platform === "windows" ? ".exe" : ""; 
+     const ext = platform.indexOf("-windows-") !== -1 ? ".exe" : "";
```

**Comment by RReverser** [comment]
Yeah, purely by looking at the code and recent changes, I don't understand how this could've happened, either.

Unless there was already another Rust Analyzer process trying to download the binary in parallel, and so it temporarily existed but couldn't execute yet?

Either way, seems like a weird one-off, hopefully won't happen again or for anyone else.

**Comment by hweom** [comment]
This happened to me too: 

```
INFO [7/28/2022, 10:14:52 AM]: Using server binary at /home/mikhail/.config/Code - OSS/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu
WARN [7/28/2022, 10:14:52 AM]: /home/mikhail/.config/Code - OSS/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu --version: {
  error: Error: spawnSync /home/mikhail/.config/Code - OSS/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu EACCES
      at Object.spawnSync (node:internal/child_process:1083:20)
      at spawnSync (node:child_process:821:24)
      at Yy (/home/mikhail/.vscode-oss/extensions/matklad.rust-analyzer-0.2.853/out/main.js:61:4063)
      at L0 (/home/mikhail/.vscode-oss/extensions/matklad.rust-analyzer-0.2.853/out/main.js:109:3680)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at F0 (/home/mikhail/.vscode-oss/extensions/matklad.rust-analyzer-0.2.853/out/main.js:109:1881)
      at O0 (/home/mikhail/.vscode-oss/extensions/matklad.rust-analyzer-0.2.853/out/main.js:108:3977)
      at lC (/home/mikhail/.vscode-oss/extensions/matklad.rust-analyzer-0.2.853/out/main.js:108:3808)
      at b._activate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:85:8180)
      at b._waitForDepsThenActivate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:85:8122)
      at b._initialize (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:85:7486) {
    errno: -13,
    code: 'EACCES',
    syscall: 'spawnSync /home/mikhail/.config/Code - OSS/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu',
    path: '/home/mikhail/.config/Code - OSS/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu',
    spawnargs: [ '--version' ]
  },
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
ERROR [7/28/2022, 10:14:52 AM]: Bootstrap error Error: Failed to execute /home/mikhail/.config/Code - OSS/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu --version
    at L0 (/home/mikhail/.vscode-oss/extensions/matklad.rust-analyzer-0.2.853/out/main.js:109:3922)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at F0 (/home/mikhail/.vscode-oss/extensions/matklad.rust-analyzer-0.2.853/out/main.js:109:1881)
    at O0 (/home/mikhail/.vscode-oss/extensions/matklad.rust-analyzer-0.2.853/out/main.js:108:3977)
    at lC (/home/mikhail/.vscode-oss/extensions/matklad.rust-analyzer-0.2.853/out/main.js:108:3808)
    at b._activate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:85:8180)
    at b._waitForDepsThenActivate (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:85:8122)
    at b._initialize (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:85:7486)
```

I noticed that `rust-analyzer-x86_64-unknown-linux-gnu` doesn't have executable bit set:
```
-rw-r--r-- 1 mikhail mikhail 37482712 Jul 28 10:14 rust-analyzer-x86_64-unknown-linux-gnu
```

After setting the bit and restarting VSCode, the plugin activated successfully.

**Comment by victor-girardin** [comment]
> This happened to me too:
...
> 
> After setting the bit and restarting VSCode, the plugin activated successfully.

Can confirm

```chmod +x ~/.config/Code\ -\ OSS/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu```

^ fixes the issue. This should probably by addressed.

**Comment by lnicola** [comment]
@hweom, @victor-girardin you're running a version from last year, see https://github.com/rust-lang/rust-analyzer/issues/11080.

Instead, uninstall it and download VSIX from the GitHub Release page.

**Comment by 0123cf** [comment]
emm  windows   
![image](https://github.com/rust-lang/rust-analyzer/assets/22963895/5ea08676-de80-4bce-aaa1-598e25557230)

**Comment by lnicola** [comment]
@0123cf you're running a different extension, we don't offer any support for it.
