### ISSUE TITLE
CoC + NeoVim: typing `.unwrap(` locks up UI thread

### ISSUE THREAD

**Issue by jrop** [rust-analyzer/rust-analyzer#7066]
Firstly, rust-analyzer is amazing.  Thank you for the high-quality tool!

I am using CoC + NeoVim, and strangely whenever I type `.unwrap(`, the UI thread locks up until documentation for the `unwrap()` signature is brought back, almost 10s later.  This happens on some rust-analyzer releases, but not others (which I have yet to narrow down).

```
2020-12-28T08:34:07.306 WARN (pid:22362) [events] - Handler of TextChangedI blocked more than 2s: Error
    at Events.on (/Users/jonathan/.local/share/nvim/plugged/coc.nvim/build/index.js:16529:25)
    at new Signature (/Users/jonathan/.local/share/nvim/plugged/coc.nvim/build/index.js:97241:26)
    at new Handler (/Users/jonathan/.local/share/nvim/plugged/coc.nvim/build/index.js:94469:26)
    at Plugin.init (/Users/jonathan/.local/share/nvim/plugged/coc.nvim/build/index.js:23940:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

```sh
❯ nvim --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/config -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/src -I/usr/local/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/include
Compiled by brew@Catalina

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.4/share/nvim"

Run :checkhealth for more info
❯ ~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer --version
rust-analyzer 1d53075
```

Also, in NeoVim`:CocUpdate` shows:

```
Update finished

- ✓ coc-json Current version 1.3.2 is up to date.
- ✓ coc-rust-analyzer Current version 0.24.0 is up to date.
- ✓ coc-snippets Current version 2.3.1 is up to date.
- ✓ coc-tsserver Current version 1.6.6 is up to date.
```

**Comment by NAlexPear** [comment]
I'm getting this same behavior on `.expect()` as well

**Comment by lnicola** [comment]
Does it still happen the second time you type it during the same session?

**Comment by jrop** [comment]
@lnicola yes it does, unfortunately

**Comment by lnicola** [comment]
Is that on a specific project? And can you take a LSP trace while it happens (not sure how)? Monitoring the CPU usage of vim and rust-analyzer during the hang would also be worth trying.

**Comment by GopherJ** [comment]
you can try neovim@0.5-dev to see if it's that

**Comment by lnicola** [comment]
Can't reproduce with LanguageClient-nvim.

**Comment by GopherJ** [comment]
@jrop @NAlexPear Hi, have you checked if neovim0.5-dev works for you?

**Comment by NAlexPear** [comment]
@GopherJ  Looks like the nightly neovim install (`0.5.0+dev+982+g69fc6c2de-1`) eliminates the issue I had with `.expect()` :+1:

**Comment by lnicola** [comment]
Is that still with CoC or with the native LSP client?

**Comment by jrop** [comment]
@GopherJ I just installed NeoVim 0.5, and have confirmed that the issue no longer persists.
@lnicola I am still using CoC.

I will close this issue, since it does not seem to have anything to do with rust-analyzer.  Thanks for the pointer!
