### ISSUE TITLE
No value set for FileTextQuery(FileId(0)) after clearing the database

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#7074]
Spotted on the docs.rs codebase after triggering `Memory usage`:

```
Panic context:
> request: textDocument/codeLens CodeLensParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            host: None,
            port: None,
            path: "/home/me/Projects/rust-analyzer/crates/hir_def/src/item_tree.rs",
            query: None,
            fragment: None,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'no value set for FileTextQuery(FileId(0))', /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.0/src/input.rs:104:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f0f68778f798d6d34649745b41770829b17ba5b8/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/f0f68778f798d6d34649745b41770829b17ba5b8/library/std/src/panicking.rs:435:5
   2: <salsa::input::InputStorage<Q> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch::{{closure}}
   3: <salsa::input::InputStorage<Q> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   4: <DB as base_db::SourceDatabaseExt>::file_text::__shim
   5: <ide_db::LineIndexQuery as salsa::plumbing::QueryFunction>::execute
   6: salsa::runtime::Runtime::execute_query_implementation
   7: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   8: salsa::derived::slot::Slot<Q,MP>::read
   9: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  10: <DB as ide_db::LineIndexDatabase>::line_index::__shim
  11: ide::Analysis::file_line_index
  12: rust_analyzer::handlers::handle_code_lens
  13: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: textDocument/hover HoverParams {
    text_document_position_params: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                host: None,
                port: None,
                path: "/home/me/Projects/rust-analyzer/crates/hir_def/src/item_tree.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 137,
            character: 18,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
}```

**Comment by lnicola** [comment]
Duplicate of #9168
