### ISSUE TITLE
wsl2 bootstrap error

### ISSUE THREAD

**Issue by PeterLinX** [rust-analyzer/rust-analyzer#7087]
```
ERROR [12/30/2020, 1:01:39 PM]: Bootstrap error [FetchError: request to https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/2020-12-28 failed, reason: connect ECONNREFUSED 127.0.0.1:11091
	at ClientRequest.<anonymous> (/home/peter/.vscode-server/extensions/matklad.rust-analyzer-0.2.432/out/src/main.js:20589:11)
	at ClientRequest.emit (events.js:228:7)
	at onerror (/home/peter/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node_modules/https-proxy-agent/node_modules/agent-base/index.js:101:9)
	at callbackError (/home/peter/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node_modules/https-proxy-agent/node_modules/agent-base/index.js:123:5)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)] {
  message: 'request to https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/2020-12-28 failed, reason: connect ECONNREFUSED 127.0.0.1:11091',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
```
It seems that wsl2 has some issue of network. When I open vscode, rust-analyzer is trying to fetch something and failed.

**Comment by bjorn3** [comment]
> connect ECONNREFUSED 127.0.0.1:11091

Are you using a proxy?

**Comment by PeterLinX** [comment]
> > connect ECONNREFUSED 127.0.0.1:11091
> 
> Are you using a proxy?

@bjorn3 yes, I'm using shadowsocks. I tested several times, 11091 is occupied by shadowsocks may causes this issue. Thanks a lot.

**Comment by lnicola** [comment]
It was probably stopped at that point, which would explain the error.
