### ISSUE TITLE
Panic in highlighting injection

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#7203]
![image](https://user-images.githubusercontent.com/1711539/103956985-be818d80-515a-11eb-81d1-9ddb63415f82.png)

```
Panic context:
> request: textDocument/semanticTokens/full SemanticTokensParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            host: None,
            port: None,
            path: "/home/matklad/tmp/hello/src/main.rs",
            query: None,
            fragment: None,
        },
    },
}

thread '<unnamed>' panicked at 'left: HighlightedRange {
    range: 20..47,
    highlight: Highlight {
        tag: StringLiteral,
        modifiers: HighlightModifiers(
            16,
        ),
    },
    binding_hash: None,
}, right: HighlightedRange {
    range: 29..46,
    highlight: Highlight {
        tag: Comment,
        modifiers: HighlightModifiers(
            0,
        ),
    },
    binding_hash: None,
}', crates/ide/src/syntax_highlighting.rs:392:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
   2: ide::syntax_highlighting::highlight
   3: std::panicking::try
   4: ide::Analysis::highlight
   5: rust_analyzer::handlers::handle_semantic_tokens_full
   6: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by matklad** [comment]
fixed in https://github.com/rust-analyzer/rust-analyzer/pull/7212
