### ISSUE TITLE
rust-language-server panic 

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rust-analyzer/rust-analyzer#7609]
here is the rust-analyzer-language outputChannel log:
```
Panic context:
> request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            host: None,
            port: None,
            path: "/e%3A/rust/tinylang-rs/src/interpreter/interpreter.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 0,
            character: 0,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'expected substs of len 1, got Substs([Apply(ApplicationTy { ctor: Adt(EnumId(EnumId(467))), parameters: Substs([]) }), Apply(ApplicationTy { ctor: Adt(StructId(StructId(234))), parameters: Substs([]) })])', crates\hir_ty\src\lib.rs:404:13
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: rust-analyzer/inlayHints InlayHintsParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            host: None,
            port: None,
            path: "/e%3A/rust/tinylang-rs/src/interpreter/interpreter.rs",
            query: None,
            fragment: None,
        },
    },
}

thread '<unnamed>' panicked at 'expected substs of len 1, got Substs([Apply(ApplicationTy { ctor: Adt(EnumId(EnumId(467))), parameters: Substs([]) }), Apply(ApplicationTy { ctor: Adt(StructId(StructId(234))), parameters: Substs([]) })])', crates\hir_ty\src\lib.rs:404:13
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: textDocument/documentHighlight DocumentHighlightParams {
    text_document_position_params: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                host: None,
                port: None,
                path: "/e%3A/rust/tinylang-rs/src/interpreter/interpreter.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 370,
            character: 19,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'expected substs of len 1, got Substs([Apply(ApplicationTy { ctor: Adt(EnumId(EnumId(467))), parameters: Substs([]) }), Apply(ApplicationTy { ctor: Adt(StructId(StructId(234))), parameters: Substs([]) })])', crates\hir_ty\src\lib.rs:404:13
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            host: None,
            port: None,
            path: "/e%3A/rust/tinylang-rs/src/interpreter/interpreter.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 370,
            character: 19,
        },
        end: Position {
            line: 370,
            character: 19,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'expected substs of len 1, got Substs([Apply(ApplicationTy { ctor: Adt(EnumId(EnumId(467))), parameters: Substs([]) }), Apply(ApplicationTy { ctor: Adt(StructId(StructId(234))), parameters: Substs([]) })])', crates\hir_ty\src\lib.rs:404:13
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
repo here https://github.com/IWANABETHATGUY/tinylang-rs

**Comment by IWANABETHATGUY** [comment]
only happen when i open `interpreter.rs`

**Comment by lnicola** [comment]
Minimized test case:

```rust
fn foo(expr: Option<Box<i32>>) {
    match expr {
        Some(box ref expr) => {}
        _ => {}
    }
}
```

**Comment by edwin0cheng** [comment]
triage :  no panic in above test case at 9bf7ca59e

Feel free to reopen it if needed.
