### ISSUE TITLE
Panic in proc macro expand, rust 1.5.0, analyzer 0.2.505

### ISSUE THREAD

**Issue by DanielJoyce** [rust-analyzer/rust-analyzer#7875]
Using Fake crate to fake data

Example of problematic code:

``` rust
#[derive(Serialize, Deserialize, Dummy)]
#[serde(rename_all = "camelCase")]
pub struct Project {
    #[dummy(faker = "UuidFaker")]
    pub id: Uuid,
    #[dummy(faker = "Word()")]
    pub name: String,
    #[dummy(faker = "LabelFaker")]
    pub label: String,
    pub ingestion_source: IngestionSource,
    pub risk_threshold_actions: Vec<RiskThresholdAction>,
    #[dummy(faker = "(Faker, 3..5)")]  // <<<< Problematic macro
    pub dependencies: Vec<Package>,
    pub risk_scores: RiskScores,
    pub total_risk_score_dynamics: ScoreDynamics,
    pub issues: IssuesList,
    pub issue_statuses: Vec<IssueStatusListItem>,
}
```

`Package` is another struct being included in this one.

code compiles/checks fine, I just get a warning about proc macro expansion failing in vscode and squiggles everywhere.

Log:
```
Panic context:
> request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/danieljoyce/.cargo/registry/src/github.com-1ecc6299db9ec823/uuid-0.8.2/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 0,
            character: 0,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'internal error: entered unreachable code: disjunction in conjunction', crates/cfg/src/dnf.rs:157:36
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: cfg::dnf::Conjunction::new
   3: cfg::dnf::Conjunction::new
   4: cfg::dnf::Conjunction::new
   5: cfg::dnf::DnfExpr::new
   6: <hir_def::diagnostics::InactiveCode as hir_expand::diagnostics::Diagnostic>::message
   7: hir_expand::diagnostics::DiagnosticSinkBuilder::on::{{closure}}
   8: hir_expand::diagnostics::DiagnosticSink::_push
   9: hir_def::nameres::diagnostics::DefDiagnostic::add_to
  10: hir_def::nameres::DefMap::add_diagnostics
  11: hir::code_model::Module::diagnostics
  12: ide::diagnostics::diagnostics
  13: ide::Analysis::diagnostics
  14: rust_analyzer::handlers::handle_code_action
  15: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/danieljoyce/.cargo/registry/src/github.com-1ecc6299db9ec823/uuid-0.8.2/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 260,
            character: 11,
        },
        end: Position {
            line: 260,
            character: 11,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'internal error: entered unreachable code: disjunction in conjunction', crates/cfg/src/dnf.rs:157:36
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: cfg::dnf::Conjunction::new
   3: cfg::dnf::Conjunction::new
   4: cfg::dnf::Conjunction::new
   5: cfg::dnf::DnfExpr::new
   6: <hir_def::diagnostics::InactiveCode as hir_expand::diagnostics::Diagnostic>::message
   7: hir_expand::diagnostics::DiagnosticSinkBuilder::on::{{closure}}
   8: hir_expand::diagnostics::DiagnosticSink::_push
   9: hir_def::nameres::diagnostics::DefDiagnostic::add_to
  10: hir_def::nameres::DefMap::add_diagnostics
  11: hir::code_model::Module::diagnostics
  12: ide::diagnostics::diagnostics
  13: ide::Analysis::diagnostics
  14: rust_analyzer::handlers::handle_code_action
  15: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'internal error: entered unreachable code: disjunction in conjunction', crates/cfg/src/dnf.rs:157:36
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: cfg::dnf::Conjunction::new
   3: cfg::dnf::Conjunction::new
   4: cfg::dnf::Conjunction::new
   5: cfg::dnf::DnfExpr::new
   6: <hir_def::diagnostics::InactiveCode as hir_expand::diagnostics::Diagnostic>::message
   7: hir_expand::diagnostics::DiagnosticSinkBuilder::on::{{closure}}
   8: hir_expand::diagnostics::DiagnosticSink::_push
   9: hir_def::nameres::diagnostics::DefDiagnostic::add_to
  10: hir_def::nameres::DefMap::add_diagnostics
  11: hir::code_model::Module::diagnostics
  12: ide::diagnostics::diagnostics
  13: ide::Analysis::diagnostics
  14: rust_analyzer::handlers::publish_diagnostics
  15: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  16: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
  17: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by lnicola** [comment]
Just to make sure: are you using rustc 1.5.0 and not 1.50.0?

**Comment by jonas-schievink** [comment]
Reproduction:

```toml
[dependencies]
fake = { version = "2.4.0", features = ["derive"] }
rand = "0.8.3"
```

```rust
use fake::{Dummy, Fake, Faker};

#[derive(Dummy)]
struct Project {
    #[dummy(faker = "(Faker, 3..5)")] // <<<< Problematic macro
    pub dependencies: Vec<u8>,
}
```

```
proc macro returned error: proc-macro panicked: called `Result::unwrap()` on an `Err` value: Error(\"unexpected token\")",
```

The panics in the logs are unrelated. Can you provide the source code so I can reproduce those too @DanielJoyce?

**Comment by lnicola** [comment]
@jonas-schievink is that on 1.50?

**Comment by jonas-schievink** [comment]
Yeah

**Comment by jonas-schievink** [comment]
Ah, no, nightly `(a143517d4 2021-02-16)`

**Comment by lnicola** [comment]
I can reproduce on stable (I need to edit the file first, though), so it's not a proc macro ABI issue.

**Comment by kevinmehall** [comment]
With those parentheses in the string in the attribute, this looks the same as https://github.com/rust-analyzer/rust-analyzer/issues/7810#issuecomment-791478042
