### ISSUE TITLE
chalk-ir: assertion failed: (left == right)

### ISSUE THREAD

**Issue by paulcmmrclly** [rust-analyzer/rust-analyzer#8150]
rust-analyzer: d4fa6721afacec78a750df1bb1f0e7e950eaf73c
rustc 1.52.0-nightly (3a5d45f68 2021-03-09)

Panic:

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `^1`,
 right: `^0`', /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/chalk-ir-0.60.0/src/lib.rs:2853:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f5d8117c338a788bd24abec733fd143dfceb25a0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/f5d8117c338a788bd24abec733fd143dfceb25a0/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: <&chalk_ir::SubstFolder<I,A> as chalk_ir::fold::Folder<I>>::fold_free_var_ty
   5: <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with
   6: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with
   7: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
   8: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with
   9: <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with
  10: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with
  11: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  12: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with
  13: <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with
  14: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with
  15: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  16: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with
  17: <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with
  18: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with
  19: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  20: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with
  21: <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with
  22: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with
  23: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  24: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with
  25: <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with
  26: chalk_ir::_DERIVE_chalk_ir_fold_Fold_I_FOR_DomainGoal::<impl chalk_ir::fold::Fold<I> for chalk_ir::DomainGoal<I>>::fold_with
  27: chalk_ir::_DERIVE_chalk_ir_fold_Fold_I_FOR_ProgramClauseImplication::<impl chalk_ir::fold::Fold<I> for chalk_ir::ProgramClauseImplication<I>>::fold_with
  28: chalk_solve::infer::instantiate::<impl chalk_solve::infer::InferenceTable<I>>::instantiate_binders_existentially
  29: chalk_recursive::fulfill::Fulfill<I,Solver>::new_with_clause
  30: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  31: chalk_recursive::fulfill::Fulfill<I,Solver>::prove
  32: chalk_recursive::fulfill::Fulfill<I,Solver>::solve
  33: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  34: chalk_recursive::fulfill::Fulfill<I,Solver>::prove
  35: chalk_recursive::fulfill::Fulfill<I,Solver>::solve
  36: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  37: <chalk_recursive::recursive::RecursiveSolver<I> as chalk_solve::solve::Solver<I>>::solve_limited
  38: hir_ty::traits::trait_solve_query
  39: salsa::runtime::Runtime::execute_query_implementation
  40: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  41: salsa::derived::slot::Slot<Q,MP>::read
  42: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  43: <DB as hir_ty::db::HirDatabase>::trait_solve::__shim
  44: <DB as hir_ty::db::HirDatabase>::trait_solve
  45: hir_ty::infer::InferenceContext::resolve_ty_as_possible
  46: hir_ty::infer::InferenceContext::resolve_associated_type_with_params
  47: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  48: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  49: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_method_call
  50: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  51: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  52: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  53: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  54: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
  55: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_method_call
  56: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  57: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  58: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  59: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  60: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  61: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  62: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  63: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  64: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  65: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  66: hir_ty::infer::infer_query
  67: salsa::runtime::Runtime::execute_query_implementation
  68: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  69: salsa::derived::slot::Slot<Q,MP>::read
  70: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  71: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  72: hir_ty::db::infer_wait
  73: hir::source_analyzer::SourceAnalyzer::new_for_body
  74: hir::semantics::SemanticsImpl::analyze_impl
  75: hir::semantics::SemanticsImpl::descend_into_macros
  76: ide_completion::context::CompletionContext::new
  77: ide_completion::completions
  78: std::panicking::try
  79: ide::Analysis::completions
  80: rust_analyzer::handlers::handle_completion
  81: <F as threadpool::FnBox>::call_box
```

Sorry, I am currently unable to extract a minimal reproducible example since I am getting this on internal code but I can say for sure that this is a regression.

Good: 858ad554374a8b1ad67692558a0878391abfdd86 (I am currently using that, which seems to work without panicking.)

@flodiebold Your recent changes might be the cause of this.

**Comment by flodiebold** [comment]
Yeah, that's very likely my change. If you can't provide the code, can you try to narrow it first?
1. Try `rust-analyzer analysis-stats .` on the code base, hopefully it crashes in the same way
2. See the last function name logged before the crash; confirm that `rust-analyzer analysis-stats -o {that function} .` also crashes
3. Various options, maybe you can provide just the code of that function, or you could try running with `CHALK_DEBUG=debug RA_LOG=hir_ty=debug` and provide those logs (that will probably be a lot).

The problem is that the stacktrace doesn't really give a hint where the bad data was produced for these bugs. Maybe I should add some validation of binders somewhere :thinking:

**Comment by paulcmmrclly** [comment]
`rust-analyzer analysis-stats .` does not show the last/current processed function name. How can I enable that?

**Comment by lnicola** [comment]
@paulcmmrclly try adding `-v`.

**Comment by paulcmmrclly** [comment]
@lnicola @flodiebold Thanks. I got a repro, however it has `warp` as a dependency and it not exactly that minimal and doesn't really compile because of the omitted code.

```toml
[dependencies]
warp = "0.3.0"
```

```rust
use std::{io, net::ToSocketAddrs, sync::Arc};

use warp::Filter;

pub struct State {
}

#[derive(Debug, Deserialize)]
struct Config {
}

async fn entry(config: Config) -> Result<(), io::Error> {
    let state = Arc::new(State {  });
    let with_state = warp::any().map(move || state.clone());

    // Initialize web server

    // GET /accounts
    let accounts = warp::path!("accounts")
        .and(warp::path::end())
        .and(with_state.clone())
        .and_then(v1::accounts);

    // GET /last_updated
    let last_updated = warp::path!("last_updated")
        .and(warp::path::end())
        .and(with_state.clone())
        .and_then(v1::last_updated);

    // POST /export
    let export = warp::path!("export")
        .and(warp::path::end())
        .and(with_state.clone())
        .and(warp::filters::body::json())
        .and_then(v1::export);

    // GET /
    let index = warp::get().and(warp::path::end()).map(|| "api-server");

    let post_routes = warp::post().and(export);
    let get_routes = warp::get().and(accounts.or(last_updated));

    // [GET/POST] /v1/...
    let routes = warp::path("v1").and(get_routes.or(post_routes).or(index));

    // Start server.
    warp::serve(routes).run(addr).await;

    Ok(())
}

fn main() {
    println!("Hello, world!");
}
```

**Comment by flodiebold** [comment]
That should be enough for me to be able to look into it, thanks.

**Comment by matklad** [comment]
This pretty reliably reproducec in rust-analyzer itself: 

```
> request: rust-analyzer/inlayHints InlayHintsParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/matklad/projects/rust-analyzer/crates/ide_assists/src/handlers/move_bounds.rs",
            query: None,
            fragment: None,
        },
    },
}

thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `^1`,
 right: `^0`', /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/chalk-ir-0.60.0/src/lib.rs:2853:9
stack backtrace:
```

**Comment by lnicola** [comment]
Happens on `rust-analyzer -v analysis-stats --load-output-dirs --with-proc-macro -o expand .`. This wasn't the case on Monday's release.

**Comment by flodiebold** [comment]
Hmm, I thought I checked analysis-stats, not with proc macros though...

**Comment by lnicola** [comment]
Sorry, also crashes with `rust-analyzer -v analysis-stats  -o expand .` (on the latest commit).

**Comment by jonas-schievink** [comment]
Seems like this was caused by https://github.com/rust-analyzer/rust-analyzer/pull/8136

**Comment by flodiebold** [comment]
Yeah, I knew that already ;) I basically expected some fallout of this sort from that change (which is why I'm pretty sure I checked analysis-stats -- so maybe this was some last-minute change I did :thinking: ). I'm planning to add some validation of binders so that this kind of bug gets easier to notice and fix.
