### ISSUE TITLE
ParesInt panic in proc macros

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#8270]
```
          134ms - trait_solve_query (494 calls)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }', crates/proc_macro_srv/src/rustc_server.rs:537:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: <proc_macro_srv::rustc_server::Rustc as proc_macro_srv::proc_macro::bridge::server::Literal>::integer
   4: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
   5: <proc_macro_srv::proc_macro::bridge::server::Dispatcher<proc_macro_srv::proc_macro::bridge::server::MarkedTypes<S>> as proc_macro_srv::proc_macro::bridge::server::DispatcherTrait>::dispatch
   6: <proc_macro_srv::proc_macro::bridge::closure::Closure<A,R> as core::convert::From<&mut F>>::from::call
   7: proc_macro::bridge::closure::Closure<A,R>::call
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/proc_macro/src/bridge/closure.rs:27:18
   8: proc_macro::bridge::client::Literal::integer::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/proc_macro/src/bridge/client.rs:244:25
   9: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::with::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/proc_macro/src/bridge/client.rs:336:47
  10: proc_macro::bridge::client::BridgeState::with::{{closure}}::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/proc_macro/src/bridge/client.rs:293:17
  11: proc_macro::bridge::scoped_cell::ScopedCell<T>::replace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/proc_macro/src/bridge/scoped_cell.rs:75:9
  12: proc_macro::bridge::client::BridgeState::with::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/proc_macro/src/bridge/client.rs:291:13
  13: std::thread::local::LocalKey<T>::try_with
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:272:16
  14: std::thread::local::LocalKey<T>::with
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:248:9
  15: proc_macro::bridge::client::BridgeState::with
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/proc_macro/src/bridge/client.rs:290:9
  16: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::with
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/proc_macro/src/bridge/client.rs:329:9
  17: proc_macro::bridge::client::Literal::integer
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/proc_macro/src/bridge/client.rs:237:17
  18: proc_macro::Literal::u128_unsuffixed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/proc_macro/src/lib.rs:978:21
  19: proc_macro2::imp::Literal::u128_unsuffixed
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.24/src/wrapper.rs:776:56
  20: proc_macro2::Literal::u128_unsuffixed
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.24/src/lib.rs:1018:41
  21: enumset_derive::enum_set_type_impl
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset_derive-0.5.4/src/lib.rs:247:24
  22: enumset_derive::derive_enum_set_type_0
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset_derive-0.5.4/src/lib.rs:521:12
  23: enumset_derive::derive_enum_set_type
             at /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset_derive-0.5.4/src/lib.rs:498:11
  24: core::ops::function::FnOnce::call_once
             at /home/matklad/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  25: proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run::{{closure}}
             at /home/matklad/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/proc_macro/src/bridge/client.rs:410:40
  26: proc_macro::bridge::client::run_client::{{closure}}::{{closure}}
             at /home/matklad/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/proc_macro/src/bridge/client.rs:377:26
  27: proc_macro::bridge::scoped_cell::ScopedCell<T>::set::{{closure}}
             at /home/matklad/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/proc_macro/src/bridge/scoped_cell.rs:80:33
  28: proc_macro::bridge::scoped_cell::ScopedCell<T>::replace
             at /home/matklad/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/proc_macro/src/bridge/scoped_cell.rs:75:9
  29: proc_macro::bridge::scoped_cell::ScopedCell<T>::set
             at /home/matklad/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/proc_macro/src/bridge/scoped_cell.rs:80:9
  30: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}
             at /home/matklad/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/proc_macro/src/bridge/client.rs:325:35
  31: std::thread::local::LocalKey<T>::try_with
             at /home/matklad/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  32: std::thread::local::LocalKey<T>::with
             at /home/matklad/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  33: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter
             at /home/matklad/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/proc_macro/src/bridge/client.rs:325:9
  34: proc_macro::bridge::client::run_client::{{closure}}
             at /home/matklad/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/proc_macro/src/bridge/client.rs:370:9
  35: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/matklad/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  36: std::panicking::try::do_call
             at /home/matklad/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  37: __rust_try
  38: std::panicking::try
             at /home/matklad/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  39: std::panic::catch_unwind
             at /home/matklad/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  40: proc_macro::bridge::client::run_client
             at /home/matklad/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/proc_macro/src/bridge/client.rs:369:5
  41: proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run
             at /home/matklad/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/proc_macro/src/bridge/client.rs:410:13
  42: proc_macro_srv::proc_macro::bridge::server::run_server
  43: proc_macro_srv::dylib::Expander::expand
  44: proc_macro_srv::ProcMacroSrv::expand
  45: proc_macro_srv::cli::run
  46: rust_analyzer::main
```

**Comment by matklad** [comment]
cc @edwin0cheng

**Comment by edwin0cheng** [comment]
I tested in `enumset` and this should works now.
