### ISSUE TITLE
Panic in completion/HirDisplay

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#8370]
```
Panic context:
> request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/matklad/projects/rust-analyzer/crates/rust-analyzer/src/reload.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 384,
            character: 20,
        },
        end: Position {
            line: 384,
            character: 20,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'HirDisplay failed when calling Display::fmt!', crates/hir_ty/src/display.rs:233:17
stack backtrace:
   0: std::panicking::begin_panic
   1: <hir_ty::display::HirDisplayWrapper<T> as core::fmt::Display>::fmt
   2: core::fmt::write
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
   3: <hir_ty::types::Ty as hir_ty::display::HirDisplay>::hir_fmt
   4: hir_ty::display::HirDisplay::display_source_code
   5: ide_assists::handlers::add_explicit_type::add_explicit_type
   6: ide_assists::Assist::get
   7: std::panicking::try
   8: ide::Analysis::assists
   9: rust_analyzer::handlers::handle_code_action
  10: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: textDocument/completion CompletionParams {
    text_document_position: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                username: "",
                password: None,
                host: None,
                port: None,
                path: "/home/matklad/projects/rust-analyzer/crates/rust-analyzer/src/reload.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 256,
            character: 60,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    context: Some(
        CompletionContext {
            trigger_kind: TriggerForIncompleteCompletions,
            trigger_character: None,
        },
    ),
}

thread '<unnamed>' panicked at '

Failed to lookup BLOCK_EXPR@86..250 in this Semantics.
Make sure to use only query nodes, derived from this instance of Semantics.
root node:   MACRO_STMTS@0..251
known nodes: MACRO_CALL@0..49, MACRO_STMTS@0..90, SOURCE_FILE@0..18863, MACRO_STMTS@0..251, MACRO_STMTS@0..93, MACRO_STMTS@0..62

', crates/hir/src/semantics.rs:634:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:435:5
   2: hir::semantics::SemanticsImpl::find_file::{{closure}}
   3: hir::semantics::SemanticsImpl::find_file
   4: hir::semantics::SemanticsImpl::analyze_impl
   5: hir::semantics::SemanticsImpl::scope
   6: ide_db::helpers::import_assets::ImportAssets::search_for
   7: ide_db::helpers::import_assets::ImportAssets::search_for_imports
   8: ide_completion::completions::flyimport::import_on_the_fly
   9: ide_completion::completions
  10: std::panicking::try
  11: ide::Analysis::completions
  12: rust_analyzer::handlers::handle_completion
  13: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Veykril** [comment]
Been seeing the display panic on `hovering` as well, #8077
