### ISSUE TITLE
Duplicate progress

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#8509]
```
[Error - 7:33:53 PM] Registering progress handler for token rustAnalyzer/indexing failed.
Error: Progress handler for token rustAnalyzer/indexing already registered
	at Object.onProgress (/home/matklad/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/src/main.js:5384:23)
	at LanguageClient.onProgress (/home/matklad/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/src/main.js:13071:45)
	at new ProgressPart (/home/matklad/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/src/main.js:11050:41)
	at createHandler (/home/matklad/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/src/main.js:14415:34)
	at handleRequest (/home/matklad/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/src/main.js:4917:41)
	at processMessageQueue (/home/matklad/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/src/main.js:4781:17)
	at Immediate._onImmediate (/home/matklad/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/src/main.js:4771:13)
	at processImmediate (internal/timers.js:456:21)
```

**Comment by kjeremy** [comment]
We don't honor cancellation and are probably running into that.

**Comment by matklad** [comment]
@kjeremy do you mean this is pre-existing and not a regression due to changes on our side?

**Comment by lnicola** [comment]
CC https://github.com/rust-analyzer/rust-analyzer/issues/8414, https://github.com/rust-analyzer/rust-analyzer/issues/5436.

**Comment by kjeremy** [comment]
Pre-existing. We need to support WorkDoneProgressCancel.

See #6782
