### ISSUE TITLE
rust-analyzer freezes and panics with cycle error

### ISSUE THREAD

**Issue by programmerjake** [rust-analyzer/rust-analyzer#8757]
Running in VSCode on https://salsa.debian.org/Kazan-team/vector-math/-/tree/rust-analyzer-cycle-error

rust-analyzer a3e5dcc

```
thread '<unnamed>' panicked at 'Internal error, cycle detected:

DatabaseKeyIndex { group_index: 7, query_index: 11, key_index: 732 }
DatabaseKeyIndex { group_index: 7, query_index: 9, key_index: 49 }
', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.0/src/lib.rs:490:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
   2: salsa::QueryTable<Q>::get::{{closure}}
   3: <DB as hir_ty::db::HirDatabase>::generic_defaults::__shim
   4: <DB as hir_ty::db::HirDatabase>::generic_defaults
   5: hir_ty::lower::substs_from_path_segment
   6: hir_ty::lower::<impl hir_ty::TraitRef>::from_resolved_path
   7: hir_ty::lower::<impl hir_ty::TraitRef>::from_path
   8: hir_ty::lower::<impl hir_ty::GenericPredicate>::from_type_bound
   9: hir_ty::lower::<impl hir_ty::GenericPredicate>::from_where_predicate
  10: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
  11: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
  12: <hir_ty::db::GenericPredicatesForParamQuery as salsa::plumbing::QueryFunction>::execute
  13: salsa::runtime::Runtime::execute_query_implementation
  14: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  17: <DB as hir_ty::db::HirDatabase>::generic_predicates_for_param::__shim
  18: <DB as hir_ty::db::HirDatabase>::generic_predicates_for_param
  19: hir_ty::utils::all_super_trait_refs
  20: hir_ty::utils::associated_type_by_name_including_super_traits
  21: hir_ty::lower::<impl hir_ty::Ty>::from_partly_resolved_hir_path
  22: hir_ty::lower::<impl hir_ty::Ty>::from_hir_ext
  23: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  24: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
  25: <hir_ty::db::GenericDefaultsQuery as salsa::plumbing::QueryFunction>::execute
  26: salsa::runtime::Runtime::execute_query_implementation
  27: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  28: salsa::derived::slot::Slot<Q,MP>::read
  29: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  30: <DB as hir_ty::db::HirDatabase>::generic_defaults::__shim
  31: <DB as hir_ty::db::HirDatabase>::generic_defaults
  32: hir_ty::lower::substs_from_path_segment
  33: hir_ty::lower::<impl hir_ty::TraitRef>::from_resolved_path
  34: hir_ty::lower::<impl hir_ty::TraitRef>::from_path
  35: <hir_ty::db::ImplTraitQuery as salsa::plumbing::QueryFunction>::execute
  36: salsa::runtime::Runtime::execute_query_implementation
  37: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  38: salsa::derived::slot::Slot<Q,MP>::read
  39: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  40: <DB as hir_ty::db::HirDatabase>::impl_trait::__shim
  41: <DB as hir_ty::db::HirDatabase>::impl_trait
  42: hir_ty::method_resolution::TraitImpls::trait_impls_in_crate_query
  43: salsa::runtime::Runtime::execute_query_implementation
  44: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  45: salsa::derived::slot::Slot<Q,MP>::read
  46: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  47: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate::__shim
  48: hir_ty::method_resolution::TraitImpls::trait_impls_in_deps_query
  49: salsa::runtime::Runtime::execute_query_implementation
  50: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  51: salsa::derived::slot::Slot<Q,MP>::read
  52: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  53: <DB as hir_ty::db::HirDatabase>::trait_impls_in_deps::__shim
  54: hir_ty::traits::chalk::<impl chalk_solve::RustIrDatabase<hir_ty::traits::chalk::interner::Interner> for hir_ty::traits::ChalkContext>::impls_for_trait
  55: chalk_solve::clauses::program_clauses_for_goal
  56: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  57: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  58: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  59: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  60: <chalk_recursive::recursive::RecursiveSolver<I> as chalk_solve::solve::Solver<I>>::solve_limited
  61: hir_ty::traits::solve::{{closure}}
  62: hir_ty::traits::trait_solve_query
  63: salsa::runtime::Runtime::execute_query_implementation
  64: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  65: salsa::derived::slot::Slot<Q,MP>::read
  66: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  67: salsa::QueryTable<Q>::get
  68: <DB as hir_ty::db::HirDatabase>::trait_solve::__shim
  69: <DB as hir_ty::db::HirDatabase>::trait_solve
  70: hir_ty::infer::InferenceContext::resolve_ty_as_possible
  71: hir_ty::infer::path::<impl hir_ty::infer::InferenceContext>::infer_path
  72: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  73: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  74: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  75: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  76: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  77: hir_ty::infer::infer_query
  78: salsa::runtime::Runtime::execute_query_implementation
  79: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  80: salsa::derived::slot::Slot<Q,MP>::read
  81: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  82: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  83: hir_ty::db::infer_wait
  84: hir_ty::diagnostics::validate_body
  85: hir::code_model::Function::diagnostics
  86: hir::code_model::Module::diagnostics
  87: ide::diagnostics::diagnostics
  88: ide::Analysis::diagnostics
  89: rust_analyzer::handlers::publish_diagnostics
  90: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            host: None,
            port: None,
            path: "/home/jacob/projects/vector-math/src/scalar.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 8,
            character: 25,
        },
        end: Position {
            line: 8,
            character: 28,
        },
    },
    context: CodeActionContext {
        diagnostics: [
            Diagnostic {
                range: Range {
                    start: Position {
                        line: 8,
                        character: 25,
                    },
                    end: Position {
                        line: 8,
                        character: 28,
                    },
                },
                severity: Some(
                    Error,
                ),
                code: Some(
                    String(
                        "E0405",
                    ),
                ),
                code_description: Some(
                    CodeDescription {
                        href: Url {
                            scheme: "https",
                            host: Some(
                                Domain(
                                    "doc.rust-lang.org",
                                ),
                            ),
                            port: None,
                            path: "/error-index.html",
                            query: None,
                            fragment: Some(
                                "E0405",
                            ),
                        },
                    },
                ),
                source: Some(
                    "rustc",
                ),
                message: "cannot find trait `Add` in this scope\nnot found in this scope",
                related_information: Some(
                    [
                        DiagnosticRelatedInformation {
                            location: Location {
                                uri: Url {
                                    scheme: "file",
                                    host: None,
                                    port: None,
                                    path: "/home/jacob/projects/vector-math/src/scalar.rs",
                                    query: None,
                                    fragment: None,
                                },
                                range: Range {
                                    start: Position {
                                        line: 0,
                                        character: 0,
                                    },
                                    end: Position {
                                        line: 0,
                                        character: 0,
                                    },
                                },
                            },
                            message: "consider importing one of these items",
                        },
                    ],
                ),
                tags: None,
                data: None,
            },
        ],
        only: Some(
            [
                CodeActionKind(
                    "quickfix",
                ),
            ],
        ),
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'Internal error, cycle detected:

DatabaseKeyIndex { group_index: 7, query_index: 11, key_index: 732 }
DatabaseKeyIndex { group_index: 7, query_index: 9, key_index: 49 }
', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.0/src/lib.rs:490:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
   2: salsa::QueryTable<Q>::get::{{closure}}
   3: <DB as hir_ty::db::HirDatabase>::generic_defaults::__shim
   4: <DB as hir_ty::db::HirDatabase>::generic_defaults
   5: hir_ty::lower::substs_from_path_segment
   6: hir_ty::lower::<impl hir_ty::TraitRef>::from_resolved_path
   7: hir_ty::lower::<impl hir_ty::TraitRef>::from_path
   8: hir_ty::lower::<impl hir_ty::GenericPredicate>::from_type_bound
   9: hir_ty::lower::<impl hir_ty::GenericPredicate>::from_where_predicate
  10: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
  11: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
  12: <hir_ty::db::GenericPredicatesForParamQuery as salsa::plumbing::QueryFunction>::execute
  13: salsa::runtime::Runtime::execute_query_implementation
  14: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  17: <DB as hir_ty::db::HirDatabase>::generic_predicates_for_param::__shim
  18: <DB as hir_ty::db::HirDatabase>::generic_predicates_for_param
  19: hir_ty::utils::all_super_trait_refs
  20: hir_ty::utils::associated_type_by_name_including_super_traits
  21: hir_ty::lower::<impl hir_ty::Ty>::from_partly_resolved_hir_path
  22: hir_ty::lower::<impl hir_ty::Ty>::from_hir_ext
  23: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  24: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
  25: <hir_ty::db::GenericDefaultsQuery as salsa::plumbing::QueryFunction>::execute
  26: salsa::runtime::Runtime::execute_query_implementation
  27: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  28: salsa::derived::slot::Slot<Q,MP>::read
  29: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  30: <DB as hir_ty::db::HirDatabase>::generic_defaults::__shim
  31: <DB as hir_ty::db::HirDatabase>::generic_defaults
  32: hir_ty::lower::substs_from_path_segment
  33: hir_ty::lower::<impl hir_ty::TraitRef>::from_resolved_path
  34: hir_ty::lower::<impl hir_ty::TraitRef>::from_path
  35: <hir_ty::db::ImplTraitQuery as salsa::plumbing::QueryFunction>::execute
  36: salsa::runtime::Runtime::execute_query_implementation
  37: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  38: salsa::derived::slot::Slot<Q,MP>::read
  39: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  40: <DB as hir_ty::db::HirDatabase>::impl_trait::__shim
  41: <DB as hir_ty::db::HirDatabase>::impl_trait
  42: hir_ty::method_resolution::TraitImpls::trait_impls_in_crate_query
  43: salsa::runtime::Runtime::execute_query_implementation
  44: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  45: salsa::derived::slot::Slot<Q,MP>::read
  46: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  47: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate::__shim
  48: hir_ty::method_resolution::TraitImpls::trait_impls_in_deps_query
  49: salsa::runtime::Runtime::execute_query_implementation
  50: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  51: salsa::derived::slot::Slot<Q,MP>::read
  52: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  53: <DB as hir_ty::db::HirDatabase>::trait_impls_in_deps::__shim
  54: hir_ty::traits::chalk::<impl chalk_solve::RustIrDatabase<hir_ty::traits::chalk::interner::Interner> for hir_ty::traits::ChalkContext>::impls_for_trait
  55: chalk_solve::clauses::program_clauses_for_goal
  56: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  57: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::prove
  58: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::solve
  59: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  60: <chalk_recursive::recursive::RecursiveSolver<I> as chalk_solve::solve::Solver<I>>::solve_limited
  61: hir_ty::traits::solve::{{closure}}
  62: hir_ty::traits::trait_solve_query
  63: salsa::runtime::Runtime::execute_query_implementation
  64: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  65: salsa::derived::slot::Slot<Q,MP>::read
  66: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  67: salsa::QueryTable<Q>::get
  68: <DB as hir_ty::db::HirDatabase>::trait_solve::__shim
  69: <DB as hir_ty::db::HirDatabase>::trait_solve
  70: hir_ty::infer::InferenceContext::resolve_ty_as_possible
  71: hir_ty::infer::path::<impl hir_ty::infer::InferenceContext>::infer_path
  72: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  73: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  74: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  75: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  76: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  77: hir_ty::infer::infer_query
  78: salsa::runtime::Runtime::execute_query_implementation
  79: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  80: salsa::derived::slot::Slot<Q,MP>::read
  81: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  82: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  83: hir_ty::db::infer_wait
  84: hir_ty::diagnostics::validate_body
  85: hir::code_model::Function::diagnostics
  86: hir::code_model::Module::diagnostics
  87: ide::diagnostics::diagnostics
  88: ide::Analysis::diagnostics
  89: rust_analyzer::handlers::handle_code_action
  90: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by flodiebold** [comment]
What version of rust-analyzer are you using?

**Comment by matklad** [comment]
> rust-analyzer a3e5dcc

that’s a pretty old version, we fixed a couple of bugs around this area recently, try updating to the latest version.

**Comment by programmerjake** [comment]
> > rust-analyzer [a3e5dcc](https://github.com/rust-analyzer/rust-analyzer/commit/a3e5dcc1778d5703a20e7f11cc0268026d121b73)
> 
> that’s a pretty old version, we fixed a couple of bugs around this area recently, try updating to the latest version.

Ah, thanks, reinstalling fixed the issue, idk why my installation stopped auto updating...
