### ISSUE TITLE
Odd panic and spurious syntax errors

### ISSUE THREAD

**Issue by vgel** [rust-analyzer/rust-analyzer#8788]
(Sorry if this is formatted wrong, never submitted an issue to RA before -- haven't needed to since it's very stable and works great usually :) )

rust-analyzer version: nightly (As of May 9th, 2021 -- rust version ` v1.54.0-nightly`)

Having a strange issue with spurious syntax errors. Manifests similarly to #4829, but with an additional panic.

![image](https://user-images.githubusercontent.com/980096/117587955-67260680-b0d5-11eb-8501-b32efc65a803.png)

Panic trace (this happens whenever I hover over one of the error locations):

```
thread '<unnamed>' panicked at 'Internal error, cycle detected:

DatabaseKeyIndex { group_index: 7, query_index: 12, key_index: 5869 }
DatabaseKeyIndex { group_index: 7, query_index: 9, key_index: 132 }
', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.0/src/lib.rs:490:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:435:5
   2: salsa::QueryTable<Q>::get::{{closure}}
   3: <DB as hir_ty::db::HirDatabase>::generic_defaults::__shim
   4: hir_ty::lower::TyLoweringContext::substs_from_path_segment
   5: hir_ty::lower::TyLoweringContext::lower_trait_ref_from_path
   6: hir_ty::lower::TyLoweringContext::lower_type_bound
   7: hir_ty::lower::TyLoweringContext::lower_where_predicate
   8: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
   9: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  10: hir_ty::lower::generic_predicates_for_param_query
  11: salsa::runtime::Runtime::execute_query_implementation
  12: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  13: salsa::derived::slot::Slot<Q,MP>::read
  14: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  15: <DB as hir_ty::db::HirDatabase>::generic_predicates_for_param::__shim
  16: hir_ty::utils::all_super_trait_refs
  17: hir_ty::utils::associated_type_by_name_including_super_traits
  18: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
  19: hir_ty::lower::TyLoweringContext::lower_ty_ext
  20: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  21: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  22: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  23: hir_ty::lower::generic_defaults_query
  24: salsa::runtime::Runtime::execute_query_implementation
  25: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  26: salsa::derived::slot::Slot<Q,MP>::read
  27: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  28: <DB as hir_ty::db::HirDatabase>::generic_defaults::__shim
  29: hir_ty::lower::TyLoweringContext::substs_from_path_segment
  30: hir_ty::lower::TyLoweringContext::lower_trait_ref_from_path
  31: hir_ty::lower::impl_trait_query
  32: salsa::runtime::Runtime::execute_query_implementation
  33: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  34: salsa::derived::slot::Slot<Q,MP>::read
  35: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  36: <DB as hir_ty::db::HirDatabase>::impl_trait::__shim
  37: <DB as hir_ty::db::HirDatabase>::impl_trait
  38: hir_ty::method_resolution::TraitImpls::trait_impls_in_crate_query
  39: salsa::runtime::Runtime::execute_query_implementation
  40: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  41: salsa::derived::slot::Slot<Q,MP>::read
  42: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  43: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate::__shim
  44: hir_ty::method_resolution::TraitImpls::trait_impls_in_deps_query
  45: salsa::runtime::Runtime::execute_query_implementation
  46: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  47: salsa::derived::slot::Slot<Q,MP>::read
  48: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  49: <DB as hir_ty::db::HirDatabase>::trait_impls_in_deps::__shim
  50: hir_ty::traits::chalk::<impl chalk_solve::RustIrDatabase<hir_ty::traits::chalk::interner::Interner> for hir_ty::traits::ChalkContext>::impls_for_trait
  51: chalk_solve::clauses::program_clauses_that_could_match
  52: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  53: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  54: <chalk_recursive::recursive::RecursiveSolver<I> as chalk_solve::solve::Solver<I>>::solve_limited
  55: hir_ty::traits::trait_solve_query
  56: salsa::runtime::Runtime::execute_query_implementation
  57: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  58: salsa::derived::slot::Slot<Q,MP>::read
  59: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  60: <DB as hir_ty::db::HirDatabase>::trait_solve::__shim
  61: <DB as hir_ty::db::HirDatabase>::trait_solve
  62: hir_ty::autoderef::deref
  63: <core::iter::sources::successors::Successors<T,F> as core::iter::traits::iterator::Iterator>::next
  64: core::iter::traits::iterator::Iterator::find_map
  65: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  66: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  67: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_method_call
  68: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  69: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  70: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_method_call
  71: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  72: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  73: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_method_call
  74: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  75: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  76: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  77: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  78: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  79: hir_ty::infer::infer_query
  80: salsa::runtime::Runtime::execute_query_implementation
  81: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  82: salsa::derived::slot::Slot<Q,MP>::read
  83: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  84: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  85: hir_ty::db::infer_wait
  86: hir::source_analyzer::SourceAnalyzer::new_for_body
  87: hir::semantics::SemanticsImpl::analyze_impl
  88: hir::semantics::SemanticsImpl::descend_into_macros
  89: ide::hover::hover
  90: base_db::CheckCanceled::catch_canceled
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/vogel/Dropbox/prog/themengi/src/main.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 7,
            character: 28,
        },
        end: Position {
            line: 7,
            character: 28,
        },
    },
    context: CodeActionContext {
        diagnostics: [
            Diagnostic {
                range: Range {
                    start: Position {
                        line: 7,
                        character: 28,
                    },
                    end: Position {
                        line: 7,
                        character: 28,
                    },
                },
                severity: Some(
                    Error,
                ),
                code: None,
                code_description: None,
                source: Some(
                    "rust-analyzer",
                ),
                message: "Syntax Error: expected COMMA",
                related_information: None,
                tags: None,
                data: None,
            },
            Diagnostic {
                range: Range {
                    start: Position {
                        line: 7,
                        character: 28,
                    },
                    end: Position {
                        line: 7,
                        character: 28,
                    },
                },
                severity: Some(
                    Error,
                ),
                code: None,
                code_description: None,
                source: Some(
                    "rust-analyzer",
                ),
                message: "Syntax Error: expected one of `*`, `::`, `{`, `self`, `super` or an identifier",
                related_information: None,
                tags: None,
                data: None,
            },
            Diagnostic {
                range: Range {
                    start: Position {
                        line: 7,
                        character: 17,
                    },
                    end: Position {
                        line: 7,
                        character: 28,
                    },
                },
                severity: Some(
                    Error,
                ),
                code: Some(
                    String(
                        "unresolved-import",
                    ),
                ),
                code_description: Some(
                    CodeDescription {
                        href: Url {
                            scheme: "https",
                            username: "",
                            password: None,
                            host: Some(
                                Domain(
                                    "rust-analyzer.github.io",
                                ),
                            ),
                            port: None,
                            path: "/manual.html",
                            query: None,
                            fragment: Some(
                                "unresolved-import",
                            ),
                        },
                    },
                ),
                source: Some(
                    "rust-analyzer",
                ),
                message: "unresolved import",
                related_information: None,
                tags: None,
                data: None,
            },
            Diagnostic {
                range: Range {
                    start: Position {
                        line: 7,
                        character: 25,
                    },
                    end: Position {
                        line: 7,
                        character: 35,
                    },
                },
                severity: Some(
                    Error,
                ),
                code: Some(
                    String(
                        "E0061",
                    ),
                ),
                code_description: Some(
                    CodeDescription {
                        href: Url {
                            scheme: "https",
                            username: "",
                            password: None,
                            host: Some(
                                Domain(
                                    "doc.rust-lang.org",
                                ),
                            ),
                            port: None,
                            path: "/error-index.html",
                            query: None,
                            fragment: Some(
                                "E0061",
                            ),
                        },
                    },
                ),
                source: Some(
                    "rustc",
                ),
                message: "this function takes 1 argument but 3 arguments were supplied\nexpected 1 argument",
                related_information: Some(
                    [
                        DiagnosticRelatedInformation {
                            location: Location {
                                uri: Url {
                                    scheme: "file",
                                    username: "",
                                    password: None,
                                    host: None,
                                    port: None,
                                    path: "/home/vogel/Dropbox/prog/themengi/src/main.rs",
                                    query: None,
                                    fragment: None,
                                },
                                range: Range {
                                    start: Position {
                                        line: 7,
                                        character: 36,
                                    },
                                    end: Position {
                                        line: 7,
                                        character: 39,
                                    },
                                },
                            },
                            message: "",
                        },
                        DiagnosticRelatedInformation {
                            location: Location {
                                uri: Url {
                                    scheme: "file",
                                    username: "",
                                    password: None,
                                    host: None,
                                    port: None,
                                    path: "/home/vogel/Dropbox/prog/themengi/src/main.rs",
                                    query: None,
                                    fragment: None,
                                },
                                range: Range {
                                    start: Position {
                                        line: 7,
                                        character: 41,
                                    },
                                    end: Position {
                                        line: 7,
                                        character: 44,
                                    },
                                },
                            },
                            message: "",
                        },
                        DiagnosticRelatedInformation {
                            location: Location {
                                uri: Url {
                                    scheme: "file",
                                    username: "",
                                    password: None,
                                    host: None,
                                    port: None,
                                    path: "/home/vogel/Dropbox/prog/themengi/src/main.rs",
                                    query: None,
                                    fragment: None,
                                },
                                range: Range {
                                    start: Position {
                                        line: 7,
                                        character: 46,
                                    },
                                    end: Position {
                                        line: 7,
                                        character: 49,
                                    },
                                },
                            },
                            message: "supplied 3 arguments",
                        },
                    ],
                ),
                tags: None,
                data: None,
            },
        ],
        only: Some(
            [
                CodeActionKind(
                    "quickfix",
                ),
            ],
        ),
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'Internal error, cycle detected:

DatabaseKeyIndex { group_index: 7, query_index: 12, key_index: 5869 }
DatabaseKeyIndex { group_index: 7, query_index: 9, key_index: 132 }
', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.0/src/lib.rs:490:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:435:5
   2: salsa::QueryTable<Q>::get::{{closure}}
   3: <DB as hir_ty::db::HirDatabase>::generic_defaults::__shim
   4: hir_ty::lower::TyLoweringContext::substs_from_path_segment
   5: hir_ty::lower::TyLoweringContext::lower_trait_ref_from_path
   6: hir_ty::lower::TyLoweringContext::lower_type_bound
   7: hir_ty::lower::TyLoweringContext::lower_where_predicate
   8: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
   9: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  10: hir_ty::lower::generic_predicates_for_param_query
  11: salsa::runtime::Runtime::execute_query_implementation
  12: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  13: salsa::derived::slot::Slot<Q,MP>::read
  14: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  15: <DB as hir_ty::db::HirDatabase>::generic_predicates_for_param::__shim
  16: hir_ty::utils::all_super_trait_refs
  17: hir_ty::utils::associated_type_by_name_including_super_traits
  18: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
  19: hir_ty::lower::TyLoweringContext::lower_ty_ext
  20: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  21: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  22: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  23: hir_ty::lower::generic_defaults_query
  24: salsa::runtime::Runtime::execute_query_implementation
  25: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  26: salsa::derived::slot::Slot<Q,MP>::read
  27: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  28: <DB as hir_ty::db::HirDatabase>::generic_defaults::__shim
  29: hir_ty::lower::TyLoweringContext::substs_from_path_segment
  30: hir_ty::lower::TyLoweringContext::lower_trait_ref_from_path
  31: hir_ty::lower::impl_trait_query
  32: salsa::runtime::Runtime::execute_query_implementation
  33: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  34: salsa::derived::slot::Slot<Q,MP>::read
  35: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  36: <DB as hir_ty::db::HirDatabase>::impl_trait::__shim
  37: <DB as hir_ty::db::HirDatabase>::impl_trait
  38: hir_ty::method_resolution::TraitImpls::trait_impls_in_crate_query
  39: salsa::runtime::Runtime::execute_query_implementation
  40: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  41: salsa::derived::slot::Slot<Q,MP>::read
  42: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  43: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate::__shim
  44: hir_ty::method_resolution::TraitImpls::trait_impls_in_deps_query
  45: salsa::runtime::Runtime::execute_query_implementation
  46: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  47: salsa::derived::slot::Slot<Q,MP>::read
  48: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  49: <DB as hir_ty::db::HirDatabase>::trait_impls_in_deps::__shim
  50: hir_ty::traits::chalk::<impl chalk_solve::RustIrDatabase<hir_ty::traits::chalk::interner::Interner> for hir_ty::traits::ChalkContext>::impls_for_trait
  51: chalk_solve::clauses::program_clauses_that_could_match
  52: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
  53: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  54: <chalk_recursive::recursive::RecursiveSolver<I> as chalk_solve::solve::Solver<I>>::solve_limited
  55: hir_ty::traits::trait_solve_query
  56: salsa::runtime::Runtime::execute_query_implementation
  57: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  58: salsa::derived::slot::Slot<Q,MP>::read
  59: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  60: <DB as hir_ty::db::HirDatabase>::trait_solve::__shim
  61: <DB as hir_ty::db::HirDatabase>::trait_solve
  62: hir_ty::autoderef::deref
  63: <core::iter::sources::successors::Successors<T,F> as core::iter::traits::iterator::Iterator>::next
  64: core::iter::traits::iterator::Iterator::find_map
  65: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  66: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  67: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_method_call
  68: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  69: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  70: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_method_call
  71: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  72: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  73: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_method_call
  74: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  75: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  76: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  77: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  78: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  79: hir_ty::infer::infer_query
  80: salsa::runtime::Runtime::execute_query_implementation
  81: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  82: salsa::derived::slot::Slot<Q,MP>::read
  83: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  84: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  85: hir_ty::db::infer_wait
  86: hir_ty::diagnostics::validate_body
  87: hir::Function::diagnostics
  88: hir::Module::diagnostics
  89: ide::diagnostics::diagnostics
  90: ide::Analysis::diagnostics
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by flodiebold** [comment]
This is a bug that should be fixed on nightly. Can you make sure you've got the current version? (Check the "Show RA version" command; if it just says "nightly" try reinstalling the extension)

**Comment by vgel** [comment]
> This is a bug that should be fixed on nightly. Can you make sure you've got the current version? (Check the "Show RA version" command; if it just says "nightly" try reinstalling the extension)

That worked, thanks! Not sure why I was on an old version, I made sure to run `rustup update` first, but when I reinstalled the extension it prompted me to download the language server anyways, so sorry about that! Thanks for the awesome software :)
