### ISSUE TITLE
thread '<unnamed>' panicked at 'internal error: entered unreachable code: Replacement

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#8809]
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/33961674/117900349-9918b200-b2fb-11eb-8969-ab1f6152817f.png">

RA crashed while working on https://github.com/parallel-finance/parallel, I just did:

```
vim runtime/parallel/src/lib.rs
```

**Comment by edwin0cheng** [comment]
The actual error :

<details>
<summary>Error Log</summary>

```log
thread '<unnamed>' panicked at 'internal error: entered unreachable code: Replacement (Replacement { current_name: Name(Text("__sp_api__input_data")), suggested_text: "__sp_api__input_data", expected_case: LowerSnakeCase }) was generated for a function parameter which was not found: InFile { file_id: HirFileId(MacroFile(MacroFile { macro_call_id: LazyMacro(LazyMacroId(58173)) })), value: Fn { syntax: FN@36454..46214 } }', crates/hir_ty/src/diagnostics/decl_check.rs:282:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:92:14
   2: hir_ty::diagnostics::decl_check::DeclValidator::validate_item
   3: hir_ty::diagnostics::validate_module_item
   4: hir::Function::diagnostics
   5: hir::Module::diagnostics
   6: hir::Module::diagnostics
   7: ide::diagnostics::diagnostics
   8: ide::Analysis::diagnostics
   9: rust_analyzer::handlers::publish_diagnostics
  10: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  11: alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  12: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 0900beeaa 2021-05-09 dev
request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/edwin/Sandbox/rust-root/bugs/parallel/runtime/parallel/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 0,
            character: 0,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}
```

</details>

It seem to be related to validate item do not handle macro generated code, but I am not so sure.

**Comment by GopherJ** [comment]
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/33961674/118077259-58499780-b3e6-11eb-945f-938355e48f4e.png">

**Comment by GopherJ** [comment]
this also happens to `rust-analyzer@2021-05-03`

**Comment by GopherJ** [comment]
hi any ideas on this? my RA crashes frequently, I tried to downgrade to 2021-05-03 but it didn't work

**Comment by edwin0cheng** [comment]
@GopherJ A minimal reproducible example will be helpful here.

**Comment by GopherJ** [comment]
@edwin0cheng indeed it just crashes frequently while working on https://github.com/parallel-finance/parallel

**Comment by GopherJ** [comment]
I think this is solved by using github release. @edwin0cheng do you know why:

```
cargo xtask --install server
```

produce a not working version comparing to github release?

**Comment by matklad** [comment]
minimal failing test:

```rust
diff --git a/Cargo.toml b/Cargo.toml
index 498cf7d62..b377b2fe9 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -24,7 +24,7 @@ miniz_oxide.opt-level = 3
 # We do want incremental release builds, but they are broken at the moment :(
 # https://github.com/rust-lang/rust/issues/85003#issuecomment-833796289
 incremental = false
-debug = 0 # Set this to 1 or 2 to get more useful backtraces in debugger.
+debug = 2 # Set this to 1 or 2 to get more useful backtraces in debugger.
 
 [profile.test]
 incremental = false
diff --git a/crates/hir_ty/src/diagnostics/decl_check.rs b/crates/hir_ty/src/diagnostics/decl_check.rs
index 075dc4131..5afa29ea2 100644
--- a/crates/hir_ty/src/diagnostics/decl_check.rs
+++ b/crates/hir_ty/src/diagnostics/decl_check.rs
@@ -1039,4 +1039,9 @@ fn qualify() {
             "#,
         )
     }
+
+    #[test]
+    fn parenthesized_parameter() {
+        check_diagnostics(r#"fn f((O): _) {}"#)
+    }
 }
```
