### ISSUE TITLE
Yet another stuck in vscode

### ISSUE THREAD

**Issue by la10736** [rust-analyzer/rust-analyzer#8849]
Updated with the last release (but also occurred before). Unfortunately this time I cannot find the root cause, but the ids stuck after some minutes.

Follow the thread stack trace from gdb of the busy process:

```
(gdb) thread apply all bt

Thread 10 (Thread 0x7f4440f16700 (LWP 62347)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00005632b46e381a in crossbeam_channel::context::Context::with::{{closure}} () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#2  0x00005632b46e2f64 in crossbeam_channel::select::run_select () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#3  0x00005632b471803b in flycheck::FlycheckActor::run () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#4  0x00005632b470b7dc in std::sys_common::backtrace::__rust_begin_short_backtrace () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#5  0x00005632b470f1b3 in core::ops::function::FnOnce::call_once{{vtable-shim}} () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#6  0x00005632b531e5aa in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/alloc/src/boxed.rs:1546
#7  <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/alloc/src/boxed.rs:1546
#8  std::sys::unix::thread::Thread::new::thread_start () at library/std/src/sys/unix/thread.rs:71
#9  0x00007f444246f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#10 0x00007f4442247293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 9 (Thread 0x7f4441318700 (LWP 62125)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00005632b538a32a in crossbeam_channel::context::Context::wait_until ()
#2  0x00005632b4f833a4 in crossbeam_channel::context::Context::with::{{closure}} () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#3  0x00005632b4f7bfc5 in proc_macro_api::process::client_loop () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#4  0x00005632b521524b in std::sys_common::backtrace::__rust_begin_short_backtrace () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#5  0x00005632b510753a in core::ops::function::FnOnce::call_once{{vtable-shim}} () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#6  0x00005632b531e5aa in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/alloc/src/boxed.rs:1546
#7  <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/alloc/src/boxed.rs:1546
#8  std::sys::unix::thread::Thread::new::thread_start () at library/std/src/sys/unix/thread.rs:71
#9  0x00007f444246f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#10 0x00007f4442247293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7f4441519700 (LWP 62114)):
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:535
#1  0x00005632b4a8504a in chalk_recursive::fulfill::Fulfill<I,Solver>::apply_solution () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#2  0x00005632b4a80906 in chalk_recursive::fulfill::Fulfill<I,Solver>::solve () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#3  0x00005632b4b480be in chalk_recursive::solve::SolveIterationHelpers::solve_from_clauses () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#4  0x00005632b4b42977 in <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#5  0x00005632b4b411e3 in <chalk_recursive::recursive::RecursiveSolver<I> as chalk_solve::solve::Solver<I>>::solve_limited () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#6  0x00005632b49b9e68 in salsa::derived::slot::Slot<Q,MP>::read_upgrade () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#7  0x00005632b4ae1aac in <DB as hir_ty::db::HirDatabase>::trait_solve_query::__shim () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#8  0x00005632b4bc896d in <DB as hir_ty::db::HirDatabase>::trait_solve_query () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#9  0x00005632b4ab9b29 in hir_ty::db::trait_solve_wait () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#10 0x00005632b4bc891d in <DB as hir_ty::db::HirDatabase>::trait_solve () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#11 0x00005632b4a59fa0 in hir_ty::infer::InferenceContext::resolve_ty_as_possible () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#12 0x00005632b4a698b4 in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#13 0x00005632b4a6b6e9 in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#14 0x00005632b4a6c93d in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_method_call () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#15 0x00005632b4a5d3c4 in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#16 0x00005632b4a69798 in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#17 0x00005632b4a67500 in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#18 0x00005632b4a5e5eb in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#19 0x00005632b4a69798 in hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#20 0x00005632b4998108 in salsa::derived::slot::Slot<Q,MP>::read_upgrade () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#21 0x00005632b4aba82c in <DB as hir_ty::db::HirDatabase>::infer_query::__shim () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#22 0x00005632b4ab985f in hir_ty::db::infer_wait () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#23 0x00005632b475e38d in hir::semantics::SemanticsImpl::analyze_impl () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#24 0x00005632b4e72a2e in ide_db::defs::NameRefClass::classify () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#25 0x00005632b4e69e98 in ide_db::search::FindUsages::search () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#26 0x00005632b4c17d69 in ide::references::find_all_refs () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
--Type <RET> for more, q to quit, c to continue without paging--c
#27 0x00005632b50fcbcd in rust_analyzer::handlers::handle_code_lens_resolve () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#28 0x00005632b5235655 in <F as threadpool::FnBox>::call_box () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#29 0x00005632b535f7ba in std::sys_common::backtrace::__rust_begin_short_backtrace ()
#30 0x00005632b53605cc in core::ops::function::FnOnce::call_once{{vtable-shim}} ()
#31 0x00005632b531e5aa in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/alloc/src/boxed.rs:1546
#32 <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/alloc/src/boxed.rs:1546
#33 std::sys::unix::thread::Thread::new::thread_start () at library/std/src/sys/unix/thread.rs:71
#34 0x00007f444246f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#35 0x00007f4442247293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7f444171a700 (LWP 62113)):
#0  __lll_lock_wait (futex=futex@entry=0x5632b6df14d0, private=0) at lowlevellock.c:52
#1  0x00007f44424720a3 in __GI___pthread_mutex_lock (mutex=0x5632b6df14d0) at ../nptl/pthread_mutex_lock.c:80
#2  0x00005632b535f29f in std::sys_common::backtrace::__rust_begin_short_backtrace ()
#3  0x00005632b53605cc in core::ops::function::FnOnce::call_once{{vtable-shim}} ()
#4  0x00005632b531e5aa in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/alloc/src/boxed.rs:1546
#5  <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/alloc/src/boxed.rs:1546
#6  std::sys::unix::thread::Thread::new::thread_start () at library/std/src/sys/unix/thread.rs:71
#7  0x00007f444246f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007f4442247293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7f444191b700 (LWP 62112)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00005632b4f4a199 in parking_lot::condvar::Condvar::wait_until_internal () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#2  0x00005632b4a8db94 in salsa::blocking_future::BlockingFuture<T>::wait () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#3  0x00005632b4aba8c6 in <DB as hir_ty::db::HirDatabase>::infer_query::__shim () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#4  0x00005632b4ab985f in hir_ty::db::infer_wait () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#5  0x00005632b475e38d in hir::semantics::SemanticsImpl::analyze_impl () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#6  0x00005632b4e72a2e in ide_db::defs::NameRefClass::classify () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#7  0x00005632b4e69e98 in ide_db::search::FindUsages::search () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#8  0x00005632b4c17d69 in ide::references::find_all_refs () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#9  0x00005632b50fcbcd in rust_analyzer::handlers::handle_code_lens_resolve () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#10 0x00005632b5235655 in <F as threadpool::FnBox>::call_box () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#11 0x00005632b535f7ba in std::sys_common::backtrace::__rust_begin_short_backtrace ()
#12 0x00005632b53605cc in core::ops::function::FnOnce::call_once{{vtable-shim}} ()
#13 0x00005632b531e5aa in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/alloc/src/boxed.rs:1546
#14 <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/alloc/src/boxed.rs:1546
#15 std::sys::unix::thread::Thread::new::thread_start () at library/std/src/sys/unix/thread.rs:71
#16 0x00007f444246f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#17 0x00007f4442247293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7f4441b1c700 (LWP 62111)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00005632b531b83a in std::sys::unix::futex::futex_wait () at library/std/src/sys/unix/futex.rs:25
#2  std::sys_common::thread_parker::futex::Parker::park () at library/std/src/sys_common/thread_parker/futex.rs:50
#3  std::thread::park () at library/std/src/thread/mod.rs:894
#4  std::sync::mpsc::blocking::WaitToken::wait () at library/std/src/sync/mpsc/blocking.rs:68
#5  0x00005632b535fced in std::sys_common::backtrace::__rust_begin_short_backtrace ()
#6  0x00005632b53605cc in core::ops::function::FnOnce::call_once{{vtable-shim}} ()
#7  0x00005632b531e5aa in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/alloc/src/boxed.rs:1546
#8  <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/alloc/src/boxed.rs:1546
#9  std::sys::unix::thread::Thread::new::thread_start () at library/std/src/sys/unix/thread.rs:71
#10 0x00007f444246f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007f4442247293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7f4441d1d700 (LWP 62110)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00005632b46e381a in crossbeam_channel::context::Context::with::{{closure}} () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#2  0x00005632b46e2f64 in crossbeam_channel::select::run_select () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#3  0x00005632b5396f5b in vfs_notify::NotifyActor::run ()
#4  0x00005632b538b413 in std::sys_common::backtrace::__rust_begin_short_backtrace ()
#5  0x00005632b538b8be in core::ops::function::FnOnce::call_once{{vtable-shim}} ()
#6  0x00005632b531e5aa in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/alloc/src/boxed.rs:1546
#7  <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/alloc/src/boxed.rs:1546
#8  std::sys::unix::thread::Thread::new::thread_start () at library/std/src/sys/unix/thread.rs:71
#9  0x00007f444246f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#10 0x00007f4442247293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f4441f1e700 (LWP 62108)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00005632b538a32a in crossbeam_channel::context::Context::wait_until ()
#2  0x00005632b4ef5168 in crossbeam_channel::context::Context::with::{{closure}} () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#3  0x00005632b4eef54d in crossbeam_channel::channel::Sender<T>::send () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#4  0x00005632b4ef6e13 in std::sys_common::backtrace::__rust_begin_short_backtrace () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#5  0x00005632b4ef78e0 in core::ops::function::FnOnce::call_once{{vtable-shim}} () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#6  0x00005632b531e5aa in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/alloc/src/boxed.rs:1546
#7  <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/alloc/src/boxed.rs:1546
#8  std::sys::unix::thread::Thread::new::thread_start () at library/std/src/sys/unix/thread.rs:71
#9  0x00007f444246f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#10 0x00007f4442247293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f444211f700 (LWP 62107)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00005632b538a32a in crossbeam_channel::context::Context::wait_until ()
#2  0x00005632b4ef4974 in crossbeam_channel::context::Context::with::{{closure}} () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#3  0x00005632b4eee569 in crossbeam_channel::channel::Receiver<T>::recv () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#4  0x00005632b4ef622c in std::sys_common::backtrace::__rust_begin_short_backtrace () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#5  0x00005632b4ef7c60 in core::ops::function::FnOnce::call_once{{vtable-shim}} () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#6  0x00005632b531e5aa in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/alloc/src/boxed.rs:1546
#7  <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/alloc/src/boxed.rs:1546
#8  std::sys::unix::thread::Thread::new::thread_start () at library/std/src/sys/unix/thread.rs:71
#9  0x00007f444246f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#10 0x00007f4442247293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f4442120a80 (LWP 62106)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00005632b4f49429 in parking_lot::raw_rwlock::RawRwLock::wait_for_readers () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#2  0x00005632b462eb43 in parking_lot::raw_rwlock::RawRwLock::lock_exclusive_slow ()
#3  0x00005632b52c8fe1 in salsa::runtime::Runtime::with_incremented_revision () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#4  0x00005632b4e0c80d in ide_db::apply_change::<impl ide_db::RootDatabase>::request_cancellation () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#5  0x00005632b4e0c99a in ide_db::apply_change::<impl ide_db::RootDatabase>::apply_change () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#6  0x00005632b51dc60f in rust_analyzer::global_state::GlobalState::process_changes () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#7  0x00005632b51cb2d2 in rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::handle_event () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#8  0x00005632b51ef70e in rust_analyzer::main_loop::main_loop () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#9  0x00005632b528cd63 in rust_analyzer::main () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#10 0x00005632b52af7c3 in std::sys_common::backtrace::__rust_begin_short_backtrace () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
#11 0x00005632b527caf6 in main () at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:143
(gdb) 
```

**Comment by la10736** [comment]
After a process kill vscode come back up and go.

**Comment by Veykril** [comment]
I don't think this is actionable as there is not much info here aside from the traces, so closing. If it pops up again feel free to open a new issue about it.
