### ISSUE TITLE
Bootstrap error [TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by quantumsheep** [rust-analyzer/rust-analyzer#9280]
In VSCode, using the latest version of Rust-Analyzer nightly, I get this error:

```
ERROR [6/15/2021, 3:02:45 AM]: Bootstrap error [TypeError: Only absolute URLs are supported
	at getNodeRequestOptions (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:20682:9)
	at /Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:20787:19
	at new Promise (<anonymous>)
	at Object.fetch (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:20784:9)
	at /Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:22713:36
	at downloadFile (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:22714:7)
	at /Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:22693:15
	at C._withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:44110)
	at C.withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:43864)
	at Object.withProgress (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:30045)
	at Object.download (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:22687:45)
	at /Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:23057:19
	at downloadWithRetryDialog (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:23095:26)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async getServer (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:23056:5)
	at async bootstrapServer (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:22957:18)
	at async bootstrap (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:22893:18)
	at async tryActivate (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:22778:24)
	at async activate (/Users/qtmsheep/.vscode/extensions/matklad.rust-analyzer-0.3.638/out/src/main.js:22769:5)]
```

This is a serious regression in nightly and it's important to fix it before the next release.
@matklad, please take a look.

**Comment by NateLing** [comment]
same

**Comment by wxb1ank** [comment]
Looks like this is a regression from #8951. Specifically, in `downloadFile()` from `/editors/code/src/net.ts`, a `vscode.Uri`'s `.path` property is mistakenly used as a URL (I think the `.toString()` method should work?). I don't immediately see any other sites where this is an issue.
