### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by zeenix** [rust-analyzer/rust-analyzer#9442]
After recently upgrading node.js, coc.nvim and rust-analyzer, rust-analyzer mostly just stopped working for me. I wasn't sure at first if this is a rust-analyzer issue or the CoC integration but after some troubleshooting, it turns out that rust-analyzer was crashing for me:

```
thread '<unnamed>' panicked at 'Internal error, cycle detected:

DatabaseKeyIndex { group_index: 7, query_index: 11, key_index: 680 }
DatabaseKeyIndex { group_index: 7, query_index: 9, key_index: 62 }
', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.0/src/lib.rs:490:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
   2: salsa::QueryTable<Q>::get::{{closure}}
   3: <DB as hir_ty::db::HirDatabase>::generic_defaults::__shim
   4: <DB as hir_ty::db::HirDatabase>::generic_defaults
   5: hir_ty::lower::substs_from_path_segment
   6: hir_ty::lower::<impl hir_ty::TraitRef>::from_resolved_path
   7: hir_ty::lower::<impl hir_ty::TraitRef>::from_path
   8: hir_ty::lower::<impl hir_ty::GenericPredicate>::from_type_bound
   9: hir_ty::lower::<impl hir_ty::GenericPredicate>::from_where_predicate
  10: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
  11: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
  12: <hir_ty::db::GenericPredicatesForParamQuery as salsa::plumbing::QueryFunction>::execute
  13: salsa::runtime::Runtime::execute_query_implementation
  14: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  17: <DB as hir_ty::db::HirDatabase>::generic_predicates_for_param::__shim
  18: <DB as hir_ty::db::HirDatabase>::generic_predicates_for_param
  19: hir_ty::utils::all_super_trait_refs
  20: hir_ty::utils::associated_type_by_name_including_super_traits
  21: hir_ty::lower::<impl hir_ty::Ty>::from_partly_resolved_hir_path
  22: hir_ty::lower::<impl hir_ty::Ty>::from_hir_ext
  23: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  24: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
  25: <hir_ty::db::GenericDefaultsQuery as salsa::plumbing::QueryFunction>::execute
  26: salsa::runtime::Runtime::execute_query_implementation
  27: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  28: salsa::derived::slot::Slot<Q,MP>::read
  29: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  30: <DB as hir_ty::db::HirDatabase>::generic_defaults::__shim
  31: <DB as hir_ty::db::HirDatabase>::generic_defaults
  32: hir_ty::lower::substs_from_path_segment
  33: hir_ty::lower::<impl hir_ty::TraitRef>::from_resolved_path
  34: hir_ty::lower::<impl hir_ty::TraitRef>::from_path
  35: <hir_ty::db::ImplTraitQuery as salsa::plumbing::QueryFunction>::execute
  36: salsa::runtime::Runtime::execute_query_implementation
  37: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  38: salsa::derived::slot::Slot<Q,MP>::read
  39: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  40: <DB as hir_ty::db::HirDatabase>::impl_trait::__shim
  41: <DB as hir_ty::db::HirDatabase>::impl_trait
  42: hir_ty::method_resolution::TraitImpls::trait_impls_in_crate_query
  43: salsa::runtime::Runtime::execute_query_implementation
  44: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  45: salsa::derived::slot::Slot<Q,MP>::read
  46: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  47: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate::__shim
  48: hir_ty::method_resolution::TraitImpls::trait_impls_in_deps_query
  49: salsa::runtime::Runtime::execute_query_implementation
  50: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  51: salsa::derived::slot::Slot<Q,MP>::read
  52: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  53: <DB as hir_ty::db::HirDatabase>::trait_impls_in_deps::__shim
  54: hir_ty::traits::chalk::<impl chalk_solve::RustIrDatabase<hir_ty::traits::chalk::interner::Interner> for hir_ty::traits::ChalkContext>::impls_for_trait
  55: chalk_solve::clauses::program_clauses_for_goal
  56: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
  57: <chalk_recursive::recursive::RecursiveSolver<I> as chalk_solve::solve::Solver<I>>::solve_limited
  58: hir_ty::traits::solve::{{closure}}
  59: hir_ty::traits::trait_solve_query
  60: salsa::runtime::Runtime::execute_query_implementation
  61: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  62: salsa::derived::slot::Slot<Q,MP>::read
  63: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  64: salsa::QueryTable<Q>::get
  65: <DB as hir_ty::db::HirDatabase>::trait_solve::__shim
  66: <DB as hir_ty::db::HirDatabase>::trait_solve
  67: hir_ty::autoderef::deref
  68: <core::iter::sources::Successors<T,F> as core::iter::traits::iterator::Iterator>::next
  69: core::iter::traits::iterator::Iterator::find_map
  70: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  71: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  72: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  73: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  74: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  75: hir_ty::infer::infer_query
  76: salsa::runtime::Runtime::execute_query_implementation
  77: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  78: salsa::derived::slot::Slot<Q,MP>::read
  79: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  80: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  81: hir_ty::db::infer_wait
  82: hir_ty::diagnostics::validate_body
  83: hir::code_model::Function::diagnostics
  84: hir::code_model::Module::diagnostics
  85: ide::diagnostics::diagnostics
  86: ide::Analysis::diagnostics
  87: rust_analyzer::handlers::publish_diagnostics
  88: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  89: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
  90: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Trace - 4:45:04 PM] Received response 'textDocument/semanticTokens/full - (1)' in 3631ms. Request failed: content modified (-32801).
[Trace - 4:45:32 PM] Sending request 'textDocument/documentHighlight - (2)'.
Params: {
    "textDocument": {
        "uri": "file:///home/zeenix/checkout/smol-rs/async-broadcast/src/lib.rs"
    },
    "position": {
        "line": 156,
        "character": 4
    }
}
```
https://github.com/smol-rs/async-broadcast is the repo I can easily reproduce this with but I think it's crashing on my machine for all projects. :(

**Comment by flodiebold** [comment]
This looks like an old crash. Can you check which RA version you're running?

**Comment by jonas-schievink** [comment]
yeah this doesn't include https://github.com/salsa-rs/salsa/pull/260, so it must be an old r-a version

**Comment by zeenix** [comment]
> yeah this doesn't include [salsa-rs/salsa#260](https://github.com/salsa-rs/salsa/pull/260), so it must be an old r-a version

Right. Turns out I had some old data files in the  `~/.config/coc/extensions/coc-rust-analyzer-data` file and somehow that was the source of the problem. I uninstalled `coc-rust-analyzer` extension, removed that directory and installed `coc-rust-analyzer` again and now everything works again.

Sorry for the noise.
