### ISSUE TITLE
Salsa cycle when evaluating block def map

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#9481]
```
Panic context:
> 
version: 266636450 2021-07-04 dev
request: rust-analyzer/inlayHints InlayHintsParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/matklad/projects/rust-analyzer/crates/rust-analyzer/src/to_proto.rs",
            query: None,
            fragment: None,
        },
    },
}

thread '<unnamed>' panicked at 'Internal error, cycle detected:

block_def_map(BlockId(332))
', /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.1/src/lib.rs:528:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:435:5
   2: salsa::QueryTable<Q>::get::{{closure}}
   3: <DB as hir_def::db::DefDatabase>::block_def_map::__shim
   4: hir_def::visibility::Visibility::is_visible_from_def_map
   5: <core::iter::adapters::cloned::Cloned<I> as core::iter::traits::iterator::Iterator>::next
   6: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   7: hir_def::nameres::collector::DefCollector::update_recursive
   8: hir_def::nameres::collector::DefCollector::record_resolved_import
   9: hir_def::nameres::collector::collect_defs
  10: hir_def::nameres::DefMap::block_def_map_query
  11: salsa::runtime::Runtime::execute_query_implementation
  12: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  13: salsa::derived::slot::Slot<Q,MP>::read
  14: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  15: <DB as hir_def::db::DefDatabase>::block_def_map::__shim
  16: hir_def::body::lower::ExprCollector::collect_block
  17: hir_def::body::lower::ExprCollector::maybe_collect_expr
  18: hir_def::body::lower::ExprCollector::collect_expr_opt
  19: hir_def::body::lower::lower
  20: hir_def::body::Body::body_with_source_map_query
  21: salsa::runtime::Runtime::execute_query_implementation
  22: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  23: salsa::derived::slot::Slot<Q,MP>::read
  24: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  25: <DB as hir_def::db::DefDatabase>::body_with_source_map::__shim
  26: hir::source_analyzer::SourceAnalyzer::new_for_body
  27: hir::semantics::SemanticsImpl::analyze_impl
  28: hir::semantics::SemanticsImpl::scope
  29: ide::inlay_hints::inlay_hints
  30: std::panicking::try
  31: ide::Analysis::inlay_hints
  32: rust_analyzer::handlers::handle_inlay_hints
  33: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by matklad** [comment]
This reproduces when I remove this closing `}` in this commit:

https://github.com/rust-analyzer/rust-analyzer/pull/9485/commits/3be9ebe2c3726c7efc77ebdddb4445f7aff4260e#diff-5432b98d7968fe0154258257763520ecf07ecc2769c9e2a55db02389f183c906R292

**Comment by jonas-schievink** [comment]
Minimized to:

```rs
fn outer() {
    mod command {
        use crate::to_proto;
    }

    mod tests {
        use super::*;
    }
}
```
