### ISSUE TITLE
cargo xtask install fails with UnhandledPromiseRejectionWanding: Canceled: Canceled

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#9615]
I'm seeing the following error on `cargo xtask install`. Running vscode 1.58.2.

> $ cmd.exe /c code.cmd --install-extension rust-analyzer.vsix --force
> Installing extensions...
> (node:9596) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> (Use `Code --trace-deprecation ...` to show where the warning was created)
> Extension 'rust-analyzer.vsix' was successfully installed.
> (node:9596) UnhandledPromiseRejectionWarning: Canceled: Canceled
>     at Object.O [as canceled] (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:5:1157)
>     at T.cancel (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:62864)
>     at T.dispose (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:63004)
>     at k.dispose (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:63266)
>     at W (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3428)
>     at d.clear (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3888)
>     at dispose (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3867)
>     at dispose (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:4402)
>     at dispose (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:11:7229)
>     at W (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3428)
>     at C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3634
>     at Object.dispose (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3706)
>     at Object.W [as dispose] (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3567)
>     at C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:14:41195
>     at Map.forEach (<anonymous>)
>     at Ne.dispose (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:14:41182)
>     at W (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3428)
>     at d.clear (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3888)
>     at dispose (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3867)
>     at a.dispose (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:4402)
>     at Object.g [as main] (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:17:51594)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async k (C:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:12:13756)
> (node:9596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:9596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lnicola** [comment]
That's Code, right? I think I saw this a couple of times after upgrading to 1.58.

**Comment by kjeremy** [comment]
Yes vscode stable.

**Comment by lnicola** [comment]
I mean, we don't run any code at extension install time, so it could be a Code bug.
