### ISSUE TITLE
rust-analyzer crashes on type inference

### ISSUE THREAD

**Issue by s1ck** [rust-analyzer/rust-analyzer#9680]
Hey, I'm trying to run rust-analyzer in vscode on linux. However it breaks and makes the plugin unusable. Any ideas are welcome. Everything works fine on M1 and x86 Mac :crying_cat_face: 

```
❯ ./rust-analyzer-x86_64-unknown-linux-gnu --version                                    
rust-analyzer ea105f939 2021-07-19 stable
```

```
❯ ./rust-analyzer-x86_64-unknown-linux-gnu analysis-stats ~/Devel/Rust/subgraph-matching
root = AbsPathBuf("/home/s1ck/Devel/Rust/subgraph-matching")
root = CargoToml(AbsPathBuf("/home/s1ck/Devel/Rust/subgraph-matching/Cargo.toml"))
Database loaded:     601.05ms, 172minstr
  crates: 4, mods: 23, decls: 159, fns: 109
Item Collection:     4.83s, 42ginstr
26/109 23% processing: order::tests::test_gql_orderthread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', crates/hir_ty/src/builder.rs:35:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed::inner
   3: core::panicking::assert_failed
   4: hir_ty::builder::TyBuilder<hir_def::AdtId>::build
   5: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
   6: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
   7: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
   8: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
   9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  10: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  11: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  12: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  13: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  14: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  15: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  16: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  17: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  18: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  19: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  20: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  21: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  22: hir_ty::infer::infer_query
  23: salsa::runtime::Runtime::execute_query_implementation
  24: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  25: salsa::derived::slot::Slot<Q,MP>::read
  26: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  27: <DB as hir_ty::db::HirDatabase>::infer_query
  28: hir_ty::db::infer_wait
  29: rust_analyzer::cli::analysis_stats::AnalysisStatsCmd::run
  30: rust_analyzer::main
```

```
❯ neofetch
            .-/+oossssoo+/-.               s1ck@sh1va 
        `:+ssssssssssssssssss+:`           ---------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.2 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Kernel: 5.4.0-80-generic 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 6 hours, 20 mins 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 2344 (dpkg), 5 (snap) 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: zsh 5.8 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Resolution: 2560x1440, 2560x1440 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   DE: MATE 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Metacity (Marco) 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM Theme: Ambiant-MATE 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Ambiant-MATE [GTK2/3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Ambiant-MATE [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: terminator 
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: AMD Ryzen 9 3950X (32) @ 3.500GHz 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: NVIDIA GeForce RTX 2070 SUPER 
    .ossssssssssssssssssdMMMNysssso.       Memory: 6627MiB / 64296MiB 
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`                                   
            .-/+oossssoo+/-.                                       

```

Can be reproduced with: https://github.com/s1ck/subgraph-matching

Thanks.

**Comment by jonas-schievink** [comment]
Can't reproduce this on current master

**Comment by s1ck** [comment]
I just tried on master with 
```
[profile.release]
incremental = true
debug = 2
```

```
❯ ./rust-analyzer --version                                            
rust-analyzer 1dd181410 2021-07-23 dev
```

```
❯ ./rust-analyzer analysis-stats ~/Devel/Rust/graph                    
Database loaded:     561.61ms, 116minstr
  crates: 2, mods: 7, decls: 121, fns: 86
Item Collection:     3.37s, 28ginstr
8/86 9% processing: tests::directed_usize_graph_from_edge_listthread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', crates/hir_ty/src/builder.rs:35:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed::inner
   3: core::panicking::assert_failed
             at /home/s1ck/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:143:5
   4: hir_ty::builder::TyBuilder<D>::build_internal
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/builder.rs:35:9
   5: hir_ty::builder::TyBuilder<hir_def::AdtId>::build
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/builder.rs:145:28
   6: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer/expr.rs:592:21
   7: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer/expr.rs:62:18
   8: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer/expr.rs:969:17
   9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer/expr.rs:343:17
  10: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer/expr.rs:833:42
  11: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer/expr.rs:62:18
  12: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer/expr.rs:861:29
  13: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer/expr.rs:186:29
  14: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer/expr.rs:62:18
  15: hir_ty::infer::InferenceContext::infer_body
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer.rs:713:9
  16: hir_ty::infer::infer_query
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer.rs:69:5
  17: <hir_ty::db::InferQueryQuery as salsa::plumbing::QueryFunction>::execute
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/db.rs:27:21
  18: salsa::derived::slot::Slot<Q,MP>::read_upgrade::{{closure}}
             at /home/s1ck/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.1/src/derived/slot.rs:219:13
  19: salsa::runtime::Runtime::execute_query_implementation
             at /home/s1ck/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.1/src/runtime.rs:251:21
  20: salsa::derived::slot::Slot<Q,MP>::read_upgrade
             at /home/s1ck/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.1/src/derived/slot.rs:216:26
  21: salsa::derived::slot::Slot<Q,MP>::read
             at /home/s1ck/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.1/src/derived/slot.rs:149:9
  22: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
             at /home/s1ck/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.1/src/derived.rs:172:13
  23: salsa::QueryTable<Q>::try_get
             at /home/s1ck/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.1/src/lib.rs:532:9
  24: salsa::QueryTable<Q>::get
             at /home/s1ck/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.1/src/lib.rs:527:9
  25: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/db.rs:21:1
  26: hir_ty::db::infer_wait
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/db.rs:168:5
  27: <DB as hir_ty::db::HirDatabase>::infer
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/db.rs:21:1
  28: rust_analyzer::cli::analysis_stats::AnalysisStatsCmd::run_inference
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/rust-analyzer/src/cli/analysis_stats.rs:225:36
  29: rust_analyzer::cli::analysis_stats::AnalysisStatsCmd::run
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/rust-analyzer/src/cli/analysis_stats.rs:136:13
  30: rust_analyzer::try_main
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/rust-analyzer/src/bin/main.rs:93:55
  31: rust_analyzer::main
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/rust-analyzer/src/bin/main.rs:44:23
  32: core::ops::function::FnOnce::call_once
             at /home/s1ck/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
```

**Comment by jonas-schievink** [comment]
What commit of https://github.com/s1ck/subgraph-matching are you using? The current one is s1ck/subgraph-matching@cfa07f0cf9b5beefbc287fc1c7776f43a3699932 and that doesn't seem to reproduce the problem for me

**Comment by s1ck** [comment]
The issue is independent of the project. I just used `subgraph-matching` as an example. Same problem for `rust-analyzer`:

```
❯ ./rust-analyzer analysis-stats ~/Devel/Rust/rust-analyzer    
Database loaded:     21.61s, 269minstr
  crates: 38, mods: 741, decls: 15834, fns: 11769
Item Collection:     12.73s, 74ginstr
107/11769 0% processing: input::transitive_depsthread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', crates/hir_ty/src/builder.rs:35:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed::inner
   3: core::panicking::assert_failed
             at /home/s1ck/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:143:5
   4: hir_ty::builder::TyBuilder<D>::build_internal
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/builder.rs:35:9
   5: hir_ty::builder::TyBuilder<hir_def::AdtId>::build
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/builder.rs:145:28
   6: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer/expr.rs:592:21
   7: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer/expr.rs:62:18
   8: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer/expr.rs:969:17
   9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer/expr.rs:343:17
  10: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer/expr.rs:833:42
  11: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer/expr.rs:62:18
  12: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer/expr.rs:861:29
  13: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer/expr.rs:186:29
  14: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer/expr.rs:62:18
  15: hir_ty::infer::InferenceContext::infer_body
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer.rs:713:9
  16: hir_ty::infer::infer_query
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/infer.rs:69:5
  17: <hir_ty::db::InferQueryQuery as salsa::plumbing::QueryFunction>::execute
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/db.rs:27:21
  18: salsa::derived::slot::Slot<Q,MP>::read_upgrade::{{closure}}
             at /home/s1ck/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.1/src/derived/slot.rs:219:13
  19: salsa::runtime::Runtime::execute_query_implementation
             at /home/s1ck/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.1/src/runtime.rs:251:21
  20: salsa::derived::slot::Slot<Q,MP>::read_upgrade
             at /home/s1ck/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.1/src/derived/slot.rs:216:26
  21: salsa::derived::slot::Slot<Q,MP>::read
             at /home/s1ck/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.1/src/derived/slot.rs:149:9
  22: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
             at /home/s1ck/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.1/src/derived.rs:172:13
  23: salsa::QueryTable<Q>::try_get
             at /home/s1ck/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.1/src/lib.rs:532:9
  24: salsa::QueryTable<Q>::get
             at /home/s1ck/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.1/src/lib.rs:527:9
  25: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/db.rs:21:1
  26: hir_ty::db::infer_wait
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/db.rs:168:5
  27: <DB as hir_ty::db::HirDatabase>::infer
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/hir_ty/src/db.rs:21:1
  28: rust_analyzer::cli::analysis_stats::AnalysisStatsCmd::run_inference
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/rust-analyzer/src/cli/analysis_stats.rs:225:36
  29: rust_analyzer::cli::analysis_stats::AnalysisStatsCmd::run
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/rust-analyzer/src/cli/analysis_stats.rs:136:13
  30: rust_analyzer::try_main
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/rust-analyzer/src/bin/main.rs:93:55
  31: rust_analyzer::main
             at /home/s1ck/Devel/Rust/rust-analyzer/crates/rust-analyzer/src/bin/main.rs:44:23
  32: core::ops::function::FnOnce::call_once
             at /home/s1ck/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
```

**Comment by lnicola** [comment]
I can't reproduce it either, neither with a local build, nor the GitHub release. Which `rustc` version are you using?

```
root = AbsPathBuf("/home/s1ck/Devel/Rust/subgraph-matching")
root = CargoToml(AbsPathBuf("/home/s1ck/Devel/Rust/subgraph-matching/Cargo.toml"))
```

I'm not sure what's up with this, but I see it too in the nightly on GitHub.

**Comment by s1ck** [comment]
```
❯ rustc --version
rustc 1.53.0 (53cb7b09b 2021-06-17)
```

Are you running on Ubuntu, too? I tried to reproduce in a Ubuntu 20.04 LTS VM (arm64) on M1 -> no issue.

**Comment by lnicola** [comment]
No, Arch with the same `stable` toolchain.

> I tried to reproduce in a Ubuntu 20.04 LTS VM (arm64) on M1 -> no issue.

Uhh..

Can you try picking up some older releases from GitHub to see when it started crashing? Maybe we can bisect it.

**Comment by s1ck** [comment]
I went back until `2021-02-01` and the issue still occurs. I stopped suspecting `rust-analyzer` to be the issue ... but I can't come up with anything that would interfere with it :thinking:

**Comment by s1ck** [comment]
I just installed a VM on the ubuntu machine with a fresh ubuntu 20.04.LTS, rust and rust-analyzer .. no issue :( 
I'll close this issue as it is obviously an issue with my machine / OS.

Thanks for your suggestions!

**Comment by lnicola** [comment]
You could try reinstalling the toolchain (with `rustup`), just in case something got messed up in `rust-src`.

**Comment by s1ck** [comment]
@lnicola reinstalling the toolchain solved the issue. Thanks again for the suggestion!
